### ISSUE TITLE
object_types=> comment - form action is not specified.

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#109]
I dont see any option to specify a form action. For a comment form to post, I believe I need to have the ability to specify `form action="action="'.get_option("siteurl").'/wp-comments-post.php""`. 

 I tried using the front end form, setting the `object_type` to `comment` but with no action, the form does nothing but refresh the page.  

Additionally, wordpress' own `comment_form()` accepts an array of `$args`, one of which is `$fields`.  It would be great if you guys (developers) could add a helper function that rendered the comment form complete with the proper action specified.  Possible? Or, a helper function that only returns the rendered fields html ready to be used with the `comment_form()` function.

**Comment by tw2113** [comment]
Any issues still lingering here @GregLancaster71 ?

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
