### ISSUE TITLE
Metaboxes not saving only on specific page

### ISSUE THREAD

**Issue by cmlowe** [WebDevStudios/CMB2#114]
I posted this elsewhere, but I think this is the proper place.

I have a series of meta boxes on my homepage, ID 4, but the values aren't saving. They were working fine locally, and also on my staging environment but on production they aren't saving.

The only difference I can identify is production is ID 4 wheras local/staging was ID 726. I've of course updated the ID in 'show_on' but the values won't save on page update.

I also have a Custom Post Type using a meta box defined in the same function and those are saving just fine.

Thanks, otherwise this is a great plugin!

Here is a sample of some code that results in not saving.
```
$meta_boxes['hero_metabox'] = array(
		'id'            => 'hero_metabox',
		'title'         => __( 'Hero Call-to-Action', 'cmb2' ),
		'object_types'  => array( 'page', ), // Post type
		'context'       => 'normal',
		'priority'      => 'high',
		'show_on'      	=> array( 'id' => array( 4, ) ),
		'show_names'    => true, // Show field names on the left
		'fields'        => array(
			array(
				'name'       => __( 'Heading', 'cmb2' ),
				'desc'       => __( 'Heading to appear above content', 'cmb2' ),
				'id'         => $prefix . 'cta_heading',
				'type'       => 'text',
			),
			array(
				'name'    => __( 'Call-to-Action Content', 'cmb2' ),
				'id'      => $prefix . 'cta_content',
				'type'    => 'wysiwyg',
				'options' => array( 'textarea_rows' => 5, ),
			)
		),
	);
```

**Comment by underscorefunk** [comment]
I'm having the same problem, even without "show_on" being enabled/filtered.

**Comment by tnorthcutt** [comment]
@cmlowe can you confirm if this is still an issue? If not, can you please close this? Thanks!

**Comment by tnorthcutt** [comment]
I'm closing this issue as it's quite old with no response from the original reporter. If this is still a concern, please feel free to re-open with more details or new information as relevant. Thanks!
