### ISSUE TITLE
Loading scripts on localhost

### ISSUE THREAD

**Issue by ghost** [WebDevStudios/CMB2#118]
Hi guys, I had a problem with loading scripts on localhost, and I modified the code a little then it works. I think I should let you know about my issue.

On the file CMB2_hookup.php

Changed the commented code to uncommented code.

//wp_register_style( 'cmb2-styles', cmb2_utils()->url( "css/cmb2{$min}.css" ), $styles );
		wp_register_style( 'cmb2-styles',get_template_directory_uri()."/inc/cmb2/css/cmb2{$min}.css", $styles );

Before I making changes, scripts were loading like this
src="http://website.com/D:\workspace\projects\myproject\file.js"

Thanks

**Comment by tnorthcutt** [comment]
Closing as this is over a year old.

**Comment by alanef** [comment]
I get this issue developing on XAMPP -  PHP_OS: WINNT

**Comment by tw2113** [comment]
@alanef see https://github.com/WebDevStudios/CMB2/wiki/Troubleshooting#cmb2-urls-issues

**Comment by alanef** [comment]
Thank - the str_replace is a good idea.  Its a Windows mklink that caused the issue
