### ISSUE TITLE
CMB2 in plugins priority

### ISSUE THREAD

**Issue by Benoti** [WebDevStudios/CMB2#121]
hello,
I am currently developing a new plugin (locally with mamp), using CMB2 walking fine but when another of my plugin is enabled (which also uses CMB2 ) the metaboxes don't appear for the new plugin, the other continues to function perfectly and display correctly the metaboxes .
Basically, I joined the CMB2 library in both plugins with your method, after many tests, I installed the plugin CMB2, but the same problem persists.
Apparently, this is the oldest plugin (installed first) that would hand over CMB2 class and the new plugin even if it loads the file does not seem to detect add_filter (' cmb2_meta_boxes ', ' form_cpt_metaboxes '); so nothing is displayed even if I play with priority. As soon as I turn off the other plugin, everything works admirably for the new plugin.
I try to use add_action instead of add_filter, but there is non changes.

Any idea on this or a better implementation way to make coexist several plugins including cmb2 ?
Thank you by advance and excuse my bad english.
Benoti

**Comment by tnorthcutt** [comment]
Closing as this is over a year old.
