### ISSUE TITLE
get property of non-object error

### ISSUE THREAD

**Issue by wearesupa** [WebDevStudios/CMB2#133]
Hi,

This was working in CMB1 but since upgrading to CMB2 I'm getting errors, tho may not be down to CMB2.

Have custom post type with taxonomies, created a cmb repeat group with the following option...

    array(
        'name'     => __( 'Category', 'cmb2' ),
        'id'       => 'category_select',
        'type'     => 'taxonomy_select',
        'taxonomy' => 'portfolio_category',    
    )

The above cmb displays the select list of taxonomies fine.

I'm then using the following markup...

    foreach ( (array) $entries as $key => $entry ) {
        if ( isset( $entry['category_select'] ) ) {
            $categoryportfolio = esc_html( $entry['category_select'] );
        }
    
    $term = get_term( $categoryportfolio, 'portfolio_category' );
    $catslug = $term->slug;
    $name = $term->name;
    $desc = $term->description; `

I'm getting the following errors...

**Notice: Trying to get property of non-object...**

for the following lines

    $catslug = $term->slug;
    $name = $term->name;
    $desc = $term->description;

Thanks

**Comment by jtsternberg** [comment]
The 'taxonomy_select' field is not a repeatable field. It is meant to set one term to a post.

**Comment by wearesupa** [comment]
Silly me, many thanks.

I guess I could use https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types#example-2-taxonomy-dropdown-store-term_id and produce the desired results with the above markup?

Thanks again
Michael

**Comment by jtsternberg** [comment]
Unfortunately that example is out of date so won't work as expected & definitely wouldn't work in a repeatable group. I'll try to update the example today.

**Comment by tnorthcutt** [comment]
Closing as this is over a year old.
