### ISSUE TITLE
Limit file_list repeatable to a quantity

### ISSUE THREAD

**Issue by mrtwebdesign** [WebDevStudios/CMB2#134]
This is a **feature request**
I'm working with a repeatable field group that includes an image and a few text fields. I'm using the group to make a slider for the home page. I can't us `file` type because that's documented as not repeatable(I tried it anyway :) ).
This is a case of trying to keep a client from getting confused. I don't want them adding multiple images to the first slide thinking they are adding slides. I'm only going to grab the first image for each group entry. So I'm hoping for something like this usable in a group:
```
array(
  'name' => 'Slide Image',
  'id'   => 'image',
  'type' => 'file_list',
  'preview_size' => array( 100, 100 ),
  'allow' => array( 'attachment' ), // limit to just attachments
  'count_limit' => '1', // limit the number of files that can be added, 
),
```

**Comment by jtsternberg** [comment]
Why wouldn't you use the 'file' field type?

**Comment by mrtwebdesign** [comment]
I didn't detail what when wrong when I tried `file` in a repeatable group. It was ignoring `'allow' => array( 'attachment' ),`.  Some of my clients are very intelligent and sophisticated. Some will break anything that isn't nailed donw. Having an editable url after they attach an image is just asking for trouble.
I didn't file a bug report on that since the documentation noted that `file` in a group is "* Not available as a repeatable field".  Now that I re-read that, it doesn't say it's not usable inside a repeatable group. But what about the `allow` parameter? I was still getting the url form field and no ID was stored. I wasn't even trying to get it to display right away. I was using `print_r` to show me the entire object that the group was building. It was just storing the url and no attachment id.
```
$entries = get_post_meta( get_the_ID(), '_apcorp_home-slides', true );
print_r($entries);
```

**Comment by AlchemyUnited** [comment]
re: "I can't us file type because that's documented as not repeatable" 

I read that as well, but then when I sent to find it again. it wasn't there. In any case, I just put file in a group and best I can tell it's okay. 

There was another issue in Dec about someone asking for a limit on repeating rows in a group. I'm not sure what happened with that. The gist seemed to be you could pull it off with a bit of js.

**Comment by AlchemyUnited** [comment]
https://github.com/WebDevStudios/CMB2/issues/119

**Comment by tnorthcutt** [comment]
Closing as this is over a year old.

**Comment by devmahbub** [comment]
I want to limit the file_list to take only 3 images. can it be done now?

**Comment by tw2113** [comment]
No changes that I'm aware of to CMB2 core files that would allow limiting to 3 images. Best route would still be just 3 individual file fields instead of file list.

**Comment by devmahbub** [comment]
Thank you, but we can't always do what we want when we have  PSD design. I need to match the PSD as much as I can. So it be great if developer can add an option to limit the number of file selection in file_list field type.
