### ISSUE TITLE
image-Field saves right URL, but wrong ID

### ISSUE THREAD

**Issue by andy-tschiersch** [WebDevStudios/CMB2#137]
A image-Field inside a group-Field:

```php
array(
	'id'          => $prefix . 'referenz',
	'type'        => 'group',	
	'options'     => array(
		'add_button'    => __( 'Add Image', 'huku' ),
		'remove_button' => __( 'Remove Image', 'huku' ),
		'sortable'      => true,
	),	
	'fields'      => array(						
		array(
			'name' => 'Image',
			'id'   => 'image',
			'type' => 'file',
		),					
	),
),
```
This works in most cases, but not in this case:
(all following URLs are shortened)

I add 'uploads/2015/01/spitz.png' and it shows me the right Preview-Image.
When i save the post, it shows me the right URL ('uploads/2015/01/spitz.png'),
but the wrong Preview-Image -> 'uploads/2014/12/logo_spitz.png'.

The Database-Records holds also the right URL and the wrong ID (the ID of 'uploads/2014/12/logo_spitz.png' ).
I suppose it has something todo with the similar filename, both ends with spitz.png.

I give you more Details if needed.

**Comment by jtsternberg** [comment]
If you want the id to be saved correctly, you need to click the button to attach the media from the media library. It automatically gets the ID for you. Otherwise it's trying to extrapolate the ID from the url and as you have witnessed, can sometimes fail.

**Comment by andy-tschiersch** [comment]
Sorry I've forgotten this detail in my description above, but i used the button and select the image from the media library. After is used the button, the preview shows the correct image. When i save the post, it shows the wrong image.

**Comment by jtsternberg** [comment]
I can't imagine a scenario where that would occur. Is your media library in good shape? Or are you working on local/dev environment with a cloned database? Also, when you select a file from the media modal, the attachment ID gets added to a hidden field (screenshot: http://b.ustin.co/1d7u7 ). Does it add the attachment ID for you? and if so, is it the correct ID?

**Comment by creativesponge** [comment]
Any other reports of this?

I'm facing this exact issue too. It's a repeatable group with an image field. The URL is being set, and displays correctly in both the back and front end. The preview image is displaying correctly when first selecting an image from the media library, but is actually passing an incorrect attachment ID to the hidden field.

Using CMB 2.0.5 on WP 4.1.1 vanilla, no other plugins.

**Comment by tnorthcutt** [comment]
I'm closing this issue as it's quite old with no response from the original reporter. If this is still a concern, please feel free to re-open with more details or new information as relevant. Thanks!
