### ISSUE TITLE
Front-end post not saving to the post.

### ISSUE THREAD

**Issue by wpbean** [WebDevStudios/CMB2#139]
Hi, I use CMB front-end posting few days ago and that's works fine. Recently I start a project with CMB2.
Problem is when I add new post form front-end, it's not saving. 

I have tried few hours and found it's for the <b>wp_meta_box_nonce</b> function. That is not available on CMB2. 

The code that check the  nonce on CMB previous version was like -
<pre>
if ( ! ( isset( $_POST['submit-cmb'], $_POST['wp_meta_box_nonce'] ) && wp_verify_nonce( $_POST['wp_meta_box_nonce'], cmb_Meta_Box::nonce() ) ) ) {

}
</pre>

Now can anybody tell me, how can I check the nonce in CMB2. 

Thanks 
Imran Khan
WPBean.com

**Comment by GregLancaster71** [comment]
Im not sure if there is an official way, but I am verifying the nonce like so:

` $nonce = sanitize_html_class( 'nonce_CMB2php'. $this->meta_box['id'] );`

`if ( wp_verify_nonce( $_POST[$nonce], $nonce ) ) {}`

**Comment by BenRacicot** [comment]
@wpbean hey! Is there any way you could show me how you managed creating a front end post? I can't find anything on the subject anywhere.

**Comment by wpbean** [comment]
@BenRacicot Check CMB wiki. There is a nice documentation for that. But I am not sure about the CMB2 yet.

https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/wiki/Create-New-Posts-Post-Type-Entries-Using-A-Front-End-Form

Thanks

**Comment by BenRacicot** [comment]
Yeah I spent about an hour with that. Can't seem to get a grip on this project. Thanks for replying.

**Comment by jtsternberg** [comment]
Just a heads up, I have a tutorial blog post on this very topic queued up which should be coming up in the next week or two.

**Comment by BenRacicot** [comment]
Woot woot JS. Can't wait.

**Comment by kidesigner** [comment]
Need help submit post using A Front End Form (with wordpress default title, featured image)

**Comment by jtsternberg** [comment]
@kidesigner you are absolutely abusing issues, and spamming every channel. (see #168, #184, #174, https://github.com/WebDevStudios/CMB2-Snippet-Library/issues/1, and this issue, #139)

Please stop. I would love to write the tutorial and WILL will write the tutorial as soon as I have a time, and unfortunately that time is not this moment. I'm going to close all the other issues you're commenting on and leave this one open.

**Comment by kidesigner** [comment]
Thank you so much.

**Comment by BenRacicot** [comment]
@jtsternberg I wrote mine from scratch and propagate CMB2 fields with raw url fields I've validated myself. However if you ever do have the time to show me the basics I would be willing to write a seriously awesome tutorial for this with screencast etc... I'm getting some decent recognition for tutorials and plugins lately and would love to be the one to help you guys and the community out.

**Comment by kidesigner** [comment]
@BenRacicot can you help me? I very very need it now :(

**Comment by sinanisler** [comment]
hey kidesigner whats up ! :smile: 


Here working form  with image support. 
Yes it has so many features I dont have time to clear that up for you take this and make it for your own use. It is not making featured but it is ataching on post so you can do whatever you want. 


Form: 

```html
            <form action="<?php the_permalink(); ?>#yor" method="post" enctype="multipart/form-data">
                
                <textarea class="i2" name="yorumunuz" placeholder="comment"></textarea>
                <input type="text" name="title" class="i1" placeholder="Title">
                
                <label class="i4">
                Resim <input type="file" name="resim" placeholder="Resim Seç">
                </label>
                
                <input type="submit" value="Gönder"   class="i3">
            </form>
```

PHP
```php
        <?php if ( is_user_logged_in() ) { ?>
        <?php if (! empty($_POST)){ ?>
            <META http-equiv="refresh" content="1; URL=<?php get_permalink(get_the_ID()) ?>#yor">
		<?php }
		
		
        if(isset($_POST['yorumunuz'])){
			$yorumekle = array(
			  'post_title'    => strip_tags($_POST['title']),
			  'post_content'  => strip_tags($_POST['yorumunuz']),
			  'post_status'   => 'publish',
			  'post_author'   => $girisyapankullanici->ID,
			  'post_type'	  => 'yorum'
			);
			
			$yorumPOSTid = wp_insert_post( $yorumekle );
			
			
			
			if($_FILES["resim"]["type"] =="image/gif" or $_FILES["resim"]["type"] =="image/png" or  $_FILES["resim"]["type"] =="image/jpeg" ) {
				
				if(!empty($_FILES["resim"])) {
					$uploads = wp_upload_dir();
					$fileName    = $_FILES["resim"]["name"]; 
					$fileTmpLoc  = $_FILES["resim"]["tmp_name"];
					$uzanti = pathinfo($fileName, PATHINFO_EXTENSION);
					$remove_these = array(' ','`','"','\'','\\','/');
					$fileName = str_replace($remove_these,'', $_FILES['resim']['name']);
					$newname = time().'-hepyorum.'.$uzanti;
					$pathAndName = $uploads['path'].'/'.$newname;
					
					$moveResult  = move_uploaded_file($fileTmpLoc, $pathAndName);	
					
					if ($moveResult == true) {
						// echo "File has been moved from " . $fileTmpLoc . " to " . $pathAndName;
						$resimadresi = 'http://www.hepyorum.com/'.substr($pathAndName, 27);
						// add_post_meta($yorumPOSTid, 'resim' , $resimadresi, true ); 
						
						$filename = $pathAndName;
						
						$parent_post_id = $yorumPOSTid;
						
						$filetype = wp_check_filetype( basename( $filename ), null );
						
						$wp_upload_dir = wp_upload_dir();
						
						$attachment = array(
							'guid'           => $wp_upload_dir['url'] . '/' . basename( $filename ), 
							'post_mime_type' => $filetype['type'],
							'post_title'     => preg_replace( '/\.[^.]+$/', '', basename( $filename ) ),
							'post_content'   => '',
							'post_status'    => 'inherit'
						);
						
						$attach_id = wp_insert_attachment( $attachment, $filename, $parent_post_id );
						require_once( ABSPATH . 'wp-admin/includes/image.php' );
						
						$attach_data = wp_generate_attachment_metadata( $attach_id, $filename );
						wp_update_attachment_metadata( $attach_id, $attach_data );						
						
						$resimadresi = wp_get_attachment_url( $attach_id );
						
						
					} else {
						// echo "ERROR";
					}
					
					
				}
			
			}
			
			
			
		}
		
        ?>

```

**Comment by kidesigner** [comment]
@sinanisler thank my friend so much!! I think your way is so good. But, seem don't to use CMB2 shortcode to generate form?

**Comment by kidesigner** [comment]
@jtsternberg : When you publish tutorial Front-end submit? Please tell me because I have important project used CMB2 plugin. Please help me my friend.

**Comment by jtsternberg** [comment]
The tutorial is almost complete, just waiting on a publish slot on the [WebDevStudios blog](http://webdevstudios.com/blog). For now, there is a [working example in the snippet library](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-submit.php). It requires [2.0.3](https://github.com/WebDevStudios/CMB2/releases/tag/v2.0.3). The tutorial will basically cover how that snippet works. Hopefully it's enough to get you started.

@kidesigner You do not take a hint, or a straight up request to stop spamming, but I'm asking you again, please do not continue spamming github with tutorial requests.

**Comment by jtsternberg** [comment]
Tutorial is published: [Use CMB2 to Create a New Post Submission Form](http://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form)

**Comment by kidesigner** [comment]
Great, i feel i can't wait anymore.
