### ISSUE TITLE
Adding a "tool bar" - Anyone have an thoughts / suggesting?

### ISSUE THREAD

**Issue by AlchemyUnited** [WebDevStudios/CMB2#140]
This is not a bug.

I have a project where one of the CPT currently has over 6 CMB2 meta boxes.

I'm considering the possibility of a "toolbar" that would be a metabox before all others and would more of less just be a series of buttons to open / close the individual metaboxes from the toolbar. Or maybe even open and move to top. Is that's possible. 

I'm also considering adding a field type call 'note' (?) basically it would / could be the first field in the list but it would also appear next to the metabox title. I'm not sure if that's even possible but the abilitry to see a note on a close metabox makes a lot of sense, at least to me. 

I was wondering if these are things someone might want to use. And if so, what are your thoughts on the functionality. 

Thx
mfs

**Comment by jtsternberg** [comment]
I think that could make a nice extension. I'm trying to clean up issues, so I'll be closing this. If you find an actual issue, feel free to open another. Thanks.
