### ISSUE TITLE
Feature Request - Custom metabox forms

### ISSUE THREAD

**Issue by underscorefunk** [WebDevStudios/CMB2#142]
I think it'd be fantastic if we could specify a callback function or could have some kind of filter to produce custom form output. A bit part about making usable UI is being able to group and order meta box items so that they make sense.

**Comment by jtsternberg** [comment]
There are many many filters and callbacks to do just about anything you want. Could you be more specific?

**Comment by underscorefunk** [comment]
Thanks for the speedy response. What I'm looking for is an easy way to create alternate layouts of metabox forms. I think perhaps I posted too soon. I'm starting to dig into the source and helper functions and see that there is a lot in here--well documented too! Chalk this up to a work in progress wiki perhaps?

**Comment by jtsternberg** [comment]
Ah yes, documentation is painfully behind. So much more you can do that is not documented there. One of my goals is to get that fleshed out and document all the actions/filters/callbacks. It will be quite an undertaking.

**Comment by jtsternberg** [comment]
To create a custom field with multiple inputs, a good place to start is with this tutorial: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types#example-4-multiple-inputs-one-field-lets-create-an-address-field

**Comment by underscorefunk** [comment]
Oh, no doubt. What you've done already is such a huge undertaking and I'm exceptionally appreciative of the hard work. I hadn't thought of making the field set a single custom 'field' but that might be a really elegant solution. Sort of like a metaset within a metabox. Thanks!

**Comment by underscorefunk** [comment]
I looked into the CMB2_Types class to find the $field_type_object->input used in your example. I noticed that there is only a method for input and textarea. Is there a recommended away to do the "multiple fields in one" with checkboxes, radio buttons, etc?

**Comment by bigevent** [comment]
I am sorry but I have no idea about this code. Is it because I forked the
code? I did it by accident. I am having problem on using CMB2 for creating
front end form with wordpress. Please let me know if you are familiar with
the front end form with the CMB2.

Thank you.

Jo Daekyung

**Comment by jtsternberg** [comment]
@bigevent please do not hijack another person's issue. The issues section is for bug reports and feature requests only. If you need help, please use [stackoverflow](http://stackoverflow.com/search?q=cmb), or the [wordpress.org plugin forums](http://wordpress.org/support/plugin/cmb2).

**Comment by jtsternberg** [comment]
@underscorefunk best bet is to look at the methods in CMB2_Types that accomplish the types of inputs you are looking to duplicate. Not super helpful, but my best recommendation right now.

**Comment by underscorefunk** [comment]
Thanks @jtsternberg. I was looking there already and I noticed that a lot of the methods don't exist or those that do don't currently accept args for configuration. Now that I look more closely it looks like the ones available through this class in this context are fields available as repeater/group fields. I think maybe my request to do this is just a little too early in the dev cycle.
