### ISSUE TITLE
Fix conditional logic for 'text_money' field.

### ISSUE THREAD

**Issue by Mamaduka** [WebDevStudios/CMB2#144]
This was partially addressed in #28. `before_field` won't display anything unless callback is passed as value, which in this case is wrong logic.

**Comment by jtsternberg** [comment]
Hmm.. actually, before_field can be a callback as well. I think some additional logic is needed there. Nice catch though. Going to make some modifications.

**Comment by Mamaduka** [comment]
@jtsternberg yeah was thinking about the same case.

We have two option here:
* Use only one type value for 'before_field'.
* Add check to `text_money` using `CMB2_Field::maybe_callable()` method and prefix input based on use case.
