### ISSUE TITLE
Color Picker Default Ignored

### ISSUE THREAD

**Issue by jamiechong** [WebDevStudios/CMB2#147]
This is my code 
```php
	array(
		'name' => 'Background Color',
		'id' => CMB_PREFIX.'mag_recent_bg_color',
		'default' => '#7EBBA2',
		'type' => 'colorpicker',
	),		
```

This is what I see: 
[http://cl.ly/image/173D1u1A3t1L](http://cl.ly/image/173D1u1A3t1L)

Has the API changed for this type recently? I'm using the Wordpress plugin and have updated the minor version, but the changelog only shows 2.0.0 - not for 2.0.0.8.

**Comment by jtsternberg** [comment]
@jamiechong This was broken during a previous update (7e521ed8368672090b9fac28ab4f6da19c74f91b). Let me know if you have any problems at this point.
