### ISSUE TITLE
CMB2 installation - cannot get it to work

### ISSUE THREAD

**Issue by leetee4000** [WebDevStudios/CMB2#154]
I have followed the documentation on this page: https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage but cannot get it to work.

I have gone through posts with the same issue and tried all of the suggestions and still nothing. This has left me confused on the installation process.

Can someone confirm whether the following code is needed?

if ( file_exists( DIR . '/cmb2/init.php' ) ) { require_once DIR . '/cmb2/init.php'; } elseif ( file_exists( DIR . '/CMB2/init.php' ) ) { require_once DIR . '/CMB2/init.php'; }

and also whether the cmb2 folder should be installed in the theme folder or the plugin folder. Documentation says theme, installation page on wordpress says plugin.  I have installed in plugin.

Also where should the code from example_functions.php go? Should it be in the functions.php file in the theme folder?

I have installed the plugin via wordpress and therefore the folder is installed in the plugins folder. I have then copied and pasted all of the code from example_functions.php into my functions.php file within my theme folder. I have then added the below code to the page.php file in my theme folder.

$text = get_post_meta( get_the_ID(), '_cmb2_text', true ); 
echo $text;

Please help.

**Comment by jtsternberg** [comment]
If you have CMB2 installed as a plugin, then you do not need to manually include the init.php file.. WordPress does that for you. You only need to include the file manually if you are bundling CMB2 with your theme or plugin. 

Yes, the code from example-functions.php can go in your functions.php. You can also create a new php file in your theme and include it from your functions.php.. That part is up to you.

The `get_post_meta` part will not work until you have saved some values to your page via the metaboxes.

**Comment by leetee4000** [comment]
Thats great, thanks for clarifying.  I have it working now.
