### ISSUE TITLE
Using CMB2 for Options Page - Default Value Not Showing

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#157]
Copied and pasted this example; 
`https://github.com/WebDevStudios/CMB2/wiki/Using-CMB-to-create-an-Admin-Theme-Options-Page`

Added some default values, and it seems the text fields, and color pickers default value option do not work.  Not a huge deal but something I just spent an hour debugging code trying to fix before i realized it was a bug.

**Comment by jtsternberg** [comment]
Last update should fix that. Please let me know.

**Comment by jtsternberg** [comment]
Still an issue?

**Comment by GregLancaster71** [comment]
It appears so.  I tested it with fresh code, and all I added to the example above was the following fields;

```
            array(
                'name'       => __( 'Icon Set', 'sr' ),
                'desc'       => __( 'Check out <a href="http://fortawesome.github.io/Font-Awesome/cheatsheet/" target="_blank">FontAwesome</a> Cheatsheet. ', 'sr' ),
                'id'         => 'icon_select',
                'type'       => 'text',
                'default'    => 'f005',
                'attributes' => array(
                    'placeholder' => 'f005',
                    'required'    => 'required',
                ),
            ),
            array(
                'name'       => __( 'Rating Color', 'sr' ),
                'desc'       => __( 'Set the color of your choice for rating icons.', 'sr' ),
                'id'         => 'icon_color',
                'type'       => 'colorpicker',
                'default'    => '#FCA602',
                'attributes' => array(
                    'required'    => 'required',
                ),
            ),
```

The default field values do not show.  Sorry for the delayed reply, I wanted to test it again to be sure, and as far as I can tell it is infact an issue.

**Comment by GregLancaster71** [comment]
@jtsternberg Could you / anyone verify this is a bug?

**Comment by jtsternberg** [comment]
Yah, verified. Checking into it

**Comment by jtsternberg** [comment]
Should be good now if you update.

**Comment by jeffryevans** [comment]
In my install, even though I have programmed the default values, when I click to create a new user, it defaults the fields to same selections as my account, instead of the defaults I programmed. I removed one of the values from my account, then clicked to create a new account, and the default value I programmed showed up. Please help.

**Comment by jtsternberg** [comment]
@jeffryevans please open a new issue if this isn't related to 'Using CMB2 for Options Page'. And when you do so, you'll nee to provide much more info. Please see the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md).
