### ISSUE TITLE
Smart Feature Request: Conditionally Disable Inputs

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#163]
I would love to see an option to conditionally disable an input field, based on another input fields value.  It would eliminate the need for writing custom callbacks to check if a field is set.

**Comment by jtsternberg** [comment]
I think that would be better suited for JS, right? Either way, I'd be open to a PR.

**Comment by KeinTrong** [comment]
+1,
Would like some required function like this: Display field base on user input, maybe dome via some JS:
Here is what I'm using in ReduxFramework :
<pre>
 array(
                            'id'       => 'custom_title',
                            'type'     => 'text',
                            'title'    => __('Custom Title', 'wpcharming'),
                            'subtitle' => '',
                            'desc'     => "",
                            'default'  => "Get In Touch",
                            'required' => array('show_custom_title','=',true, ),
                        ),
</pre>
@jtsternberg Thanks

**Comment by jcchavezs** [comment]
Hi @GregLancaster71, @KienTrong and @jtsternberg,

I just published a plugin based on CMB2 which allows you to relate fields in the way you describe above: https://github.com/jcchavezs/cmb2-conditionals.

All feedback is welcome!

**Comment by tw2113** [comment]
Closing in favor of @jcchavezs' plugin above.
