### ISSUE TITLE
Post ID vs object ID

### ISSUE THREAD

**Issue by ryanhellyer** [WebDevStudios/CMB2#164]
I was very confused trying to read the documentation as it referred to object ID, but I didn't know what this was. Eventually I realised it was just the post ID. I think it would be best to settle on using post ID, as object ID makes it sound like something different.

**Comment by jtsternberg** [comment]
It's only the post ID if using post objects. CMB2 also works w/ users, comments, and options. Which documentation are you referring to? I'm working on updating docs, so want to make sure it's clear.

**Comment by jtsternberg** [comment]
Anything we can do here?

**Comment by ryanhellyer** [comment]
Sorry. I have no idea what this documentation was referring to. It's too long ago now.

**Comment by jrfnl** [comment]
Hiya, I just ran into the same issue trying to get a field using one of the helper functions. I though the object id was the CMB2 object id or something along those lines.
The inline function documentation of the helper functions is what misled me. Hope that helps.
