### ISSUE TITLE
Creating Default Entries within a Repeatable Group

### ISSUE THREAD

**Issue by ogdsgn** [WebDevStudios/CMB2#165]
Wondering how I would approach creating some default entries within the repeatable group type?

ie. I have a Meta Box "Meta Group" with a repeatable group of a text input & text area, and I would like to be able to have a few defaults populated, with the option to create more.

Here's my code.

    $meta_boxes['meta_group'] = array(
        'id'           => 'meta_group',
        'title'        => __( 'Meta Group', 'cmb2' ),
        'object_types' => array( 'post', ),
		'closed'       => true,       
        'fields'       => array(
            array(
                'id'          => $prefix . 'meta_group',
                'type'        => 'group',
                'options'     => array(
                    'group_title'   => __( 'Meta Group {#}', 'cmb2' ), 
                    'add_button'    => __( 'Add Paragraph', 'cmb2' ),
                    'remove_button' => __( 'Remove Paragraph', 'cmb2' ),
                    'sortable'      => false, // beta
                ),
                'fields'      => array(
                    array(
                        'name' => 'Title',
                        'default' => 'Title ',                        
                        'id'   => 'title',
                        'type' => 'text',
                    ),
                    array(
                        'name' => 'Description',
                        'id'   => 'description',
                        'type' => 'textarea',
                    ),
                ),
            ),
        ),
    ); 

Thanks in advance, and Love the plugin. Super awesome!!!

**Comment by tw2113** [comment]
Hi @ogdsgn if you would be so kind, could you start a thread over at https://wordpress.org/support/plugin/cmb2 and we'll get your questions answered there.

**Comment by ogdsgn** [comment]
Will do, sorry about that, new to this whole thing.

**Comment by tw2113** [comment]
No worries.
