### ISSUE TITLE
Video Embeds not working in Wysiwyg

### ISSUE THREAD

**Issue by jcamomile** [WebDevStudios/CMB2#166]
1. I added a youtube video in a wysiwyg. I tried it both as IFrame and Share Link (i.e. http://youtu.be/Dach1nPbsY8 ).
2. Both times the video displays fine in the editor window.
3. Both cases, the video does not display on the public viewable page. The iframe is stripped completely and the share shows as text. 

I imagine it could be the way I am calling the content. Since this is not the_content I am not sure.

**Comment by jtsternberg** [comment]
[Check the documentation](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#oembed). It will not display automatically since it simply saves as a url. You need to make sure the oembed filters are applied to it.

**Comment by jcamomile** [comment]
Hi Justin,

The reference you sent was for the oembed field. What I am saying is that
when the iframe or share address is placed in the wysiwyg, it is expected
that they work the same as if they were in the_content, Or that there
should be some documentation saying that it should not be expected. I added
several custom meta boxes to a client site and they had this expectation.

Maybe it would suffice to a line to the documentation for the wysiwyg field
(next to the line about applying wpautop) saying that to make video embeds
work, run your content through another filter. I could not find one that
applies wp_oembed_get to content in the middle of a string so I tried
passing it through the "the_content" filter. That had other problems,
actually broke the site at WPengine. I made a function to do what I need
but would love to find a better one. Let me know if you have any
suggestions.

Thanks!

Jim

On Sat, Jan 31, 2015 at 8:44 AM, Justin Sternberg <notifications@github.com>
wrote:

> Check the documentation
> <https://github.com/WebDevStudios/CMB2/wiki/Field-Types#oembed>. It will
> not display automatically since it simply saves as a url. You need to make
> sure the oembed filters are applied to it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebDevStudios/CMB2/issues/166#issuecomment-72320369>.
>



-- 
Jim Camomile
Lead Developer
Castle Media Group, LLC

512.914.8458

www.authormedia.com

**Comment by jtsternberg** [comment]
I apologize for misunderstanding. I added [more to the documentation](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#wysiwyg). Keep in mind, the documentation is a wiki, so if you feel certain parts are not clear, you may feel free to edit them.

**Comment by jcamomile** [comment]
Hi Justin,

I will do that in the future. I am still a bit baffled at the wiki concept
of editing docs for someone else's software, but I can get over that.
Thanks for the support on this. CMB2 is truly awesome.

Jim

On Mon, Feb 2, 2015 at 9:38 AM, Justin Sternberg <notifications@github.com>
wrote:

> I apologize for misunderstanding. I added more to the documentation
> <https://github.com/WebDevStudios/CMB2/wiki/Field-Types#wysiwyg>. Keep in
> mind, the documentation is a wiki, so if you feel certain parts are not
> clear, you may feel free to edit them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebDevStudios/CMB2/issues/166#issuecomment-72477511>.
>



-- 
Jim Camomile
Lead Developer
Castle Media Group, LLC

512.914.8458

www.authormedia.com

**Comment by jtsternberg** [comment]
@jcamomile ha, I totally understand. But hey, keep in mind that this software is OUR software. Open source FTW ;)

**Comment by jcamomile** [comment]
Thanks for the extra documentation! This is really great!
