### ISSUE TITLE
The 'default' => true always reverts to default when diactivated

### ISSUE THREAD

**Issue by zealmurapa** [WebDevStudios/CMB2#167]
I have my array

array(
                            'name' => 'Bread Crumbs',
                            'desc' => 'Check to enable/disable breadcrumbs for this page ',
                            'id' => $prefix . 'breadcrumbs_checkbox',
                            'type' => 'checkbox',
                            'default' => true,
                        ),

the default part reverts to default in the post edit screen even when I previously disabled it on my last edits, anyone?

**Comment by jtsternberg** [comment]
https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#setting-a-default-value-for-a-checkbox

**Comment by zealmurapa** [comment]
am Glad jtsternberg
