### ISSUE TITLE
Any way to allow the user to crop images from the `file` field type?

### ISSUE THREAD

**Issue by lmartins** [WebDevStudios/CMB2#175]
The experience with CMB2 so far as been nothing short of amazing.
Theres one details im not being to able to achieve - allowing the user to crop the attached image from the `file`field type.

Is this possible?

**Comment by jtsternberg** [comment]
With the [2.0.2 release](https://github.com/WebDevStudios/CMB2/releases/tag/v2.0.2), clicking the thumbnail will re-open the modal, and there should be an edit image link in there.

**Comment by lmartins** [comment]
Cool, thanks.
