### ISSUE TITLE
Each time I make changes to CMB2 config menu gets reset

### ISSUE THREAD

**Issue by lmartins** [WebDevStudios/CMB2#176]
Hi,

I'm having an issue I haven't been able to find it's origin.
Each time I make any change to a CMB2 metabox/fields configuration the menu on my site gets reset and I need to rebuild it. Any ideia what might be going on?

**Comment by jtsternberg** [comment]
when you say make changes, do you mean in the code, or saving/updating field values? When you say 'menu on my site', do you mean a WordPress menu (wp-admin/nav-menus.php)?

Either way, I've never experienced that. Can you verify it still occurs with all other plugins deactivated?

**Comment by lmartins** [comment]
Hi Justin, I've meant changes in the PHP where i had CMB2 config.
I'll close this for now and let you know if I can replicate the issue in the circumstances you suggest.

**Comment by jtsternberg** [comment]
yah, that is super weird. Thanks for investigating.
