### ISSUE TITLE
Undefined Offset for file_list output

### ISSUE THREAD

**Issue by mathetos** [WebDevStudios/CMB2#179]
When using the sample function in the [wiki](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#sample-function-for-getting-and-outputting-file_list-images) and `WP_DEBUG` is on, I get an `Undefined offset` notice when outputting a file_list field.

Here's my field array:
```
array(
            'id' => $prefix . 'gallery',
            'type' => 'file_list',
            'preview_size' => array( 100, 100 ),
      ),
```

And here's how I output it in my plugin:

```
$ftg_thumbsize = get_post_meta( get_the_id(), 'ftg_step3-imgsize', true );
$ftg_gall = get_post_meta( get_the_id(), 'ftg_gallery', true );

foreach ( (array) $ftg_gall as $attachment_id => $attachment_url ) {
		
			echo '<a href="'. $attachment_url .'">';
			echo wp_get_attachment_image( $attachment_id, $ftg_thumbsize );
			echo '</a>';
	}
```
 
Note the $ftg_thumbsize is a custom field that outputs the sizes of the registered images. It outputs correctly. The Undefined offset notice only appears when the foreach statement above is present.

[This](https://github.com/WebDevStudios/CMB2/issues/13#issuecomment-57407482) was the only other reference to an Undefined offset notice in the issues, and I tried using `reset()` but without success.

**Comment by jtsternberg** [comment]
What is the whole notice? And you should have a line number given which will tell you where the notice happens.

**Comment by mathetos** [comment]
Shoot, not sure how I left that out. That project is at home, will update tonight.

**Comment by codot91** [comment]
same problem, my problem is how to get url from image.....
<a href="url" >

**Comment by jtsternberg** [comment]
Are you using this snippet exactly? https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/front-end/output-file-list.php

**Comment by tw2113** [comment]
Assuming "ftg_gallery" is the ID given to the file list, I'm not seeing anything that would cause this, and I'm using a copy/paste from the wiki page itself. It output the file list fine.

I think this is minor enough we could close. If it comes up again, we'll address at that time.
