### ISSUE TITLE
taxonomy_* - Force to use post meta

### ISSUE THREAD

**Issue by phh** [WebDevStudios/CMB2#180]
It seems like all the `taxonomy_*` are alternatives for the build in `tagsdiv` metabox. But what if you want to have multiple metas for the same taxonomy? Like 

Taxonomy `Subject`

Metaboxes: `Major subjects`, `Minor subjects`, `Related subjects`?

Would be useful to be able to force type `taxonomy_*` to save as post_meta instead of post terms.

**Comment by jtsternberg** [comment]
There happens to be tip/trick just for you: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post

**Comment by phh** [comment]
Awesomeness! Thank you very much :)
