### ISSUE TITLE
Please teach me Front-end submit. I can't do that!

### ISSUE THREAD

**Issue by kidesigner** [WebDevStudios/CMB2#184]
Please teach me Front-end submit. I can't do that! :(

**Comment by jtsternberg** [comment]
@kidesigner you are absolutely abusing issues, and spamming every channel. (see #168, https://github.com/WebDevStudios/CMB2/issues/139#issuecomment-73177096, #174, https://github.com/WebDevStudios/CMB2-Snippet-Library/issues/1, and this issue)

Please stop. I will write a tutorial as soon as I have a time, and unfortunately that time is not this moment. I'm going to close all the other issues you're commenting on and leave this one open.
