### ISSUE TITLE
How to access a field's arguments in CMB2?

### ISSUE THREAD

**Issue by JohEngstrom** [WebDevStudios/CMB2#186]
I'm porting some custom fields over from CMB to CMB2 and I can't work out how to access the field arguments in the new version.

In the old version I could do like this

```
function my_cmb_render_text_maxlength( $field_args, $escaped_value, $object_id, $object_type, $field_type_object ) {
    echo $field_type_object->input( array( 'class' => 'cmb_text', 'maxlength' => $field_args['maxlength'] ) );
}
add_action( 'cmb_render_text_maxlength', 'my_cmb_render_text_maxlength', 10, 5 );
```

I could then get the maxlength value from the field arguments and pass it to the maxlength attribute in an input field.

As the render function look a bit different in CMB2 I can't get this to work. I've dumped both the $field and the $field_type_object objects and I can see my maxlength value in there but I can't seem to echo it out.

So what should I use instead of $field_args['maxlength'] in CMB2 please?

Any help would be much appreciated!

**Comment by JohEngstrom** [comment]
I worked it out from reading through the source code a bit closer.

Instead of $field_args['maxlength'] I now use $field_type_object->field->args( 'maxlength' ) ).

```
function cmb2_render_callback_for_text_maxlength( $field, $escaped_value, $object_id, $object_type, $field_type_object ) {
    echo $field_type_object->input( array( 'class' => 'cmb_text', 'maxlength' => $field_type_object->field->args( 'maxlength' ) ) );
}
add_action( 'cmb2_render_text_maxlength', 'cmb2_render_callback_for_text_maxlength', 10, 6 );
```

**Comment by jtsternberg** [comment]
The wiki has pretty in-depth examples/documentation as well. https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types

**Comment by JohEngstrom** [comment]
I read that bit first but couldn't work out how to access a fields argument.

I've worked on my solution a bit further and I think I can replace $field_type_object->field->args( 'maxlength' ) ) with $field->args( 'maxlength' ) ) to make it shorter.

Thanks for all your work on this library. It's great!

The only thing I'm missing is a range slider input but I'll add that as as a custom field.

**Comment by jtsternberg** [comment]
@JohEngstrom would love a submission to the snippet library if you get that range slider input done. :) https://github.com/WebDevStudios/CMB2-Snippet-Library
