### ISSUE TITLE
Repeatable Group: Image gallery empties on changing order

### ISSUE THREAD

**Issue by Gaffen** [WebDevStudios/CMB2#187]
CMB 2.0.1, Wordpress 4.1

If a repeatable group has an image gallery in it, changing the order removes the gallery from the one that end up on top, replacing it from the gallery below.

Test case:

1. Create two repeatable field items, assign them names and image galleries:
![screen shot 2015-02-13 at 14 42 34](https://cloud.githubusercontent.com/assets/718125/6189126/10479962-b390-11e4-9068-4215b61ed855.png)

2. Update the post

3. Change the order of the items.

4. Update the post

5. One of the galleries disappears and the other is replaced 
![screen shot 2015-02-13 at 14 42 46](https://cloud.githubusercontent.com/assets/718125/6189140/2ce43fee-b390-11e4-8a79-d1a6746778d4.png)

This is inconvenient as it makes it difficult to hand projects over to clients knowing they may accidentally start undoing image galleries.

**Comment by bonny** [comment]
This happens for us too. Re-order = images get lost.

**Comment by bonny** [comment]
Ok, I just made a fix that you can see above. Was going to create a pull request when I saw that this probably was fixed here already (but not merged yet - let's hope it will be soon because we can't release our client website until this is fixed): https://github.com/WebDevStudios/CMB2/pull/153

**Comment by jtsternberg** [comment]
This is fixed in trunk and will be in the next release, thanks to @jamiechong!
