### ISSUE TITLE
Repeatable Group: Colour field doesn't update

### ISSUE THREAD

**Issue by Gaffen** [WebDevStudios/CMB2#189]
CMB 2.0.1, Wordpress 4.1

On changing the order of a repeatable group item, the colour picker doesn't update.

Test case
1. create two repeatable field items, assign them colours and names:
   ![screen shot 2015-02-13 at 14 42 03](https://cloud.githubusercontent.com/assets/718125/6189046/67d2c9fa-b38f-11e4-9511-623231a5a99d.png)
2. Change the order of the two items:
   ![screen shot 2015-02-13 at 14 42 13](https://cloud.githubusercontent.com/assets/718125/6189067/8bc1e9d6-b38f-11e4-929c-55337a10533b.png)

The properties for the items will change, yet the colours don't update. Clicking update post returns the states to normal, but it is quite confusing in terms of UI

**Comment by tnorthcutt** [comment]
@Gaffen Do you know if this is still an issue?

**Comment by Gaffen** [comment]
I'll check on this over the weekend and get back to you.

**Comment by tw2113** [comment]
@Gaffen did you ever get the chance to re-test this one?

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
