### ISSUE TITLE
How to stop fields from adding escaping

### ISSUE THREAD

**Issue by jawittdesigns** [WebDevStudios/CMB2#195]
The text and textarea fields are adding a `/` before all apostrophes. 

How can I stop it from doing that?

**Comment by jawittdesigns** [comment]
Found the solution from a old CMB issue.

By added custom escape `'escape_cb' => 'stripslashes_deep'` fixed the issue.

**Comment by jtsternberg** [comment]
Can you test with trunk and see if that solves the issue?

**Comment by joshuadavidnelson** [comment]
I've also seen this happen just now with the moment using the admin options page. I just tried with trunk and it's still escaping a bit much. I wasn't able to get the `'escape_cb' => 'stripslashes_deep'` solution to work for me.

**Comment by joshuadavidnelson** [comment]
I was able to get (this solution)[https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/issues/518#issuecomment-42781594] to work (changing the filter prefix, of course, to `cmb2_`)

**Comment by joshuadavidnelson** [comment]
I'm seeing this issue with text fields as well now, though applying that same filter seems to fix it.

**Comment by colinsanford** [comment]
@jawittdesigns @joshuadavidnelson This issue was fixed in 2.0.3 (thought you might want to know).
