### ISSUE TITLE
Default Values Not Populated Correctly for Object Type "User"

### ISSUE THREAD

**Issue by jeffryevans** [WebDevStudios/CMB2#201]
In my install, even though I have programmed the default values, when I click to create a new user, it defaults the fields to same selections as my account, instead of the defaults I programmed. I removed one of the values from my account, then clicked to create a new account, and the default value I programmed showed up. Please help.

Wordpress 4.1, CMB2 2.0.2

[example only]

array(
    'name'    => __( 'User Type', 'cmb2' ),
    'id'      => $prefix . 'select',
    'type'    => 'select',
    'options' => array(
        'option1' => __( 'Option One', 'cmb2' ),
        'option2' => __( 'Option Two', 'cmb2' ),
        'option3' => __( 'Option Three', 'cmb2' ),
    ),
    'default' => 'option2',
),

The expected default value should be option2. The actual value is whatever the admin has selected for their own account.

**Comment by jtsternberg** [comment]
I have a hunch I have an idea what this is, and would love it if you could investigate for me. If you replace your install w/ the [2.0.1](https://github.com/WebDevStudios/CMB2/releases/tag/v2.0.1) version, does it work as expected?

**Comment by jeffryevans** [comment]
I'm sorry but we are in production, and its a medium to large company, I don't want to risk a downgrade. If you can help I would really appreciate it, if not its okay. I appreciate your timely response!

**Comment by AbacusPowers** [comment]
Hi there, I think I'm having this same issue. [Here's my post](https://wordpress.org/support/topic/user-fields-showing-previous-registrants-info) on wordpress.org about the problem.
