### ISSUE TITLE
Change/Bundle UI for Timepicker & Datepicker with Timepicker field types

### ISSUE THREAD

**Issue by JonMasterson** [WebDevStudios/CMB2#204]
Using something like http://trentrichardson.com/examples/timepicker/ would enable users to:
- Select any time with timepicker field type (timepicker currently defaults to 30-minute increments)
- Bundle UI for combined date/timepicker (instead of separate date/timepicker)

An additional "Date/Time Range" field type with start/end fields would be fairly easy to implement with the script mentioned above.

**Comment by jtsternberg** [comment]
IANAL, but I'm not sure the license is compatible w/ GPL.

**Comment by JonMasterson** [comment]
Should be, it's MIT. https://kovshenin.com/2012/the-mit-license-is-compatible-with-the-gpl/

**Comment by Ramblurr** [comment]
+1 from me, this would be great.

**Comment by jtsternberg** [comment]
It's in trunk, and will be in the next release.

**Comment by Ramblurr** [comment]
Super!

**Comment by tw2113** [comment]
@jtsternberg you mention this being in trunk, did it for sure get out as part of an official release since?

**Comment by jtsternberg** [comment]
@tw2113 yep!
