### ISSUE TITLE
Drop ScrollTo Field Upon Adding New Repeatable Item

### ISSUE THREAD

**Issue by DevinWalker** [WebDevStudios/CMB2#205]
I want to propose that the scrolling feature when adding a new repeatable field is phased out. It may seem like a good idea, but really it can get in the way of the user experience. The user already knows that they need to fill in fields, often times the first field may not be the first one required to be completed. Users who create their own repeatable field groups will also run into issues. Let me know what you think!

**Comment by jtsternberg** [comment]
I think I'm board, though I'd prefer to extract it as an add-on if someone used it/liked it. But yah, the feature is a little presumptuous.

**Comment by DevinWalker** [comment]
Thanks @jtsternberg - glad you approve
