### ISSUE TITLE
How to make a custom field type using CMB2 that input db values

### ISSUE THREAD

**Issue by mayeenulislam** [WebDevStudios/CMB2#207]
Can I have your attention to this StackOverflow thread?
http://stackoverflow.com/questions/28213706/how-to-make-a-custom-field-type-using-cmb2-that-input-db-values

I'm afraid the question was asked their first, and that's why not repeating that here.

**Comment by tnorthcutt** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
