### ISSUE TITLE
Installing as a Composer module fails.

### ISSUE THREAD

**Issue by conatus** [WebDevStudios/CMB2#209]
Thanks very much for all your work on this stuff.

When you bring this in as a Composer dependency two things fail.

1. It brings it in assuming you want to use it as a WordPress plugin. You can overwrite this with extras -> installer paths in your `composer.json`. I am not aware of your intentions with this project, but if the intent is to smoothly enable it to be used as a dependency then this feels like a bit of a hack.

2. PHPUnit dependencies fail when pinned to a 3.7.*.

Thanks very much for this.

**Comment by mAAdhaTTah** [comment]
[This is what I use to install CMB2 with composer](https://gist.github.com/mAAdhaTTah/68b7fa1a5e9525b48e60). The reason it's set up this way is related to the discussion [here](https://github.com/WebDevStudios/CMB2/commit/e4d03897689a16d0231c2a344fc15b0439e2155f).

**Comment by jtsternberg** [comment]
@conatus what do you recommend for your 2nd point?

**Comment by conatus** [comment]
Tying the dependency for PHPUnit to a specific version which is known to work fine on `composer install`.

**Comment by jtsternberg** [comment]
Does it work with something like: `"phpunit/phpunit": ">=3.8"`?

The way it's setup currently is the way it is recommended: https://phpunit.de/manual/current/en/installation.html#installation.composer
https://coderwall.com/p/mklvdw/install-phpunit-with-composer

**Comment by mAAdhaTTah** [comment]
I think he means bump it to 4.*

**Comment by conatus** [comment]
Turns out the problem was in my own library - solved by https://github.com/phpspec/prophecy/issues/149. 

This library alone installed without error on my machine. My bad! 

If you are interested in how I am using this: https://github.com/recordsonribs/thorax

**Comment by jtsternberg** [comment]
Glad you got it sorted, and that looks like a cool tool you're building!
