### ISSUE TITLE
PHP notice for custom "show on" filter

### ISSUE THREAD

**Issue by mandiwise** [WebDevStudios/CMB2#211]
I'm using WP 4.1.1 and CMB2 v2.0.2, and recently a PHP noticed started popping up on all of the post edit screens where I'm using CMB2 metaboxes:

```
NOTICE: wp-content/plugins/sbbc-core-functionality/lib/functions/metaboxes.php:1090 - Undefined index: key

include('wp-admin/edit-form-advanced.php'), do_action('add_meta_boxes'), call_user_func_array, CMB2_hookup->add_metaboxes, CMB2_hookup->show_on, apply_filters('cmb2_show_on'), call_user_func_array, CF_Metaboxes->show_metabox_on_front_page
```

I'm using the [front page show on filer](https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-front-page-show_on-filter) exactly as it is outlined in the wiki, and applying to the field like this:

```
'show_on' => array( 'key'   => 'front-page', 'value' => '' ),
```

The weird thing is that despite WP DEBUG complaining that the index "key" is undefined, when I `print_r` the entire metabox array I can see `...['show_on']['key']...` there and it still appears to work on all of the pages where I'm using it.

Any insight on this? Could this have anything to do with the metabox config array being protected?

Thanks.

**Comment by mandiwise** [comment]
An update...

Checking `isset` on the `$meta_box['show_on']['key']` appears to fix the problem. So the first line of the front page show filter would change from this:

```
if ( 'front-page' !== $meta_box['show_on']['key'] )
```
To this:

```
if ( ! isset( $meta_box['show_on']['key'] ) || 'front-page' !== $meta_box['show_on']['key'] )
```

**Comment by jtsternberg** [comment]
yah, that example needs to be updated to more closely resemble the built-in examples: https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Show_Filters.php

But please, feel free to edit, as that is a community wiki. :)
