### ISSUE TITLE
Are Field Specific Filters Possible?

### ISSUE THREAD

**Issue by DevinWalker** [WebDevStudios/CMB2#215]
I'm trying to make it easy for users to hook into a certain field position and add their own fields below it. 

Is it possible to create field filters like so:

```
apply_filters('field_test_filter', array(
					'name'         => __( 'Set Amount', 'give' ),
					'description'  => __( 'This is the set donation amount for this form.', 'give' ),
					'id'           => $prefix . 'set_price',
					'type'         => 'text_money',
					'before_field' => give_currency_symbol(), // Replaces default '$'
					'attributes'   => array(
						'placeholder' => give_format_amount( '0.00' ),
						'value'       => isset( $price ) ? esc_attr( give_format_amount( $price ) ) : '',
					),
				)),
```

And then allow the user to hook into that specific position and output the fields like so:

```
function levels_recurring_fields( $settings ) {

	$prefix = '_give_';

	//ensure the $settings are in an array we can merge into

	$recurring_select_field =
		array(
			'name'    => __( 'Recurring', 'give-recurring' ),
			'id'      => $prefix . 'recurring',
			'type'    => 'select',
			'options' => array(
				'no'  => __( 'No', 'give-recurring' ),
				'yes' => __( 'Yes', 'give-recurring' ),
			),
			'default' => 'no',
		);

	return array_merge( $settings, $recurring_select_field );

}

add_filter( 'give_donation_levels_table_row', 'give_donation_levels_recurring_fields' );
add_filter( 'field_test_filter', 'give_donation_levels_recurring_fields' ); 
```

It seems like CMB2 expects the arrays separately, not multi-dimensional, which is why I'm not seeing anything display...

Any suggestions as to how a user can insert fields to a group at a specific index?

**Comment by DevinWalker** [comment]
I guess we can use `array_splice` to insert fields at a certain position, but it's not very evergreen as the plugin author could easily switch around the fields and there's no guarantee that we're hooking in exactly after a certain field.

**Comment by jtsternberg** [comment]
`CMB2::add_field()` [takes `$position` as a third argument](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2.php#L652-L671), and is demoed in [this example in the snippet library](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/filters-and-actions/cmb2_init_before_hookup-add-fields.php#L6-L37).

**Comment by DevinWalker** [comment]
This is great. Thanks for taking the time to answer my questions.
