### ISSUE TITLE
Docs request: css for metabox display

### ISSUE THREAD

**Issue by Ramblurr** [WebDevStudios/CMB2#217]
It would be nice if the css classes used in the metabox fields were documented. Even better would be a sample css theme to work off of.

**Comment by jtsternberg** [comment]
cc: @gregrickaby @coreymcollins, My CSS partners in crime.

**Comment by coreymcollins** [comment]
Hey @Ramblurr - I just updated the docs to list the class for each field type beneath their example usage: https://github.com/WebDevStudios/CMB2/wiki/Field-Types

The class displayed is the class added by CMB2 to the parent div of the field itself, so you now have an easy reference for each field type when needing to add additional styles or functionality to the WP Dashboard.

**Comment by Ramblurr** [comment]
Super, thanks @coreymcollins, thanks exactly what I was looking for.
