### ISSUE TITLE
jtsternberg: When you publish tutorial Front-end post? Im not spammer.

### ISSUE THREAD

**Issue by kidesigner** [WebDevStudios/CMB2#223]
I just want to ask you: When you publish tutorial Front-end post?

It has been nearly one month since I asked you about this problem, I and my project was paused to wait for your tutorial.

Im not spammer, i very need it because CMB2 is an important part of my project. I love CMB2 plugin.

PS: Sorry my bad EL.

**Comment by Strap1** [comment]
I have no idea when the tutorial will be published, but I suggest you wait patiently. You can see that this project is actively maintained, enjoyed by many, and most importantly, is free! I suspect you are not the only one who would like this tutorial, but banging at the door this way will likely not make it come any sooner! (Sorry for off-topic post).

**Comment by kidesigner** [comment]
@Strap1 : Thank you for your reply. I can wait, but I want to see his plan I was determined to get time to complete my project.
