### ISSUE TITLE
File works in group but file_list doesn't?

### ISSUE THREAD

**Issue by qwertydude** [WebDevStudios/CMB2#224]
I know your docs say file field shouldn't work in groups, but it seems to for me. What problem is there meant to be?

However, file_list has problems when re-ordering if more than one image is selected. The URL gets moved to the wrong field.

**Comment by tw2113** [comment]
Can confirm as well. Here's my saved meta when I did some debugging for a forum thread.

**BEFORE trying to reorder, after initial save:**
```
a:2:{
	i:0;
	a:2:{
		s:23:"_omni_grupo_anexo_title";
		s:4:"1234";
		s:31:"_omni_portfolio_attachment_list";
		a:1:{
			i:10897;
			s:78:"http://wds.dev/wp-content/uploads/2015/08/4dffa40bbefa68fd45af84442d4de867.gif";
		}
	}
	i:1;
	a:2:{
		s:23:"_omni_grupo_anexo_title";
		s:4:"5678";
		s:31:"_omni_portfolio_attachment_list";
		a:1:{
			i:10884;
			s:78:"http://wds.dev/wp-content/uploads/2015/08/046c93773389381773f7eb241df44632.gif";
		}
	}
}
```
**AFTER reordering and second save:**
```
a:2:{
	i:0;
	a:2:{
		s:23:"_omni_grupo_anexo_title";
		s:4:"5678";
		s:31:"_omni_portfolio_attachment_list";
		a:1:{
			i:10897;
			s:78:"http://wds.dev/wp-content/uploads/2015/08/4dffa40bbefa68fd45af84442d4de867.gif";
		}
	}
	i:1;
	a:1:{
		s:23:"_omni_grupo_anexo_title";
		s:4:"1234";
	}
}
```

Image value switched the index they are in, and the second value is lost.

**Comment by jtsternberg** [comment]
For confirmation, are you testing on the most recent updated version of trunk?

**Comment by tw2113** [comment]
I was using the latest available from .org

**Comment by tw2113** [comment]
If needed, I can test the same bits from a site running trunk a bit later or this weekend.

**Comment by tw2113** [comment]
Confirmed this is working fine in CMB2 Trunk.
