### ISSUE TITLE
text_date change the year range

### ISSUE THREAD

**Issue by liusashmily** [WebDevStudios/CMB2#226]
I used the text_date field type. However, it seems it only gave me 20 years' range.

So i am wondering if there is any way I can extend it? I could not find it in the documentation. Thanks in advance for your help!

**Comment by austinjreilly** [comment]
I accomplished this by filtering the `$l10n` array. It looks like I have access to all of the [settings for the jQuery UI Datepicker widget](http://api.jqueryui.com/datepicker/).

```php
function update_date_picker_defaults( $l10n ) {
    $current_year = date('Y');
    $l10n['defaults']['date_picker']['yearRange'] = '1975:'.$current_year;
    
    return $l10n;
}
add_filter( 'cmb2_localized_data', 'update_date_picker_defaults' );
```

**Comment by joshuadavidnelson** [comment]
Be careful: http://www.wikiwand.com/en/Year_2038_problem

**Comment by austinjreilly** [comment]
@joshuadavidnelson Is there something specific that I'm doing in the code snippet I included above that makes me more susceptible to that problem than anyone else using the jQuery UI Datepicker widget?

**Comment by joshuadavidnelson** [comment]
No, either way, if you save a timestamp value great than 2147483647 (Jan 19, 2038) it could result in issues later when you try to retrieve it. So, if you're adding years to the date range I'd limit it to 2037.

**Comment by tnorthcutt** [comment]
Closing as it looks like this is closed by https://github.com/WebDevStudios/CMB2/issues/226#issuecomment-78278448
