### ISSUE TITLE
Request: Styling in LESS

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#231]
Would it be possible to have LESS and SCSS provided?  I think many people are more familiar with LESS than SASS, this would make alterations to the code easier.

**Comment by jtsternberg** [comment]
Sorry, no that will not happen. Our team is sass-only, and there would be very little motivation to maintain a LESS version adjacent to the SASS version. If you want to contribute, feel free to edit the css directly. If it's a PR we want to merge in, we can then talk about getting it back over to the SASS files.
