### ISSUE TITLE
Feature Request: Callback for Default

### ISSUE THREAD

**Issue by joshuadavidnelson** [WebDevStudios/CMB2#233]
It would be nice to have a callback option for default values, to populate defaults based on the field object. Or, the specific example I'm thinking of is a default for color picker that is a random color generated by a [callback function](https://stackoverflow.com/questions/5614530/generating-a-random-hex-color-code-with-php/9901154#9901154).

**Comment by jtsternberg** [comment]
I like it. Added to trunk. The callback passes in an array of all the field arguments as the first argument, and the field object as the second argument. (which means you can get the post id using `$field->object_id`)

**Comment by joshuadavidnelson** [comment]
👍 I'll try it out later tonight!

**Comment by joshuadavidnelson** [comment]
Awesome stuff, thanks!
