### ISSUE TITLE
text_money field at 100% width when context=side

### ISSUE THREAD

**Issue by manwithpowers** [WebDevStudios/CMB2#234]
It looks like the "cmb2_text_money" style (width:90px) gets overridden by the #side-sortables style and the field is set to 100% width, putting the currency symbol on a different line when the metabox is set to be in the side column.

My code:
```
$meta_boxes[] = array(
    'id'         => 'product_price',
    'title'      => 'Price',
    'object_types'      => array('custom_post_types_here'),
    'context'    => 'side',
    'priority'   => 'default',
    'show_names' => true,
    'fields'     => array(
      array(
        'name' => 'Retail Price',
        'desc' => '',
		'id'   => 'tm_retail_price',
        'type' => 'text_money',
      ),
      array(
        'name' => 'Wholesale Price',
        'desc' => '',
		'id'   => 'tm_wholesale_price',
        'type' => 'text_money',
      ),
    ),
  );
```
![screen shot 2015-03-06 at 1 50 33 pm](https://cloud.githubusercontent.com/assets/5508635/6525615/d1d5eaca-c407-11e4-8506-f0d9606402bb.png)

Unfortunately, I don't use SASS, so not sure I'm up to the task of a pull request on this issue, but seems like it should be a relatively easy fix around line 16 in `_sidebar_placements.scss`

**Comment by jtsternberg** [comment]
Thank you for reporting. It's fixed in trunk.

**Comment by manwithpowers** [comment]
Thanks for the quick fix!
