### ISSUE TITLE
Get All Object Type Field IDS?

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#237]
I dont see any clear way to return an array of field ids associated with a specific object type or meta box.  Am I missing something?  I could really make use of that for populating a global variable with the post_meta values much quicker.

**Comment by jtsternberg** [comment]
For all field ids in a specific metabox:
```php
$field_ids = wp_list_pluck( cmb2_get_metabox( 'my_metabox_id' )->prop( 'fields' ), 'id' );
```
You can get an array of all field ids by post_type with something like this:
```php
$field_ids = array();
foreach ( CMB2_Boxes::get_all() as $cmb ) {
	$type = $cmb->mb_object_type();
	$field_ids[ $type ] = is_array( $field_ids[ $type ] ) ? $field_ids[ $type ] : array();
	$field_ids[ $type ] += wp_list_pluck( $cmb->prop( 'fields' ), 'id' );
}
```

**Comment by GregLancaster71** [comment]
Excellent! Thank you!  A nice helper function to add would be something like:
