### ISSUE TITLE
Add Metabox to edit-comment.php

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#238]
Looked through `https://github.com/WebDevStudios/CMB2-Snippet-Library` and didn't see a snippet for this.  CMB2 says it supports a `object_type => array( 'comment', )` but I don't see the functionality built into the code.  Is there a way to do this with filters?

Adding the functionality would not be hard.  A dozen lines in `CMB2_Hookup.php` in `function admin_hooks()` would do it. So I think its safe to assume this was an intentional exclusion?

**Comment by jtsternberg** [comment]
Short answer is that it was just never added. I'd be happy to take a look at a PR if you're up for one. If it's not super clean, I may leave it as being better suited for an add-on.

**Comment by GregLancaster71** [comment]
Sorry about the multiple notifications guys, I had to change some things on my local github and re-fork CMB2.
