### ISSUE TITLE
cant change upload_dir any more

### ISSUE THREAD

**Issue by cannap** [WebDevStudios/CMB2#243]
Hi i have this to change the upload dir on a custom post type this works when i dont have any Metaboxes with upload 

	add_filter( 'wp_handle_upload_prefilter', 'rsg_pre_upload' );
	function rsg_pre_upload( $file ) {
		add_filter( 'upload_dir', 'rsg_custom_upload_dir' );
		return $file;
	}

	function rsg_custom_upload_dir( $param ) {
		$id = $_REQUEST['post_id'];
		$parent = get_post( $id )->post_parent;
		if( "rsg_download" == get_post_type( $id ) || "rsg_download" == get_post_type( $parent ) )    {
			$mydir         = '/rsg_uploads';
			$param['path'] = $param['basedir'] . $mydir;
			$param['url']  = $param['baseurl'] . $mydir;
		}
		return $param;

	}

when i now add as example

after the function above 
```php
add_filter( 'cmb2_meta_boxes', 'cmb2_sample_metaboxes' );
	/**
	 * Define the metabox and field configurations.
	 *
	 * @param  array $meta_boxes
	 * @return array
	 */
	function cmb2_sample_metaboxes( array $meta_boxes ) {
		//add_filter( 'wp_handle_upload_prefilter', 'rsg_pre_upload' );

		// Start with an underscore to hide fields from custom fields list
		$prefix = '_cmb2_';

		/**
		 * Sample metabox to demonstrate each field type included
		 */
		$meta_boxes['test_metabox'] = array(
			'id'            => 'test_metabox',
			'title'         => __( 'Test Metabox', 'cmb2' ),
			'object_types'  => array( 'rsg_download', ), // Post type
			'context'       => 'normal',
			'priority'      => 'high',
			'show_names'    => true, // Show field names on the left
			// 'cmb_styles' => false, // false to disable the CMB stylesheet
			// 'closed'     => true, // Keep the metabox closed by default
			'fields'        => array(

				array(
					'name' => 'Test File List',
					'desc' => '',
					'id' => $prefix . 'file_list',
					'type' => 'file_list',
					// 'preview_size' => array( 100, 100 ), // Default: array( 50, 50 )
				),
			),
		);

		// Add other metaboxes as needed

		return $meta_boxes;
	}
```
the download folder is still wp-uploads/y/month and not rsg_uploads ;/

thx for this nice framework i found this today :dancer:

**Comment by cannap** [comment]
got it 

	function rsg_custom_upload_dir( $param ) {

		$current_page = $_SERVER['HTTP_REFERER'];
		$id          = $_REQUEST['post_id'];
		$parent      = get_post( $id )->post_parent;

		//"rsg_download" == get_post_type( $id ) || "rsg_download" == get_post_type( $parent ) )

		if ( "rsg_download" == get_post_type( $id ) || "rsg_download" == get_post_type( $parent ) ) {
			$mydir         = '/rsg_uploads';
			$param['path'] = $param['basedir'] . $mydir;
			$param['url']  = $param['baseurl'] . $mydir;

		} elseif ( strpos( $current_page, 'rsg_download' ) ) {
			$mydir         = '/rsg_uploads';
			$param['path'] = $param['basedir'] . $mydir;
			$param['url']  = $param['baseurl'] . $mydir;

		}

		return $param;

	}

**Comment by jtsternberg** [comment]
Looks like you got it, so closing.

**Comment by JUVOJustin** [comment]
I still have this issue. The upload_dir seems to be missing some context. I don´t get any post id when using with cmb2. Same filter fired for regular post types and without cmb2 works as it is supposed to. 

@cannap Is there a reason you moved the add_filter( 'upload_dir', 'rsg_custom_upload_dir' ); inside the prefilter´s callback?

**Comment by tw2113** [comment]
Can you provide your own code for what you're using for all of this?

**Comment by cannap** [comment]
i dont have this any more

**Comment by JUVOJustin** [comment]
Adding filter with loader class
`$this->loader->add_filter('upload_dir', $fileHandling, "modifyUploadDir");`


This is the callback. It is called corretly, i verified that with the debugger.
```
public function modifyUploadDir(array $args): array {

    if (!isset($_REQUEST['post_id'])) {
        return $args;
    }

    $post = get_post();

    // Check the post-type of the current post
    if ( Downloads_PT::PT == $post->post_type ) {
        $args['path'] = $this->uploadDirPath;
        $args['url'] = $this->uplaodDirUrl;
        //$args['basedir'] = plugin_dir_path(__FILE__) . "uploads";
        //$args['baseurl'] = plugin_dir_url(__FILE__) . "uploads";
    }

    return $args;
}
```
When i upload a file using cmb2 the $_REQUEST['post_id'] is either null or zero. When used on a default post type and without cmb2 the correct post id is passed.

**Comment by tw2113** [comment]
Curious what the stack trace would be on that, as $_REQUEST is a superglobal to PHP, and not something custom/special to CMB2
