### ISSUE TITLE
problem saving postmeta?

### ISSUE THREAD

**Issue by yivi** [WebDevStudios/CMB2#245]
I must be doing something fairly basic wrong... but I can't fathom what.

Brand new WP 4.1.1 install, only CMB2 installed, and the plugin that's going to define the post-types for the site (almost blank apart from a very simple definition so far).

I have:
```
add_filter( 'cmb2_init', 'ojiva_portfolio_metaboxes_fields' );
function ojiva_portfolio_metaboxes_fields() {
	$prefix = '_ojiva_portfolio_';

	$main = new_cmb2_box( [
		'id'           => $prefix . 'main',
		'title'        => __( 'Principal', 'ojiva-plugin' ),
		'context'      => 'normal',
		'priority'     => 'high',
		'show_names'   => true,
		'object_types' => [ 'ojiva-portfolio ' ]
	] );

	$main->add_field(
		[
			'name'      => __( 'URL', 'ojiva-plugin' ),
			'id'        => $prefix . 'url',
			'type'      => 'text_url',
			'protocols' => [ 'http', 'https' ]
		]
	);

	$main->add_field(
		[
			'name'        => __( 'Fecha', 'ojiva-plugin' ),
			'id'          => $prefix . 'fecha_realizacion',
			'type'        => 'text_date_timestamp',
			'date_format' => 'd-m-Y',
		]
	);
```
`ojiva-portfolio` is my CPT, and shows appropriately in the dashboard, and can save new posts. The metabox and fields display and work (with the exception of ignoring my date_format, as I commented in #39).

But when I click publish/update, no postmeta are created... There are only a few rows in my postmeta table, so there is no room for me somehow missing the rows. They are simply not there (the post I'm editing is 10).
![screen shot 2015-03-11 at 12 18 11](https://cloud.githubusercontent.com/assets/1815039/6595247/bb9a392a-c7e8-11e4-8aec-2b1c0202938c.png)

Am I missing something? 

Many thanks and regards.

**Comment by yivi** [comment]
In action:

http://cl.ly/0L3p1R0f1y40

**Comment by mattkrupnik** [comment]
Try set instead  
```php 
'object_types' => [ 'ojiva-portfolio ' ]
 ``` 
this one 
```php
'object_types' => 'ojiva-portfolio ' 
``` 
or 
```php 
'object_types' => array( 'ojiva-portfolio ')
 ```

**Comment by jtsternberg** [comment]
you also have a space in your post_type name, `'ojiva-portfolio '` should probably be `'ojiva-portfolio'`.

**Comment by yivi** [comment]
Wow. I'm really sorry... A typical case of being a moron. 
Many thanks for spotting that space for me... :P

**Comment by jtsternberg** [comment]
It happens. ;)
