### ISSUE TITLE
Sortable group not saving radio options initially

### ISSUE THREAD

**Issue by joshuadavidnelson** [WebDevStudios/CMB2#246]
I've created a sortable group with a couple of fields, one of which is a radio option that defaults to one of three choices. It appears to work just fine in populating new rows to the group, and saving values from the other fields, but on the post-new.php save it only stores the first group's radio button value and the others revert to the default. It works fine on the the post.php screen's save, so it just needs to be created and then re-saved with new values.

**Comment by jtsternberg** [comment]
related #341

**Comment by jtsternberg** [comment]
Should be good in the trunk branch. please test.

**Comment by joshuadavidnelson** [comment]
This looks to be working now, thanks!
