### ISSUE TITLE
CMB2 (and 1) Multiple File upload and Single File upload Fields dont work

### ISSUE THREAD

**Issue by exbm** [WebDevStudios/CMB2#249]
CMB2 Team,

First thanks for release such a valuable tool in theme and plugin development. This is a huge timesaver.

I have a custom page template that I want to show CMB2 meta boxes on. the multiple file upload field correctly shows when you select my custom page template in the page template dropdown box on the page edit in wp admin. However, when I click on the button nothing happens. I didnt find any javascript errors.  I am using wp ver 3.8.1

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
