### ISSUE TITLE
Email sending

### ISSUE THREAD

**Issue by levipadre** [WebDevStudios/CMB2#251]
Hi,

I just stared to use this plugin and seems really cool, thank for that.
I have a question. I would like to send the the actual page url to an email address using the email field, but I don't know how can I add a submit button and send it.
This function would be like a recommendation form.
Is that possible? Do you have any suggestion about it?
I would really appreciate some help. Thanks.

**Comment by jtsternberg** [comment]
CMB2 is made to save and display values. If you want a submission form, your best bet would be to [read this tutorial](http://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form/).
