### ISSUE TITLE
Group Repeater not working on v2.0.3

### ISSUE THREAD

**Issue by kidesigner** [WebDevStudios/CMB2#252]
Group Repeater wrong saving data.

**Comment by maciekkus** [comment]
I've noticed that issue today too. For me saving (for the first time only) seems to be working OK. The problem is after refreshing edit post page. Every field group is the same (as first one) or there is only one. Saving again brokes data.

**Comment by phh** [comment]
Seems like the first input field of the group is gone. Label is just shown with an empty cmb-td div.

Using version 2.0.2 works.

**Comment by jtsternberg** [comment]
Hey guys, sorry for the issues. 2.0.5 should resolve them for you. Please let me know.

**Comment by kidesigner** [comment]
It' working! Thank @jtsternberg

**Comment by jtsternberg** [comment]
:+1:

**Comment by phh** [comment]
Mine seems fixed. Yay :)
