### ISSUE TITLE
Can't add a new metabox, help needed.

### ISSUE THREAD

**Issue by AF4Q** [WebDevStudios/CMB2#253]
A friend installed the CMB2 plugin on my WordPress for some WooCommerce modification I needed. Now I need to add a new metabox but I am not in contact with that friend. So I need some help:

    add_filter( 'cmb2_meta_boxes', 'bhww_core_cpt_metaboxes' );
    function bhww_core_cpt_metaboxes( $meta_boxes ) {
	$prefix = '_bhww_'; // Prefix for all fields	
	$meta_boxes[] = array(
		'id'         => 'bhww_slides_metabox',
		'title'         => __( 'Additional Product Information - <strong>Optional</strong>', 'cmb2' ),
		'object_types'      => array( 'product' ), // Which post type to associate with?
		'context'    => 'normal',
		'priority'   => 'default',
		'show_names' => true, 					
		'fields'     => array(
			array(
				'name'    => __( 'Expert Reviews', 'cmb2' ),
				'desc'    => __( 'Anything you enter here will be displayed on the Expert Reviews tab.', 'cmb2' ),
				'id'      => $prefix . 'expertreviews_wysiwyg',
				'type'    => 'wysiwyg',
				'options' => array( 'textarea_rows' => 5, ),
			),
		),
	);
	return $meta_boxes;	
    }

I want a couple of URL type meta boxes and I tried added them in the fields => array but it starts giving me an error in object_types line. Any help will be highly appreciated. Thanks.

**Comment by jtsternberg** [comment]
Hey @AF4Q, best bet would be to follow the examples in [`example-functions.php`](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php) and have a look at the [basic usage instructions](https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage). If you need more assistance, please open a new ticket at the [wordpress.org plugin forums](http://wordpress.org/support/plugin/cmb2).
