### ISSUE TITLE
Frontend form not getting reset for custom post type after saving and reloading page.

### ISSUE THREAD

**Issue by shivgre** [WebDevStudios/CMB2#254]
I used CMB2 to create a frontend form with some wysiwyg editors and file_list inputs. Its rendering fine.

But after I save it, and then whenever I open this form again it displays the last entered values, specially the file_list input which is showing old files added in it the last time.
Please let me know how to fix this as I cant find anything in documentation for CMB2.

**Comment by kidesigner** [comment]
I also have same problem.

**Comment by shivgre** [comment]
@kidesigner I found the issues cause: no matter if you provide the post id in the short codes to display frontend form or not, its taking the page_id by default on which the form is displayed and then it saves that data in that page_id in database as postmeta which then displays it on frontend form on reload.

Should be an option to add frontend form for custom post types which is not dependent on post_id(page_id).

**Comment by kidesigner** [comment]
you've solved the problem yet? Please teach me, thank you so much!

**Comment by shivgre** [comment]
@kidesigner I found a workaround to clear the form values using jquery.

I have given a custom class(reset_frontend_form_feilds) to all the fields in form which I wanted to clear on reload. Also file_list fields I cleared the li inside the ul for that file_list field(you should inspect your file_list field html for the ul idafter you attach a file and then use it in the below jQuery code to reset).

    jQuery(document).ready(function($){
    //        $('form#formId').clearForm();
            $('form#formId').find('.reset_frontend_form_feilds').val('');
    //        // RESET THE FILE LIST FIELD
            $('ul#tormId_uploads-status').empty();
      });

**Comment by kidesigner** [comment]
I think it's will working with your way, but seem this isn't right way. Thank you so much. How i can contact to you with skype? I want ask you something

**Comment by shivgre** [comment]
@kidesigner send me you skype Id I will add you.

**Comment by kidesigner** [comment]
hbk.cvenhau

**Comment by kidesigner** [comment]
Added

**Comment by jtsternberg** [comment]
@shivgre CMB2 is made to save and display values. If you want a submission form, your best bet would be to [read this tutorial](http://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form/).
