### ISSUE TITLE
Group Field broken after update to 2.0.4

### ISSUE THREAD

**Issue by wavefreak** [WebDevStudios/CMB2#255]
So I've a Group Field, that now shows in every repeat of the group only the first group entry.
I mean the id and name of every group fields stays _group_field[0]. By the way I get the right amount of repeats.

**Comment by yivi** [comment]
I'm seeing the same.
The right values are saved in the DB (for new rows), but when rendering them it repeats the same group over and over. 

Maybe it's unrelated, but I was trying to see if I found what was going on and saw this:

CMB2.php:277
```
	foreach ( $group_val as $iterator => $field_id ) {
				$this->render_group_row( $field_group, $remove_disabled );
			}
```

Which seemed weird to me. You are initializing `$iterator` and $ `field_id`, but not using them in the foreach loop at all. Is there something I'm missing?

**Comment by jtsternberg** [comment]
Hey guys, I can confirm this issue on my end. I'm digging into it.

**Comment by wavefreak** [comment]
Fast like a rocket. Thanks.

**Comment by jtsternberg** [comment]
Sorry for the issue. Should fix it for you.
