### ISSUE TITLE
Support later registration of metaboxes (after init action hook)

### ISSUE THREAD

**Issue by PeterKnight** [WebDevStudios/CMB2#256]
Right now I believe metabox registration happens during the init hook phase which means you can't tap into global $post for example at the time of configuring the metabox fields. Is there a reason why CMB2 meta boxes need to be registered so early in the load sequence?

**Comment by jtsternberg** [comment]
There are several reasons, yes. Please provide an example of what you're trying to do. It's likely there's a filter, action or callback available to accomplish it.

**Comment by PeterKnight** [comment]
So far I had two situations where it would have been convenient to get $post access: 

1 Setting a dynamic value for a default value of a field, i.e. based on another field.
2 Setting dynamic data-attributes that may use post data, like the post ID. I was trying to set a nonce in a data attribute for use in some custom js ( example: wp_create_nonce( "my_action_{$post_id}" ) . There were workarounds for my scenario (using $_GET['post'] for the post id or using wp_localize_script to register custom vars later on.

**Comment by jtsternberg** [comment]
**1)** [Added in 2.0.3](https://github.com/WebDevStudios/CMB2/releases/tag/v2.0.3)), `'default'` now accepts a callback as well as an actual value. example:
field config:
```php
$cmb->add_field( array(
	'name'    => __( 'Test', 'cmb2' ),
	'id'      => $prefix . 'test',
	'type'    => 'text',
	'default' => 'prefix_set_test_default',
) );
```
callback:
```php
function prefix_set_test_default( $field_args, $field ) {
	return 'Post ID: '. $field->object_id
}
```
**2)** Can be accomplished by hooking in earlier in the field process and modify the field `'attributes'` array dynamically. example:
field config:
```php
$cmb->add_field( array(
	'name'   => __( 'Test', 'cmb2' ),
	'id'     => $prefix . 'test',
	'type'   => 'text',
	'before' => 'prefix_set_field_data_attr',
) );
```
callback:
```php
function prefix_set_field_data_attr( $args, $field ) {
	$field->args['attributes']['data-postid'] = $field->object_id;
}
```

**Comment by PeterKnight** [comment]
Perfect! I needs to update. Thank you for the examples.

**Comment by jtsternberg** [comment]
Updated the wiki as well: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#setting-a-default-field-value-via-a-callback

**Comment by uzzaldey** [comment]
Hi, Is there any way to crate different custom meta box with different name (as if i create a custom meta box for a page it shows all the pages)for different page like contact, about or any other pages? Please help me . Thanks in advance.
