### ISSUE TITLE
v2.0.5 > Fatal error: Call to undefined method CMB2_Utils::isempty()

### ISSUE THREAD

**Issue by AlchemyUnited** [WebDevStudios/CMB2#259]
Just updated my Pantheon dev env and pulled this error. 

Fatal error: Call to undefined method CMB2_Utils::isempty() in /srv/bindings/4632511e60064e2280577e7a8cf827eb/code/wp-content/plugins/cmb2/includes/CMB2_Field.php on line 585

fyi - I'm running 2.0.0.4 - via ServerPress - locally and not seeing that error. Also, I just went back to 2.0.0.4 on Pantheo and everything is fine.

**Comment by jtsternberg** [comment]
It's [definitely there](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Utils.php#L128-L130). It's possible the update was corrupt? Very little changed between 2.0.4 and 2.0.5, and nothing change in either the CMB2_Field.php file or the CMB2_Utils.php file. If you're really talking about 2.0.0.4 and not 2.0.4, then it's possible some things have changed and you may be using deprecated methods. Best to read through the [changelog](https://github.com/WebDevStudios/CMB2/blob/master/CHANGELOG.md).

**Comment by AlchemyUnited** [comment]
Yes. 2.0.0.4 (not 2.0.4) but shouldn't an update via the admin CP more or less just give me a fresh copy, etc?

**Comment by AlchemyUnited** [comment]
I'm not using any of the CMB2 methods myself so best I can tell its the plugin calling the plugin, yes?

**Comment by AlchemyUnited** [comment]
Ok. Sorry. I needed to commit my updates in Pantheon. Sorry. Thanks for you help.

**Comment by jtsternberg** [comment]
Ok thanks for updating.
