### ISSUE TITLE
Make wysiwyg repeatable pretty please?

### ISSUE THREAD

**Issue by rclai** [WebDevStudios/CMB2#26]
This would be awesome!

**Comment by dmott** [comment]
+1 to this!

**Comment by bonny** [comment]
It may be a bit cumbersome to do with TinyMCE, but it's absolutely possible. Other plugins manage to make TinyMCE repeatable/drag and drop/order changeable (I did it in my own plugin [Simple Fields](http://simple-fields.com)).

**Comment by jtsternberg** [comment]
Currently not supported, but is on the list for improvements.

**Comment by jtsternberg** [comment]
Related #264
