### ISSUE TITLE
wysiwyg not working

### ISSUE THREAD

**Issue by fysalyaqoob** [WebDevStudios/CMB2#260]
wysiwyg is not working in repeatable group. 

check screenshot:  http://awesomescreenshot.com/02b4oqjs7e

**Comment by jtsternberg** [comment]
It is not supported. Please see the documentation for [field types](https://github.com/WebDevStudios/CMB2/wiki/Field-Types).

**Comment by sbouafif** [comment]
What happened to the wysiwyg support in groups? It seems to work well a few days ago.

**Comment by jtsternberg** [comment]
It's never been supported. It's on our wish-list.

**Comment by sbouafif** [comment]
Ok. Thank you :)

**Comment by jtsternberg** [comment]
related: #264
