### ISSUE TITLE
add_field via foreach

### ISSUE THREAD

**Issue by teamcrisis** [WebDevStudios/CMB2#261]
I'm trying to add fields via a foreach:
```
foreach($multicheckbox_meta_boxes as $value => $meta_box_name) { 

$cmb_about_page->add_field( array(
   'name'        => $meta_box_name . ' Field',
   'desc'        => 'Set your value.',
   'id'          => $prefix . $meta_box_name,
   'type'        => 'checkbox',
));

}
```

The fields add without an issue, but the values do not save. Any idea why? I'm not seeing any info in the wiki about this. Did I simply miss it?

**Comment by jtsternberg** [comment]
Can you create a new ticket in the support forums? [https://wordpress.org/support/plugin/cmb2](https://wordpress.org/support/plugin/cmb2)

Also, when you do, please provide the entire code you're using to add your metabox.
