### ISSUE TITLE
Not saving data in a 'page' with different template

### ISSUE THREAD

**Issue by codetorex** [WebDevStudios/CMB2#266]
Wordpress Version: **4.1.1**
CMB2 Version: both **trunk** and **2.0.5**

I had a metabox for pages only, but it wasn't saving the meta data. I debugged the problem and found out; **save_post** action is never reached by WP(**wp_insert_post** from **post.php**) when post type is 'page' and 'page_template' is set. It returns 0 before executing the actions hooked by CMB2.

**post.php:3410**
```
$post = get_post( $post_ID );

if ( ! empty( $postarr['page_template'] ) && 'page' == $data['post_type'] ) {
	$post->page_template = $postarr['page_template'];
	$page_templates = wp_get_theme()->get_page_templates( $post );
	if ( 'default' != $postarr['page_template'] && ! isset( $page_templates[ $postarr['page_template'] ] ) ) {
		if ( $wp_error ) {
			return new WP_Error('invalid_page_template', __('The page template is invalid.'));
		} else {
			return 0; // function returns from here
		}
	}
	update_post_meta( $post_ID, '_wp_page_template', $postarr['page_template'] );
}
```

I was imported the subject page from somewhere else, probably *page_template* variable was different because of this. Creating a new page or using with clean installation doesn't causes this error. So this is a rare bug depends on data.

For fixing the problem I added a new action hook for **pre_post_update** after the line in **CMB2_hookup.php:68**;
```
add_action( 'save_post', array( $this, 'save_post' ), 10, 2 );
add_action( 'pre_post_update', array( $this, 'save_post' ) ); // fix
```

After the change it works but I didn't tested extensively, so I don't know if it causes any problems later or if it is a correct solution.

Thanks

**Comment by jtsternberg** [comment]
The only reason `wp_insert_post` would return early based on the conditions you listed (when post type is 'page' and 'page_template' is set), is if the page has a page-template set that is not actually in your theme. This could happen if you had one theme installed, saved the page template, then switched themes. The error returned is:
```php
return new WP_Error('invalid_page_template', __('The page template is invalid.'));
```

So this is definitely not a CMB2 issue (I just tested a page with a page template set, and it worked as expected), but rather an issue with your particular setup.
