### ISSUE TITLE
Front-end edit post

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#268]
Hi, I found the great snippet for creating new posts with CMB2. Is it possible to edit the post somehow also?

**Comment by tw2113** [comment]
Hey @vasikgreif could you please start a thread over at http://www.wordpress.org/support/plugin/cmb2 and we'll get your questions answered the best we can there?

We try to leave the issues tracker here for confirmed bugs or enhancement ideas, an the support forums for implementation questions.

Thank you :)
