### ISSUE TITLE
How to: Dropdown value dynamic using AJAX to another dropdown value

### ISSUE THREAD

**Issue by mayeenulislam** [WebDevStudios/CMB2#270]
![two dropdown menus](https://cloud.githubusercontent.com/assets/4551598/6963596/ec158718-d962-11e4-84d8-abc6cb76cdfa.png)

I have two `select` fields, where the second field should be dependent to the first.

* the first one is loading its options using a custom function and within it using `get_posts()`, and,
* the second one is loading its options using another custom function and within it using `get_post_meta( 10, 'my_meta_key' )`

Where you can see that the `post_id` value (10) is hard coded. I need it to be dynamic as per the selection of the first dropdown. I used WordPress AJAX. But need a basic direction so that I can proceed.

**Comment by jtsternberg** [comment]
Hey @mayeenulislam this sounds like a good question for [wordpress.stackexchange.com](http://wordpress.stackexchange.com/), as it's a very specific implementation question.

We try to leave the issues tracker here for confirmed bugs or enhancement requests, and the support forums for implementation questions.

Thank you :)

**Comment by JayWood** [comment]
@mayeenulislam I created a snippet that should help you, if you have any questions just let me know. https://github.com/JayWood/cmb2-ajaxified-dropdown-snippet

**Comment by mayeenulislam** [comment]
@JayWood thanks a lot for your patch. Hope someone surely gonna get help with this. I loved CMB2, but just switched from it to my core. :(

**Comment by regidias2006** [comment]
Hello,

Mayeenulislam, i have your problem in my code you see  a light for this question ?

**Comment by mayeenulislam** [comment]
@regidias2006 I switched from CMB2 for that case, and implemented my own framework.

**Comment by regidias2006** [comment]
@mayeenulislam I could bring a metabox with ajax and dropdown selector using cmb2 to my website if you want I can provide here or soon ride a tutorial and post the link here, but still thank you for your attention.

**Comment by mayeenulislam** [comment]
@regidias2006 I, and the CMB2 based WP Dev. community would love to have such tutorials or code snippets. We will be thankful to you if you provide so. Thanks in advance. :)
