### ISSUE TITLE
Wiki: Basic usage code typo 

### ISSUE THREAD

**Issue by andreacanton** [WebDevStudios/CMB2#271]
In the wiki at [Basic Usage - Create a Metabox](https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage#create-a-metabox) I've found a typo in the definition of the function `cmb2_sample_metaboxes`

```php
function cmb2_sample_metaboxes( array $meta_boxes ) {
```
should be

```php
function cmb2_sample_metaboxes() {
```
###### Flattering time
You saved days of work with this project, thank you for the great effort! Good job, I mean it!

**Comment by jtsternberg** [comment]
@andreacanton thanks for reporting, It's fixed! The wiki is a public wiki, so feel free to make any future corrections if see them.

**Comment by andreacanton** [comment]
Sorry, didn't noticed the "Edit" button :D
Thanks!

**Comment by jtsternberg** [comment]
:thumbsup:
