### ISSUE TITLE
Donate / Support

### ISSUE THREAD

**Issue by spwebguy** [WebDevStudios/CMB2#273]
Hi there,

I really hope you will keep on maintaining CMB2, I'm sure I'm not the only one that heavily relies on it for themes/plugins. I would like to encourage you and would totally be able to make a donation.

**Comment by DevinWalker** [comment]
+1 here

**Comment by leogopal** [comment]
+1

**Comment by gilbarbara** [comment]
me too!

**Comment by BoweFrankema** [comment]
+1

**Comment by carasmo** [comment]
+1
contact@webdevstudios.com 
![screen shot 2016-01-21 at 11 36 10 pm](https://cloud.githubusercontent.com/assets/1124594/12502528/d2a4f7e2-c097-11e5-8f70-da3bd9426c79.png)

**Comment by carasmo** [comment]
I sent you want I would have spent on ACF for a single site I'm working on, my own. I also bought ACF and Elliot is really nice, but I really want something that I can use without a commercial plugin, the file_list is GREAT as a gallery and the hybrid group is awesome for repeating fields. Wish there was drag and drop and the tiny_mce thing with the repeater would work better, but still it's an amazing library. Thank you deeply.

**Comment by richardtape** [comment]
:+1: Justin, WDS team; where do we send money to ensure this is specifically for CMB2. It's invaluable.

**Comment by spwebguy** [comment]
![screen shot 2016-01-22 at 3 58 13 pm](https://cloud.githubusercontent.com/assets/8936613/12505354/fdece764-c120-11e5-9a42-b7a2e0b7ecf6.png)

Same here. Thank you for everything. Repeatable TinyMCE/ drag and drop and anything you can come up with to make CMB2 even more awesome than what it is already would be wonderful.

**Comment by richardtape** [comment]
![wds25paypal](https://cloud.githubusercontent.com/assets/116946/12516504/a2c72d88-c0e2-11e5-86ea-9ba44840476e.png)

I'm liking the $25 idea. Have a few cold ones on me, folks.

**Comment by tw2113** [comment]
Closing as not an issue. People can still comment on closed issues if they so choose to :)

Thanks everyone who's donated thus far.
