### ISSUE TITLE
featured image displays above form on front end after form submission 

### ISSUE THREAD

**Issue by leetee4000** [WebDevStudios/CMB2#274]
I have created a form on the front end of my site for a custom post type and allow users to upload images which I set as the featured image. 

This works fine apart from the fact that the featured image is then displayed above the form once the form has been submitted and is still there even after refreshing and even after logging out and logging back in! 

I have no idea where the HTML is coming from.  Can anyone assist me with getting rid of this?  

NB:  I am using the previous version of this plugin (https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/).  I have added this query to the other plugins issue page but have had no response and was hoping I would get some kind of response within the new version as I assume the code is very similar.

class uploadForm {

    // Set prefix

    public $prefix = '_cmb_'; 

    /**

     * Construct the class.

     */

    public function __construct() {

        add_filter( 'cmb_meta_boxes', array( $this, 'cmb_metaboxes' ) );

        add_shortcode( 'cmb-form', array( $this, 'do_frontend_form' ) );

        add_action( 'init', array( $this, 'initialize_cmb_meta_boxes' ), 9 );

        add_action( 'save_post', array( $this, 'save_fields' ), 10, 4 );

    }

    /**

     * Define the metabox and field configurations.

     */

    public function cmb_metaboxes( array $meta_boxes ) {

        /**

         * Metabox for the "Memorials" front-end submission form

         */

        $meta_boxes['upload_files_metabox'] = array(

            'id'         => 'files',

            'title'      => __( 'Upload files', 'cmb' ),

            'pages'      => array( 'Files' ), // Post type

            'context'    => 'normal',

            'priority'   => 'high',

            'show_names' => true, // Show field names on the left

            'fields'     => array(

                array(

                    'name'       => __( 'Title', 'cmb' ),

                    'desc'       => __( 'Title for files, link or media', 'cmb' ),

                    'id'         => $this->prefix . 'title',

                    'type'       => 'text',

                ),

                array(

                    'name'       => __( 'Description', 'cmb' ),

                    'desc'       => __( 'Description of files, link or media', 'cmb' ),

                    'id'         => $this->prefix . 'description',

                    'type'       => 'textarea',

                ),

                array(

                    'name'     => __( 'Project stage', 'cmb' ),

                    'desc'     => __( 'Assign to stage of project', 'cmb' ),

                    'id'       => $this->prefix . 'category',

                    'type'     => 'taxonomy_select',

                    'taxonomy' => 'stages', // Taxonomy Slug

                ),

                array(

                    'name' => __( 'Link to website', 'cmb' ),

                    'desc' => __( 'Add url to website', 'cmb' ),

                    'id'   => $this->prefix . 'url',

                    'type' => 'text_url',

                    'protocols' => array('http', 'https', 'ftp', 'ftps', 'mailto', 'news', 'irc', 'gopher', 'nntp', 'feed', 'telnet'), // Array of allowed protocols

                    // 'repeatable' => true,

                ),

               array(

                    'name' => __( 'Add image', 'cmb' ),

                    'desc' => __( 'Upload an image or enter a URL', 'cmb' ),

                    'id'   => $this->prefix . 'image',

                    'type' => 'file',

                ),

              array(

                  'name'         => __( 'Add files', 'cmb' ),

                  'desc'         => __( 'Upload file(s)', 'cmb' ),

                  'id'           => $this->prefix . 'file_list',

                  'type'         => 'file_list',

              ),

              array(

                'name' => __( 'oEmbed', 'cmb' ),

                'desc' => __( 'Enter a youtube, twitter, or instagram URL to embed. Supported services are listed at <a href="http://codex.wordpress.org/Embeds">http://codex.wordpress.org/Embeds</a>.', 'cmb' ),

                'id'   => $this->prefix . 'embed',

                'type' => 'oembed',

             ), 

                array(

                    'name'       => __( '', 'cmb' ),

                    'id'         => $this->prefix . 'select-files',

                    'type' => 'multicheck',

                    'options' => array(

                        'link' => '<span class="dashicons dashicons-admin-links"></span>',

                        'image' => '<span class="dashicons dashicons-format-image"></span>',

                        'files' => '<span class="dashicons dashicons-admin-page"></span>',

                        'embed' => '<span class="dashicons dashicons-admin-media"></span>'

                    )

                ),

            ),

        );

        return $meta_boxes;

    }

    /**

     * Shortcode to display a CMB form for a post ID.

     */

    public function do_frontend_form() {

        // Default metabox ID

        $metabox_id = 'upload_files_metabox';

        // Get all metaboxes

        $meta_boxes = apply_filters( 'cmb_meta_boxes', array() );

        // If the metabox specified doesn't exist, display error.

        if ( ! isset( $meta_boxes[ $metabox_id ] ) ) {

            return __( "A metabox with the specified 'metabox_id' doesn't exist.", 'cmb' );

        }

        // This is the WordPress post ID where the data should be stored/displayed.

        $post_id = 0;

        if ( $new_id = $this->intercept_post_id() ) {

            $post_id = $new_id;

            echo '<div id="message">';
            echo '<p>Your file entry has been submitted.</p>';
            echo '</div>';
        } 

        // Shortcodes need to return their data, not echo it.

        $echo = false;

        // Get our form

        $form = cmb_metabox_form( $meta_boxes[ $metabox_id ], $post_id, $echo );

        return $form;

    }

    /**

     * Get data before saving to CMB.

     */

    public function intercept_post_id() {

        // Check for $_POST data

        if ( empty( $_POST ) ) {

            return false;

        } 

        // Check nonce

        if ( ! ( isset( $_POST['submit-cmb'], $_POST['wp_meta_box_nonce'] ) && wp_verify_nonce( $_POST['wp_meta_box_nonce'], cmb_Meta_Box::nonce() ) ) ) {

            return;

        }

        // Setup and sanitize data

        if ( isset( $_POST[ $this->prefix . 'title' ] ) && ($_POST[ $this->prefix . 'title'] != '')   ) {

            //add post data to database    

            $this->new_submission = wp_insert_post( array(

                'post_title'            => sanitize_text_field( $_POST[ $this->prefix . 'title' ] ),

                'post_content'          => sanitize_text_field( $_POST[ $this->prefix . 'description' ] ),

                'post_author'           => get_current_user_id(),

                'post_status'           => 'publish', // Set to draft so we can review first

                'post_type'             => 'file',

            ), true );

            // If no errors, save the data into a new post draft

            if ( ! is_wp_error( $this->new_submission ) ) {

                 wp_set_object_terms( $this->new_submission, $_POST[ $this->prefix . 'category' ], 'stages' ); //add select custom taxonomy (project stage)

                return $this->new_submission;

            } 

        } else {
            return new WP_Error( 'post_data_missing', __( 'File post requires a title.' ) );
        }

    }

    /**

     * Grant temporary permissions to subscribers.

     */

    public function grant_publish_caps( $caps, $cap, $args ) {

        if ( 'edit_post'  == $args[0] ) {

            $caps[$cap[0]] = true;

        }

        return $caps;

    }

    /**

     * Save custom fields and uploaded files 

     */

    public function save_fields( $post_id, $post  ) {

            if($_POST['_cmb_url'] != ''){

                add_post_meta( $post_id, '_cmb_url', $_POST['_cmb_url'], true );

            }

            if($_POST['_cmb_embed'] != ''){

                add_post_meta( $post_id, '_cmb_embed', $_POST['_cmb_embed'], true );

            }            

            if($_POST['_cmb_file_list'] != ''){

                add_post_meta( $post_id, '_cmb_file_list', $_POST['_cmb_file_list'], true );

            }

            if($_POST['_cmb_image'] != ''){

                add_post_meta( $post_id, '_cmb_image', $_POST['_cmb_image'], true );

            } 

            if($_POST['_cmb_image_id'] != 0){

                add_post_meta( $post_id, '_cmb_image_id', $_POST['_cmb_image_id'], true );

                $img_id = $_POST['_cmb_image_id'];

            }

            //set featured image
            if($img_id){
               set_post_thumbnail( $post_id, $img_id );
            }    

    }

    /**

     * Initialize CMB.

     */

    public function initialize_cmb_meta_boxes() {

        if ( ! class_exists( 'cmb_Meta_Box' ) ) {

            require_once 'init.php';

        }

    }

} 
$uploadForm = new uploadForm();

The HTML showing the image is:

<div id="post-200" class="post-200 page type-page status-publish has-post-thumbnail hentry">

                    <div class="text">
                                                                                                                                           <div class="thumbnail">
                                                    <img width="1840" height="3264" src="http://ibuild.fsnuclear.com/wp-content/uploads/2015/04/IMAG0235.jpg" class="attachment-full wp-post-image" alt="IMAG0235">                                                    </div>
                                                                <div class="entry">

                        <form class="cmb-form" method="post" id="files" enctype="multipart/form-data" encoding="multipart/form-data"><input type="hidden" name="object_id" value="0"><input type="hidden" id="wp_meta_box_nonce" name="wp_meta_box_nonce" value="c8d9574fe7">

<table class="form-table cmb_metabox"><tbody><tr class="cmb-type-text cmb_id__cmb_title">
<th style="width:18%"><label for="_cmb_title">Title</label></th>
    <td>
<input type="text" class="regular-text" name="_cmb_title" id="_cmb_title" value="">
<p>Title for files, link or media</p>

    </td>
</tr><tr class="cmb-type-textarea cmb_id__cmb_description">
<th style="width:18%"><label for="_cmb_description">Description</label></th>
    <td>
<textarea class="cmb_textarea" name="_cmb_description" id="_cmb_description" cols="60" rows="10"></textarea>
<p>Description of files, link or media</p>

    </td>
</tr><tr class="cmb-type-taxonomy_select cmb_id__cmb_category">
<th style="width:18%"><label for="_cmb_category">Project stage</label></th>
    <td>
<select class="cmb_select" name="_cmb_category" id="_cmb_category"> <option value="buy-plot">Buy Plot</option>
    <option value="design-house">Design House</option>
    <option value="engage-builders" selected="selected">Engage builders</option>
    <option value="misc">Misc</option>
</select>
<p>Assign to stage of project</p>

    </td>
</tr><tr class="cmb-type-text_url cmb_id__cmb_url">
<th style="width:18%"><label for="_cmb_url">Link to website</label></th>
    <td>
<input type="text" class="cmb_text_url regular-text" name="_cmb_url" id="_cmb_url" value="">
<p>Add url to website</p>

    </td>
</tr><tr class="cmb-type-file cmb_id__cmb_image">
<th style="width:18%"><label for="_cmb_image">Add image</label></th>
    <td>
<input type="text" class="cmb_upload_file" name="_cmb_image" id="_cmb_image" value="" size="45"><input class="cmb_upload_button button" type="button" value="Upload File">
<p>Upload an image or enter a URL</p>
<input type="hidden" class="cmb_upload_file_id" name="_cmb_image_id" id="_cmb_image_id" value="0"><div id="_cmb_image_id_status" class="cmb_media_status"></div>
    </td>
</tr><tr class="cmb-type-file_list cmb_id__cmb_file_list">
<th style="width:18%"><label for="_cmb_file_list">Add files</label></th>
    <td>
<input type="hidden" class="cmb_upload_file cmb_upload_list" name="_cmb_file_list" id="_cmb_file_list" value="" size="45"><input type="button" class="cmb_upload_button button cmb_upload_list" name="" id="" value="Upload Files">
<p>Upload file(s)</p>
<ul id="_cmb_file_list_status" class="cmb_media_status attach_list"></ul>
    </td>
</tr><tr class="cmb-type-oembed cmb_id__cmb_embed">
<th style="width:18%"><label for="_cmb_embed">oEmbed</label></th>
    <td>
<input type="text" class="cmb_oembed regular-text" name="_cmb_embed" id="_cmb_embed" value="" data-objectid="200" data-objecttype="post">
<p>Enter a youtube, twitter, or instagram URL to embed. Supported services are listed at <a href="http://codex.wordpress.org/Embeds">http://codex.wordpress.org/Embeds</a>.</p>
<p class="cmb-spinner spinner" style="display:none;"><img src="http://ibuild.fsnuclear.com/wp-admin/images/wpspin_light.gif" alt="spinner" style="display: none;"></p><div id="_cmb_embed_status" class="cmb_media_status ui-helper-clearfix embed_wrap"></div>
    </td>
</tr><tr class="cmb-type-multicheck cmb_id__cmb_select-files">
<th style="width:18%"><label for="_cmb_select-files"></label></th>
    <td>
<ul class="cmb_checkbox_list cmb_list"> <li><input type="checkbox" class="cmb_option" name="_cmb_select-files[]" id="_cmb_select-files1" value="link"> <label for="_cmb_select-files1"><span class="dashicons dashicons-admin-links"></span></label></li>
    <li><input type="checkbox" class="cmb_option" name="_cmb_select-files[]" id="_cmb_select-files2" value="image"> <label for="_cmb_select-files2"><span class="dashicons dashicons-format-image"></span></label></li>
    <li><input type="checkbox" class="cmb_option" name="_cmb_select-files[]" id="_cmb_select-files3" value="files"> <label for="_cmb_select-files3"><span class="dashicons dashicons-admin-page"></span></label></li>
    <li><input type="checkbox" class="cmb_option" name="_cmb_select-files[]" id="_cmb_select-files4" value="embed"> <label for="_cmb_select-files4"><span class="dashicons dashicons-admin-media"></span></label></li>
</ul>
<p></p>

    </td>
</tr></tbody></table>

<input type="submit" name="submit-cmb" value="Save" class="wpcf7-form-control wpcf7-submit"></form>

                    </div>
                    </div>

                </div>

**Comment by tw2113** [comment]
Hi @leetee4000 
A couple things to note.

We're no longer doing any development for https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/ which is what you're presently using. We recommend moving up to https://github.com/WebDevStudios/CMB2/ which is the next evolution in the library. Because of that, we're also not doing very much support for the old version.

Is there any reason why you're choosing the old one over the new?

**Comment by leetee4000** [comment]
CMB2 wasn't ready when I started this project.  I have tried to switch to CMB2 but had difficulties and due to limited time on this project I decided to stick with the previous version as it all works fine apart from this weird image issue.  Have you any idea what it could be or have any tips on how to prevent this from showing?  Im desperate to get this project finished and would be really grateful for any help.

**Comment by tw2113** [comment]
I wager the template being used for the page you're embedding all of this on has the_post_thumbnail() called in it, and thus once you get a featured thumbnail attached to that page/post/whathaveyou, it starts displaying. That'd make it not something directly related to CMB itself.

**Comment by leetee4000** [comment]
Ok, Thanks for your help.

**Comment by mehmetsarr** [comment]
@LOL2011 


hello, i am trying to edit custom post type on the front end like yours but i couldnt Your form is good but does not work. Is there an example of how you do it?
