### ISSUE TITLE
Title type is not showing up for some reason

### ISSUE THREAD

**Issue by joshuairl** [WebDevStudios/CMB2#278]
![screenshot 2015-04-09 13 01 56](https://cloud.githubusercontent.com/assets/171077/7072226/a607fb06-deb8-11e4-9c3a-a43a7eed472b.png)

It's physically not placing the input field into the html.

![screenshot 2015-04-09 13 03 20](https://cloud.githubusercontent.com/assets/171077/7072242/d069ab7e-deb8-11e4-897a-e91799bce1dc.png)

**Comment by jtsternberg** [comment]
The title type is literally just a title. There is no associated input. You're probably looking for the `text`field type.

**Comment by joshuairl** [comment]
LOL omg sorry for this.
I guess I was looking for a full span width text input field and I saw ‘title’ so I went for it! :p
When I use “text” it just goes about half way.

Thanks for all you do!

**Comment by jtsternberg** [comment]
No worries. May have to add some custom css if you want further control over how they are displayed.

**Comment by joshuairl** [comment]
Maybe off-topic but any tips on where best place is to add said CSS?

**Comment by jtsternberg** [comment]
I added a snippet to the snippet library to demo that: https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/filters-and-actions/custom-css-for-specific-metabox.php
