### ISSUE TITLE
Can't delete row from repeatable group

### ISSUE THREAD

**Issue by rossb** [WebDevStudios/CMB2#281]
To delete a row from a repeatable group, I find I first have to move it to the bottom of all rows.

Or more accurately, I delete the row (by either the X or "remove" button) and update the post and it's still there. By then moving this "phantom" row down so it's the last entry and updating again, it disappears on update (without a further delete command).

**Comment by jtsternberg** [comment]
@rossb Can you please confirm that your issue is fixed by checking out the trunk branch and testing?

**Comment by rossb** [comment]
@jtsternberg will do at my first chance, thanks for the update! :)
