### ISSUE TITLE
manage_options capability needed to upload from frontend

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#283]
I'm using a front-end form with upload field. The user has to have `manage_options` capability though to be able to upload a file. Is this a bug, or is there any workaround? It's pretty scarry to give the users `manage_options` capability...

**Comment by jtsternberg** [comment]
Front-end forms are not supported out of the box.. we can't provide support for it, as there are a ton of things to keep in mind. With that said, if you want to add a file uploader on the front-end for non-manage_options users, that is definitely on you. :) Would be happy to take a pull request if you want to [submit a snippet to the snippet library](https://github.com/WebDevStudios/CMB2-Snippet-Library/). You also might want to look for or submit a question on [wordpress.stackexchange](http://wordpress.stackexchange.com/).

**Comment by vasikgreif** [comment]
For anyone who comes across this, I solved this by adding capability for users on specific pages only:

```php
/**
 * Allow the media uploader work on specific pages
 */
add_action('init', 'nevestam_allow_contributor_uploads');
function nevestam_allow_contributor_uploads() {
    $path=$_SERVER['REQUEST_URI'];
   if ( $path == '/page-slug'
        || strpos($path,str_replace(site_url(),'',bp_core_get_user_domain( get_current_user_id())) !== false )
        || $path == '/another-page-slug/'
    ) {
        $subscriber = get_role('subscriber');
        $subscriber->add_cap('manage_options');
    }
}
```

Not sure if this is a good snippet for the library..:)

**Comment by jtsternberg** [comment]
Won't that allow your subscriber to then edit the existing media? Like delete media, rename media, etc?

**Comment by vasikgreif** [comment]
I also added a filter, which displays only user's media:

```php
/**
 * Display only user-uploaded files to each user
 */

add_action('pre_get_posts','ml_restrict_media_library');
function ml_restrict_media_library( $wp_query_obj ) {
    global $current_user, $pagenow;
    if( !is_a( $current_user, 'WP_User') )
        return;
    if( 'admin-ajax.php' != $pagenow || $_REQUEST['action'] != 'query-attachments' )
        return;
    if( !current_user_can('manage_media_library') )
        $wp_query_obj->set('author', $current_user->ID );
    return;
}
```

**Comment by jtsternberg** [comment]
nice! That probably would make a nice snippet.

**Comment by vasikgreif** [comment]
I don't have an idea how to do the pull requests here, feel free to add it to the snippet library if you like this...:) Thanks

**Comment by leetee4000** [comment]
I have the exact same issue with a front end form.  @vasikgreif that is exactly what I was looking for thanks :)

**Comment by vasikgreif** [comment]
Glad this found some use...:)

**Comment by jtsternberg** [comment]
I got it [added to the snippet library](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-wordpress-media-uploader.php). I'd still like to do some testing for security concerns.

**Comment by Beee4life** [comment]
I think this is what I am looking for as well @vasikgreif BUT I have 1 question...
Does the extra capability only exist on this specific page or does it stay 'added' to this user role ?

Why do I ask ? Yesterday I came to the same conclusion independently and added the manage options role to my desired user role and then extended all my current_user_can statements with specific user roles.

**Comment by tw2113** [comment]
I do believe capability manipulation happens once, and is stored in the database. However, depending on how things are done by the user, the manipulation/saving could be running regularly. Say if done on the init hook. I believe most recommend having this specific detail run on activation/deactivation hooks instead.

**Comment by Beee4life** [comment]
My idea as well... but I have added it with user role editor, which gets the same result.
