### ISSUE TITLE
Notice: Array to string conversion 

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#284]
I followed this example: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types#example-4-multiple-inputs-one-field-lets-create-an-address-field

When trying to save a multi-input field like this(in a repeatable group), I get a `Notice: Array to string conversion in /Applications/AMPPS/www/local.dev/wp-includes/formatting.php on line 721`.

The values do not appear to save, but if I `error_log` the `$field_object` I see the value saved.  The field does not populate though.  Is this a bug?  Or maybe the tutorial is out of date?

**Comment by jtsternberg** [comment]
You closes this, did you get it figured out?

**Comment by GregLancaster71** [comment]
Yes, but I should share that the tutorial listed needs array_filter() added to prevent infinite empty inputs from being added with each save.  I created a pull request over there: https://github.com/WebDevStudios/CMB2-Snippet-Library/pull/8
