### ISSUE TITLE
Using multiple repeatable groups in one metabox?

### ISSUE THREAD

**Issue by elbsurfer** [WebDevStudios/CMB2#287]
Hello,
currently I use the group field to be flexible and make things a bit more easier on the backend side.

I have now several entries which can be added through the group type, but I want another repeatable group field within the current group. So the structure should be:

```
- Group
--Text field
--Group
--- Textfield
```
Does support CMB2 supports what I try to achieve?

**Comment by vandigroup** [comment]
Same question here....

**Comment by jtsternberg** [comment]
No, CMB2 does not currently support nested groups.

**Comment by scottsawyer** [comment]
Is there any plan to support nested groups in the future?

**Comment by jtsternberg** [comment]
It's planned, yes, but will require a large effort, so we don't have a definite timeline. Duplicate #565.
