### ISSUE TITLE
PDF only file field?

### ISSUE THREAD

**Issue by zu** [WebDevStudios/CMB2#288]
Is it possible to have a file field accept pdf only and would it even be possible to only show pdf files in the media gallery?

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
