### ISSUE TITLE
Feature Request: Arbitrary HTML Type

### ISSUE THREAD

**Issue by superdummy** [WebDevStudios/CMB2#290]
One of the most important types is actually missing: A generic Type that outpouts arbitrary HTML. 

As far as I can tell from the Code: CMB2 has a very big limitation, in that you can of course create your custom Types, but they will always trigger lots of unnecessary Database-Calls in trying to retrieve and store Data. There are cases one wants to embed Types that are completely independent of CMB2. Yes there is one Type named Title, that is more ore less how it should work, it does NOT trigger and DB calls. And case this could be faked. But it would be much cleaner having a complete empty HTML special Type.

Example: Substituting the Built-In Category-Metabox of WP with a custom Select Implementation. I know there is a Select Type, but this Type will store the Information in an additional PostMeta and NOT use the WP-Terms Post Relationship. So this is something completely different. 
A Clean way to to this is to have a Type that (when rendered) does NOT do any datalookups by CMB2. When submitted, the Post Data will NOT be processed by CMB2 in any way. (Currently any Post Form Element will trigger Database update, unless 2 Hooks are implemented to intercept this). This is a lot of overhead. The Title Type is exactly the correct way but not generic enough...

Thanks!

**Comment by jtsternberg** [comment]
I think you're overstating things a bit by saying it's the most important type, as you are only the 2nd to make the request. Creating a dropdown to save term ids as post-meta is [simple enough](https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post), and creating a generic html field is as simple as using the `title` field type with no 'name' attribute. You can then use any of these field params to output your generic html:
'before_field'
'before_row'
'before'
'after'
'after_row'
'after_field'

**Comment by superdummy** [comment]
thanks!

with this "hack" using the title field the problem is sovled. (but this solution is not obvious for someone who is not deeply into cmb2)

To make it easier for others (and google to find the solution above):  **CMB2 HTML Type, CMB Generic HTM Type**

Just to explain "most important": I think for every framework a very easy "build your own xyz/integrate any legacy code" is the most important feature... and for me an generic HTML Type would have been that. But with your fix, feature is more or less existant.

**Comment by jtsternberg** [comment]
Understood, and thank you for your feedback. I'll consider for the future.
