### ISSUE TITLE
Save to custom table

### ISSUE THREAD

**Issue by jawittdesigns** [WebDevStudios/CMB2#294]
Is there a way to save the meta boxes to a custom table with corresponding table columns instead of the postmeta table?

**Comment by jtsternberg** [comment]
Definitely, though not out of the box. You'll want to override the [setting](https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Field.php#L282-L291) and [getting](https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Field.php#L218-L227) of the value. You'll need to use the trunk branch (until the next release) as some of those filters have changed a bit to accommodate that type of thing better.

**Comment by jawittdesigns** [comment]
Hey, great! I'll look into these filters.

Thanks

**Comment by oterox** [comment]
@jawittdesigns did you get it to work with a custom table? if so, how?

**Comment by jawittdesigns** [comment]
No, I was never able to figure it out. It would be cool if there was documentation for this.

**Comment by stuberm** [comment]
```php
add_filter('cmb2_override_meta_value', 'get_custom_data', 10, 4);
add_filter('cmb2_override_meta_save', 'save_custom_data', 10, 2);

function get_custom_data($data, $id, $arguments, $field)
{
	// Load data from database ...

	return 44;
}

function save_custom_data($data, $values)
{
	// Print values for debugging purposes
	echo "<pre>";
	print_r($values);
	echo "</pre>";

	// Write data into database ...

	return true;
}
```

The dump will look like:
```
Array
(
    [type] => post
    [id] => 1
    [field_id] => id_of_test_field
    [repeat] => 
    [single] => 1
    [value] => 44
)
```
