### ISSUE TITLE
multiple taxonomy_multicheck or taxonomy_radio don't work properly

### ISSUE THREAD

**Issue by jerry-woo** [WebDevStudios/CMB2#295]
In document neither taxonomy_multicheck nor taxonomy_radio is repeatable, but even with different ids?

     $cmb_demo->add_field( array(
		'name'         => __( 'Speakers', 'cmb2' ),
		'desc'         => __( '', 'cmb2' ),
		'id'           => $prefix . 'speakers',
		'taxonomy'     => 'post_tag',
		'type'         => 'taxonomy_multicheck',
		'inline'       => true,
	) );

	$cmb_demo->add_field( array(
		'name'         => __( 'Attendees', 'cmb2' ),
		'desc'         => __( '', 'cmb2' ),
		'id'           => $prefix . 'attendees',
		'taxonomy'     => 'post_tag',
		'type'         => 'taxonomy_multicheck',
		'inline'       => true,
	) );

Above code result in value of "attendees" is saved for both "attendees" and "speakers" no matter what value of "speakers" is.

**Comment by jtsternberg** [comment]
The taxonomy fields are not intended to provide an arbitrary list of terms to pick from, but are intended to be a replacement for the default taxonomy metaboxes. I.e. they are meant to set the taxonomy terms on an object. Any other use of these types will be hacky and/or buggy. I suggest looking at building a custom field type for this: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post

**Comment by jerry-woo** [comment]
Thank you for the reply and explanation.
