### ISSUE TITLE
Adding "Add Media" button to front-end form or adding 'featured image' to file_list type

### ISSUE THREAD

**Issue by leetee4000** [WebDevStudios/CMB2#297]
I am currently using the file_list field type to upload multiple files via a front end form.  This works, however, it would be better if it could show the same screen as the "Add Media" button in the back-end form to add posts.  The reason I think this is because it would also allow users to set a featured image for the post and also a Gallery etc and hopefully make use of the in built wordpress functions for this.

Is this a possibility using CMB?  If not, the ability to set featured image would be sufficient. 

Many thanks,

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
