### ISSUE TITLE
Open Media Upload form direct from link instead of button with file_list

### ISSUE THREAD

**Issue by leetee4000** [WebDevStudios/CMB2#298]
I want to be able to open the media upload popup via an image instead of the default button.  Is there a way to do this outside of the $meta_boxes array?

Thanks

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
