### ISSUE TITLE
Problem with 'taxonomy_select' - how to remove the 'SELECTED'

### ISSUE THREAD

**Issue by leetee4000** [WebDevStudios/CMB2#299]
I have a form on the front end which displays a custom taxonomy as a select list.  For some reason it always shows the 3rd option in the select and I have no idea where this is coming form or why it is happening.  I cannot find any other reference to this in my code and the only code relating to this is below:

                array(

                    'name'     => __( 'Project stage', 'cmb' ),

                    'desc'     => __( 'Assign to stage of project', 'cmb' ),

                    'id'       => $this->prefix . 'category',

                    'type'     => 'taxonomy_select',

                    'taxonomy' => 'stages', // Taxonomy Slug

                ),

I have tried displaying the taxonomy using 

<?php echo get_the_term_list( $post->ID, 'Stages', 'Stage: ', ', ', '' ); ?>  

to see if this does it and it doesn't.  Therefore it must be something to do with the CMB2 form I have created.  Is there a way to add a 'Please select' empty option and ensure this is the one displayed?  I have tried adding the below but this does nto work.

 'show_option_none' => false,

Thanks

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific custom use-case for CMB2. I suggest looking at building a custom field type for this: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post

**Comment by leetee4000** [comment]
No problem, thanks for pointing me in the right direction.
