### ISSUE TITLE
Submenu page

### ISSUE THREAD

**Issue by joneslloyd** [WebDevStudios/CMB2#301]
Hi there,

I've seen how CMB2 can be used in admin menu pages (creating a theme options page, for example).

Just wondering if it's possible to use it on a pre-existing submenu page?

For example, I have a custom post type called 'faqs', and in the wordpress backend, hovering over the faqs top-level menu I'm able to "Add new faq", "View all faqs" and see "faq categories" - and want to add a submenu page ("faq settings").

I'd like to add CMB2 fields to this custom post type's submenu page.

Do you know if, as it stands, this can be done?

If the above can't be achieved, do you know if it's possible to create a submenu page with CMB2? (rather than adding CMB2 fields to an existing one).

Thanks!

**Comment by joneslloyd** [comment]
I've actually figured out how to create a CMB2-only submenu page, so I'll close this.

Thanks!

**Comment by brice-lucas** [comment]
@joneslloyd care to share how you figured this out?  You cluttered google with your question, but there's no solution.  Boo.

**Comment by jtsternberg** [comment]
You can see a commented-out example of setting to a submenu in the example-functions.php file: https://github.com/CMB2/CMB2/blob/6fce2e7ba8f41345a23bc2064e30433bdb11c16c/example-functions.php#L665
I've also added a couple examples to the snippet library: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/submenu-options-pages.php

**Comment by jtsternberg** [comment]
Also possibly helpful, snippet to show how to register a main options page with multiple submenu option pages: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/options-pages-with-submenus.php
