### ISSUE TITLE
 Exclude on non top level posts - how to use?

### ISSUE THREAD

**Issue by evels** [WebDevStudios/CMB2#305]
'show_on' => array( 'key' => 'parent-id')

Is there a value needed? (after including the filter)

**Comment by phh** [comment]
You're missing a filter:

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
