### ISSUE TITLE
2.0.5 released but 2.0.4 in code

### ISSUE THREAD

**Issue by slaFFik** [WebDevStudios/CMB2#308]
In `init.php`:
```
/**
 * Current version number
 * @var   string
 * @since 1.0.0
 */
const VERSION = '2.0.4';
```

That's a bit confusing. Was it done on purpose or is it an error?

**Comment by jtsternberg** [comment]
Definitely not on purpose (definitely an error), and will be fixed in the next version.

**Comment by slaFFik** [comment]
I see it's already fixed in trunk. So I believe this issue can be closed.
