### ISSUE TITLE
Repeatable group number incorrect

### ISSUE THREAD

**Issue by jgclifton** [WebDevStudios/CMB2#310]
I have made a repeatable group that has two fields; a text field and a file list field. When adding more groups, the group number title is correct (i.e for every added group, it increases by one). However, upon saving it shows each group as just number 1.

Is this a known bug? I am using the latest version of CMB2, using the wordpress.org plugin.

**Comment by michaeljpowell** [comment]
+ 1, have the same issue after just upgrading to 2.0.6 today.
I have CMB2 included directly into my theme.

**Comment by jgclifton** [comment]
Glad to know that I'm not the only one. Looks like it may be a bug.

**Comment by austinjreilly** [comment]
My issue (#257 [which itself contains references to #263 and #304]) may also be related to this.

**Comment by jtsternberg** [comment]
This was definitely a bug and is now fixed in trunk. Please test.

**Comment by michaeljpowell** [comment]
Thank you! It's working well for me now :)

**Comment by jajouka79** [comment]
can someone please tell me if this fix has been included in the github repo, I'm not sure what 'trunk' is refering to. thanks

**Comment by jtsternberg** [comment]
@jajouka79 it is in the trunk branch and will be in master when we release the next version. You can download trunk or checkout the trunk branch from the repo.

https://github.com/WebDevStudios/CMB2/tree/trunk

**Comment by jajouka79** [comment]
ok, thanks justin
