### ISSUE TITLE
Plugin Header issues

### ISSUE THREAD

**Issue by stlouisweb** [WebDevStudios/CMB2#314]
I'm trying to use this CMB2 within another plugin and I ca't get it working.

I get an error:  "The plugin does not have a valid header."

So I tried removing the header from CMB2/init.php and the error goes away but I don't see any of the custom metaboxes.

I have a functions.php file a directory above CMB2/ where I copied the example functions.

Not sure what I'm doing wrong?

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.

**Comment by stlouisweb** [comment]
It's not a very custom implementation, I'm simply trying to embed the plugin within another plugin (that isn't doing anything else yet), as described in the installation instructions in the [README.md](https://github.com/WebDevStudios/CMB2#installation) file. That sounds like a bug to me, or perhaps the documentation is lacking or out of date?

**Comment by stlouisweb** [comment]
Got it working but the process is a little cumbersome, I must be doing something wrong or there is something amiss with my environment. [stackoverflow](http://stackoverflow.com/questions/30106111/wordpress-cmb2-how-to-embed-in-a-plugin)
