### ISSUE TITLE
Generating dynamic fields by another cmb2 field.

### ISSUE THREAD

**Issue by tonezzz** [WebDevStudios/CMB2#317]
Firstly, I want to know if this is possible.  I'm making a simplify version of my code, will post it asap.

I'm making a repeatable group with a field name "type".
After selecting the "type" other fields will be generated accordingly.  I've tried this but the value didn't get saved.  But when I made all fields as static, it's saved correctly.

I wonder if this is possible or if I did something wrong.  Any idea?

Thanks,
Tony.

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.

**Comment by tonezzz** [comment]
No problem, so I assume it's not possible.  I'll have to find my own way then.
Anyway, thanks for your hard working to make this great library.
Have a nice day.
Cheers,
Tony.
