### ISSUE TITLE
get_the_ID fails within jQuery UI tabs after first field

### ISSUE THREAD

**Issue by bobbiejwilson** [WebDevStudios/CMB2#319]
The first field is pulled in just fine. Subsequent fields in other tabs need the actual ID to display additional fields. There are loops present in each tab.

**Comment by jtsternberg** [comment]
@bobbiejwilson can you provide your code?

**Comment by jtsternberg** [comment]
We discussed off-channel. @bobbiejwilson feel free to re-open if you encounter another issue!
