### ISSUE TITLE
Showing a metabox on all post types (including CPT from other plugins)

### ISSUE THREAD

**Issue by vpratfr** [WebDevStudios/CMB2#320]
Hi,

As a theme developer I'd like some metaboxes to show up on any custom post type available. 

I see that I can specify an array of post types when creating the metabox, but how can I just say "show this box on any type of post"?

**Comment by jtsternberg** [comment]
Something like:
```php
$args = array( 'public' => true );
$public_post_types = get_post_types( $args );
$cmb_demo = new_cmb2_box( array(
	'id'            => $prefix . 'metabox',
	'title'         => __( 'Test Metabox', 'cmb2' ),
	'object_types'  => $public_post_types,
) );
```

https://codex.wordpress.org/Function_Reference/get_post_types

**Comment by vpratfr** [comment]
Could be a nice addition to have a shortcut to do that.

Something like `'object_types'  => 'any-cpt'` where args would be `show_ui => true` by default.

**Comment by tnorthcutt** [comment]
@vpratfr the problem with that would be that if there were a post type called `any-cpt` you'd have quite a mess :smile:

**Comment by abuyoyo** [comment]
`WP_Query` allows for arg `'post_type'=>'any'` which returns *any* post_type. Not a post type named `'any'`. So I think the `'any'` keyword is safe to use.

Consider re-opening this issue.

@jtsternberg

**Comment by tw2113** [comment]
out of curiosity, have you tried passing that as is, to see what happens? Like it doesn't need to have anything changed to make this work still.

**Comment by abuyoyo** [comment]
Just tried it.
Passing `'object_types'  => 'any'` does not work.
Only `'object_types'  => get_post_types()` works ATM.

**Comment by tw2113** [comment]
Pass as an array. `[ 'any' ]`

**Comment by abuyoyo** [comment]
Nope.
I also just looked at how `WP_Query` handles this. It specifically checks if `$post_type == 'any'` and then calls `get_post_types()`.

**Comment by tw2113** [comment]
gotcha, just had to check and cover bases :)
