### ISSUE TITLE
Multiple show_on filters

### ISSUE THREAD

**Issue by gyrus** [WebDevStudios/CMB2#323]
I think this is a feature request, but maybe I'm missing something - this seems like important core functionality, but I can't find a way. Is there a way of applying multiple `show_on` filters to a box?

I've tried passing an array of arrays to `show_on`, doesn't seem to work.

The `cmb2_show_on` filter seems to receive all the box's arguments, so initially I thought this would mean I could add a custom argument, e.g. `show_on_extra`, an array of arrays, and test multiple conditions (I'd probably have to duplicate one or both of the built-in `show_on` filters, which seems wrong). Anyway, this approach didn't seem to work as custom arguments seem to be stripped out.

I'm in the process of converting from Developer's Custom Fields, and being able to apply any number of conditions became crucial to me through using that. I'm prepared to do some coding and submit a pull request - I just don't want to re-invent a wheel I can't find.

**Comment by jtsternberg** [comment]
There's a new parameter in the most recent version, `show_on_cb`, which allows you to conditionally display a cmb metabox/form via a callback. See the first point in the release notes: https://github.com/WebDevStudios/CMB2/releases/tag/v2.0.6

In that callback, you can check as many things as you want.. just return true to show the box, or false.

**Comment by gyrus** [comment]
Thanks - but that seems a bit inflexible.

If I want to be able to limit display according to a user's capability, I'd need to create a separate function for each capability I want to deal with (unless there's a way of passing args?). If I happen to have another kind of limitation, I'd have to create functions for every combination of the two limitations - and straight away it's impractical.

Again, this could be made more flexible if we could pass custom arguments as well, for the function to check against, but these seem to be stripped out.

**Comment by gyrus** [comment]
Allowing `show_on` to pass an array of arrays, any number of which could be custom, dealt with by the `cmb2_show_on` hook, would be infinitely scalable.

**Comment by jtsternberg** [comment]
@gyrus can you provide _pseduo-code_ to demo what you're trying to do? I think you'll be able to do anything you want in the `'cmb2_show_on'` callback... it's a function callback which gets called right before the metabox is registered, so you can check as many conditions at that point as you want. Also, the parameters are not stripped. You can access them via the CMB2 `prop` method (`$custom_arg_val = $cmb->prop( 'custom-argument' )`).  Using the callback is preferable for several reasons, but the main reason is that if you try and do any logic in the cmb2_init hook (like figuring out users or whatever), those queries and that logic is going to happen on every page-load for every user. When using the callback, those queries and that logic will only happen in wp-admin on a post-edit (or user or whatever) screen.

```php
/**
 * Sample metabox
 */
$cmb_demo = new_cmb2_box( array(
	'id'              => 'cmb_demo_metabox',
	'title'           => __( 'Test Metabox', 'cmb2' ),
	'object_types'    => array( 'page', ), // Post type
	'show_on_cb'      => 'my_cmb_conditional_show_callback', // function should return a bool value
	'custom-argument' => 'A custom value',
) );

... 

function my_cmb_conditional_show_callback( $cmb ) {
	$show_it = true;
	$val = $cmb->prop( 'custom-argument' );

	if ( 'test' !== $val ) {
		$show_it = false;
	}

	return $show_it;
}
```

**Comment by gyrus** [comment]
Great, I think I've got it:
```php
$cmb = new_cmb2_box( array(
	'id'				=> 'slideshow_config_box',
	'title'				=> __( 'Slideshow configuration' ),
	'object_types'		=> array( 'page' ),
	'show_on'			=> array(
		'key'		=> 'id',
		'value'		=> array( 2 )
	),
	'show_on_cb'		=> 'pilau_cmb2_show_on_custom',
	'show_on_custom'	=> array(
		'user_can'			=> 'publish_pages',
	),
));

function pilau_cmb2_show_on_custom( $cmb ) {
	$show = true;
	$show_on_custom = $cmb->prop( 'show_on_custom' );

	if ( ! empty( $show_on_custom ) ) {

		// Loop through restrictions
		foreach ( $show_on_custom as $show_on_type => $show_on_condition ) {

			switch ( $show_on_type ) {
				case 'user_can': {
					// Check user capability
					$show = current_user_can( $show_on_condition );
					break;
				}
			}

			// If a condition has failed, break out
			if ( ! $show ) {
				break;
			}

		}

	}

	return $show;
}
```

The `show_on_custom` arg should then be infinitely extendable. It currently has an implicit AND relationship between multiple conditions. I guess the syntax could be changed to work like `WP_Query` meta queries, with an array of arrays for `show_on_custom`, and you can `'relation' => 'OR'` to change the test. However, I can't think of instances where I'd need to use an OR relationship between multiple conditions.

Is there a reason the default `show_on` uses:

`show_on => array( 'key' => 'id', 'value' => array( 2 )`

Instead of:

`show_on => array( 'id' => array( 2 ) )`

?

**Comment by jtsternberg** [comment]
Yah, that looks like a great solution. The `'show_on'` parameter is somewhat-legacy and supported mostly for simple uses and legacy support. I agree it is a weird syntax. The '`show_on_cb'` is the way forward.
