### ISSUE TITLE
Documentation seems to list the wrong hook

### ISSUE THREAD

**Issue by curtismchale** [WebDevStudios/CMB2#324]
When using the Basic Setup docs it seems that the wrong hook is listed to setup metaboxes.

https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage

When I change 'cmb2_init' to 'cmb2_meta_boxes' as my hook it all works fine.

So am I missing something or are the docs actually incorrect?

**Comment by jtsternberg** [comment]
`'cmb2_init'` is correct. if you're using the `'cmb2_meta_boxes'` hook (and it works), then you're using the old registration API (a bunch of arrays passed back at the end), and not the new one. You can see the new registration API in [that same doc](https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage) or in [example-functions.php](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php)

**Comment by curtismchale** [comment]
So I've likely got to dig through a bunch of other plugins and figure out which one has me pinned to the older API.

**Comment by jtsternberg** [comment]
@curtismchale Not sure I understand fully, but the older api will be maintained for backwards-compatibility. But using it will cause you to miss out on some newer functionality.

**Comment by curtismchale** [comment]
So copy/paste from the docs page shows me absolutely nothing on a fresh release (2.0.6) using the default hook cmb2_init.

If I only change the hook to cmb_meta_boxes but don't return an array it works.

```php
add_action( 'cmb2_meta_boxes', array( $this, 'cmb2_sample_metaboxes' ) );
	/**
	 * Define the metabox and field configurations.
	 */
	function cmb2_sample_metaboxes() {

		// Start with an underscore to hide fields from custom fields list
		$prefix = '_woo_product_vis_';

		/**
		 * Initiate the metabox
		 */
		$cmb = new_cmb2_box( array(
			'id'            => 'woo_product_vis',
			'title'         => __( 'Product Visibility', 'cmb2' ),
			'object_types'  => array( 'product', ), // Post type
			'context'       => 'side',
			'priority'      => 'high',
			'show_names'    => true, // Show field names on the left
			// 'cmb_styles' => false, // false to disable the CMB stylesheet
			// 'closed'     => true, // Keep the metabox closed by default
		) );

		// Regular text field
		$cmb->add_field( array(
			'name'       => __( 'Restricted Product to Purchasers of:', 'cmb2' ),
			'desc'       => __( 'This product will only show to users that have purchased the product specified above', 'cmb2' ),
			'id'         => $prefix . 'text',
			'type'       => 'text',
			// 'sanitization_cb' => 'my_custom_sanitization', // custom sanitization callback parameter
			// 'escape_cb'       => 'my_custom_escaping',  // custom escaping callback parameter
			// 'on_front'        => false, // Optionally designate a field to wp-admin only
			// 'repeatable'      => true,
		) );
```

Obviously this is inside a class.

If I make the action:

```php
		add_action( 'cmb2_init', array( $this, 'cmb2_sample_metaboxes' ) );
```

No metaboxes show up at all in my product.

**Comment by jtsternberg** [comment]
hmmm is that the entire code? What happens if you change 'product' to 'post'? Does it show on the post-edit page? Also, please at least return whatever is passed into that filter. If you don't, you could break others' legacy use-cases because their metaboxes are no longer registered.

**Comment by jtsternberg** [comment]
Changing 'product' to 'page' in my local setup and using the following code:
```php
add_action( 'cmb2_init', 'cmb2_sample_metaboxes' );
/**
 * Define the metabox and field configurations.
 */
function cmb2_sample_metaboxes() {

	// Start with an underscore to hide fields from custom fields list
	$prefix = '_woo_product_vis_';

	/**
	* Initiate the metabox
	*/
	$cmb = new_cmb2_box( array(
		'id'            => 'woo_product_vis',
		'title'         => __( 'Product Visibility', 'cmb2' ),
		'object_types'  => array( 'page', ), // Post type
		'context'       => 'side',
		'priority'      => 'high',
		'show_names'    => true, // Show field names on the left
		// 'cmb_styles' => false, // false to disable the CMB stylesheet
		// 'closed'     => true, // Keep the metabox closed by default
	) );

	// Regular text field
	$cmb->add_field( array(
		'name'       => __( 'Restricted Product to Purchasers of:', 'cmb2' ),
		'desc'       => __( 'This product will only show to users that have purchased the product specified above', 'cmb2' ),
		'id'         => $prefix . 'text',
		'type'       => 'text',
		// 'sanitization_cb' => 'my_custom_sanitization', // custom sanitization callback parameter
		// 'escape_cb'       => 'my_custom_escaping',  // custom escaping callback parameter
		// 'on_front'        => false, // Optionally designate a field to wp-admin only
		// 'repeatable'      => true,
	) );
}
```
Results in a metabox at the top of my sidebar: http://b.ustin.co/zsuY

**Comment by curtismchale** [comment]
yeah I tried all the page/post stuff to get it working as well. I also tried it out of the class.

All I can figure is a bug with an older version then.
