### ISSUE TITLE
text_datetime_timestamp as a repeater field not saving proper timestamp

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/CMB2#330]
It's saving the current time instead of the set time.

https://wordpress.org/support/topic/date-will-not-save-saves-today-instead?replies=4#post-6984530

**Comment by tw2113** [comment]
@jtsternberg have you looked into this one at all? Original reporter is still having issues and wondering if there's possible chance for some sort of fix for it.

**Comment by turegjorup** [comment]
I can confirm I'm seeing the same issue. WP 4.4 beta4, CMB2 2.1.2 on both Firefox and Chrome. I'm also only seeing it with a repeatable datetime field. 

Looking through #446 there are some changes to the code taht fails, but I still don't think they properly account for repeating datetime fields.

**Comment by jtsternberg** [comment]
This should be good in [trunk](https://github.com/WebDevStudios/CMB2/tree/trunk). Please test.

**Comment by turegjorup** [comment]
Just tested with WP 4.4-beta4-35734, repeatable datetime fields now works as expected. Thank you for fixing it.
