### ISSUE TITLE
Group field import doesn't work

### ISSUE THREAD

**Issue by php-xpert** [WebDevStudios/CMB2#331]
Hi,

We are facing following issues while importing data using wordpress import plugin..

- We have a custom post type.
We have following field structure of CMB2 with custom post type
- text
- text
- CMB2 Group field ( text, wysiwyg ) 
set with custom post type..

While importing first 2 text fields get imported but Group field failed..

How can we resolve it..

Kindly help... its urgent..

**Comment by theKhorshed** [comment]
I am also facing the import issue for group fields. I've total 8 group fields and 2 of them isn't importing properly. Rest others are working fine.

Trying to figure out the the issue.

**Comment by BobaWebDev** [comment]
It gets corrupted. If you get the value from the export and try to unserialize it won't work. Not sure what and why, looking into it.

**Comment by jtsternberg** [comment]
I suggest looking into a tool like the [serialized search & replace tool by interconnect/it](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/). Exporting/importing sorta falls out of the scope of what CMB2 is all about, thought I can see a scenario where imports/exports could be a nice addon plugin.

**Comment by carasmo** [comment]
Serialized search & replace tool by interconnect/it saved my tushy last week, it's very good and easy to use.

**Comment by BobaWebDev** [comment]
It seems the value itself is somehow corrupted, not just related to export/import, I went into phpMyAdmin, took the value, did unserialize on it and got "error at offset..."

But when I use get_post_meta() it gets unserialized properly.

However it does get completely broken if I reapply the exact same value to the same field via phpMyAdmin. 

Weird stuff.

**Comment by jtsternberg** [comment]
Thanks @carasmo for a good suggestion here: https://github.com/WebDevStudios/CMB2/issues/631#issuecomment-212097539
