### ISSUE TITLE
Uncaught TypeError: $id(...).hide(...).farbtastic is not a function

### ISSUE THREAD

**Issue by jedrzejchalubek** [WebDevStudios/CMB2#333]
Getting error form js file: `Uncaught TypeError: $id(...).hide(...).farbtastic is not a function` and of course all js based repeatable UI elements dont work.

Wordpress: 4.2.2
CMB: dev-trunk

**Comment by jtsternberg** [comment]
The only reason that would happen is if this condition: `(typeof jQuery.wp === 'object' && typeof jQuery.wp.wpColorPicker === 'function')` is false. This means the colorpicker is not enqueued or some other script is causing that script to not work. There is nothing in CMB2 that would cause this to occur.

**Comment by jedrzejchalubek** [comment]
But on version CMB2 2.0.6 this error not appears.

**Comment by jtsternberg** [comment]
If you're replacing default WordPress scripts, there's not much I can do to help.

**Comment by michaeljpowell** [comment]
I get this same error when I'm on a custom options page (specifically with the file upload field). When it's within a page it appears to be working fine.

I am using the WP plugin version.

**Comment by EvanHerman** [comment]
I too was getting the same error using the version up here on GitHub and the version found in the WordPress plugin repo. Whenever I included a color picker field I was getting the same error as OP.

This was on a fresh TwentyFifteen install with no other plugins installed.

Adding the following, just below colorpicker field definition, did the trick for me:
```php
wp_enqueue_style( 'wp-color-picker' );
wp_enqueue_script( 'wp-color-picker' );
```

It seems to only be the color picker field that's causing this issue.


Evan

**Comment by jtsternberg** [comment]
Thanks for reporting. The issue should be addressed in https://github.com/WebDevStudios/CMB2/commit/244d39fc3c27cfc195e495ecb331fac73e51399a
