### ISSUE TITLE
Update language from transifex

### ISSUE THREAD

**Issue by Mte90** [WebDevStudios/CMB2#337]
I've translated cmb2 in italian weeks ago on transifex but i see that the languages are not updated on github.

**Comment by jtsternberg** [comment]
Sorry, I haven't gotten into a good system w/ pulling/pushing using Transifex. I will be sure to update with the next release.

**Comment by Mte90** [comment]
Is easy download alla the file with the command line client http://docs.transifex.com/client/pull

**Comment by jtsternberg** [comment]
Not as simple as it sounds because of the translations provided via github PRs. See relevant discussion: https://twitter.com/fxbenard/status/605752066980626432 :)

**Comment by jtsternberg** [comment]
Your translation should now be in trunk (see: https://github.com/WebDevStudios/CMB2/commit/39a2042ee69cefdf4d7adadb20f72a3ceaa61226)

**Comment by Mte90** [comment]
thanks!

**Comment by Mte90** [comment]
Uhm i see that in the languages folder there are the file po for many languages but not the file mo...

**Comment by jtsternberg** [comment]
Which file are you looking for specifically

**Comment by Mte90** [comment]
For the italian language, but as i can see exist all the files po but not for the files mo
https://github.com/WebDevStudios/CMB2/tree/master/languages

**Comment by jtsternberg** [comment]
Please, tell me the file explicitly. I have no idea which file is the Italian language. Once you tell me, I can generate the mo file and get it into trunk.

**Comment by Mte90** [comment]
The file is `cmb2-it_IT.po` but CMB2 with all this languages supported but not enabled (compiled in mo) is unuseful for everyone, so i think that is better compile all the file in the languages folder.

**Comment by jtsternberg** [comment]
Please review the trunk branch: https://github.com/WebDevStudios/CMB2/tree/trunk/languages

**Comment by Mte90** [comment]
this trunk is perfect :-D
