### ISSUE TITLE
Clarification on sanitization

### ISSUE THREAD

**Issue by hexagongirl** [WebDevStudios/CMB2#342]
My first time using CMB2, and just after a bit of clarification on sanitization/escaping (sorry if I've missed something, but couldn't find it in docs).  Happy to help by adding this info to the docs once confirmed if you think appropriate - let me know how/where.

Am I right that:

1) A default set of sanitization gets done (as defined in https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Sanitize.php) depending on the field type. Being sanitization, this is before the data is saved to the DB.

2) No default sanitization gets done on WYSIWYG fields - as lines 86-87 in above mentioned file are commented out?

3) I can get around no.2 by adding a custom sanitization function via `sanitization_cb` callback

4) The `escape_cb` callback is used if you want custom escaping of values in the admin area (or wherever cmb2 is displaying the field).  As a general rule, this can be left to the default?

5) Escaping still needs to be done manually as usual when outputting data in the front end via `get_post_meta()`.

Thanks!

**Comment by jtsternberg** [comment]
1. Correct, sanitized by default.
2. Incorrect, that case falls through to the next instance of `break;`: https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Sanitize.php#L89
3. Correct, you can always add your own `sanitization_cb` to override cmb's
4. That is correct.
5. That is also correct unless using the CMB2 field value APIs, but generally I recommend NOT using those, as front-end output will always be tailored to the individual use-case. Using them on the front-end is not documented, though I would like to get to it eventually. And one other point.. escaping should happen at the last instance possible (https://vip.wordpress.com/2014/06/20/the-importance-of-escaping-all-the-things/), so using the CMB2 output API would be cheating that a bit. :)

**Comment by hexagongirl** [comment]
Ah, ok - got it! (didn't twig the lack of break and it following through to next case).  So it's using wp_kses_post for wysiwyg.

Thanks so much for the quick reply.

**Comment by jtsternberg** [comment]
:thumbsup:
