### ISSUE TITLE
Translation: Wrong Timeformat for German Speaking countries

### ISSUE THREAD

**Issue by superdummy** [WebDevStudios/CMB2#347]
in the German Translation (MO/PO Files) there is the Translation for this String (the Date Timepicker): 

	´'timeFormat'    => _x( 'hh:mm TT', 'Valid formatting string, as per http://trentrichardson.com/examples/timepicker/', 'cmb2' ),`

defined as : `hh:mm TT` 

But it should be `HH:mm` 

so no AM/PM Format. It would bet, that 70% of the Germans speaking population have completely no Idea how the AM/PM Format works. IT seems I can not upload a file so I will at least report it here. (I have currently not setup my WP to be gitifed and I am not able to push it to the repo...)

**Comment by jtsternberg** [comment]
Would you be willing to update the translation? You can do so with http://wp-translations.org/cmb2

**Comment by superdummy** [comment]
yes of course. 

I was not aware, that the translations are on transifex, know transifex but never used it. 

I have translated it now, should be ok now.

**Comment by jtsternberg** [comment]
@superdummy thank you sir!
