### ISSUE TITLE
Saving of empty option using Taxonomy_Metadata_CMB2 doesn't overwrite the old value

### ISSUE THREAD

**Issue by johnsonpaul1014** [WebDevStudios/CMB2#350]
We are unable to save an empty value for a CMB2 taxonomy metadata field.  We are also using the wlo_large_options plugin for it.  To fix this, I had to default the $resave argument to true in the CMB2_Options class remove method:

`public function remove( $field_id, $resave = true )'

I'm not sure how this affects other plugin functionality though, and I thought I would just raise an issue first before making a pull request.  It was obviously set to false by default for a reason.

**Comment by jtsternberg** [comment]
If this is a bug with Taxonomy_Metadata_CMB2, can you open an issue there instead? `CMB2_Options` is used for a lot of other things that are not related to that project, so we shouldn't modify it for the sake of that one project, but rather determine the best way to fix it there.
