### ISSUE TITLE
Any way to add metaboxes in custom settings page?

### ISSUE THREAD

**Issue by ashawkat** [WebDevStudios/CMB2#351]
Hi I would like to add metaboxes under custom settings page which is under a custom post type. I can create metaboxes for custom post types also I can create a theme options. But can't find any way to add the metaboxes on a custom settings page. Like my post type hierarchy is like below:
Products
 - All item
 - Add Item
 - Product Category
 - Product Settings

I want to add the metaboxes & create a options page on that settings page. Can you please guide me through this one.

I've been trying to follow this gist but can't find a way.
https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php

Also can you let me know if I can achieve something by tweaking this code where key|value operates
``$cmb = new_cmb2_box( array(
	'id'      => $this->metabox_id,
	'hookup'  => false,
	'show_on' => array(
	// These are important, don't remove
	'key'   => 'options-page',
	'value' => array( $this->key, )
	),
) );
``
I've created the settings page by this code
``
add_submenu_page('edit.php?post_type=ch_product_showcase', 'Product Showcase Settings', 'Showcase Settings', 'edit_posts', basename(__FILE__), array( $this, 'chProductShowcaseSettingsOptions') );
``

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
