### ISSUE TITLE
Select multiple ordered field type.

### ISSUE THREAD

**Issue by erikdrums** [WebDevStudios/CMB2#353]
I needed a field type that allowed selecting of multiple elements and also ordering them.

Though https://jqueryui.com/sortable I made a fairly simple solution. Is this something that might be interesting to implement into CMB2 core or snippets?

**Comment by jtsternberg** [comment]
We're always open to snippets. You could submit a pull request to the snippet library: https://github.com/WebDevStudios/CMB2-Snippet-Library

Several have also created their own custom field types which we feature: https://github.com/WebDevStudios/CMB2#custom-field-types

**Comment by erikdrums** [comment]
Alright. Thanks!
