### ISSUE TITLE
Default field values (from current post ID) in a front-end form

### ISSUE THREAD

**Issue by JiveDig** [WebDevStudios/CMB2#355]
I'm using CMB2 for a complex front end form, to post to a CPT. The form itself is not saving values ('save_fields'  => false). I need to allow front end editing of posts via the same form used for posting. The main issue is that I need to load values like the post_title into my 'submission_post_title' field.

It seems like cmb2_init runs too early? If I try something like `'default' => get_the_title(),` nothing happens.

I've done this before via ACF and the 'load_value' filter here: http://thestizmedia.com/front-end-post-editing-with-acf-pro/

Wondering if there is a similar load_value or load_default type filter in CMB2. Doesn't look like it at the moment.

Any ideas?

**Comment by jtsternberg** [comment]
It takes a callback. try `'default' => 'jivedig_get_the_title'` where `jivedig_get_the_title` is:

```php
function jivedig_get_the_title( $args, $field ) {
	return get_the_title( $field->object_id );
}
```

**Comment by JiveDig** [comment]
facepalm... that was obvious. Didn't even think about callback. I was thinking that was only for show_on. Thank you!

**Comment by jtsternberg** [comment]
Well.. it's not really obvious. It takes a value OR a callback. Glad it works for you though.

**Comment by JiveDig** [comment]
Callback allows me to only set a default value if i'm editing a post, not creating a new post... somehow.
