### ISSUE TITLE
Repeatable WYSIWYG field breaks when inserting/cloning new row

### ISSUE THREAD

**Issue by tylerdigital** [WebDevStudios/CMB2#356]
When a WYSIWYG field is inside a repeater, the javascript that creates a new row successfully duplicates and clears the content from the textarea (HTML view) of the WYSIWYG field, but I can't click the Visual tab of the new WYSIWYG field. I think WP does some initial processing when the page is loaded to render/prep a visual editor iFrame? 

If I type some content into the text view and publish/save changes to the post, the WYSIWYG visual editor mode works after the page reloads.

Any idea how to get the Visual Editor mode working in a repeater right after a new row is created?

**Comment by jgclifton** [comment]
This is a known issue:

"Metabox containing WYSIWYG editor cannot be moved or used in a repeatable way at this time (this is a TinyMCE issue)."

**Comment by jtsternberg** [comment]
Currently not supported, but is on the list for improvements.
