### ISSUE TITLE
Frontend Forms errors

### ISSUE THREAD

**Issue by wpgaijin** [WebDevStudios/CMB2#359]
I'm have some issues with a frontend form. I want to use repeatable groups and the wysiwyg, but I'm have probelms with loading the cmb2.js. I'm getting this error in the console.

    Uncaught TypeError: Cannot read property 'defaults' of undefined

Obviously thus is causing the groups to break and I think it's breaking the wysiwyg, too.

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.

**Comment by wpgaijin** [comment]
Oh, you know what. I totally forgot to update this. I originally followed a tutorial on the blog for adding front end fields, and that was causing the issues. Once I used the example in the snippets it worked fine.

**Comment by jtsternberg** [comment]
Awesome, glad to hear it!
