### ISSUE TITLE
Warning: Attempt to modify property of non-object when removing group field

### ISSUE THREAD

**Issue by daveromsey** [WebDevStudios/CMB2#362]
I noticed that a warning is issued when trying to remove a field from a group field. Despite the warning, the field is still removed, so it's not all gloom and doom.

I reproduced the issue using the following code along with CMB2's example-functions.php

```php
function cmbdude_remove_group_field_test() {
	$prefix = '_yourprefix_group_';
	
	$cmb = cmb2_get_metabox( $prefix . 'metabox' );

	$cmb->remove_field( 'description', $prefix . 'demo' );
}
add_action( 'cmb2_init', 'cmbdude_remove_group_field_test', 11 ); // Wasn't sure if this is the correct hook for removing stuff, but I figured it was alright as long as the priority was after the one where the fields are originally registered (10)
```

The full warning:
```Warning: Attempt to modify property of non-object in \wp-content\plugins\cmb2\includes\CMB2.php on line 891```

I'm using CMB2 version 2.0.8 and WP 4.2.1

**Comment by jtsternberg** [comment]
try using the `'cmb2_after_init'` hook. There is no guarantee all the fields are registered yet when you use `'cmb2_init'`.

**Comment by daveromsey** [comment]
Thanks for the suggestion @jtsternberg, but the warning remains even when firing super late on `cmb2_after_init`:
```add_action( 'cmb2_after_init', 'cmbdude_remove_group_field_test', 99999 );```

While debugging, I've noticed that `$this->fields` is just an empty array where as `$this->meta_box` is populated with the expected data (and this is the case before anything is done with `$this->fields` inside of the `remove_field` method).
