### ISSUE TITLE
Missing resources in the Readme/Wiki

### ISSUE THREAD

**Issue by Mte90** [WebDevStudios/CMB2#363]
I've see that exist many resources for CMB2 but they are missing in this readme/wiki:
* https://github.com/WebDevStudios/CMB2-Remote-Image-Select-Field
* https://github.com/FacetWP/facetwp-cmb2
* https://github.com/WebDevStudios/CMB2-Example-Theme

**Comment by jtsternberg** [comment]
thanks!

**Comment by Mte90** [comment]
Is missing also https://wordpress.org/plugins/cmb-field-type-sorter/

**Comment by jtsternberg** [comment]
updated

**Comment by Mte90** [comment]
There is a new field, this time by me https://github.com/Mte90/CMB2-User-Search-field :-D
