### ISSUE TITLE
Hidden field type

### ISSUE THREAD

**Issue by JiveDig** [WebDevStudios/CMB2#365]
I'm using a hidden field with a value of the post ID (front end form). It's working well.

When trying to use a 'show_on' callback function, it's not working. Does that mean we need too officially create a hidden field type?

**Comment by jtsternberg** [comment]
There actually IS a `hidden` field type, but it wasn't documented (I just rectified that: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#hidden). Also of note is that @JPry just fixed a bug where the hidden field type was not honoring the `'show_on_cb'`, so you will need to use the trunk branch until the next release.

**Comment by JiveDig** [comment]
Great!
