### ISSUE TITLE
White Screen when publishing post

### ISSUE THREAD

**Issue by esaunders5** [WebDevStudios/CMB2#375]
I am building a custom plugin and am using this for my custom fields for my custom post type. I have the fields appearing and the data is displaying when I call it in the page template. My issue is when I save my post it goes to a white screen and doesn't redirect. 

This is the url after I push the 'publish' button.

http://localhost:8888/wp-admin/post.php

Any help would be wonderful.

**Comment by jtsternberg** [comment]
Do you have WP_DEBUG in your wp-config.php? That should tell you the error you're getting. https://codex.wordpress.org/Debugging_in_WordPress

**Comment by esaunders5** [comment]
That helped. Thanks a bunch!
