### ISSUE TITLE
Displaying all group fields

### ISSUE THREAD

**Issue by esaunders5** [WebDevStudios/CMB2#379]
I have a repeatable group and I am wanting to display them on the front end. The only one that is displaying is the last entered field group. Below is my code.

```php
$entries = get_post_meta( get_the_ID(), 'matches', true );

			foreach ( (array) $entries as $key => $entry ) {
				
				$match_name = $skill = $matchTime = '';
				
				if(isset($entry['match_name'])){
					$match_name = $entry['match_name'];
				}
				
				if(isset($entry['skill'])){
					$skill = $entry['skill'];
				}
				
				if (isset($entry['match_time'])){
					$matchTime = $entry['match_time'];
				}
			}
```
This is my code for displaying:

```php
echo "<p>Start Time: " . $datetime . "</p>";
			echo "<p>Contact Phone: " . $phone . "</p>";
			echo "<p>Game Type: " . $gameType . "</p>";
			echo '<h3>Matches</h3>';
			echo "<p>" . $match_name . "</p>";
			echo "<p>Skill Level: " . $skill . "</p>";
			echo "<p>Match Start Time: " . $matchTime . "</p>";
```
I have tried using a loop to loop through all the match entries, but have failed. What is the best way to get them to display?

Thanks

**Comment by jtsternberg** [comment]
You need to put your code for displaying within the foreach loop.

Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
