### ISSUE TITLE
Missing cmb2-front.min.css

### ISSUE THREAD

**Issue by artuze** [WebDevStudios/CMB2#384]
Awesome system! It's quickly becoming one of my new favorite tools.

I'm using it for a project right now with a frontend form where I have `SCRIPT_DEBUG` off (in staging) and there's no styles being loaded, or rather, the stylesheet it's trying to load doesn't exist.

Guessing that a change to the Gruntfile and committing the minified version would do it?

I'll try to take a minute to do get a pull request in today sometime.

I should also mention that I'm using the WordPress plugin, but it seems that there isn't a minified version in here either. I'll just deregister and register without the .min suffix until that can get updated.

**Comment by jtsternberg** [comment]
This has been addressed in the trunk branch in will be in the next release: https://github.com/WebDevStudios/CMB2/commit/aab8a3f661e244f952945f6ad1db1aa278d35204

**Comment by artuze** [comment]
Perfect! Hadn't checked that branch.

Thanks!
