### ISSUE TITLE
Call to undefined function cmb2_get_option()

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#386]
Trying to include CMB2 in my custom plugin, but getting `Call to undefined function cmb2_get_option()` when trying to retrieve the options. The CMB2 files are loaded correctly, as I get my metaboxes in administration when I comment out the `cmb2_get_option()`... Am I missing something?

```php
<?php
/*
Plugin Name: MyPlugin
*/
/**
 * Include CMB2
 */
require_once('inc/bs-setup.php');
require_once('inc/bs-options.php');

add_action('plugins_loaded','test');
function test () {
   cmb2_get_option('my_option');
}

```

**Comment by jtsternberg** [comment]
The earliest you can use the cmb2 helper functions is during or after the 'cmb2_init' hook (which happens late on the 'init' hook).

**Comment by vasikgreif** [comment]
Thanks for help, this hook worked!

**Comment by jtsternberg** [comment]
:thumbsup:
