### ISSUE TITLE
wp_query orderby

### ISSUE THREAD

**Issue by fredleput** [WebDevStudios/CMB2#388]
Does a cmb field can be used a orderby parameter of wp_query ?

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
