### ISSUE TITLE
date_format parameter not applied to non-timestamp based date inputs.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/CMB2#39]
Looks like `date_format` is only ever applied inside of text_date_timestamp(). I would assume we want it to be applicable to `text_time` and `text_date`, but I'll leave it up to your discretion

**Comment by danielmilner** [comment]
It appears that `text_date` honors the `date_format`, but only when you edit and re-save the record. It may be that the date picker is not honoring the `date_format`.

**Comment by yivi** [comment]
I can confirm that something goes weird regarding 'date_format'.

This code:
```
$main->add_field(
		[
			'name'        => __( 'Fecha', 'ojiva-plugin' ),
			'id'          => $prefix . 'fecha_realizacion',
			'type'        => 'text_date',
			'date_format' => 'd-m-Y'
		]
	);
```

Produces this:
![screen shot 2015-03-11 at 11 20 44](https://cloud.githubusercontent.com/assets/1815039/6594359/b5430316-c7e0-11e4-95e9-bb9f6560e490.png)

**Comment by tacone** [comment]
That's precisely what happens to me, the format is applied to the textbox, but not to the datepicker.

**Comment by tacone** [comment]
My current workaround:

```js
$('.cmb2-datepicker').focus(function () {
        var val = $(this).val();
        $(this).datepicker("option", "dateFormat", "dd/mm/yy");
        $(this).val(val);
});
```

**Comment by yivi** [comment]
@tacone, I have working fix in #446.
You can checkout my fork at https://github.com/yivi/CMB2, which fixes all these problems. If you can test it out to confirm things are working as expected, it would be nice.

Hopefully at some point we can finish integrating my PR into the main project.

Regards.

**Comment by tacone** [comment]
I can't test right now, as I'm a under a tight deadline, will surely do in the next project.

Thank you for now.

**Comment by jtsternberg** [comment]
This should be good in [trunk](https://github.com/WebDevStudios/CMB2/tree/trunk). Huge thanks for @yivi's work. Please test.

**Comment by tnorthcutt** [comment]
Closing as this looks resolved; @jtsternberg please reverse if I'm wrong 😄
