### ISSUE TITLE
Group field - collapsed by default

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#391]
Is it possible to set the group fields to be collapsed by default? I have many fields in my groups, and having the groups opened by default makes it difficult to navigate thru.

**Comment by jtsternberg** [comment]
Now possible (https://github.com/WebDevStudios/CMB2/blob/9d691b17c3a53d8f369b322a82aeeafc753183c3/example-functions.php#L416). You'll need to use the trunk branch.

**Comment by vasikgreif** [comment]
Very cool, thanks!

**Comment by vlaellayug** [comment]
Not working if there's no group field type that is file.
