### ISSUE TITLE
Translating CMB2 when including in custom plugin

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#392]
I'm including CMB2 as a library in my plugin, which obviously has different textdomain than CMB2. What is the preffered way to load translations with mixed textdomains?

**Comment by robneu** [comment]
IMO the best solution for this is to use [grunt-wp-i18n](https://github.com/cedaro/grunt-wp-i18n) in your customer plugin and replace the CMB textdomain on build.

**Comment by vasikgreif** [comment]
Thanks... Time to learn how that `grunt` works..:D
