### ISSUE TITLE
How to show CMB2 on specific post category

### ISSUE THREAD

**Issue by sajiddesigner** [WebDevStudios/CMB2#393]
Hello
 i want to show meta box on specific post category. but it is not working
I am using code
```
$promotion_post = new_cmb2_box( array(
        'id'            => 'centrality-promotion-post',
        'title'         => __( 'Promotion Post', 'cmb2' ),
        'object_types'  => array( 'post', ), // Post type
        'show_on' => array( 'key' => 'category', 'value' => 'promotion' ),
        'context'       => 'normal',
        'priority'      => 'high',
        'show_names'    => true, // Show field names on the left
        // 'cmb_styles' => false, // false to disable the CMB stylesheet
        'closed'     => true, // Keep the metabox closed by default
    ) );
```

Please tell me how can i do this.

**Comment by jtsternberg** [comment]
I would look at the example in example-functions.php: https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L31-L37

Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.

**Comment by mw247** [comment]
Just a heads up that the example uses "has_tags". Use "has_category" to target categories.
