### ISSUE TITLE
cmb_styles false not working on options page

### ISSUE THREAD

**Issue by JiveDig** [WebDevStudios/CMB2#394]
Maybe i'm doing it wrong, but turning styles off for a post/page metabox seems to work, but this isn't.

Here's my code.
```$cmb = new_cmb2_box( array(
			'id'         => $this->metabox_id,
			'hookup'     => false,
			'cmb_styles' => false,
			'show_on'    => array(
				// These are important, don't remove
				'key'   => 'options-page',
				'value' => array( $this->key, )
			),
		) );```

**Comment by jtsternberg** [comment]
What's your whole code? Because, you'll have to [remove this](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php#L68) if you're using the current version.

**Comment by JiveDig** [comment]
Wow... yeah my code was taken right from that. Perfect now. Thanks!

**Comment by jtsternberg** [comment]
:thumbsup:
