### ISSUE TITLE
Saving "dynamic" WYSIWYG fields doesn't work

### ISSUE THREAD

**Issue by chrishandy9** [WebDevStudios/CMB2#395]
Hi, I have created a textbox that accepts user input to decide how many additional boxes to display, once that number is entered and saved, the edit post page reloads and displays the amount of WYSIWYG boxes as requested. Upon saving the post, nothing gets updated/inserted into the database. The $_POST data appears in the object if dumped, but it doesn't make it to the database.

I manually added each box instead of looping through them (with the same ID as if they were being looped through) and it saved the post meta fine. My code is as follows:

    $cmb = new_cmb2_box(array(
		'id' 			=> 'num_slides_box',
		'title' 		=> __( 'Enter number of slides', 'cmb2'),
		'object_types' 	=> array('post'), //post type
		'context'		=> 'normal',
		'priority'		=> 'high',
		'show_names'	=> 'true',//show the field names on the left
	) );
    $slideNum = get_post_meta($post_id, 'num_slides', true);
    for ($i = 0; $i < $slideNum; $i++) { 
		$cmb->add_field(  array(
			'id'   		=> 'slider_group_'.$i,
			'name' 		=> 'Slide',
			'desc' 		=> 'Side contents'.$i,
			'type' 		=> 'wysiwyg',
			'options' 	=> array(),
		) );
	}

Is there a reason as to why it won't save fields that have been looped through?

**Comment by tw2113** [comment]
Confirmed, but I can't determine why the data isn't reaching a point of being able to be saved.

**Comment by jtsternberg** [comment]
Where are you getting `$post_id` from? Because it's likely it's not available when the saving happens.

**Comment by tw2113** [comment]
With my testing, as dirty as it was, I was just grabbing the ID from $_GET['post'] in the editor screen. By the time everything was getting to processing methods, the fields from the for loop weren't populated.

**Comment by jtsternberg** [comment]
right, there are no `$_GET` query variables during the save_post hook.

**Comment by jtsternberg** [comment]
This should work:
```php
$cmb = new_cmb2_box(array(
    'id'            => 'num_slides_box',
    'title'         => __( 'Enter number of slides', 'cmb2'),
    'object_types'  => array('post'), //post type
    'context'       => 'normal',
    'priority'      => 'high',
    'show_names'    => 'true',//show the field names on the left
) );

$post_id = 0;
if ( isset( $_REQUEST['post'] ) ) {
    $post_id = $cmb_demo->object_id( absint( $_REQUEST['post'] ) );
} elseif ( isset( $_REQUEST['post_ID'] ) ) {
    $post_id = $cmb_demo->object_id( absint( $_REQUEST['post_ID'] ) );
}

if ( $post_id ) {
    if ( $slideNum = get_post_meta( $post_id, 'num_slides', true ) ) {
        for ( $i = 0; $i < $slideNum; $i++ ) { 
            $cmb->add_field(  array(
                'id'      => 'slider_group_'.$i,
                'name'    => 'Slide',
                'desc'    => 'Side contents'.$i,
                'type'    => 'wysiwyg',
            ) );
        }
    }
}
```

**Comment by tw2113** [comment]
Just tested this myself and it worked. Thanks Justin.

@chrishandy9 not sure if you're still paying attention here, but give it a go when you got the time, if still needed.
