### ISSUE TITLE
css-front.min.css is missing

### ISSUE THREAD

**Issue by 1bigidea** [WebDevStudios/CMB2#398]
The Gruntfile.js doesn't minify the css-front.css file and therefore the wp_enqueue_style fails. There is a workaround by adding
define('SCRIPT_DEBUG', true); 
to wp-config.php

I'd fix it but I don't have grunt installed and if it is anything like gulp, that is a bag of flies I don't want to open.

**Comment by jtsternberg** [comment]
Related: #384
