### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by hyyan** [WebDevStudios/CMB2#399]
Is there any interest in adding a RTL support , I would like to make a PR to add RLT Support but I want to make sure if such a PR would be accepted.

Thanks in advance

**Comment by jtsternberg** [comment]
Would love that.

**Comment by hyyan** [comment]
I'll start working on that

**Comment by moonman22** [comment]
I use CMB2 in most of many projects  and as they are mostly in Arabic i would really appreciate RTL support for it , so i will be patiently waiting.

**Comment by devinsays** [comment]
There's a great grunt task that auto-generates these RTL stylesheets (cssjanus). Let me know if you need a hand @hyyan.

**Comment by safiro** [comment]
It'll be awesome.

**Comment by adilelsaeed** [comment]
@hyyan any progress?

**Comment by devinsays** [comment]
I took a first pass at this. Stylesheets are now generated. Haven't had a chance to test if they're all loading correctly and look correct yet.

**Comment by devinsays** [comment]
This morning I tested in Hebrew with the example-functions.php loaded. The RTL stylesheets loaded correctly and the all the metaboxes appeared to be loading properly RTL.

For anyone else who wishes to test this, go to "Settings > General" and select an RTL language like Arabic or Hebrew under the "Site Language" drop down.

Although I normally use the the "RTL Tester" plugin for front end testing, this wasn't working for me properly today. Perhaps has something to do with load order of plugins.

It would be great to have some actual Arabic/Hebrew (or RTL language) readers test this out with their projects before we merge.
