### ISSUE TITLE
Windows IIS Fatal Error on Go Daddy

### ISSUE THREAD

**Issue by DevinWalker** [WebDevStudios/CMB2#400]
Using WordPress on GoDaddy's IIS and installing CMB2 results in the following error:

`PHP Warning:  is_readable(): open_basedir restriction in effect. File(/languages/en_US.mo) is not within the allowed path(s): (G:/PleskVhosts//give.advancedwp.org\;C:\Windows\Temp\) in G:\PleskVhosts\give.advancedwp.org\httpdocs\wordpress\wp-includes\l10n.php on line 476`

Which basically means that the server configuration has a setting for permitted file paths, and that this plugin does not match the required pattern... hence the error. 

I've narrowed it down to the `l10ni18n` method: https://github.com/WebDevStudios/CMB2/blob/master/init.php#L157

I'm looking into a fix right now that'll make IIS happy and preserve the method's functionality.

**Comment by DevinWalker** [comment]
Looks like this specific function is throwing the error: https://github.com/WebDevStudios/CMB2/blob/master/init.php#L163

Which is a core WP function... still investigating

**Comment by DevinWalker** [comment]
Got it... adding the full path to the to the function fixes the error we're experiencing in IIS:

`$loaded = load_theme_textdomain( 'cmb2', get_template_directory() . '/languages/' );`

All the examples on the Codex use `get_template_directory` as well: https://codex.wordpress.org/Function_Reference/load_theme_textdomain 

I'm not sure why CMB2 omitted it. PR coming in a sec

**Comment by jtsternberg** [comment]
Because load_plugin_textdomain && load_muplugin_textdomain both expect a relative path, and apparently load_theme_textdomain expects an absolute path. Good catch!

**Comment by tld1990** [comment]
Why on earth are you using load_theme_textdomain(); in your plugin? Doesn't that go completely against the logic of internationalization? Certainly messes up translation plugins such as xili-language.
