### ISSUE TITLE
taxonomy_radio_inline is empty

### ISSUE THREAD

**Issue by Mte90** [WebDevStudios/CMB2#405]
If i choose the field `taxonomy_radio_inline` the field is missing but with `taxonomy_radio` i get the field without problems with the other same parameters.

**Comment by Mte90** [comment]
it was so easy to fix?
i've tried to do myself but the code is not simple XD

**Comment by jtsternberg** [comment]
It was only easy after staring at CMB2 code for years. :D

**Comment by Mte90** [comment]
[**@jtsternberg**](https://github.com/jtsternberg) commented on [28 lug 2015 23:10 CEST](https://github.com/WebDevStudios/CMB2/issues/405#issuecomment-125755161 "2015-07-28T21:10:53Z - Replied by Github Comment Enhancer"):
> It was only easy after staring at CMB2 code for years. :D

ahahah you win :-D
