### ISSUE TITLE
oembed field type creating additional post meta.

### ISSUE THREAD

**Issue by tubiz** [WebDevStudios/CMB2#406]
Please the oembed field type is creating additional post meta.
In a post I can see multiple additional post meta added

Their names are listed below

_oembed_69acdd5f091b570c740c067e833ae240
_oembed_9e11919759e9c2cd4f87e9304fc369a0
_oembed_aba4d8d299694591da665025ea8e13d2
_oembed_time_7e49ff23699fecf9574a3d347759be63

Please is this normal.

**Comment by jtsternberg** [comment]
Yes, this is normal. This is WordPress caching the results of oembed lookups in order to avoid API calls every page load.
