### ISSUE TITLE
Custom fields and rendering on the admin pages

### ISSUE THREAD

**Issue by bbmatt** [WebDevStudios/CMB2#409]
I'm wondering whether the rendering of custom fields is working as expected. Apologies for the rushed issue here, really up against it work wise!

I'm creating a custom field group which includes a persons name, position and photo (which is part of a repeatable cmb2 group) 

One thing I've noticed with custom fields, specifically custom fields with multiple items, is that they 'inherit' the description from the cmb2 add_group_field entry. 

So, here's the entry in my cmb2 group for a custom field 'person', note the description:

```php
$feature_group->add_group_field($feature_group_field_id, array(
    'name' => __('Person', 'cmb2'),
    'description' => __('Optional photo, name and title for person linked with feature.', 'cmb2'),
    'id'   => 'person',
    'type' => 'person'
  ));
```

Here's the render callback for one of the fields in my custom person type:
(Note, I'm trying to add a description for this field, using 'desc') 

```php
<div class="alignleft"><p><label for="<?php echo $field_type_object->_id( '_person_name' ); ?>'"><?php echo esc_html( $field_type_object->_text( 'person_person_name_text', 'Persons name' ) ); ?></label></p>
    <?php echo $field_type_object->input( array(
      'name'  => $field_type_object->_name( '[person-name]' ),
      'desc' => 'Enter the persons name',
      'id'    => $field_type_object->_id( '_person_name' ),
      'value' => $value['person-name'],
    ) ); ?>
  </div>
```

Here's the resulting layout in the page editor:

![image](https://cloud.githubusercontent.com/assets/1204915/8986546/93473418-36d4-11e5-9f18-e658d94bf90b.png)

You can clearly see it's repeated the cmb2 group field description for each entry. The desc has been added, but it's not formatted with a paragraph (cmb2-metabox-description class)

Either I'm doing something wrong, or there's some code issues with the rendering of custom fields.

If I get time, I'll look into this, assuming it is an issue.

**Comment by jtsternberg** [comment]
Take a look at the address field example as it uses a description as well. It might point you in the right direction. https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/custom-field-types/address-field-type.php#L72-L136

**Comment by bbmatt** [comment]
Sure, I've been following that - works great. 

I *can* hardcode in a description within the render callback:

```php 
<div class="alignleft"><p><label for="<?php echo $field_type_object->_id( '_person_name' ); ?>'"><?php echo esc_html( $field_type_object->_text( 'person_person_name_text', 'Persons name' ) ); ?></label></p>
    <?php echo $field_type_object->input( array(
      'name'  => $field_type_object->_name( '[person-name]' ),
      'id'    => $field_type_object->_id( '_person_name' ),
      'value' => $value['person-name'],
    ) ); ?>
    <p class="cmb2-metabox-description">A description</p>
  </div>
```

However, that doesn't detract from the fact, that unless you set a custom field to *repeatable*, the cmb2 metabox description will repeat for each field.

includes/CMB2_Types.php is checking for repeatable and descriptions in repeat groups (public function _desc), but it's not doing that for non-repeatable fields in repeat groups.

**Comment by bbmatt** [comment]
Here's the address type exhibiting the issue:

![image](https://cloud.githubusercontent.com/assets/1204915/8987720/64b6137a-36da-11e5-9df5-cf26a5379540.png)

That's a direct implementation of the address type.

```php
$feature_group->add_group_field($feature_group_field_id, array(
    'name' => __('Address', 'cmb2'),
    'description' => __('This will repeat for each field', 'cmb2'),
    'id'   => 'address',
    'type' => 'address'
  ));
```

**Comment by tnorthcutt** [comment]
@bbmatt is this still a issue? If not, would you mind closing, or if it is, could you update with any new info available? Thanks!

**Comment by bbmatt** [comment]
I haven't checked - found another workaround some time ago, but as nobody else has posted a related issue, I'll close it.
