### ISSUE TITLE
Is it possible to update a repeating-metabox via phpmyadmin?

### ISSUE THREAD

**Issue by jaxgeller** [WebDevStudios/CMB2#410]
I have a bunch of repeatable fields backups, like so 

```
a:1:{s:16:\"NG_members_group\";a:100:{i:0;a:10:{s:4:\"name\";s:11:\"Susan 
...
```
this goes on for about 300 lines. 

What I need to do is go into the phpmyadmin, and replace whats already in there with the snippet above. 

For some reason, if I edit the metabox field in the phpmyadmin, no effects are registered. Is there some kind of hook im missing by directly altering the php table (maybe the `save_fields` function)? Ive tried raw update queries as well, but to no avail. 

Heres a sample picture of me trying to change the values. 
![image](https://cloud.githubusercontent.com/assets/4494509/8990527/f031968c-36c0-11e5-9e00-c76d9ffd036b.png)

Is there anyway given the snippet above to drop-insert it into the meta fields, without having to go through each metabox and filling out the content again.

Thanks!

**Comment by jaxgeller** [comment]
Ive tried running queries like 

```
UPDATE `wp_options` SET `option_value`=‘…'  WHERE `option_name` = 'NG_members_options'
``` 

Still not updating values.

**Comment by Mte90** [comment]
When an array is saved in wordpress the value are serialized, you need to serialize the value after the changing in the db http://php.net/manual/en/function.serialize.php
For this reason is better working on the values on wordpress.

**Comment by jtsternberg** [comment]
@jaxgeller are you using a persistent cache? What do you see in the admin when you update the value in the DB? And I assume you're inserting a serialized string?

**Comment by jaxgeller** [comment]
@Mte90 The situation im in is a little tricky, i had over 90 repeating metaboxes with lots of content. Since then, i have a backup of the serialized database entry, but have since lost all the data. Im trying to drop-replace the db entry so i dont have to go in and re-add all of the metabox entries. 

@jtsternberg Here's the string ive been running with the query above with some data omitted.

```
a:1:{s:16:\"NG_members_group\";a:100:{i:0;a:10:{s:4:\"name\";s:11:\"Susan Tynan\";s:4:\"work\";s:11:\"Framebridge\";s:5:\"title\";s:3:\"CEO\";s:11:\"headshot_id\";s:2:\"99\";s:8:\"headshot\";s:27:\"http://placehold.it/200x200\";s:8:\"location\";s:1:\"0\";s:4:\"desc\";s:492:\"Susan Tynan is ....\";s:7:\"twitter\";s:31:\"https://twitter.com/...\";s:8:\"linkedin\";s:38:\"https://www.linkedin.com/in/...\";s:6:\"sector\";s:1:\"4\";}i:1;
```

And heres a video of me detailing whats going on (no audio) just to make sure i'm not missing any steps.

https://www.youtube.com/watch?v=zHbzOwq5_Tk

**Comment by jaxgeller** [comment]
There was a cache that comes with wpengine by default, it has been purged and disabled at the time of the video

**Comment by jaxgeller** [comment]
Just going to re-input the data
