### ISSUE TITLE
Security question / HTML as input

### ISSUE THREAD

**Issue by spwebguy** [WebDevStudios/CMB2#413]
Hi,

I have a custom type with a couple of fields and I would like the user to be able to **input HTML**.

Example of fields for a "Book" custom type:
Title (text) — Subtitle (text) — Genre (text) — Synopsis (textarea) — Excerpt (textarea)

I would like my user to be able to enter things like this in any of these fields:
`<span style="color: red;"></span>`

I know how to remove sanitization of course but I don't think I should be doing this, so: 

**how do I let people input HTML in the CMB2 fields (admin panel, not front-end) without having to worry about security / technical issues?**

Thanks a lot for all the great work.

**Comment by jtsternberg** [comment]
[`wp_kses_post`](https://codex.wordpress.org/Function_Reference/wp_kses_post) is the default sanitization for [wysiwyg and textarea field types](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Sanitize.php#L288-L294) and is a wrapper for [`wp_kses`](https://codex.wordpress.org/Function_Reference/wp_kses) with the `$allowed_html` and `$allowed_protocols` defined. You could define your own `wp_kses` sanitization callback and define those `$allowed_html` and `$allowed_protocols` yourself, or just let CMB2 handle it with it's built-in sanitization. :)

**Comment by spwebguy** [comment]
Hi Justin!

Just when you answer me I found this function... I should have looked for it more before asking. I'll let **CMB2** do that for me in most cases but will still have custom sanitization in a few others.

Thank you for the speedy answer, and thank you for working on CMB2. I'm glad you're still maintaining it, it's a very important tool for many of us. 

Also **THANKS** for adding the fix for the issue that happens when deleting an item from a repeatable group (when it left a "ghost" item), it's very useful. 

Good luck!

**Comment by jtsternberg** [comment]
awesome, you're welcome!
