### ISSUE TITLE
dateFormat issue

### ISSUE THREAD

**Issue by feliksby** [WebDevStudios/CMB2#414]
1) I've changed dateFormat in localization .po file to dd.mm.yy
Dates are stored correct in database(dd.mm.yy). But after saving all dates displaying as default mm/dd/yy
2) I guess it's would be great to apply by default dateFormat that is choosen in wordpress options, isn't it?

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
