### ISSUE TITLE
CMB2 front end question

### ISSUE THREAD

**Issue by AGDesignStudio** [WebDevStudios/CMB2#416]
All working perfectly I just have a question about how I could fix this:

        // build id number for user
        $id = $_SERVER['REMOTE_ADDR'];
        $unique_id = hexdec( substr(sha1($id), 0, 15) );

        // Add the user id number to a session for later
        $_SESSION['ag'] = $unique_id;

        // This is the WordPress post ID where the data should be stored/displayed.
        $object_id = $unique_id;
        $metabox_id = 'ag';

        cmb2_metabox_form( $metabox_id, $object_id);

The above code is working fine.. but what I want to do is save the metabox data to a post, but still use the $unique_id so each user will see their data that has been added....

What I am working on is some extra fields for a product page, which a visitor can come and add items to then checkout.

I need the items stored on the product meta but not have it so each user can see each others bits..

Hope that makes seance..

Aaron

**Comment by tnorthcutt** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
