### ISSUE TITLE
User fields aren't saving in 2.0.9

### ISSUE THREAD

**Issue by achavez** [WebDevStudios/CMB2#417]
Custom metabox fields on user object types have stopped saving in v2.0.9. Best I can tell, it's because of the introduction of `can_save()` in [CMB2_hookup.php](https://github.com/WebDevStudios/CMB2/blob/dff3d6158c8ba915e542c6cf9a9f4d846fe37866/includes/CMB2_hookup.php#L341-L343) without the object type being passed.

It works for me after changing to:
```php
if ( $this->can_save( 'user' ) ) {
    $this->cmb->save_fields( $user_id, 'user', $_POST );
}
```

Happy to send a PR if you agree with the solution and that'd be of help. For now, rolling back to v2.0.8 fixes this in my case.

**Comment by jtsternberg** [comment]
This is a pretty big bug, so I'm not waiting for a PR, but will give you props. I'll need to release the next version asap to address it. Thank you for reporting.

**Comment by achavez** [comment]
No problem! Thanks for the quick response and for pushing a commit so quickly.

**Comment by jtsternberg** [comment]
https://github.com/WebDevStudios/CMB2/releases/tag/v2.1.0
