### ISSUE TITLE
Page Specific Metafields

### ISSUE THREAD

**Issue by mick3dx** [WebDevStudios/CMB2#418]
Just want to start off with, thanks for creating CMB, creating custom websites is infinitely easier because of it.

For a given website I use several metaboxes on all pages (hero, footer etc), but I don't always use the same fields, is there in-built functionality to remove metafields on pages with specific IDs?

**Comment by jtsternberg** [comment]
You can use the [`'show_on_cb'` field parameter](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#user-content-show_on_cb).
Demoed in example-functions.php:
https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L97
https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L39-L52
