### ISSUE TITLE
user field not saving

### ISSUE THREAD

**Issue by gyrus** [WebDevStudios/CMB2#419]
I'm creating a user field for the first time and the value isn't saving. Here's my code:

	$cmb = new_cmb2_box( array(
		'id'				=> 'venue_youth_hub_manager_box',
		'title'				=> __( 'Youth hub manager details' ),
		'object_types'		=> array( 'user' ),
		'show_names'		=> true,
		'closed'			=> false,
	));
	$cmb->add_field( array(
		'name'				=> __( 'Youth Hub manager details' ),
		'id'				=> 'manager-youth-hub-title',
		'type'				=> 'title',
		'on_front'			=> false,
	) );
	$cmb->add_field( array(
		'name'				=> __( 'Youth Hub managed' ),
		'id'				=> 'manager-youth-hub',
		'type'				=> 'select',
		'options'			=> yh_cmb2_get_youth_hubs_options(),
		'on_front'			=> false,
	) );

The options are being populated correctly, with the correct values. When I save, the returning select doesn't keep the value I set, and there's just nothing in the usermeta table corresponding to the id.

**Comment by davidshq** [comment]
Did you upgrade to the latest version that was released today? It patched a bug with saving for user fields I believe.

**Comment by jtsternberg** [comment]
that's correct. the related issue: #417

**Comment by gyrus** [comment]
Bingo! Many thanks.
