### ISSUE TITLE
Should exists an field_type which lists the users

### ISSUE THREAD

**Issue by jcchavezs** [WebDevStudios/CMB2#421]
In some cases it is needed a **user_select** field that allows to select one or more users.

For example: In a service or product post type, one or more contact persons (users) could be needed.

**Comment by jtsternberg** [comment]
How about this one: https://github.com/WebDevStudios/CMB2/issues/363#issuecomment-126817617

**Comment by tw2113** [comment]
Closing in favor of the plugin from @Mte90 found at https://github.com/WebDevStudios/CMB2/issues/363#issuecomment-126817617
