### ISSUE TITLE
Social Accounts

### ISSUE THREAD

**Issue by mahdi-alavi** [WebDevStudios/CMB2#424]
hi,
thx for this grate plugin.
i use this for user profile by default code
https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L454-L524

how can display output user data
i test some code but can't use that,
please tell sample code to display user profile data.

**Comment by avoinicu** [comment]
You can use [get_user_meta()](https://developer.wordpress.org/reference/functions/get_user_meta/) function. It works the same way [get_post_meta()](https://developer.wordpress.org/reference/functions/get_post_meta/) does.

Also make sure you are using the latest release.

**Comment by ronalfy** [comment]
Assuming you have an array of URLs, you can use something like this to spit out FontAwesome implementations.

https://gist.github.com/ronalfy/24dc28b1ecb2b918cbca
