### ISSUE TITLE
Update Taxonomy Term with Input Text Fields

### ISSUE THREAD

**Issue by saqwild** [WebDevStudios/CMB2#425]
Hi, Firstly, thank for a great plugin.

I am in process of building my food recipe site where I already have one taxonomy named "Ingredient", I was wondering if its possible to use CMB (repeated group) and link the taxonomy "Ingredient" with it.

So, as a result when I enter some ingredients (text field) and saves the post, it check if the value already exists, if not, it adds the entered ingredient and update the taxonomy "ingredient accordingly.

Can you please confirm if this would be possible? if so, how?

**Comment by tnorthcutt** [comment]
@saqwild Great question, but to be frank this isn't really a code issue per se, so this isn't the right place for the question :smile:. I'd suggest asking somewhere like [WordPress Stackexchange](https://wordpress.stackexchange.com/) or similar.
