### ISSUE TITLE
JS Re-initializing after Rendering Field via Ajax

### ISSUE THREAD

**Issue by ingageco** [WebDevStudios/CMB2#426]
I've got an ajax call that receives the cmb2_get_field($metabox, $field)->render_field() output. This can be called multiple times, adding multiple fields to what eventually gets submitted as a form.

After adding that markup to the page, I've called window.CMB2.init() and most of the fields (tested select, text, and date) are working great. Repeatable fields seem to be a bit buggy - with the number of rows being inconsistent (should only return one new row, but sometimes return 2, 3, 4, etc)

Is there a better way to initialize the JS for CMB2 after we add the markup that will produce a better chance at it working as it should?  

Thank you guys for the great framework - by far the best WP enhancement to our dev flow this year!

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.

**Comment by surajprgupta** [comment]
I am getting an issue not similar but related perhaps,

I am rendering a field using cmb2_get_field (date picker in this case)
I think the related js for the date picker isn’t added and when I am clicking on the field, then the date picker isn’t appearing.

Here's the code I am using - 

`add_action('cmb2_admin_init', array($this, 'add_options_page_metabox'));`

`public function add_options_page_metabox()
    {

        // Add our CMB2 metabox.
        $cmb = new_cmb2_box(array(
            'id' => $this->metabox_id,
            'hookup' => false,
            'save_fields' => false,
            'cmb_styles' => false,
        ));

        // Add your fields here.
        $cmb->add_field(array(
            'name' => __('Fetch Events and Groups From Date', 'liquid-outreach'),
            'desc' => __('All events created or modified since the date will be synced',
                'liquid-outreach'),
            'id' => 'modified_since', // No prefix needed.
            'type' => 'text_date',
            'default' => !empty($_POST['modified_since']) ? $_POST['modified_since'] : '',
            'attributes' => [
                'required' => 'required'
            ]
        ));

        $cmb_box_sync_post_form = new_cmb2_box(array(
            'id' => 'ccb_event_sync_to_post_metabox',
            'hookup' => false,
            'save_fields' => false,
            'cmb_styles' => false,
        ));
        $cmb_box_sync_post_form->add_field(array(
            'name' => __('Fetch Events Start Date', 'liquid-outreach'),
            'desc' => __('',
                'liquid-outreach'),
            'id' => 'start_date', // No prefix needed.
            'type' => 'text_date',
            'default' => !empty($_POST['start_date']) ? $_POST['start_date'] : '',
            'attributes' => [
                'required' => 'required'
            ]
        ));
        $cmb_box_sync_post_form->add_field(array(
            'name' => __('Fetch Events End Date', 'liquid-outreach'),
            'desc' => __('',
                'liquid-outreach'),
            'id' => 'end_date', // No prefix needed.
            'type' => 'text_date',
            'default' => !empty($_POST['end_date']) ? $_POST['end_date'] : '',
            'attributes' => [
                'required' => 'required'
            ]
        ));

    }`


`public function admin_page_display()
    {
        ?>
        <style>
            .hide-obj {
                display: none !important;
            }
        </style>

        <div class="wrap cmb2-options-page <?php echo esc_attr($this->key); ?>">
            <h2><?php echo esc_html(get_admin_page_title()); ?></h2>
            <?php
            cmb2_metabox_form($this->metabox_id, $this->key);
            ?>
        </div>
<?php
        $this->show_sync_details();
    }`

`protected function show_sync_details()
    {
                $cmb_field_start_date = cmb2_get_field('ccb_event_sync_to_post_metabox', 'start_date');
                $cmb_field_start_date->render_field();
     }`

there's no error in the console.

**Comment by tw2113** [comment]
See Justin's reply at https://wordpress.org/support/topic/issue-after-rendering-a-field-using-cmb2_get_field/#post-9168601
