### ISSUE TITLE
User profile fields are pre populated with current user data

### ISSUE THREAD

**Issue by avoinicu** [WebDevStudios/CMB2#427]
Whenever I am adding a new user, the custom fields come pre populated with the current user's data. I am using CMB2 2.1.0 with WordPress 2.4.2

Tested field types: text and file (with and without default values).

**Comment by avoinicu** [comment]
I've managed to solve this problem by updating the [IF statement at line 228 in CMB2_Field.php](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Field.php#L228-L233) with the following:
```php
// If no override, get value normally
if ( 'cmb2_field_no_override_val' === $data ) {
	switch (true) {
		case ($a['type'] === 'options-page'):
			$data = cmb2_options( $a['id'] )->get( $a['field_id'] );
			break;
		case ($a['type'] === 'user' && get_current_screen()->action === 'add'):
			$data = cmb2_options( $a['id'] )->get( $a['field_id'] );
			break;
		default:
			$data = get_metadata( $a['type'], $a['id'], $a['field_id'], ( $a['single'] || $a['repeat'] ) );
	}
}
```

**Comment by jtsternberg** [comment]
This has been addressed in the trunk branch, thank you for reporting! Please please please don't modify CMB2 core as there may be other plugins depending on your copy of CMB2 (because of the way CMB2 loading works) and while your edits may work for your use-case, it's alway possible that they could break somebody else's.

**Comment by avoinicu** [comment]
Thank you for the quick reply!

The only reason I posted my solution is because I need a temporary fix until a new version of CMB2 is released and I thought this might help somebody else, but you are right.

Thank you again for the great work you do!

**Comment by jtsternberg** [comment]
Understood. Did you happen to test trunk? It should be good (it worked for me), but want to verify.

**Comment by avoinicu** [comment]
Yes, it worked as expected.
