### ISSUE TITLE
Image(file) ID doesn't exist in post meta

### ISSUE THREAD

**Issue by usernamethatsnottaken** [WebDevStudios/CMB2#428]
So I've been working on a plugin for the past month or so and everything worked, until recently. I believe that after I updated from CMB 2.0.9 to 2.1.0, the problem started occurring.

I have a form in the custom post type. The form is powered by CMB2. When I upload an image, the link to the image is added to postmeta, however, there's no image ID.
That wasn't the case before the update took place.

Metabox ID is contphoto. Before the update, after I'd upload an image, the postmeta would contain contphoto(link to the pic) and contphoto_id(id of the pic). Now I only have the link, but no ID and thus, I can't use the image at all.

Keep in mind that the pic IS uploaded. I can find it in the media library, I can find it in the post, but I can't use it on the front end, because I can't fetch its ID.

Does anyone know where CMB 2.1.0 store file ID's?

P.S. get_post_thumbnail_id doesn't work, I've tried.

**Comment by jtsternberg** [comment]
The attachment id gets [added to the _id hidden input via JS](https://github.com/WebDevStudios/CMB2/blob/master/js/cmb2.js#L247) when you select the attachment from the media modal. In my testing, everything is working normally.

**Comment by usernamethatsnottaken** [comment]
Yes, but how can I fetch the attachment ID based on the post id? Nothing conventional has worked for me so far. I looked in the database, and I couldn't find the connection between the post and the attachment :/

**Comment by baljindersingh88** [comment]
https://codex.wordpress.org/Function_Reference/get_post_thumbnail_id
I think it will fetch attachment id based on post id

**Comment by usernamethatsnottaken** [comment]
I found the problem. This was my code:
```
$cmb_demo->add_field( array(
		'name'		 => __( 'Contestant Photo', 'cmb2' ),
		'id'				=> $prefix . 'contphoto',
		'type'			=> 'file',
		'escape_cb'		=> false,
		'sanitization_cb' 	=> false
		) );
```

Once I removed escape_cb and sanitization_cb, the ID value was being passed again.
Thanks everyone for your help.
