### ISSUE TITLE
How to use CMB2 to build a custom wp_query by setting up a taxonomy_multicheck to a page?

### ISSUE THREAD

**Issue by monecchi** [WebDevStudios/CMB2#434]
Sorry if this is not the right place to post this question, it is more a doubt than an issue itself, but as I'm not an expert developer, I'd really appreciate if someone out there could help me to accomplish it.

Anyway, I use a theme which has a few CMB2 metaboxes set up already. My theme also uses its own framework in order to build custom blocks for a quick page design. One of its blocks is responsible for the loop of a custom post_type, so it has its default wp_query function, which I wish to change a bit in order to integrate with the CMB2 taxonomy_multicheck metabox.

My goal is to create a new taxonomy_multicheck metabox to be shown on pages only (already done), and them retrieve the selected taxonomies (categories) ids and pass them to a custom wp_query $args, specifically as an array of 'terms' => (36, 43, 44, 48)...

Here's what I've accomplished so far... 

    /**
     * Gets a number of terms and displays them as options
     * @param  string       $taxonomy Taxonomy terms to retrieve. Default is category.
     * @param  string|array $args     Optional. get_terms optional arguments
     * @return array                  An array of options that matches the CMB2 options array
     */
    function cmb2_get_term_options( $taxonomy = 'food_menu_categories', $args = array() ) {

    $args['food_menu'] = $taxonomy;
    // $defaults = array( 'taxonomy' => 'category' );
    $args = wp_parse_args( $args, array( 'food_menu' => 'food_menu_categories' ) );

    $taxonomy = $args['food_menu'];

    $terms = (array) get_terms( $taxonomy, $args );

    // Initate an empty array
    $term_options = array();
     if ( ! empty( $terms ) ) {
        foreach ( $terms as $term ) {
            $term_options[ $term->term_id ] = $term->name;
        }
    }

        return $term_options;
    }

This is how I've set up the taxonomy_multicheck metabox:

    /**
    * Page Custom Taxonomy Select
    */
    $meta_boxes[] = array(
      'id' => 'page_taxonomy_metabox',
      'title' => __('Food Categories Option', 'text_domain'),
      'object_types' => array('page'), // post type
      'context' => 'normal',
      'priority' => 'high',
      'show_names' => true, // Show field names on the left
        'fields' => array(
          array(
                'name' => __( 'Choose the Food Categories to be displayed:', 'text_domain' ),
                'desc' => __( 'This will "filter" the type of food you want to show', 'text_domain' ),
                'id' => $prefix . 'page_food_categories',
                'taxonomy' => 'food_menu_categories', //Enter Taxonomy Slug
                'type' => 'taxonomy_multicheck',
                'inline'  => true,
                'options' => cmb2_get_term_options(),    
          ),
       )
    );	

As per some tips I've read in the documentation, the function above the metabox set up, allow us to return a term_id from the taxonomy_multicheck as instructed here: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post

Now that the function is in place and the taxonomy_multicheck metabox is showing under pages in the wordpress admin, I need to get the ids from the selected categories (custom taxonomy) and pass them as an array to my wp_query construction.

My theme's block template looks like the following, it has an interface which allows me to sets a few options (posts_per_page, layout etc.), but it does not offer any way to exclude some categories from the wp_query loop it builds, what lead me to set up the taxonomy_multicheck metabox to accomplish this task. 

	<?php
		/**
		 * Theme's design block stuff
		 */	
	function block($instance) {
		extract($instance);
		
		// Fix for pagination
		if( is_front_page() ) { 
			$paged = ( get_query_var( 'page' ) ) ? get_query_var( 'page' ) : 1; 
		} else { 
			$paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) : 1; 
		}
		
		/**
		 * SET UP POST QUERY
		 */
		$query_args = array(
			'post_type' => 'food_menu',
			'posts_per_page' => $pppage,
			'paged' => $paged
		);
		
				
         // Grab the metadata from the database
         $page_food_categories = get_the_terms( get_the_ID(), '_myprefix_page_food_categories', true );

         // Echo the metadata
       //   echo esc_html( $page_food_categories );
      
		/**
		 * Set up category query if needed
		 */

			$query_args['tax_query'] = array(
			           
				array(
					'taxonomy' => 'food_menu_categories',
					'field' => 'term_id',
					'terms' => $page_food_categories, // Must be an array of ids or slugs e.g.: array => (43, 44, 38),
					'operator' => 'NOT IN'
				)
			);
	
		  $block_query = new WP_Query( $query_args ); 
	?>

In the template file after some of the theme's design block settings comes the loop... If I manually place the array => () of ids I want to exclude, the loop works, but if I set the $page_food_categories all posts from the taxonomy are pulled.

		<?php if( $type == 'grid' ) : ?>
			
			<div class="row">
				<?php 
					if ( $block_query->have_posts() ) : while ( $block_query->have_posts() ) : $block_query->the_post();
			
						/**
						 * Get Food Menu posts by food layout.
						 */
						get_template_part('loop/content', 'food_menu-grid');
						
						if( ($block_query->current_post + 1) % 3 == 0 && !( ($block_query->current_post + 1) == $block_query->post_count ) )
							echo '</div><div class="row">';
					
					endwhile;	
					else : 
						
						/**
						 * Display no posts message if none are found.
						 */
						get_template_part('loop/content','none');
						
					endif;
				?>

			</div>

Image preview of taxonomy_multicheck set up under wordpress admin >> page:
![captura de tela 2015-08-20 as 16 12 06](https://cloud.githubusercontent.com/assets/5252519/9393090/7cc1dd3c-4756-11e5-9c03-482ac9a42bd7.png)

**Comment by jtsternberg** [comment]
You'll notice [in the documentation](https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post) that the field is not using the 'taxonomy_multicheck' type, but is using a generic 'select'. In your case could probably be swapped out for 'multicheck'. But either way, you do not want any of the taxonomy_* field types if your intention is not to set the taxonomy terms for the page/post you are editing.

**Comment by monecchi** [comment]
@jtsternberg Thanks for your reply. Anyway I think I didn't got it. In fact my intention is to simply pass the taxonomy_multicheck values as an array () of another tax_query array, so here's the only thing I need to accomplish within my theme's wp_query construction:
 
Where ** $page_food_categories** is the taxonomy_multicheck, so how to output the selected checkboxes values as an array() populated with the checked categories ids?
    ...
    $query_args['tax_query'] = array(
          array(
          'taxonomy' => 'food_menu_categories',
          'field' => 'term_id',
          'terms' => $page_food_categories, // Must be an array of ids or slugs e.g.: array => (43, 44, 38),
          'operator' => 'NOT IN'
            )
    );
    ...

The way that wp_query is set up works out of the box if I manually place the array of ids such as `'terms' => array => (43, 44, 38),` It then displays all posts from the `'taxonomy' => 'food_menu_categories',` except those within the `'terms' => array()`

This is my first attempt using CMB2, and it seems great for a large of use cases, it is easier for me to output a field value within a php template, but it has been a pain to accomplish this task, I've searched through all the web and couldn't find nothing about how to do what seems to be a simple thing. Really sad here :(

**Comment by tw2113** [comment]
It's still going to be best to use https://github.com/WebDevStudios/CMB2/wiki/Field-Types#multicheck-and-multicheck_inline instead of the taxonomy_multicheck, because the taxonomy one isn't going to return data about the terms selected once it's done associating the term(s) to the post object. I'd recommend checking out the example code below that I worked up a couple days back for someone else. It'll save the selected value(s) to post meta in this case, making it query-able from wherever needed.

```
$prefix = 'myprefix_'
$cmb->add_field( array(
	'name'    => __( 'Downloads Categorys', 'cmb2' ),
	'desc'    => __( 'Select the downloads category.', 'cmb2' ),
	'id'      => $prefix . 'something',
	'type'    => 'multicheck',
	'options_cb' => 'something_get_all_terms',
) );
```

```
function something_get_all_terms() {
	$args = array(
		'taxonomy' => 'some_taxonomy',
		'hide_empty' => false
	);

	$terms = get_terms( $args );

	foreach( $terms as $term ) {
		$select_items[ $term->slug ] = $term->name;
	}

	return $select_items;
}
```
