### ISSUE TITLE
Additional after_label hook

### ISSUE THREAD

**Issue by DevinWalker** [WebDevStudios/CMB2#435]
Hey - I would like to add tooltips to our labels like so: https://github.com/WordImpress/google-maps-builder/issues/85

Currently the only way I can do this is with jQuery looping through each label and appending a span tag within the labels. Would you be open to adding a hook for us to add content/html before and after labels?

**Comment by jtsternberg** [comment]
@DevinWalker That's a good thought. The [744968d](https://github.com/WebDevStudios/CMB2/commit/744968d217d3f21374c334d31701cab852a02f86) is a step, but ideally we would have more WordPress style hooks in there. I've been mulling it around in my head, and haven't quite determined what the best option is.

**Comment by mathetos** [comment]
The easiest (for us users of CMB2) would be to add `after_label` and `before_label` strings to the array, like so:

```
    $cmb->add_field( array(
        'name'       => __( 'Test Text', 'cmb2' ),
        'desc'       => __( 'field description (optional)', 'cmb2' ),
        'id'         => $prefix . 'text',
        'type'       => 'text',
        'after_label'  => '<span class="tip"><i class="fa fa-info-circle"></i>This is info about this setting or field</span>',
    ) );
```

**Comment by DevinWalker** [comment]
@mathetos that's the exact functionality I could use.

**Comment by DevinWalker** [comment]
@jtsternberg would you be interested in a PR adding this functionality?

**Comment by jtsternberg** [comment]
Wouldn't this accomplish the same thing a little more elegantly?
```php
$cmb_demo->add_field( array(
	'name' => __( 'Test Text Area', 'cmb2' ),
	'id'   => $prefix . 'textarea',
	'type' => 'textarea',
	'label_cb' => 'render_custom_callback',
	'options' => array(
		'tooltip-class' => 'fa-info-circle',
		'tooltip'       => 'This is info about this setting or field',
	),
) );
```
With a callback like:
```php
function render_custom_callback( $field_args, $field ) {
	// Get default label
	if ( $label = $field->label() && $field->option( 'tooltip' ) ) {
		// If label and tooltip exists, add it
		$label .= sprintf( '<span class="tip"><i class="fa %s"></i>%s</span>', $field->option( 'tooltip-class' ), $field->option( 'tooltip' ) );
	}

	return $label;
}
```

**Comment by DevinWalker** [comment]
@jtsternberg tip of the hat to you sir. That looks very clean.

**Comment by jtsternberg** [comment]
Keep in mind, the `'label_cb'` only exists in trunk at the moment, but will be in the next release.

**Comment by mathetos** [comment]
Woot! Nice to see this added. Thanks!

**Comment by pgroot91** [comment]
Somehow the example provided doesn't seem to work.

**Comment by jtsternberg** [comment]
@pgroot91 you are right, I had some bugs in my sample code. I have updated to work properly in the example in the wiki: https://github.com/CMB2/CMB2/wiki/Tips-&-Tricks#modify-field-label-output

**Comment by pgroot91** [comment]
@tw2113 @jtsternberg thanks guys for the clarification and the provided update/fix. 👍
