### ISSUE TITLE
Show / hide fields depending on separate checkbox field?

### ISSUE THREAD

**Issue by khromov** [WebDevStudios/CMB2#437]
Didn't see this use case while skimming the docs - how would I go about only showing a field if a specific checkbox is checked, preferably via JS so no reload is necessary.

**Comment by safiro** [comment]
I need this too.

**Comment by jtsternberg** [comment]
I haven't used it, but you might try this library: https://github.com/jcchavezs/cmb2-conditionals

There is no conditional field-display via JS built-in, but you can do conditional field display with the `'show_on_cb'` field parameter: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#user-content-show_on_cb

**Comment by khromov** [comment]
Conditional logic should be a top priority and preferably in the core, coming off of ACF which has excellent conditional logic it feels like going back 10 years to use CMB2 unfortunately.

**Comment by jtsternberg** [comment]
@khromov It **is** a top priority. Unfortunately, our development resources (time) are limited. We are not in competition with ACF, and have differing fundamental values. If you prefer ACF, we encourage you to use it.

**Comment by khromov** [comment]
I apologize if my earlier comment came off as dismissive. CMB2 is uniquely positioned as the only easily-embeddable, fully-GPL fields framework.

**Comment by safiro** [comment]
1- I'm using a Select with id "select_style" with options
 'options'=>array(
		'first_style'=>'First Style',
		'second_style'=>'Second Style',
		'third_style'=>'Third Style',
)


and I want when I select First Style, a text field with id "add_title" displayed, when I select Second Style, the text field disappeared and colorpicker with id "article_bg" displayed and so on....

-- Can I get the complete code please.


2- I'm using another framework for global options "Redux".
How Can I display or hide CMB2 field based on what Redux returns?
if $redux['settings']['layout_one'] display cmb2 text , if $redux['settings']['layout_two'] display cmb2 file_list and so on....

Thanks.
