### ISSUE TITLE
File URL and ID values not deleting from hidden inputs in repeatable groups

### ISSUE THREAD

**Issue by mandiwise** [WebDevStudios/CMB2#439]
I Just noticed that file URL and ID values aren't cleared from their respective hidden inputs when as user clicks on the red minus sign to remove the image, so even though the image preview is cleared from its `<div>` upon click, when the user saves their changes, the image will reappear.

As far as I can tell, this is only a problem when the file field is included in a repeatable group.

**Comment by jtsternberg** [comment]
Thanks for reporting. This is now fixed in the trunk branch.

**Comment by mandiwise** [comment]
Thanks for your speedy response!
