### ISSUE TITLE
Class CMB not getting extended.

### ISSUE THREAD

**Issue by pvmishra** [WebDevStudios/CMB2#440]
I am currently tried to  add some method(function) to the CMB2 Class for that i had created my class and extended it to call the CMB2 but i am getting error for that.

 Fatal error: Class 'CMB2' not found in C:\wamp\www\some-website\wp-content\some-place\cmb2_field_table.php on line XX.

what i did is just the simple concept of OOPS.

class Own_Field_Addition_of_class extends CMB2 {
public function add_some_field( $field_id, array $field, $position = 0 ) {

      /* some logic */
}

}

**Comment by jtsternberg** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.

**Comment by pvmishra** [comment]
Than you, for your quick answer. I was curious to make a table field like the group fiend hence i raised the query. i wish that new cmb version should have the table support. its my feature request.

**Comment by jtsternberg** [comment]
I recommend viewing the documentation for extending by creating your own field types: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types
