### ISSUE TITLE
Conditional Questions

### ISSUE THREAD

**Issue by safiro** [WebDevStudios/CMB2#442]
1- I'm using a Select with id "select_style" with options

```php
'options' => array(
    'first_style' => 'First Style',
    'second_style' => 'Second Style',
    'third_style' => 'Third Style',
)
```

and I want when I select First Style, a text field with id "add_title" displayed, when I select Second Style, the text field disappeared and colorpicker with id "article_bg" displayed and so on....

-- Can I get the complete code please.

2- I'm using another framework for global options "Redux".
How Can I display or hide CMB2 field based on what Redux returns?
if `$redux['settings']['layout_one']` display cmb2 text , if `$redux['settings']['layout_two']` display cmb2 file_list and so on....

Thanks.

**Comment by fujianto** [comment]
+1 for this...

**Comment by jtsternberg** [comment]
I recommend looking at this addon by @jcchavezs: https://github.com/jcchavezs/cmb2-conditionals
