### ISSUE TITLE
Get Metabox field, but supply the value - possible?

### ISSUE THREAD

**Issue by ingageco** [WebDevStudios/CMB2#450]
Hey guys - we're using cmb2_get_field to get all of the fields to insert into some custom functionality. We then use ->render_field() to show it. Is there a way to render the field with a supplied value?

Thanks for the help.

**Comment by jtsternberg** [comment]
Can you provide some sample code for what you are doing?

**Comment by ingageco** [comment]
Justin - we're just rendering a field as so: 

$obj = cmb2_get_field($box, $field);
$obj->render_field();

This provides us with the HTML output of the field to display. Is there anywhere within this that we can specify a value for the field before showing it? Or is there a different approach that would accomplish showing the field with a supplied value?

**Comment by jtsternberg** [comment]
I suggest using the filters in place to set the value: https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Field.php#L226

**Comment by ingageco** [comment]
OK - and I should apply in between cmb2_get_field() and the render call?

**Comment by jtsternberg** [comment]
No, you would would want to apply your filter/callback before calling cmb2_get_field.

**Comment by ingageco** [comment]
Great - i'll work with it and ask another question if needed. Thanks Justin!
