### ISSUE TITLE
Insert/edit/delete an entry of a group id - frontend form

### ISSUE THREAD

**Issue by efoula** [WebDevStudios/CMB2#451]
Hello,

I am trying to create a comments system by using CMB2, as I have build a simple form in each single post that has a simple text area field ... let me explain what I have done yet

// in functions.php, I have added a new cmb group field to posts
// each entry in this group has 3 fields

> > Field 1: Recommendation (type: textarea_small)
> > Field 2: User ID (type: text)
> > Field 3: Aprroval (type: text)

After that I was trying to create a simple form that should insert a new entry in this group field that I have created with the 3 new fields, and for sure to add it to the group of the current post id, but I cannot figure it out, how to insert/edit/delete an entry of a specific cmb group from the frontend.

So, if it is a new comment, insert a new entry in the group field (ex. id = recommendation).

FYI, I use the same form to update any cmb field, for example:

```
<?php

    global $current_post;
    $recom_post_id = get_the_id();
    $postTitleError = '';

    if(isset($_POST['reco_submit']) && isset($_POST['recommend_nonce_field']) && wp_verify_nonce($_POST['recommend_nonce_field'], 'recommend_nonce')) {

        update_post_meta($recom_post_id, '_cmb_nationality_field', esc_attr(strip_tags($_POST['nationality_meta'])));

    }

?>

<form action="" method="POST" enctype="multipart/form-data">

    <div class="form-group">
        <input type="text" name="nationality_meta" id="nationality_meta" value="" />
    </div>

    <?php wp_nonce_field('recommend_nonce', 'recommend_nonce_field'); ?>
    <input type="hidden" name="reco_submit" id="reco_submit" value="true" />
    <button class="regist-btn" type="submit">Submit</button>

</form>
```

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
