### ISSUE TITLE
css and js files are not loading correctly - 403 forbidden

### ISSUE THREAD

**Issue by michaelkk** [WebDevStudios/CMB2#452]
Hi 
Im trying to include CMB2 in a plugin I'm developing 
Got everything working including few fields. 
For some reason the css and js files are not loading. it says: 
Failed to load resource: the server responded with a status of 403 (Forbidden)
Im assuming its an issue of file permissions right?
Im running it on localhost on Yosemite + Mamp
Please need help 
Thanks

**Comment by tnorthcutt** [comment]
@michaelkk that does indeed sound like an issue with file permissions, but unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
