### ISSUE TITLE
Set checked attribute to multicheck

### ISSUE THREAD

**Issue by khodorhammoud** [WebDevStudios/CMB2#455]
Is there a way to set a single check box to 'checked' by default in a cmb2 multi check form?
Thank you in advance

**Comment by jtsternberg** [comment]
Example in the wiki: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#setting-a-default-value-for-a-checkbox

**Comment by BeFiveINFO** [comment]
I also have the same question.

I have a suspicion that 'default' field for multicheck / multicheck_inline does not exist or is not taken into account even if the 'default' is set.
