### ISSUE TITLE
Encapsulate CMB2 In my own metabox

### ISSUE THREAD

**Issue by CarlosRios** [WebDevStudios/CMB2#459]
I'm writing a plugin that will utilize CMB2 to generate the fields because you guys do it best. I'm just wondering though, is there an easy way to embed CMB2 in a meta box that I've registered on my own in WP? I've looked at the docs and tried a few different things but I can't seem to get it. The reason I'm doing this is so that I can break it up into tabs as well as to have full control of what comes out in the tabs (Some will not contain metaboxes). Thanks for the help!

**Comment by jtsternberg** [comment]
Yep, you might look at these snippets: https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/misc/outputting-forms-outside-metaboxes.php

**Comment by CarlosRios** [comment]
@jtsternberg I should've closed this. I ended up figuring it out earlier this year :)
