### ISSUE TITLE
show_on filter for page template front-page.php doesn't work

### ISSUE THREAD

**Issue by benoitchantre** [WebDevStudios/CMB2#461]
Hello,

I would like to display a custom metabox for the the front page only (in the admin), but it doesn't work.
When I remove the line below, the metabox is show, but on all pages.
`'show_on'                 => array( 'key' => 'page-template', 'value' => 'front-page.php' ),`

Here's my code in function.php

```
add_action( 'cmb2_init', 'cmb_for_front_page' );
function cmb_for_front_page() {
    // Start with an underscore to hide fields from custom fields list
    $prefix = '_cmb_front_page_';
    $_cmb_front_page_ = new_cmb2_box( array(
        'id'                      => $prefix . 'metabox',
        'title'                   => __( 'Additional informations', 'quaero-team' ),
        'object_types'            => array( 'page' ), // Post type
        'show_on'                 => array( 'key' => 'page-template', 'value' => 'front-page.php' ),
        'context'                 => 'normal',
        'priority'                => 'high',
        'show_names'              => true // Show field names on the left
    ) );
    $_cmb_front_page_->add_field( array(
        'name'                    => 'test',
        'id'                      => $prefix . 'test',
        'type'                    => 'text',
    ));
}
```

Is it supposed to work like I tried?

Thanks for your help.

---

**Update:**
I try to make it work in a multilingual website that use Polylang,
The solution below works, but only for the page that was selected in the reading settings.
The custom metabox doesn't display in the translated page.
https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-front-page-show_on-filter

**Comment by tw2113** [comment]
I wager the original show_on issue is because for the "Settings > Reading > Front Page" field doesn't store metadata that gets checked for here.

**Comment by atrivisano** [comment]
Hey there, I know this is kind of grave digging but if someone comes across this looking for answers, I had the same problem `'show_on' => array( 'key' => 'page-template', 'value' => 'front-page.php' )`  wasn't showing then I decided to try `'show_on' => array( 'key' => 'page-template', 'value' => 'template_dir/front-page.php' )` and it worked.

Basically if you are organising your template files in a directory you have to specify the directory like above.

**Comment by tw2113** [comment]
Makes sense.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.

**Comment by LC43** [comment]
In case you're not using a template for the homepage, you can do like this:

```
$front_page_ID = get_option('page_on_front');
[...]

'show_on'	  => array( 'id' => array( $front_page_ID, ) ),
```

**Comment by hazelveek** [comment]
Thanks @LC43,
Just what I needed

**Comment by LC43** [comment]
glad you found it useful @hazelveek!
