### ISSUE TITLE
Prepare the library for upcoming termmeta changes

### ISSUE THREAD

**Issue by nielsvr** [WebDevStudios/CMB2#464]
I believe the library should be updated to support the upcoming changes in termmeta. The repository plugin is also affected.

https://make.wordpress.org/core/2015/09/22/preparing-your-plugins-and-your-client-sites-for-termmeta/

**Comment by jtsternberg** [comment]
There is nothing in CMB2 core which supports termmeta, so no changes are necessary. Once termmeta is officially in core, we can begin considering adding CMB2 core support.

**Comment by nielsvr** [comment]
Ah, my bad. Confused by the mention of CMB2 in that post.
