### ISSUE TITLE
Restrict Oembed (feature request?)

### ISSUE THREAD

**Issue by gareth-gillman** [WebDevStudios/CMB2#466]
Is it possible to restrict the Oembed to certain "services" e.g. youtube and vimeo?

I am using the metabox to add a "page header" and don't want them adding a polldaddy poll when it needs a video.

**Comment by jtsternberg** [comment]
hmm.. you could use the 'sanitization_cb' to strip the value if it's incorrect (and add a description stating that will happen).

**Comment by gareth-gillman** [comment]
thought so, just gonna do the check before I display the input on the frontend so not to make some annoying UX

thanks, for your input
