### ISSUE TITLE
Conditionally showing/hiding CMB2 meta boxes based on post's category

### ISSUE THREAD

**Issue by BenRacicot** [WebDevStudios/CMB2#471]
Is there currently a way to conditionally show/hide meta boxes based on which category is chosen? Perhaps with the show_on_cb args, but I'm personally not sure how to do that on the backend.

**Comment by tnorthcutt** [comment]
@BenRacicot not sure if this is up to date, but I think it should make for a good starting point: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-taxonomy-show_on-filter

If that works, please close this issue :smile:

**Comment by BenRacicot** [comment]
Hey @tnorthcutt thanks for helping out.

So I spent some serious time working through this code. I've added the recommended function to line 45 of CMB2_Show_filters.php directly under the public static get_show_on_key function. Then in my meta boxes:
````
add_action( 'cmb2_init', 'function_register_leadership_metas' );

function function_register_leadership_metas() {

	$prefix = '_function_leaders_';

	$cmb_leadership = new_cmb2_box( array(
		'id'            => $prefix . 'metabox',
		'title'         => __( 'Leader Information', 'cmb2' ),
		'object_types'  => array( 'leaders', ), // Post type
		**'show_on'		=> array( 'key' => 'taxonomy', 'value' => array( 'leaders_cat' => 'leader') ),**
		'context'    => 'normal',
		'priority'   => 'high',
		'show_names' => true,
	) );
		$cmb_leadership->add_field( array(
			'name' => __( 'Slider Thumbnail Image', 'cmb2' ),
			'desc' => __( 'These are small images that once clicked move the slider to this leader\'s slide.', 'cmb2' ),
			'id'   => $prefix . 'thumb_image',
			'type' => 'file',
		) );
		// slide number for query's orderby
		$cmb_leadership->add_field( array(
			'name' => __( 'Slide Order', 'cmb2' ),
			'desc' => __( 'Which slide number is this?', 'cmb2' ),
			'id'   => $prefix . 'slide_order',
			'type' => 'text_small',
		) );
}
````

**Comment by tnorthcutt** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.

**Comment by jtsternberg** [comment]
@BenRacicot please don't modify CMB2 core code as it could break for others. You should definitely be using the `'show_on_cb'` argument, and there is actually a really good example for how to do that in the example-functions.php file: https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L84 and https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L24-L37

The `'show_on_cb'` should simply return true or false (whether to show or not). You can do all your checks in that callback, and `$cmb->object_id` in that example is the post ID you will want to use to do your checks.

**Comment by BenRacicot** [comment]
So sorry I missed that example! 

The following worked perfectly to toggle metaboxes display based on if the current custom post was in a custom taxonomy:

function hide_if_not_leader( $cmb ) {
	if ( !has_term( 'leader', 'leaders_cat', $cmb->object_id ) ) {
		return false;
	}
	return true;
}

And using 'show_on_cb' to call it.
