### ISSUE TITLE
How to use sanitization_cb Parameter

### ISSUE THREAD

**Issue by jawittdesigns** [WebDevStudios/CMB2#478]
So I can't find any documentation on the sanitization_cb parameter. How do I get the value of the field to sanitize it?

    public function cust_sanitize() {
        $entry = stripslashes_deep( $the_value );
        return $entry;
    }

**Comment by arippberger** [comment]
@jawittdesigns did you find some documentation on this?

**Comment by widoz** [comment]
@arippberger you can simply add 'sanitization_cb' as argument, the following parameter will be passed to the callback : $meta_value, $this->args() ( the field arguments ) and $this ( the field object ), so you can get whatever you need.

**Comment by arippberger** [comment]
:tada: thank you
