### ISSUE TITLE
Show/Hide the field based on another field's value!

### ISSUE THREAD

**Issue by thirumani02** [WebDevStudios/CMB2#479]
Hello,
I am using a radio field & text field. I just want to hide the text field based on radio field values. 
This is my case 
<pre>$metabox_option->add_field( array(
	'name'	=> __('metabox radio name', 'text-domain' ),
	'id'	=> $prefix.'radio',
	'type'	=> 'radio_inline',
	'options' => array ( 
		'1' => __('1', 'text-domain' ), 
		'2' => __('2', 'text-domain' ), 
	),
	'default' => '2'
) );
$metabox_option->add_field( array( 
	'name'	=> __('metabox text name', 'text-domain' ), 
	'id'	=> $prefix.'text', 
	'type'	=> 'text_small',
) );</pre>
I want to show <code>metabox text name</code> only when<code>metabox radio name</code> is <code>1</code>. 

Thanks in advance!

**Comment by tnorthcutt** [comment]
Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
