### ISSUE TITLE
No Admin Notices When Saving Settings

### ISSUE THREAD

**Issue by jawittdesigns** [WebDevStudios/CMB2#482]
I'm using the [snippet for the setting pages](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php) to create settings for a plugin.

It's working great but the default "Settings Updated" admin notice isn't show when you save.

**Comment by DevinWalker** [comment]
I'm also seeing that +1

**Comment by jtsternberg** [comment]
That's because it's not built in. :) Happy to take a PR.

**Comment by DevinWalker** [comment]
PR on core or rather the snippet? https://github.com/WebDevStudios/CMB2-Snippet-Library/tree/master/options-and-settings-pages

**Comment by jtsternberg** [comment]
the snippet library
