### ISSUE TITLE
Turning off JS logging

### ISSUE THREAD

**Issue by gyrus** [WebDevStudios/CMB2#483]
Is there any way to completely turn off the JS console logging? I think it's causing some issues in IE9 (http://stackoverflow.com/questions/7742781/why-javascript-only-works-after-opening-developer-tools-in-ie-once). There are some hacks but I was wondering if there's a way to just turn the logging off (on staging and production).

**Comment by jtsternberg** [comment]
JS logging only occurs if you have the [SCRIPT_DEBUG constant](https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG) enabled.

**Comment by gyrus** [comment]
Of course! Thanks.
