### ISSUE TITLE
Media Library Documentation / Example

### ISSUE THREAD

**Issue by jerturowetz** [WebDevStudios/CMB2#489]
Hey there, long time listener first time caller.

Wondering if there's any danger to using <code>'object_types'  => array( 'attachment' )</code> and, if not, if you could direct me to any examples of usage.

I'm also terribly interested in learning how to get the boxes to show up in the grid view information window without hacking the crap out of cmb2.

<strong>'Traditional' view:</strong>
![screen1](https://cloud.githubusercontent.com/assets/3943852/10405829/b867610c-6ea9-11e5-961a-10545f6cf467.jpg)

<strong>'Gallery / Grid' view:</strong>
![screen2](https://cloud.githubusercontent.com/assets/3943852/10405830/b86fa2d6-6ea9-11e5-9404-5c7c715e0418.jpg)

**Comment by tnorthcutt** [comment]
@jerturowetz is this still a issue? If not, would you mind closing, or if it is, could you update with any new info available? Thanks!

**Comment by jerturowetz** [comment]
I'll take a look at the bug.  Could you provide an answer on the question of using `'object_types' => array( 'attachment' )` ?

**Comment by jtsternberg** [comment]
Yes, you can definitely use `'object_types' => array( 'attachment' )`, but as you've observed, there is no integration to the media modal (yet!). Those views are all driven by javascript and not something we can simply hook in and add.

**Comment by jerturowetz** [comment]
i guess this is more a feature request than a bug then.  Gotchya mah man - thanks for the reply!
