### ISSUE TITLE
$type class var is wrong on most filters and classes.

### ISSUE THREAD

**Issue by wpsmith** [WebDevStudios/CMB2#492]
`$type` is almost always 'post', which is obviously wrong much of the time, especially when accessing the variable in CMB_Field on `save_field` hook.

**Comment by jtsternberg** [comment]
@wpsmith `$type` is not really a thing, but I'm assuming you're referring to the `$object_type`, which is exactly that, the type of object for the current instance. `'post'` is 90% of what people use CMB for, but other object types include `'user'`, `'comment'`, `'options-page'`, and eventually `'term'`. If you're referring to the post type, that can be retrieved in most cases by calling `get_post_type` on the `$object_id`.
