### ISSUE TITLE
Help please, not really an issue...

### ISSUE THREAD

**Issue by dsgnr** [WebDevStudios/CMB2#493]
Hello, I am trying to create a new meta box which a user can enter their shortcode into. I have managed to get the shortcode to echo on the front end but I can't get the shortcode to be generated as a shortcode (the same as if a shortcode is entered into the 'HTML' side of the content editor.

Is anyone able to help me? Thanks

**Comment by jtsternberg** [comment]
Try the helper function here: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#wysiwyg

Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
