### ISSUE TITLE
File List Thumbnails Not Showing

### ISSUE THREAD

**Issue by 14850842** [WebDevStudios/CMB2#495]
Good Day,

I have an issue with the file_list thumbnails to displaying but rather just a list of file name. I have the preview set as size 50x50 but does not seem to display the thumbnails.

The thumbnails do however display when uploading/adding a new image to the file_list.

Thanks in advance

![screen shot 2015-10-15 at 5 43 41 pm](https://cloud.githubusercontent.com/assets/1675593/10519058/4f5ff268-7364-11e5-9590-5990a890cc88.png)

**Comment by 14850842** [comment]
?

**Comment by tw2113** [comment]
Hey @14850842 if this is still presenting an issue, can you start a thread at https://wordpress.org/support/plugin/cmb2 and we'll get it looked at. Please provide all relevant code with the thread, so that we can attempt to recreate on a local install.

Thanks

**Comment by webberwang** [comment]
The same issue is happening for file type.

**Comment by tw2113** [comment]
I'm curious if support for SVG as a whole for the WordPress install would take care of whatever conflicts you're encountering. I know CMB2 tries to use native functionality as much as possible. Have you made sure your install supports SVG as a whole already?

**Comment by webberwang** [comment]
Yeah I'm using an SVG plugin that helps with SVG rendering for thumbnails in the media section. But CMB2 is using it's own function to output the thumbnails, I took a quick peek at the source & it was missing the SVG file extension.

**Comment by tw2113** [comment]
@webberwang can you open a new enhancement issue for this request, so that we can get it tracked as a possible option. It's not directly related to the issue being commented on here.
