### ISSUE TITLE
Allowing html to be saved

### ISSUE THREAD

**Issue by BenRacicot** [WebDevStudios/CMB2#499]
Is there any way to allow saving html within a standard text_medium field? I'm trying to keep a <br/> from being stripped and cannot find any resources online about any success on the matter.

**Comment by JayWood** [comment]
@jtsternberg added a nifty call back parameter on a per-field basis, check out [sanitization_cb](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#user-content-sanitization_cb)

```php
$cmb->add_field( array(
    'name'       => __( 'Test Text', 'cmb' ),
    'id'         => 'wiki_test_text',
    'type'       => 'text',
   'sanitization_cb' => 'my_sanitization_func',
) );

// In another file somewhere
function my_sanitization_func( $original_value, $args, $cmb2_field ) {
    return $original_value; // Unsanitized value.
}
```

You can see it in action here: https://github.com/WebDevStudios/CMB2/blob/b3b78a569f63560d2f8a039c4c1ff412a28f0156/includes/CMB2_Field.php#L402

**Comment by BenRacicot** [comment]
@JayWood for the in! Thanks, couldn't find this anywhere.

**Comment by JayWood** [comment]
@BenRacicot don't feel bad, I didn't even know it existed until @jtsternberg told me a few weeks ago :smile:

**Comment by tnorthcutt** [comment]
I'm closing this issue as it's quite old and seems to be resolved. If it's not, feel free to re-open 😄

**Comment by pareshsojitra** [comment]
Its working fine, Thanks.
