### ISSUE TITLE
WYSIWYG autop issues

### ISSUE THREAD

**Issue by JiveDig** [WebDevStudios/CMB2#50]
I'm getting some strange inconsistencies. I have a large metabox that uses a few wysiwyg editors. 
One example is:
			array(
				'name'    => __( 'Description', 'rich-recipes' ),
				'id'      => $prefix . 'description',
				'type'    => 'wysiwyg',
				'options' => array(
					'media_buttons' => false,
					'textarea_name' => $slug . 'description',
					'textarea_rows' => 12,
					'teeny'         => false,
					'tinymce'       => array(
						'toolbar1'  => 'bold,italic,underline,link,unlink,',
					),
					'quicktags'     => false,
				),
				'before_row' => '<div style="clear:both;"></div>',
			),

In the 'options' array i've tried to set 'wpautop' => false as shown the opposite here: https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/wiki/Field-Types#wysiwyg

Here's the strangeness: No matter what I do, the first people never uses wpautop and ALL the other wysiwyg fields DO use it. No matter what I do with the setting or if I remove it altogether.

Any ideas? I've been digging, but no luck.

**Comment by JayWood** [comment]
Hey @JiveDig I'm unable to replicate this issue on my local machine with two WYSIWYG fields.  Granted, I do not have a tabulated setup like you do.  Can you confirm this still exists?

**Comment by JiveDig** [comment]
A lot has changed since then. I don't think I can confirm it's still an issue. It may have been a thing with 4.0 or whenever the editor/scroll stuff was added to core.  You can probably close this for now, or until someone else can confirm it's actually happening. I think i'm all set.
