### ISSUE TITLE
cmb2_get_metabox() returns boolean(false)

### ISSUE THREAD

**Issue by VdeVatman** [WebDevStudios/CMB2#502]
Hi there, I've followed this tutorial: https://webdevstudios.com/2015/03/30/use-cmb2-to-create-a-new-post-submission-form/ by copying exactly its snippets and when I run it it outputs: 

`Metabox configuration is required to have an ID parameter`

Debugging it I could see that the variable $cmb in:

```
    // Get CMB2 metabox object
    $cmb = cmb2_get_metabox( $metabox_id, $object_id );
```

Is set to false. Following these steps: https://github.com/WebDevStudios/CMB2/wiki/Bringing-Metaboxes-to-the-Front-end I reach the exact same result.

Would you know why that happens and how to fix it?

**Comment by jtsternberg** [comment]
The wiki example (https://github.com/WebDevStudios/CMB2/wiki/Bringing-Metaboxes-to-the-Front-end) requires you to use a shortcode and pass it a metabox ID, like `[cmb-form id="test_metabox"]. The example does NOT explain how to register that `'test_metabox'` [metabox and and its fields](https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage#create-a-metabox).

**Comment by VdeVatman** [comment]
@jtsternberg The metabox exists and is shown within /wp-admin

**Comment by tnorthcutt** [comment]
@VdeVatman is this still a issue? If not, would you mind closing, or if it is, could you update with any new info available? Thanks!

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
