### ISSUE TITLE
WordPress term meta API support 

### ISSUE THREAD

**Issue by adilelsaeed** [WebDevStudios/CMB2#505]
Is there any plan to support adding terms metaboxes using the new WordPress term meta API as it will be introduced in WordPress 4.4?
https://make.wordpress.org/core/2015/10/23/4-4-taxonomy-roundup/

**Comment by jtsternberg** [comment]
Yes, absolutely.

**Comment by adilelsaeed** [comment]
Thanks
That's really fast ^^

**Comment by christiespeich** [comment]
Was just coming to see if this was going to be added in the future, and it already is! Awesome. Thanks guys!

**Comment by sb-lc** [comment]
sorry if its a silly question but is this in a released version or just the dev trunk?
