### ISSUE TITLE
Input types doesn't allow custom class values

### ISSUE THREAD

**Issue by widoz** [WebDevStudios/CMB2#509]
Hi,

No way to add custom classes during box creation.
I see there are some extra input wrappers like **text_small**, **text_medium** etc... but no way to pass the classes to the **fields** keys during new_cmb2_box call.

Here an example

```php
$cmb = new_cmb2_box( [
			'id'         => $this->_metabox_id,
			'hookup'     => false,
			'cmb_styles' => true,
			'show_on'    => [
				'key'   => 'options-page',
				'value' => [ $this->_key, ],
			],
			'fields'     => [
				[
					'name'    => esc_html__( 'Copyright Text', 'gs' ),
					'desc'    => esc_html__( 'Add the copyright text of the site', 'gs' ),
					'default' => '',
					'id'      => 'gs_copyright_text',
					'type'    => 'text',
					'class'   => 'regular-text widefat' // Doesn't work
				],
			],
		] );
```

No method on CMB2_Types to get the classes of a input. There is another way or can be implemented?

**Comment by jtsternberg** [comment]
First, you should be using the `CMB2:add_field` method to add your fields: https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L112-L118

Second, you can override the default input classes via the attributes parameter: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#user-content-attributes

**Comment by widoz** [comment]
Hi,

Thanks for the respond. The user content attributes doesn't suggest a use of the "class" directly to the input. 

What about the **fields** arg on new_cmb2_box call? It's work and use **add_fields** method.

**Comment by jtsternberg** [comment]
'fields' arg on new_cmb2_box is deprecated. and the 'attributes' field property is for directly adding/modifying the input attributes.

**Comment by widoz** [comment]
Thank you so much.
