### ISSUE TITLE
Is there a way to add the 3rd Party Resources to the core cmb2?

### ISSUE THREAD

**Issue by Sultenhest** [WebDevStudios/CMB2#511]
I'm using CMB2 as a part of theme development and not as a plugin. Is there a way to add any of the 3rd Party Resources, say the cmb2-field-slider, permanently to the CMB2 folder instead of having to install it as a plugin?

**Comment by tw2113** [comment]
Should be able to drop their files in a folder in the theme and manually load their files as necessary, very much like how CMB2 does it itself as a library vs as a plugin found on WordPress.org
