### ISSUE TITLE
Conditional statement using checkbox from options page (fatal error)

### ISSUE THREAD

**Issue by dwruck** [WebDevStudios/CMB2#514]
I am trying to create a theme options page with checkboxes that, if checked, will enable various but related custom post types. 

No matter what I do I keep getting this error: Fatal error: Call to undefined function cmb2_get_option()..... on line 189. 

I have worked on this all day long and have even purchased and watched most of Justin's CMB2 session from WP Sessions. I would like to simply wrap this line in a conditional statement from a checkbox: 
```php
require_once( $this->directory_path . '/post-types/staff.php' );
```
I followed the settings from this page (changed out the myprefix obviously): https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php. 

Here is my code from line 189: 
```php
function compel_get_option( $key = '' ) {
	return cmb2_get_option( compel_admin()->key, $key );
}
```

This is the checkbox field I was trying to add: 
```php
	$cmb->add_field( array(
		'name' => __( 'Staff' ),
		'desc' => __( 'Select to include staff features' ),
		'id'   => 'compel_checkbox',
		'type' => 'checkbox',
	) );
```
Any help with this error would be greatly appreciated.

**Comment by widoz** [comment]
Fatal error: Call to undefined function cmb2_get_option()..... on line 189.
Probably you haven't hook your code within 'init'. The cmb2_get_option is available during the **init** action.

**Comment by dwruck** [comment]
I was trying to keep that in mind and I tried to follow this instructions here: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#using-cmb2-helper-functions-and-cmb2_init but somehow I was not able to put it all together right.

**Comment by widoz** [comment]
Uhm, honestly I don't know, I should view how your code is.

**Comment by jtsternberg** [comment]
Try updating your compel_get_option function to something like this:

```php
function compel_get_option( $field_id = '', $default = false ) {
	if ( function_exists( 'cmb2_get_option' ) ) {
		$value = cmb2_get_option( compel_admin()->key, $field_id, $default );
	} else {

		$opts = get_option( compel_admin()->key );
		$value = $default;

		if ( 'all' == $field_id ) {
			$value = $opts;
		} elseif ( array_key_exists( $field_id, $opts ) ) {
			$value = false !== $opts[ $field_id ] ? $opts[ $field_id ] : $default;
		}
	}

	return $value;
}
```

**Comment by dwruck** [comment]
Thank you so much!!! I feel like I almost have this working but I cannot seem to get the code right to call the required file. I am trying to learn as fast as I can, but I am way behind where I need to be and I am afraid I am in over my head. Can you tell what is wrong with my code?

<pre>
function cmb2_init_check_field_value() {
define('COMPEL_PLUGIN_PATH', plugin_dir_path(__FILE__)); 
$checked_value = compel_get_option( 'compel_checkbox', true );
	if( checked( $checked_value, 1, false ) ) {
		require_once COMPEL_PLUGIN_PATH . 'post-types/staff.php';
	}
}
add_action( 'cmb2_init', 'cmb2_init_check_field_value' );	
</pre>

**Comment by jtsternberg** [comment]
What happens if you remove your `if( checked(` condition? does the file load?

**Comment by dwruck** [comment]
Good thought....I tried removing the If checked function and the file did not load.
<pre>
function cmb2_init_check_field_value() {
define('COMPEL_PLUGIN_PATH', plugin_dir_path(__FILE__)); 
//This is important, otherwise we'll get the path of a subdirectory
// Include any required files
$checked_value = compel_get_option( 'compel_checkbox', true );
		require_once COMPEL_PLUGIN_PATH . 'post-types/staff.php';
}
add_action( 'cmb2_init', 'cmb2_init_check_field_value' );
</pre>
However when outside the function completely, the file did load.
<pre>
define('COMPEL_PLUGIN_PATH', plugin_dir_path(__FILE__)); 
require_once COMPEL_PLUGIN_PATH . 'post-types/staff.php';
</pre>

**Comment by dwruck** [comment]
The code I have is almost working now. I was able to put an echo inside the if checked function and it works perfectly. The problem now is getting any kind of include/require function to work inside of this function.
<pre>
function cmb2_init_check_field_value() {
$checked_value = compel_get_option( 'compel_checkbox', true );
	if ( 0 == $checked_value ) {
	require_once plugin_dir_path( __FILE__ ) . '/post-types/staff.php';
	}
}
add_action( 'cmb2_init', 'cmb2_init_check_field_value' );
</pre>

This code below works perfectly outside of the function, but inside it will not work. Could it be how or when the cmb2_init is loaded?
<pre>require_once plugin_dir_path( __FILE__ ) . '/post-types/staff.php';</pre>

**Comment by jtsternberg** [comment]
If you do:
```php
print_r( file_exists( COMPEL_PLUGIN_PATH . 'post-types/staff.php' ) );
```
And you get a truthy value in both scenarios (in and out of the function), then it's likely a load order issue. What is in that file?

**Comment by dwruck** [comment]
This is the whole file:

<pre>

   Plugin Name: Compel Church Content
   Description: A plugin to manage church content in WordPress
   Version: 1.1
   Author: Doug Wruck
   Author URI: http://dougwruck.com
   License: GPL2
   */


// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
if ( ! class_exists( 'Compel_Plugin' ) ) {
	class Compel_Plugin {
		/**
		 * Construct function to get things started.
		 */
		 	
		public function __construct() {
			// Setup some base variables for the plugin
			$this->basename       = plugin_basename( __FILE__ );
			$this->directory_path = plugin_dir_path( __FILE__ );
			$this->directory_url  = plugins_url( dirname( $this->basename ) );
			// Include any required files
			require_once( $this->directory_path . '/admin/admin.php' );
			require_once( $this->directory_path . '/assets/shortcodes.php' );
			require_once( $this->directory_path . '/includes/taxonomies.php' );
			
			// include CMB2 if it doesn't already exist
			if ( ! defined( 'CMB2_LOADED' ) ) {
				require_once( $this->directory_path . '/includes/cmb2/init.php' );
			}
			// Make sure we have our requirements, and disable the plugin if we do not have them.
			add_action( 'admin_notices', array( $this, 'maybe_disable_plugin' ) );
			
		}
		/**
		 * Check that all plugin requirements are met
		 *
		 * @return boolean
		 */
		public static function meets_requirements() {
			// Make sure we have CMB so we can use it
			if ( ! defined( 'CMB2_LOADED' ) ) {
				return false;
			}
			// We have met all requirements
			return true;
		}
		/**
		 * Check if the plugin meets requirements and
		 * disable it if they are not present.
		 */
		public function maybe_disable_plugin() {
			if ( ! $this->meets_requirements() ) {
				// Display our error
				echo '<div id="message" class="error">';
				echo '<p>' . sprintf( esc_html__( 'Compel Plugin requires CMB2 but could not find it. The plugin has been <a href="%s">deactivated</a>. Please make sure all requirements are available.', 'compel_plugin' ), admin_url( 'plugins.php' ) ) . '</p>';
				echo '</div>';
				// Deactivate our plugin
				deactivate_plugins( $this->basename );
			}
		}
	}
	$_GLOBALS['Compel_Plugin'] = new Compel_Plugin;
}
/**
 * Public wrapper function
 */
function compel_plugin() {
	return new Compel_Plugin;
}


function cmb2_init_check_field_value() {
$checked_value = compel_get_option( 'compel_checkbox', true );
	if ( 0 == $checked_value ) {
	require_once plugin_dir_path( __FILE__ ) . '/post-types/staff.php';
	}
}
add_action( 'cmb2_admin_init', 'cmb2_init_check_field_value' );
</pre>

**Comment by jtsternberg** [comment]
I meant, what is in post-types/staff.php? And did you do the test?

**Comment by dwruck** [comment]
Oh, sorry :)  I did do the test and it output the value of "1", inside and outside the function. 

The staff.php file just creates a custom post type. Code below 

<pre>
 
// No direct access
if ( ! defined( 'ABSPATH' ) ) exit;

/**********************************
 * STAFF
 **********************************/

function compel_register_post_type_staff() {

  $labels = array(  
    'name'					=> _x( 'Staff', 'post type general name', 'compel-content' ),
	'singular_name'			=> _x( 'Staff', 'post type singular name', 'compel-content' ),
	'add_new' 				=> _x( 'Add New', 'staff', 'compel-content' ),
	'add_new_item' 			=> __( 'Add Staff Member', 'compel-content' ),
	'edit_item' 			=> __( 'Edit Staff Member', 'compel-content' ),
	'new_item' 				=> __( 'New Staff Member', 'compel-content' ),
	'all_items' 			=> __( 'All Staff Members', 'compel-content' ),
	'view_item' 			=> __( 'View Staff Member', 'compel-content' ),
	'search_items' 			=> __( 'Search Staff Members', 'compel-content' ),
	'not_found' 			=> __( 'No staff members found', 'compel-content' ),
	'not_found_in_trash' 	=> __( 'No staff members found in Trash', 'compel-content' )
   );  
  
 $args = array(  
    'labels' => $labels,  
    'public' => true,  
    'publicly_queryable' => true,  
    'show_ui' => true,  
    'show_in_menu' => true,  
	'show_in_nav_menus'   => true,
    'query_var' => true,  
    'capability_type' => 'post',  
	'menu_position'       => 5,
    'has_archive' => true,  
    'hierarchical' => false,  
	'menu_icon'		=> 'dashicons-admin-users',
    'supports' => array('title', 'page-attributes' )  
  );  
  // The following is the main step where we register the post.  
  register_post_type('compel_staff',$args);  
}

add_action( 'init', 'compel_register_post_type_staff' ); // register post type 

add_filter('post_updated_messages', 'compel_staff_updated_messages');  
  
function compel_staff_updated_messages( $messages ) {  
  global $post, $post_ID;  
  
  $messages['compel_staff'] = array(  
    0 => '', // Unused. Messages start at index 1.  
    1 => sprintf( __('Staff updated. <a href="%s">View staff</a>'), esc_url( get_permalink($post_ID) ) ),  
    2 => __('Custom field updated.'),  
    3 => __('Custom field deleted.'),  
    4 => __('Staff updated.'),  
    /* translators: %s: date and time of the revision */  
    5 => isset($_GET['revision']) ? sprintf( __('Staff restored to revision from %s'), wp_post_revision_title( (int) $_GET['revision'], false ) ) : false,  
    6 => sprintf( __('Staff published. <a href="%s">View Staff</a>'), esc_url( get_permalink($post_ID) ) ),  
    7 => __('Staff saved.'),  
    8 => sprintf( __('Staff submitted. <a target="_blank" href="%s">Preview staff</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),  
    9 => sprintf( __('Staff scheduled for: <strong>%1$s</strong>. <a target="_blank" href="%2$s">Preview Staff</a>'),  
      // translators: Publish box date format, see http://php.net/date  
      date_i18n( __( 'M j, Y @ G:i' ), strtotime( $post->post_date ) ), esc_url( get_permalink($post_ID) ) ),  
    10 => sprintf( __('Staff draft updated. <a target="_blank" href="%s">Preview Staff</a>'), esc_url( add_query_arg( 'preview', 'true', get_permalink($post_ID) ) ) ),  
  );  
  
  return $messages;  
}  


function change_compel_staff_title( $title ){
     $screen = get_current_screen();
 
     if  ( 'compel_staff' == $screen->post_type ) {
          $title = 'Staff Name';
     }
 
     return $title;
}
 
add_filter( 'enter_title_here', 'change_compel_staff_title' );




if ( function_exists( 'add_image_size' ) ) { 
	add_image_size( 'staff_pic', 450, 235, true ); //(cropped)
}

 
 

add_action( 'cmb2_init', 'cmb2_compel_staff_metaboxes' );
/**
 * Define the metabox and field configurations.
 */
function cmb2_compel_staff_metaboxes() {

    // Start with an underscore to hide fields from custom fields list
    $prefix = '_compel_staff_';

    /**
     * Initiate the metabox
     */
    $cmb = new_cmb2_box( array(
        'id'            => 'staff_information',
        'title'         => __( 'Staff Information', 'cmb2' ),
        'object_types'  => array( 'compel_staff', ), // Post type
        'context'       => 'normal',
        'priority'      => 'high',
        'show_names'    => true, // Show field names on the left
        // 'cmb_styles' => false, // false to disable the CMB stylesheet
        // 'closed'     => true, // Keep the metabox closed by default
    ) );

			$cmb->add_field( array(
				'name' => 'Staff Description',
				'desc' => 'This is a small description of each staff member. Should be between 20-30 words.',
				'id'   => $prefix . 'bioexcerpt',
				'type' => 'wysiwyg',
				'options' => array(	'textarea_rows' => 5, ),
   			) );
			
			$cmb->add_field( array(
				'name' => 'Full Staff Bio',
				'desc' => 'This is for lengthy bios that will require a read more button. Any text entered in the box will produce a read more button.',
				'id'   => $prefix . 'bio',
				'type' => 'wysiwyg',
				'options' => array(	'textarea_rows' => 10, ),
   			) );
		
			$cmb->add_field( array(
				'name' => 'Church Staff Title',
				'desc' => 'Please enter the title or position of the staff member. This will be used on the school pages.',
				'id'   => $prefix . 'position',
				'type' => 'text_medium',
    		) );
			
			$cmb->add_field( array(
				'name' => 'Alternative Ministry Title',
				'desc' => 'Please enter the title or position of the staff member. This will be used on the school pages.',
				'id'   => $prefix . 'alt_position',
				'type' => 'text_medium',
    		) );

			$cmb->add_field( array(
				'name' => 'Calendar Link',
				'desc' => 'This is the url for speaking engagement calendar. Include full link including "http://"',
				'id'   => $prefix . 'calendar_link',
				'type' => 'text_medium',
    		) );
			
			$cmb->add_field( array(
				'name' => __( 'Staff Picture' ),
				'desc' => __( 'Upload an image or enter a URL.' ),
				'id'   => $prefix . 'staff_image',
				'type' => 'file',
				'save_id' => true,
			) );
			
			$cmb->add_field( array(
				'name' => __( 'Family Picture' ),
				'desc' => __( 'Upload an image or enter a URL.' ),
				'id'   => $prefix . 'family_image',
				'type' => 'file',
				'save_id' => true,
			) );
			
			$cmb->add_field( array(
				'name' => 'Staff Email',
				'desc' => 'This is an optional email link for each staff member.',
				'id'   => $prefix . 'email',
				'type' => 'text_medium',
    		) );

			$cmb->add_field( array(
				'name' => 'Staff Twitter',
				'desc' => 'This is an optional Twitter link for each staff member. Include full link including "http://"',
				'id'   => $prefix . 'twitter',
				'type' => 'text_medium',
    		) );
			
			$cmb->add_field( array(
				'name' => 'Staff Facebook',
				'desc' => 'This is an optional Facebook link for each staff member. Include full link including "http://"',
				'id'   => $prefix . 'facebook',
				'type' => 'text_medium',
    		) );
			
			$cmb->add_field( array(
				'name' => 'Staff LinkedIn',
				'desc' => 'This is an optional LinkedIn link for each staff member. Include full link including "http://"',
				'id'   => $prefix . 'linkedin',
				'type' => 'text_medium',
    		) );

}
</pre>

**Comment by jtsternberg** [comment]
Yah, lots of issues with your code. For one, you can't hook into init from inside a function that hooks to cmb2_admin_init. Just do the conditional loading stuff outside the function and you should be fine. Also, don't do `if( checked(`. Just do `if ( $checked_value ) {`.

**Comment by dwruck** [comment]
That worked. Thanks!
