### ISSUE TITLE
Add Link Field to Existing Content

### ISSUE THREAD

**Issue by wesleycole** [WebDevStudios/CMB2#515]
I often use CMB2 to build out elements of custom templates. This allows the content editor to change any content they want, without breaking the design of the page. 

I find myself often adding two fields to allow editors to be able to change the text and URLs for buttons on a page. One of the issues that I run into with this, is that the editor needs to know the URL for the button link. This is fine for when they are linking to external sites, but I think it could be a really good enhancement to allow editors to search and select existing content to link to. The idea for this came from WP's own link tool in the editor. See image below:

![screenshot 2015-11-05 12 44 59](https://cloud.githubusercontent.com/assets/1162694/10976672/1177c2a2-83bb-11e5-82cd-5a1920d08999.png)

I could see this being an extension of `text_url` as an option. Similar to how the `file` field type has the options of removing the URL input and having a button to select a file from the media library, we could do the same with `text_url`. They could either input a URL or select a button that would pull up a search form and list of all existing content on the site. 

I would think that this field would only output the URL just like `text_url`.

Just a thought, I'm sure this would be a huge endeavor.

**Comment by JayWood** [comment]
You should check out [CMB2 Post Search Field](https://github.com/WebDevStudios/CMB2-Post-Search-field)  If i'm not mistaken it stores the selected post ID, and you can handle that accordingly on the front-end or where ever you're getting the meta.

You can also do tons more, I'm sure there's filters in there somewhere.

**Comment by wesleycole** [comment]
Very nice! No idea that that existed. I will definitely give it a shot to see if it covers what I need. Looks like it will. 

Thanks!
