### ISSUE TITLE
text_money appending before instead of overwriting

### ISSUE THREAD

**Issue by SilverKenn** [WebDevStudios/CMB2#516]
Thanks for this great plugin, 

I'm not sure if the docs is not yet updated, but using ```before``` on text money field will just add another currency,

thus using something like this  
```php
$costpermon->add_field( array(
		'name'		=> __( 'Cost per Month', 'ehem' ),
		'id'		=> $p . 'costper_month',
		'type'		=> 'text_money',
		'before'	=> '€',
));
```
will result to this
![1](http://i.imgur.com/2TV09WY.png)

checking on the source code, I can see this line,
```php
public function text_money() {
	return ( ! $this->field->get_param_callback_result( 'before_field' ) ? '$ ' : ' ' ) . $this->input( array( 'class' => 'cmb2-text-money', 'desc' => $this->_desc() ) );
}
```

So the parameter supposed to be ```before_field``` and not ```before```

Hope the docs will be updated to avoid confusion.

Cheers

**Comment by jtsternberg** [comment]
Where do you see the docs being incorrect? It's correct [here](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#text_money) and [here](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L188).

**Comment by tnorthcutt** [comment]
I'm closing this issue as it's quite old with no response from the original reporter. If this is still a concern, please feel free to re-open with more details or new information as relevant. Thanks!
