### ISSUE TITLE
Tag a (beta) release

### ISSUE THREAD

**Issue by mAAdhaTTah** [WebDevStudios/CMB2#52]
I'd like to include CMB2 via Packagist, but there isn't a version number to lock into, and I'd rather not include the branch under development. Would you mind tagging a beta release? Or is it close to coming out of beta?

**Comment by mAAdhaTTah** [comment]
@jtsternberg Bump, saw you just pushed to .org. If you tag the commit on git as well, I can pull from that tag from Packagist.

**Comment by jtsternberg** [comment]
Tagged. https://github.com/WebDevStudios/CMB2/releases/tag/v2.0.0.8

**Comment by mAAdhaTTah** [comment]
Woot! Thanks.
