### ISSUE TITLE
Show metaboxes on pages only.

### ISSUE THREAD

**Issue by fysalyaqoob** [WebDevStudios/CMB2#522]
Is there any way to hide default page metaboxes on page templates. I mean, custom fields used for page.php not hide everywhere except page.php.

Thank you!

**Comment by jtsternberg** [comment]
You should register a callback for 'show_on_cb' and perform your logic there. https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#how-does-it-work
