### ISSUE TITLE
Datepicker always wrapped in cmb2-element div

### ISSUE THREAD

**Issue by johnjamesjacoby** [WebDevStudios/CMB2#527]
The WP Event Calendar plugin uses the same jQuery UI Datepicker library as CMB2. It looks like CMB2 doesn't just wrap itself, but all datepickers, resulting in broken styling when both are active.

The following code in `cmb2.js` is the culprit:
```
		// Wrap date picker in class to narrow the scope of jQuery UI CSS and prevent conflicts
		$id( 'ui-datepicker-div' ).wrap('<div class="cmb2-element" />');
```

I'm unsure if there's a way to namespace your own datepickers, but that would circumvent the issue and prevent the conflict this code was designed to prevent (but doesn't really.)

**Comment by jtsternberg** [comment]
@johnjamesjacoby Can you test this branch to see if the conflict is resolved? https://github.com/WebDevStudios/CMB2/tree/bug/narrow-datepicker-styles

**Comment by jtsternberg** [comment]
Just did some testing with a vanilla datepicker instantiation, and the aforementioned branch solves the issue.
