### ISSUE TITLE
.gitattributes file for excluding development resources

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/CMB2#53]
https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/

**Comment by benoitchantre** [comment]
@jtsternberg I can make a PR for that. My opinion is that we should exclude what is not part of the folder you get with a plugin installation from wordpress.org. Do you agree with that?

**Comment by jtsternberg** [comment]
@benoitchantre the simplest way to determine what to ignore would be to compare against what we distribute in the wordpress.org package (svn:ignore): https://plugins.trac.wordpress.org/browser/cmb2/trunk

**Comment by benoitchantre** [comment]
@jtsternberg Thanks for the link!
