### ISSUE TITLE
Conflict with Yoast 3.0

### ISSUE THREAD

**Issue by johndnixon** [WebDevStudios/CMB2#530]
After updating to the newest version of Yoast SEO the file upload button no longer works.

**Comment by ClicGraham** [comment]
It's also conflicting with repeatable fields. :-(

**Comment by jtsternberg** [comment]
Justin downloaded/activated 3.0.4 and seems to be working fine. Do you have the most recent version of Yoast?

**Comment by ClicGraham** [comment]
I've gone back to previous version of Yoast for now to give this some time to settle, then I'll do some tests and check all is fine.

**Comment by jtsternberg** [comment]
Yoast 3.0.4 update is specifically to address this issue: https://wordpress.org/plugins/wordpress-seo/changelog/

**Comment by johndnixon** [comment]
Downloaded 3.0.4 and all works.

**Comment by djapra** [comment]
im using yoast 3.6 and cmb 2.2.2.1 it adds whitespace to my  xml file when i init a cmb2 metabox, any idea  how to fix this?

**Comment by baljindersingh88** [comment]
Can you please share your code

**Comment by djapra** [comment]
My bad guys, i accidentally have whitespace on my function file :)

**Comment by baljindersingh88** [comment]
Thanks for saving my time :)
