### ISSUE TITLE
Conditional meta field showing on new posts regardless.

### ISSUE THREAD

**Issue by cggit** [WebDevStudios/CMB2#531]
I am using this show_on script from this docs https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-show-metabox-by-post-meta

I have a dropdown list of statuses internal/external and only want a contact meta fields to show if the status is set to external. The default is internal.

The problem is when you create a new custom post the contact field shows and only when you save a draft of publish does the conditional rules take effect. I would like to contact field to be hidden by default since that is what the conditional rule states.

**Comment by cggit** [comment]
The issue is

    if ( isset( $_GET['post'] ) ) {
        $post_id = $_GET['post'];
    } elseif ( isset( $_POST['post_ID'] ) ) {
        $post_id = $_POST['post_ID'];
    }

     if ( ! $post_id ) {
         return $display;
     }

as new posts do not have a post_id yet.

**Comment by cggit** [comment]
There is also a typo in the docs. They suggest using 'meta'

    $meta_boxes['show_on'] = array( 'meta' => [enter-meta-key], 'meta_value' => [enter-meta-value], );

but the function references 'meta_key'

    $meta_box['show_on']['meta_key']

could be confusing for some.

**Comment by jtsternberg** [comment]
As recommended by the [docs on the wiki page](https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#how-does-it-work), I would use the `'show_on_cb'` callback parameter instead as it is a bit more intuitive and you can do any kind of checks you need to there. Just return true or false to display the metabox.

**Comment by jtsternberg** [comment]
I've added an example to the wiki which should be what you need (or close): https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-using-the-show_on_cb-to-limit-the-display-of-a-metabox-unless-metadata-exists

**Comment by cggit** [comment]
ah this helps thanks! I saw 'show_on_cb' but wasn't sure of the best way to reference the other fields.

**Comment by tnorthcutt** [comment]
Closing this as it seems to be resolved; @cggit if it's not feel free to reopen.

**Comment by apeximum** [comment]
@cggit can you tell me the way you did it...bcoz i have the same problem...thank you in advance
