### ISSUE TITLE
How to use taxonomy_select?

### ISSUE THREAD

**Issue by ruturaaj** [WebDevStudios/CMB2#534]
Hello,

I'm facing a strange problem... I'm not able to use "taxonomy_select" in my metabox. I see the value is getting saved well because when I return back to the page in edit mode, I see my previously saved value retained by metabox field. But when I try to use the same value using "get_post_meta", the value is always empty. 

Can someone please show me the code line that calls the value of taxonomy_select in theme files?

Cheers,

Ruturaaj.

**Comment by ruturaaj** [comment]
Here is the code for my Metabox Field:

$news_mb->add_field(array(
            'type' => 'taxonomy_select',
            'id' => $prefix . 'news-group',
            'name' => 'News Category',
            'taxonomy' => 'category',
        ));

The $prefix is "_home_".

Here is the code I'm trying in my theme's page.php ...

<?php echo get_post_meta(get_the_ID(), '_home_news-group', true); ?>

Nothing is printed.

**Comment by ruturaaj** [comment]
Which is the best place to get help for CMB2? Is this forum accessed by authors regularly? Not sure where to post my queries...

**Comment by christiespeich** [comment]
It's not immediately clear in the wiki because the Note is only posted after one of the taxonomy field types, not all of them (so if you don't scroll down, you won't see it), but here's why it's not working the way you're expecting it to:


>To retrieve the values from the taxonomy fields, use get_the_terms, not get_post_meta, etc. The
>taxonomy fields are not intended to provide an arbitrary list of terms to pick from, but are intended 
>to be a replacement for the default taxonomy meta-boxes. I.e. they are meant to set the taxonomy 
>terms on an object, and will not save as a meta value. Any other use of these types will be hacky
>and/or buggy. Suggest looking at building a custom field type instead - [Example](https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post).

**Comment by tw2113** [comment]
The best place for initial support inquiries is at https://wordpress.org/support/plugin/cmb2.

Regarding the taxonomy_* fields, they're meant to be used in place of the default category/tag/taxonomy metaboxes that WordPress generates. They don't save to post meta, they instead associate the terms to the post.
