### ISSUE TITLE
oembed bug when used on the options-page

### ISSUE THREAD

**Issue by jmarceli** [WebDevStudios/CMB2#542]
Oembed field doesn't display preview image when it is used to create `options-page` (even after saving). Is there any workaround for that, or this is unknown bug?

**Comment by jtsternberg** [comment]
It's working for me. ![Demo](http://b.ustin.co/Fah7+)

**Comment by jmarceli** [comment]
Is it `trunk` branch? Mine doesn't work so nice.
Please check also if it works after initial save. I get this bug when I change existing oEmbed video.

**Comment by jtsternberg** [comment]
You're right, it does not work after saving. We'll need to look into this.

**Comment by jmarceli** [comment]
I've done it already :)
Here is my workaround (it's just  workaround I don't know why it works, but it does) https://github.com/jmarceli/CMB2/commit/acf4559d2b76a91226e556d71ecb85bfba13ee31

It's fine but doesn't display preview after pasting URL (with Ajax) only after saving. The Ajax call (probably) doesn't hit the correct CMB2 method.

**Comment by satwinderrathore** [comment]
Thanks @jmarceli , 

It's worked for me,

**Comment by devanonyme** [comment]
I have encountered a similar problem, not worth opening an new bugs so I will comment here.

I am evaluating CMB2 as a form solution to be used outside of the dashboard and support a post / edit worflow.

I have assigned a default value while calling add_group_fieldand then object is not instanciated completely.

        $cmb->add_group_field( $group_field_oembed,  array(
            'name' => 'Lien externe',
            'desc' => 'Enter a youtube, twitter, or instagram URL. Supports services listed at <a href="http://codex.wordpress.org/Embeds">http://codex.wordpress.org/Embeds</a>.',
            'id'   => 'wiki_test_embed',
            'type' => 'oembed',
            'default' => 'https://www.youtube.com/watch?v=Z4QNlurDaNc'
        ) );

As a temporary workaround, I have patched init with something like this:

                    var oEmbedList = $('.cmb2-oembed');
                    oEmbedList.each(function(index) {
                        cmb.doAjax($( this ));
                    });

And then commented out this code (assume that the object is in focus (true when updating after a url paste, but not in this case), I guess there could be a extra parameter to differentiate the use case.

                    /*
                        if ( $( '.cmb2-oembed:focus' ).val() !== oembed_url ) {
				return;
			}
                    */

My first question would surely be, is it a intended behavior?
