### ISSUE TITLE
CMB2_Utils()->url does not work when wp-content is not in the wp root

### ISSUE THREAD

**Issue by echo1consulting** [WebDevStudios/CMB2#544]
CMB2_Utils()->url() does not work when wp-content is not in the wp root. A better solution for this function would be to use the functions plugins_url( '', PATH_TO_MAIN_PLUGIN_FILE). This would resolve all cases that the CMB2_Utils()->url() function is trying to cover.

**Comment by jtsternberg** [comment]
It doesn't resolve all cases since CMB2 can be included in a plugin, as a plugin, as an mu-plugin, or in a theme.

**Comment by jtsternberg** [comment]
Related: https://github.com/WebDevStudios/CMB2/issues/27#issuecomment-64664892
