### ISSUE TITLE
Custom field type save action

### ISSUE THREAD

**Issue by azexo** [WebDevStudios/CMB2#546]
i know that we have:
- cmb2_override_meta_save
- cmb2_override_{$a['field_id']}_meta_save

but what about cmb2_override_{$a['type']}_meta_save ?

it will allow to make independent PHP function inside field type PHP file.

thanks

**Comment by jtsternberg** [comment]
That is pretty simple to accomplish w/ the first filter you listed:

```php
function cmb2_override_meta_value_for_type( $val, $object_id, $args ) {
	if ( 'your-type' === $args['type'] ) {
		// do your modification here
	}
	
	return $val;
}
add_filter( 'cmb2_override_meta_value', 'cmb2_override_meta_value_for_type', 10, 3 );
```
