### ISSUE TITLE
Group Field - Collapse state not remembered upon Post Publish/Update

### ISSUE THREAD

**Issue by ruturaaj** [WebDevStudios/CMB2#549]
Hi,

I noticed the "Group" field type comes with collapse-expand arrow placed in the top right corner of Group Title. However, if I collapse the group UI and save/update post, the group is automatically expanded upon page refresh after save/update post. Like Wordpress Metabox collapse/expand state, is there any way or property which will save the Group field collapse/expand state?

Cheers,

Ruturaaj.

**Comment by tw2113** [comment]
Related #490 Closing in favor of it as well.
