### ISSUE TITLE
Insert / edit link field

### ISSUE THREAD

**Issue by MickeyKay** [WebDevStudios/CMB2#550]
Despite my best searching, I can't seem to find a basic "Insert / edit link" field type to match the modal that appears when inserting/editing a link in the standard editor: 

![image](https://cloud.githubusercontent.com/assets/3189678/11923929/eef5eac0-a75e-11e5-9da9-8853b08819bb.png)

Does this not exist? Is the text_url field type the closest thing?

**Comment by jtsternberg** [comment]
This field is the closest thing: https://github.com/WebDevStudios/CMB2-Post-Search-field

**Comment by MickeyKay** [comment]
Right, I saw that however it doesn't include some of the core link-picker functionality such as the ability to:
* Manually specify a URL.
* Open the link in a new window
* Add title text

I'd love to develop this one when the time allows!

**Comment by jtsternberg** [comment]
Core link picker is notoriously hard to use outside of it's intended use-case (tinymce plugin). If you can get it, that would be awesome.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.

**Comment by jtsternberg** [comment]
Also, this now exists: https://wordpress.org/plugins/link-picker-for-cmb2/
