### ISSUE TITLE
Feature request: jQuery conditional functionality

### ISSUE THREAD

**Issue by MickeyKay** [WebDevStudios/CMB2#556]
I love the conditional functionality baked into CMB2, and how extensible it is. Thanks!

Unless I'm mistaken, there isn't any functionality included to incorporate real-time, JS conditional logic, is there? For example, I'd like to be able to have the user tic a checkbox and have another field appear immediately.

**Comment by ruturaaj** [comment]
Look for cmb2-conditionals plugin. It should solve your issue. 
https://github.com/jcchavezs/cmb2-conditionals

It offers `data-conditional-id` which is nothing but the ID of the dependent field. The `data-conditional-value` is an optional attribute where you can specify the value-condition, good for checking against a particular value of `select` field. 

Refer `example-functions.php` for the usage guideline.

**Comment by tnorthcutt** [comment]
Closing for now.
