### ISSUE TITLE
How to add custom metaboxes in custom theme option panel?

### ISSUE THREAD

**Issue by ngulPs** [WebDevStudios/CMB2#558]
Im having trouble how will i show the mexaboxes in my theme panel.i hope someone there to help me.
Thanks in advance

Here's the codes:
<?php
	
/*
@package shytheme

*/
// Initialize the metabox class
add_action( 'init', 'be_initialize_cmb_meta_boxes', 9999 );
function be_initialize_cmb_meta_boxes() {
    if ( !class_exists( 'cmb_Meta_Box' ) ) {
        require_once( '/../lib/metabox/init.php' );
    }
}

function shy_add_adim_page(){
	//Generate Sunset Admin Page
	add_menu_page( 'Shy Theme Option', 'Shy', 'manage_options', 'cj_shy', 'shy_theme_create_page', /*get_template_directory_uri() . '/img/sunset-icon.png'*/'dashicons-carrot', 110 );
	
	//Generate Sunset Admin Sub Pages
	add_submenu_page( 'cj_shy', 'Shy Settings', 'Settings', 'manage_options', 'cj_shy', 'shy_theme_create_page' );
	add_submenu_page( 'cj_shy', 'Shy Custom CSS', 'Custom CSS', 'manage_options', 'cj_shy_css', 'shy_theme_setting_page' );
	add_submenu_page( 'cj_shy', 'Shy Header', 'Header', 'manage_options', 'cj_shy_header', 'shy_theme_header_page' );
}
add_action( 'admin_menu', 'shy_add_adim_page' );
function shy_theme_create_page(){
	//generate of our setting page template
	require_once get_template_directory() . '/inc/templates/admin_template_settings.php';
}
function shy_theme_setting_page(){}

function shy_theme_header_page( $meta_boxes ) {
    $prefix = '_cmb_'; // Prefix for all fields
    $meta_boxes['test_metabox'] = array(
        'id' => 'test_metabox',
        'title' => 'Test Metabox',
        'pages' => array('page'), // post type
		'show_on' => array( 'key' => 'page-template', 'value' => 'templates/admin_template_settings.php' ),
        'context' => 'normal',
        'priority' => 'high',
        'show_names' => true, // Show field names on the left
        'fields' => array(
            array(
                'name' => 'Test Text',
                'desc' => 'field description (optional)',
                'id' => $prefix . 'test_text',
                'type' => 'text'
            ),
        ),
    );

    return $meta_boxes;
}
add_filter( 'cmb_meta_boxes', 'shy_theme_header_page' );

![capture](https://cloud.githubusercontent.com/assets/16441773/12005279/75a585ae-abd7-11e5-803d-96285306745c.PNG)

**Comment by tw2113** [comment]
Just to be certain, are you for sure using CMB2? the filters and functions above indicate more that you're using the legacy CMB1 library.

**Comment by tw2113** [comment]
Redacting my previous question about CMB1 since Justin retained backcompat ability with the array version.

At this point, I recommend checking out https://github.com/WebDevStudios/CMB2/wiki/Using-CMB-to-create-an-Admin-Theme-Options-Page and if you're still running into issues, please start a forum thread at https://wordpress.org/support/plugin/cmb2 and we'll get your issues looked at there.
