### ISSUE TITLE
Is there a problem with timepicker field in WordPress 4.4?

### ISSUE THREAD

**Issue by ArchimidisM** [WebDevStudios/CMB2#559]
I have updated to the latest version of WordPress and all my datetime pickers changed behaviour. Date pickers work well, however the time pickers acts as datepickers and the time sliders disappeared.

Is there any workaround for this? I tried the trunk but with no luck.

**Comment by tw2113** [comment]
Is this still presenting any sort of issue?

If yes, could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
