### ISSUE TITLE
User Meta Not Saving in 2.1.2

### ISSUE THREAD

**Issue by mgyura** [WebDevStudios/CMB2#560]
I am having issues saving user data.  I don't know if there is a conflict with the other meta boxes I am running, but everything saves normally except the User Meta.  

Here is my code:

add_action( 'cmb2_admin_init', 'pyd_partner_metabox' );

	function pyd_partner_metabox() {
		$prefix = '_pyduser_';

		$pyd_user = new_cmb2_box( array(
			                          'id'               => 'custom_user_edit',
			                          'title'            => __( 'User Profile Metabox', 'cmb2' ),
			                          'object_types'     => array( 'user' ),
			                          'show_names'       => true,
			                          'new_user_section' => 'add-existing-user',
			                          'show_on_cb'       => 'pyd_show_to_admin'
		                          ) );

		$pyd_user->add_field( array(
			                      'name'     => __( 'Partner Options', 'cmb2' ),
			                      'desc'     => __( 'Give this person extra options as a partner', 'cmb2' ),
			                      'id'       => $prefix . 'discount_title1',
			                      'type'     => 'title',
			                      'on_front' => false,
		                      ) );

		$pyd_user->add_field( array(
			                      'name'    => __( 'Partner On Hold Message', 'cmb' ),
			                      'desc'    => __( 'This option resricts this partner from ordering via their PO Number and discounted pricing.', 'cmb' ),
			                      'id'      => $prefix . 'on_hold',
			                      'type'    => 'select',
			                      'options' => array(
				                      ''            => __( 'No Message', 'cmb' ),
				                      'holdmessage' => __( 'On Hold Notice', 'cmb' )
			                      ),
		                      ) );
		$pyd_user->add_field( array(
			                      'name'    => __( 'All Products Discount', 'cmb' ),
			                      'desc'    => __( 'Select the discount to recieve (if any)', 'cmb' ),
			                      'id'      => $prefix . 'discount_all',
			                      'type'    => 'select',
			                      'options' => array(
				                      ''   => __( 'No Discount', 'cmb' ),
				                      '15' => __( '15% Discount', 'cmb' ),
				                      '20' => __( '20% Discount', 'cmb' ),
				                      '25' => __( '25% Discount', 'cmb' )
			                      ),
		                      ) );
		$pyd_user->add_field( array(
			                      'name'    => __( 'Payment Methods', 'cmb' ),
			                      'desc'    => __( 'Do you want user to have credit card and PO # or just on of them?', 'cmb' ),
			                      'id'      => $prefix . 'po_credit',
			                      'type'    => 'select',
			                      'options' => array(
				                      ''         => __( 'Credit Card Only', 'cmb' ),
				                      'po'       => __( 'PO # Only', 'cmb' ),
				                      'pocredit' => __( 'PO # and Credit Card', 'cmb' ),
				                      'noorders' => __( 'No Orders Allowed', 'cmb' ),
			                      ),
		                      ) );
		$pyd_user->add_field( array(
			                      'name'    => __( 'Allow Blind Shipments', 'cmb' ),
			                      'desc'    => __( 'Give this partner the option to blind ship.', 'cmb' ),
			                      'id'      => $prefix . 'ship_blind',
			                      'type'    => 'select',
			                      'options' => array(
				                      ''        => __( 'No Blind Shipments', 'cmb' ),
				                      'partner' => __( 'Allow Blind Shipments', 'cmb' ),
			                      ),
		                      ) );
		$pyd_user->add_field( array(
			                      'name'    => __( 'Select Default Carrier', 'cmb' ),
			                      'desc'    => __( 'Can this partner pick their own shipment options?', 'cmb' ),
			                      'id'      => $prefix . 'ship_to',
			                      'type'    => 'select',
			                      'options' => array(
				                      ''      => __( 'Default Shipping', 'cmb' ),
				                      'USPS'  => __( 'USPS', 'cmb' ),
				                      'UPS'   => __( 'UPS', 'cmb' ),
				                      'FedEx' => __( 'FedEx', 'cmb' ),
				                      'DHL'   => __( 'DHL', 'cmb' ),
			                      ),
		                      ) );
		$pyd_user->add_field( array(
			                      'name' => __( 'Carrier Account Number', 'cmb' ),
			                      'desc' => __( 'If this partner has custom shipping, what is their account number', 'cmb' ),
			                      'id'   => $prefix . 'ship_account',
			                      'type' => 'text'
		                      ) );
		$pyd_user->add_field( array(
			                      'name'    => __( 'Show Sales Rep Contact Info', 'cmb' ),
			                      'desc'    => __( 'Will you show the below sales rep info on the website?', 'cmb' ),
			                      'id'      => $prefix . 'rep_show',
			                      'type'    => 'select',
			                      'options' => array(
				                      ''        => __( 'Hide Sales Rep Info', 'cmb' ),
				                      'partner' => __( 'Show Sales Rep Info', 'cmb' ),
			                      ),
		                      ) );
		$pyd_user->add_field( array(
			                      'name' => __( 'Sales Rep Name', 'cmb' ),
			                      'desc' => __( 'The name of this partners sales representative', 'cmb' ),
			                      'id'   => $prefix . 'rep_name',
			                      'type' => 'text'
		                      ) );
		$pyd_user->add_field( array(
			                      'name' => __( 'Sales Rep Email', 'cmb' ),
			                      'desc' => __( 'The email address of this partners sales representative', 'cmb' ),
			                      'id'   => $prefix . 'rep_email',
			                      'type' => 'text_email'
		                      ) );
		$pyd_user->add_field( array(
			                      'name' => __( 'Sales Rep Phone', 'cmb' ),
			                      'desc' => __( 'The phone number of this partners sales representative', 'cmb' ),
			                      'id'   => $prefix . 'rep_phone',
			                      'type' => 'text_medium'
		                      ) );
		$pyd_user->add_field( array(
			                      'name'    => __( 'Partner Availability', 'cmb2' ),
			                      'desc'    => __( 'Should this partner see any locked products?', 'cmb2' ),
			                      'id'      => $prefix . 'partner_available',
			                      'type'    => 'select',
			                      'options' => array(
				                      'everyone'             => __( 'Everyone', 'cmb' ),
				                      'internal-only'        => __( 'Internal Only', 'cmb' ),
				                      'p-dell'               => __( 'Dell', 'cmb' ),
				                      'p-gamber-johnson'     => __( 'Gamber Johnson', 'cmb' ),
				                      'p-havis'              => __( 'Havis', 'cmb' ),
				                      'p-hp'                 => __( 'HP', 'cmb' ),
				                      'p-mobilty'            => __( 'Mobilty', 'cmb' ),
				                      'p-motion'             => __( 'Motion', 'cmb' ),
				                      'p-panasonic'          => __( 'Panasonic', 'cmb' ),
				                      'p-precision-mounting' => __( 'Precision Mounting', 'cmb' )
			                      ),
		                      ) );
	}

The function to show only to admins is here:

function pyd_show_to_admin( $field ) {
		if ( current_user_can( 'activate_plugins' ) ) {
			return true;
		} else {
			return false;
		}
	}

Any ideas?

**Comment by tw2113** [comment]
hey @mgyura 
Can you confirm whether or not this is still an issue with the updated plugin from the WordPress.org repo, or however you installed the library?

If it's still presenting issues, could you please start a support thread over at https://wordpress.org/support/plugin/cmb2? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks

**Comment by mgyura** [comment]
Looking good on my end.  Thank you.

Sincerely, 
Michael Gyura
(888) 442-8731 ext 101
http://pokayoke.design
@pokayokedesign

On Mar 14, 2016, at 12:59 PM, Michael Beckwith <notifications@github.com> wrote:

hey @mgyura <https://github.com/mgyura> 
Can you confirm whether or not this is still an issue with the updated plugin from the WordPress.org repo, or however you installed the library?

If it's still presenting issues, could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 <https://wordpress.org/support/plugin/cmb2>? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
