### ISSUE TITLE
Group Field Type - Repeating Field Box Title different than Entry {#}

### ISSUE THREAD

**Issue by ruturaaj** [WebDevStudios/CMB2#562]
Hello All,

I'm using Group Field Type under which a bunch of fields are added. CMB2 allows me to set dynamic group field title with {#} place-holder. However, is it possible for me to make this Title editable so User can give more meaningful title to the Group? Or is it possible to change this title later after publish/update Post using certain Filter where I can set the title as the value of one of the child fields?

Waiting for your reply...

Cheers,

Ruturaaj.

**Comment by mauricenaef** [comment]
Would love to know if this is possible as well? To Set it as a child field value would be great?

Thanks,

Marcel

**Comment by tw2113** [comment]
Hey @ruturaaj  

Could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
