### ISSUE TITLE
Editing multiple metaboxes from the front end

### ISSUE THREAD

**Issue by jancbeck** [WebDevStudios/CMB2#563]
I'm saving my post meta data in multiple CMB2 metaboxes and would like to edit all of them from the frontend. That's currently only possible in the post edit screen where multiple metaboxes are saved when the user hits "publish/update". If I wanted to have the same on the front end I would need loop over all metaboxes and output an individual form via `cmb2_metabox_form`. However, this results in multiple forms rendered on the page and requires the user to submit changes for each one individually - not very intuitive. There should only be one submit button on the whole page.

An obvious solution to this would be to accept an array of meta_boxes such as

```
<?php cmb2_metabox_form( array( 'pricing', 'product_images', 'location_map' ) ) ?>
```

This is related but not identical to https://github.com/WebDevStudios/CMB2/issues/286

**Comment by nonsensecreativity** [comment]
@jancbeck Do you handle your own form save field? or using the custom save field callback in the front end? if you don't need a form, you can use this example
```php
function cmb2_get_metaboxes( Array $metabox_ids, $object_id = 0, $echo = true ) {
	
	global $post;

	if( ! $object_id && isset( $post->ID ) ) {
		$object_id = $post->ID;
	}
	$cmbs = array();

	foreach( $metabox_ids as $metabox_id ) {
		$cmbs[] = $cmb = cmb2_get_metabox( $metabox_id, $object_id );
		if( $echo ) {
			$cmb->show_form( 0, $cmb->mb_object_type() );
		}
	}

	if( !$echo ) {
		return $cmbs;
	}
}

add_filter( 'the_content', 'cmb2_output_metabox_on_the_content' );
function cmb2_output_metabox_on_the_content( $content ) {
	cmb2_get_metaboxes( array( '_yourprefix_demo_metabox', '_yourprefix_about_metabox' ) );
}
```

in the codes above it will output the field without any `<form>` tag so you can put the code just inside your form.

hope this can help you

**Comment by jancbeck** [comment]
This helps me a lot, thanks @nonsensecreativity. I didn't consider saving the fields myself, but looking at your code and the one in https://github.com/WebDevStudios/CMB2/blob/b3b78a569f63560d2f8a039c4c1ff412a28f0156/includes/helper-functions.php#L238 makes it look pretty straightforward.

Still, I think it might be worth refactoring `cmb2_print_metabox_form` to accept multiple metaboxes. Expect a PR if I get to figure this out.

**Comment by jancbeck** [comment]
I ended up using this very simple code:
``` php
echo '<form class="cmb-form" method="post" id="wpcasa-listing-form" enctype="multipart/form-data" encoding="multipart/form-data">
	<input type="hidden" name="object_id" value="'. $object_id .'">';

$args = array( 'form_format' => '%3$s' );

foreach( get_meta_boxes() as $metabox ) { // loop over config array
    cmb2_metabox_form( $metabox['id'], $object_id, $args );
}

echo '<input type="submit" name="submit-cmb" value="Save" class="button-primary"></form>';
```

Using `cmb2_metabox_form` gives me fields saving and enqueueing of styles and scripts but the `form_format` argument removes the forms around the metaboxes. The two echo statements wrap that form around the boxes. That was easier than I thought.
