### ISSUE TITLE
Setting checkbox default to true causes, value is always true

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/CMB2#564]
I added 'default' => true to a checkbox array and when I go to the edit screen, the checkbox is in fact checked. Hurray! But, if I uncheck the box and save the post, the check shows back up.

**Comment by jtsternberg** [comment]
Yah, default doesn't work the same way with checkboxes. Check out this snippet for workaround: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#setting-a-default-value-for-a-checkbox

**Comment by vegasgeek** [comment]
You, sir, are awesome. Sorry I missed that in my research prior to posting a ticket.

**Comment by jtsternberg** [comment]
No worries!

**Comment by anhskohbo** [comment]
I found a another way. It's hook in `cmb2_sanitize_checkbox` and return 0 instead of false (or null).

This will avoid `CMB2_Utils::isempty()` and CMB that will save value in database. And when get value to give in to the condition, not change much.

```
add_filter( 'cmb2_sanitize_toggle', 'sanitize_checkbox', 20, 2 );

/**
 * Fixed checkbox issue with default is true.
 *
 * @param  mixed $override_value Sanitization/Validation override value to return.
 * @param  mixed $value          The value to be saved to this field.
 * @return mixed
 */
function sanitize_checkbox( $override_value, $value ) {
	// Return 0 instead of false if null value given. This hack for
	// checkbox or checkbox-like can be setting true as default value.
	return is_null( $value ) ? 0 : $value;
}
``

**Comment by tw2113** [comment]
FWIW, numeral zero very easily could get interpreted as false/falsey in PHP. Same thing with '0' with quotes. That still evaluates to true if checking for empty values. Very frustrating.
