### ISSUE TITLE
file_list data lost

### ISSUE THREAD

**Issue by vhinmanansala** [WebDevStudios/CMB2#566]
Hello, great and useful plugin by the way. Thank you. I just started using file_list with one of my projects recently and every time I migrate the database to production server the data I have for file_list is getting lost and have to add them one by one again. Is there anyway to prevent this?

**Comment by jtsternberg** [comment]
file_list saves an array of attachment ids and attachment urls, neither of which will be the same on a separate server. Solving for that is outside the scope of this plugin.

**Comment by dewaadiperdana** [comment]
Hey, did the file_list type support dragable object?

**Comment by jtsternberg** [comment]
Great solution here: https://github.com/WebDevStudios/CMB2/issues/631#issuecomment-212097539
