### ISSUE TITLE
How can I get the `text_date_timestamp` field to go farther back than 2006?

### ISSUE THREAD

**Issue by wesleycole** [WebDevStudios/CMB2#567]
Currently the `text_date_timestamp` field allows you to only go back to 2006? 

![screenshot 2016-01-18 14 14 06](https://cloud.githubusercontent.com/assets/1162694/12400420/ecaf5666-bded-11e5-89f8-31e03f95bf44.png)

I would like to be able to select dates that go back to 1996 or before, if possible. Is there a way to handle this?

**Comment by jtsternberg** [comment]
As of version 2.2.0 (to be released shortly), and in trunk, you can do this this way: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#change-the-year-range-for-the-date-field-types.

**Comment by wesleycole** [comment]
Sorry for the delayed response! Appreciate your help on this and providing the solution.
