### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by greyearlgrey85** [WebDevStudios/CMB2#569]
Not sure if anyone else is having this issue, but when google tag manager is installed on a site using CMB2 the website will break on refresh. All the styling and scripts will stop working until you clear the cookies. Im not really sure what is causing the issue but i have narrowed it down to CMB2 as websites i have built before using CMB2 work fine with GTM. Also websites created by other 2 other firms using CMB2 i have installed GTM on have the same issue. Any help or ideas would be great as i cant find anyone else having the same or similar issue anywhere.

**Comment by tnorthcutt** [comment]
@greyearlgrey85 including a link to an example would go a long way toward making this possible to debug.

**Comment by tnorthcutt** [comment]
@greyearlgrey85 I'm closing this issue now; if it's still a problem please feel free to show an example and reopen.
