### ISSUE TITLE
taxonomy_select default being stomped by get_object_terms

### ISSUE THREAD

**Issue by wilrevehl** [WebDevStudios/CMB2#572]
Hi Justin, et all,

Thanks for much for your sharing hard work on CMB2. It's definitely the best out there, we applaud you.

I'm having an issue setting default on taxonomy_select. At the time of writing, line 665 of includes\CMB2_Types.php::$saved_term has a ternary with $this->get_object_terms() taking precedence over default. get_object_terms() gets the select by using something stored as a cmb-cache. This probably has its purpose. Unfortunately, I'm trying to use taxonomy_select with dynamic data from a callback to set the default. This is important because it allows the same form for New and Edit. That other cached value is causing the intended default (from data specific to the post) to be ignored.

I'm going to see if I can workaround this using the filters. My use may be an edge case, but thought you should know this feels like an unintended consequence. Thanks. Keep rocking.

**Comment by wilrevehl** [comment]
Update: I noticed the ternary condition for $saved_term favors the $names failover because the result of $names is almost always going to return the terms the field is set to use. It's therefore nearly impossible a default setting would ever work for this, unless you added something like:

`$saved_term = is_wp_error( $names ) || empty( $names ) || $this->field->args( 'default' ) ? $this->field->args( 'default' ) : $names[key( $names )]->slug;`

**Comment by tw2113** [comment]
Any updates or progress made on this @wilrevehl ?

**Comment by wilrevehl** [comment]
Oh, I never made a fork contribution since I never heard back and the issue was small. I'm not really a GIT user as it is. Nothing has changed in [CMB2 taxonomy_select](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Types.php#L684). $names is still the sole ruler of the conditional.

**Comment by tw2113** [comment]
Closing early as Justin's commit above states it fixes this issue.
