### ISSUE TITLE
The front end integration doesnt work or the example is unclear or HELP.

### ISSUE THREAD

**Issue by sagive** [WebDevStudios/CMB2#573]
I tried getting form to the frontend

i tried the Shortcode and it doesnt work and always returns an error

Using this would retrun an error:
"Metabox configuration is required to have an ID parameter"
```
$pcid = get_the_ID();
$metaname = THEMEֹ_PREF.'lp1_toptitle';

echo do_shortcode('[cmb-form id="'.$metaname.'" post_id='.$pcid.']');
```

After looking into CMB2.php (line 119)
i changed this $pcid = get_the_ID(); to this $pcid['id'] = get_the_ID();

which gets rid of the error but returns only a save button and not the form.

Help anyone?

**Comment by tw2113** [comment]
Hey @sagive 
Could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
