### ISSUE TITLE
Taxonomy Dropdown

### ISSUE THREAD

**Issue by qimzu** [WebDevStudios/CMB2#576]
Hi!

I need to create a metabox to select a category (grab the id) to display posts from that category on the page where it is selected. So I guess I have to use the code found here : https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post
The metabox is working except that I have only one category in the select options. I can't figure out why, or is it a bug with that code?

Best regards,

Quentin

**Comment by joshuadavidnelson** [comment]
Is there only one category with posts in it? By default [`get_terms`](https://developer.wordpress.org/reference/functions/get_terms/) hides empty terms.

**Comment by tw2113** [comment]
Hey @qimzu  

Could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue if it's still presenting an issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
