### ISSUE TITLE
How to resize media/image uploaded by file_list

### ISSUE THREAD

**Issue by webdziner** [WebDevStudios/CMB2#580]
How to resize media/image uploaded by file_list, or can we add_support in functions.php to do the same?

**Comment by joshuadavidnelson** [comment]
You should be able to grab the image id from the file list (see [the wiki](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#sample-function-for-getting-and-outputting-file_list-images)), from there set the size of the image you want.

If you're hoping to have a image resized on upload, you can do that with the WP built-in [`add_image_size`](https://developer.wordpress.org/reference/functions/add_image_size/).

**Comment by tw2113** [comment]
Hey @webdziner  

Could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue if it's still presenting an issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
