### ISSUE TITLE
Theme Check Plugin giving this error on tests folder

### ISSUE THREAD

**Issue by webdziner** [WebDevStudios/CMB2#583]
WARNING: fsockopen was found in the file cmb-tests-base.php possible file operations.
INFO: Possible hard-coded links were found in the file test-cmb-core.php.

Can be delete testes folder or any fix for this?

**Comment by jtsternberg** [comment]
If you use the [version from wordpress.org](https://wordpress.org/plugins/cmb2/), you will not get any of the tests or other dev resources.
