### ISSUE TITLE
Term meta not working

### ISSUE THREAD

**Issue by weare2ndfloor** [WebDevStudios/CMB2#587]
Apologies if I'm going mad, but I can't get the example function:

yourprefix_register_taxonomy_metabox()

To work, running latest WP Plugin of CMB2 and WordPress 4.4.2.

All other CMB2 metaboxes are working for pages, posts and CPTs.

Any help welcome :)

**Comment by jtsternberg** [comment]
This is in [trunk](https://github.com/WebDevStudios/CMB2/tree/trunk), the in-development branch. Is that what you are using?

**Comment by meanthemes** [comment]
I'm running the WP Plugin of CMB2

**Comment by weare2ndfloor** [comment]
I'm running the WP Plugin of CMB2

**Comment by weare2ndfloor** [comment]
Right ok, so trunk has it but master doesn't - meaning the WP repo doesn't have it.

Sorry for the confusion, I was working off of the version numbers which match the WP repo on trunk as well as master.

Great plugin by the way, it saves me loads of time :)

Is there a release date for the new master/WP repo version including the taxonomy terms addition?

**Comment by tw2113** [comment]
@weare2ndfloor can you confirm that your issue(s) are cleared up with the released version from wordpress.org? If not, can you please start a new thread over at https://wordpress.org/support/plugin/cmb2 for lingering issue(s)?

Thanks
