### ISSUE TITLE
wp_set_object_terms during sanitization of taxonomy fields

### ISSUE THREAD

**Issue by azexo** [WebDevStudios/CMB2#589]
i try to use CMB API in my frontend submission form.
and it seems to me that this is not correct sanitization.

**Comment by azexo** [comment]
same situation for file sanitization

**Comment by tw2113** [comment]
Hey @niklasp 

Could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

If you could provide all the code you're using for trying to take care of this, when you create the thread, that'd be awesome and help us answer questions more quickly.

Thanks
