### ISSUE TITLE
WP Editor and Textarea name attribute

### ISSUE THREAD

**Issue by widoz** [WebDevStudios/CMB2#590]
Why don't allow to overwrite the option **textarea_name** for the wysiwyg editor?

In **cmb2/includes/CMB2_Field.php** at line **968** 

```php
if ( 'wysiwyg' == $args['type'] ) {
	$args['id'] = strtolower( str_ireplace( '-', '_', $args['id'] ) );
	$args['options']['textarea_name'] = $args['_name'];
}
```

In that way you are unable to store the content as sub element of an array. 
For example:

```php
$this->_cmb2->add_field( [
	'name' => 'Editor Name',
	'id' => 'content-id',
	'type' => 'wysiwyg',
	'options'   => [
		'wpautop' => true,
		'media_buttons' => false,
		'textarea_name' => $this->_key . '[my_content]',
		'teeny' => true,
		'quicktags' => false,
		'tinymce' => [
			'paste_remove_styles' => true,
			'paste_remove_spans' => true,
			'plugins' => 'wplink',
			'toolbar1' => 'bold,italic,link,unlink',
		],
	],
] );
```
Also that not break the coherency with other fields where I can set my custom **name** attribute?

In any case I change it in this way:

```php
if ( 'wysiwyg' == $args['type'] ) {
	$args['id'] = strtolower( str_ireplace( '-', '_', $args['id'] ) );

        if ( empty( $args['options']['textarea_name'] ) ) {
              $args['options']['textarea_name'] = $args['_name'];
        }
}
```

**Comment by widoz** [comment]
I think there is no way to have a different value for the name attribute without encountering issues using a custom field type. The attribute name defined within the 'attributes' argument will overwrite the field '_name' property. 


So I cannot have the id with scores and name with underscores or within a sub array element.

**Comment by tw2113** [comment]
Is this still presenting a problem for you? or did you find some sort of workaround?

**Comment by widoz** [comment]
Hello @tw2113, 

No workarounds right now, I need a moment or two to study the plugin better. 
I guess accomplishing that means rewrite part of the _name and _id properties and I'm not sure will be convenient. Mine was to get my css selectors the same ( using bem for example ) of classes, but keep the names of the input with underscore 'cause them are used as array keys.

ps. sorry for the english.

**Comment by jtsternberg** [comment]
@widoz I can't imagine a scenario where you would want the textarea_name to be different than the 'id' attribute, considering that the field would only show/save to the 'id' attribute.

**Comment by widoz** [comment]
@jtsternberg for custom fields yes, sorry me I missed to tell you that I'm currently using cmb2 only for form fields and not for post meta, so I have my own sanitize/validation classes and generally works with the name attributes with underscore 'cause them are keys of an array.

By the way, I think to change it take a lots of work and would mean redefine how the classes and fields works.

Just a question if it were possible.

**Comment by jtsternberg** [comment]
It does work w/ custom fields.
```php
function cmb2_render_custom_field( $field, $value, $object_id, $object_type, $cmb2_type ) {
	echo $cmb2_type->wysiwyg( array(
		'id'      => $cmb2_type->_id( 'desc' ),
		'value'   => stripslashes( $value['desc'] ),
		'desc'    => '',
		'options' => array(
			'textarea_rows' => 3,
			'textarea_name'  => $cmb2_type->_name( '[desc]' ),
		),
	) );
}
add_filter( 'cmb2_render_custom_field', 'cmb2_render_custom_field', 10, 5 );
```

**Comment by widoz** [comment]
Thanks, but I'll must override every field to achieve that with all fields?

**Comment by widoz** [comment]
Hi, thank you for support on this, after some research I realized that since the id's are more useful in javascript I'll keep the underscore.

Thanks again for this great plugin.
