### ISSUE TITLE
get_field_args unable to overwrite attributes

### ISSUE THREAD

**Issue by widoz** [WebDevStudios/CMB2#591]
Using cmb2 on front-end to create a new post submission form.

I build the form, then based on the $_POST values I change the classes, description etc... to the field before showing the form. 
The problem come by using **get_field_args** after the fields have been created.

I'm unable to overwrite the attributes array because of **array_merge** that take the original metabox fields as secondary parameter.

**Comment by tw2113** [comment]
Hey @widoz 

Could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Also for that, could you share the code you're using for both the metabox setup as well as the processing after the user hits submit?

Thanks
