### ISSUE TITLE
show_on_cb only hide/show metaboxes on publish/update

### ISSUE THREAD

**Issue by Taolou** [WebDevStudios/CMB2#592]
Hi everyone,

Current Usage : I have a select (i tried with a radio button too), if the value selected is "Yes", a new metabox has to be shown. If it's "No", it has to be hidden.

Perhaps it is planned to work like that, but when I select "Yes" or "No", I have to Publish or Update my post to make this new metabox appears or disappears.

Is it normal? Is there a solution to make the metabox appears/disappears as soon as an option is selected ?

Thanks in advance and sorry for my english, I'm not a native speaker.

**Comment by jrfnl** [comment]
@Taolou AFAIK the 'show_on' is supposed to work exactly like that, it is intended more to show certain metaboxes (or fields) on specific pages and not on others.

I believe what you are looking for is the [CMB2 Conditionals](https://github.com/jcchavezs/cmb2-conditionals) add-on which works with in-page conditions, though more on a field by field basis, i.e. show field B if field A has value x, though it could probably be made to work with metaboxes too.

**Comment by Taolou** [comment]
Thanks for your fast answer, i'll give it a try.

I'll close the ticket and come back if I still have a prob.

Have a nice day
