### ISSUE TITLE
How to filter field according to our post types.

### ISSUE THREAD

**Issue by webdziner** [WebDevStudios/CMB2#595]
We have four post formats.

- Standard 
- Gallery
- Image
- Quate

How can we show/hide or filter fields according to our selected post format options?

**Comment by jtsternberg** [comment]
I would look at the wiki examples: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-using-the-show_on_cb-to-limit-the-display-of-a-metabox-unless-metadata-exists.

**Comment by webdziner** [comment]
Hi, i tried same given example but its not working its that something which i am missing?

**Comment by apeximum** [comment]
i am facing the same problem too...given example is not working..does it the all or anything else we have to do to work this code

**Comment by apeximum** [comment]
`<?php 

add_action( 'cmb2_admin_init', 'page_title_bg_metabox' );

function page_title_bg_metabox() {

    $cmb = new_cmb2_box( array(
        'id'           => 'page_title',
        'title'        => 'Page Title',
        'object_types' => array( 'page', ), // Post type
    ) );

    $cmb->add_field( array(
        'name'    => 'Style',
        'id'      => 'page_title_style',
        'type'    => 'select',
        'options' => array(
            '01' => 'Style 01',
            '02' => 'Style 02',
        ),
    ) );

	$cmb = new_cmb2_box( array(
        'id'           	=> 'page_title_background',
        'title'        	=> 'Title Background',
        'object_types' 	=> array( 'page', ), // Post type
        'show_on_cb' 	=> 'cmb_page_title_background', // function should return a bool value
    ) );
	
	$cmb->add_field(array(
		'id' 		=> 'page_title_background_upload',
		'type'		=> 'file',
		'name' 		=> __( 'Background Image', 'equator' ),
		'options' 	=> array(
				'url' 					=> false,
				'add_upload_file_text' 	=> 'Add or Upload images'
			),
		)
	);
}

function cmb_page_title_background( $cmb ) {

    $style = get_post_meta( $cmb->object_id(), 'page_title_style', 1 );
	
    return '02' === $style;
}`

**Comment by jtsternberg** [comment]
Post types or post formats? You're using different terms.

**Comment by webdziner** [comment]
Hi, lets make it simple, we are trying to test your given sample code to run but its not working in same condition.
https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-using-the-show_on_cb-to-limit-the-display-of-a-metabox-unless-metadata-exists
I just try to quick check with this code how it will work, but sample not giving anything.

add_action( 'cmb2_admin_init', 'cmb2_register_conditional_metabox' );
/**
 * Hook in and add a demo metabox. Can only happen on the 'cmb2_admin_init' or 'cmb2_init' hook.
 */
function cmb2_register_conditional_metabox() {
    /**
     * Metabox to save the 'status' where 'Internal' is the default.
     */
    $cmb = new_cmb2_box( array(
        'id'           => 'wiki_status_metabox',
        'title'        => 'Status Metabox',
        'object_types' => array( 'page', ), // Post type
    ) );

    $cmb->add_field( array(
        'name'    => 'Status',
        'id'      => 'wiki_status',
        'type'    => 'select',
        'default' => 'internal',
        'options' => array(
            'internal' => 'Internal',
            'external' => 'External',
        ),
    ) );

    /**
     * Metabox to conditionally display if the 'status' is set to 'External'.
     */
    $cmb = new_cmb2_box( array(
        'id'           => 'wiki_conditonal_metabox',
        'title'        => 'Contact Info',
        'object_types' => array( 'page', ), // Post type
        'show_on_cb' => 'cmb_only_show_for_external', // function should return a bool value
    ) );

    $cmb->add_field( array(
        'name'       => 'Email',
        'id'         => 'wiki_email',
        'type'       => 'text_email',
    ) );
}

/**
 * Only display a metabox if the page's 'status' is 'external'
 * @param  object $cmb CMB2 object
 * @return bool        True/false whether to show the metabox
 */
function cmb_only_show_for_external( $cmb ) {
    $status = get_post_meta( $cmb->object_id(), 'wiki_status', 1 );

    // Only show if status is 'external'
    return 'external' === $status;
}

**Comment by tw2113** [comment]
Just copy/pasted that snippet above from @webdziner and it's working just fine. Doesn't show the new metabox automagically the moment you select "External" from the dropdown, but once you save the page with "External" selected, the 2nd metabox shows up. No fancy ajax or anything like that here, just needs a page update first.

**Comment by webdziner** [comment]
@tw2113 ok got but it should be ajax or juqery to change when i select, because how use know that anything going show when i change the option?

**Comment by tw2113** [comment]
Ended up seeing this via a different CMB2 issue: https://github.com/jcchavezs/cmb2-conditionals. Think it may suit you better than the show_on_cb at this point. Using its provided examples, you could check on the current state of the select input and show/hide the 2nd input, all without having to update the post/page AND without ajax, so fewer http requests.
