### ISSUE TITLE
render_row_cb

### ISSUE THREAD

**Issue by JasonHoffmann** [WebDevStudios/CMB2#596]
I'm wondering if there is documentation anywhere about how to use the render_row_cb callback. What arguments are passed to it? And what should it be returning?

**Comment by jtsternberg** [comment]
> I'm wondering if there is documentation anywhere about how to use the render_row_cb callback.

The only documentation for it is at the bottom, here: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#render_row_cb

> What arguments are passed to it?

It's [called here](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Field.php#L677), and gets passed `$field_args` and the `$field`object.

> And what should it be returning?

Basically, it needs to replace the functionality of the [`CMB2_Field::render_field_callback`](https://github.com/WebDevStudios/CMB2/blob/master/includes/CMB2_Field.php#L685-L728) method.

If you're render_row_cb looked like the following snippet, it would (in theory) be a direct replacement:
```php
function override_render_field_callback( $field_args, $field ) {
	// If field is requesting to not be shown on the front-end
	if ( ! is_admin() && ! $field->args( 'on_front' ) ) {
		return;
	}
	// If field is requesting to be conditionally shown
	if ( ! $field->should_show() ) {
		return;
	}
	$field->peform_param_callback( 'before_row' );
	printf( "<div class=\"cmb-row %s\">\n", $field->row_classes() );
	if ( ! $field->args( 'show_names' ) ) {
		echo "\n\t<div class=\"cmb-td\">\n";
		$field->peform_param_callback( 'label_cb' );
	} else {
		if ( $field->get_param_callback_result( 'label_cb', false ) ) {
			echo '<div class="cmb-th">', $field->peform_param_callback( 'label_cb' ), '</div>';
		}
		echo "\n\t<div class=\"cmb-td\">\n";
	}
	$field->peform_param_callback( 'before' );
	$field_type = new CMB2_Types( $field );
	$field_type->render();
	$field->peform_param_callback( 'after' );
	echo "\n\t</div>\n</div>";
	$field->peform_param_callback( 'after_row' );
	// For chaining
	return $field;
}
```

**Comment by JasonHoffmann** [comment]
Thanks! Managed to follow the thread and figure it out. I might be able to write somethings up about it for docs. Do you think there's a good place for it?

**Comment by jtsternberg** [comment]
That'd be awesome! The Tips & Tricks page would probably be a good place for it: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks

**Comment by JasonHoffmann** [comment]
Finally had a chance to add this bit of documentation. For those looking for it here's the link: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#modify-field-row-output-and-markup. 

I'm going to close this ticket now too, thanks for pointing me in the right direction!

**Comment by jtsternberg** [comment]
@JasonHoffmann that's pretty awesome, thank you!
