### ISSUE TITLE
Travis problem during the tests

### ISSUE THREAD

**Issue by Mte90** [WebDevStudios/CMB2#597]
I see that many pr have problems with Travis.
As you can see here: https://travis-ci.org/WebDevStudios/CMB2/jobs/107454357
There are some problems with installing php 5.2.

**Comment by jtsternberg** [comment]
Yes, I need to update the Travis config.

**Comment by Mte90** [comment]
I want to try the cmb2 branch with the support for rest api but travis report that problem...

**Comment by tw2113** [comment]
Is there anything stopping you from testing the branch at the moment?
