### ISSUE TITLE
Issue with remove_field

### ISSUE THREAD

**Issue by jondcampbell** [WebDevStudios/CMB2#599]
I get a 
Warning:  Attempt to modify property of non-object in :
/plugins/cmb2/includes/CMB2.php
on line 948

`unset( $this->fields[ $field_id ]->args['fields'][ $sub_field_id ] );`

Any idea why this would be happening?

The field  is being removed properly, maybe even by what is being done on the next line:
`unset( $this->meta_box['fields'][ $field_id ]['fields'][ $sub_field_id ] );`

Thanks

**Comment by daveromsey** [comment]
This is a confirmed bug, #362. Sorry, but I don't know of a fix.
