### ISSUE TITLE
Using CMB2 to create a parallax one pager screen?

### ISSUE THREAD

**Issue by paaljoachim** [WebDevStudios/CMB2#601]
Hey

I am thinking of various ways to create a one pager. One way is to create meta boxes with content. Having a menu link to the various sections.

The scenario:
Making this page a lot better: http://spirituellfilm.no/nestefilm/

A movie page that have these sections: 
synopsis, 
about the director, 
technical info who, where, how long, where to purchase the DVD etc, 
a trailer, 
and other sections that will change depending on the movie we are screening.

What I am looking at creating meta boxes for each section.
Having a sidebar menu or top menu with anchor links that lead to each section.
Having the menu follow along with the page so the user can continue to use the menu independent on where they are located.
An example can be both of these demos here: http://para.llel.us/support/tutorials/linking-menu-items-to-sections-on-the-same-page/

As this would turn into a one pager parallax screen. It could be cool to test out CMB2 with this.
Thoughts ideas? Step by step code samples I can play with? 

Disclaimer: I create tutorials and it would be awesome to create this into a tutorial that I can add to my WordPress tutorials page: http://easywebdesigntutorials.com/ 
Actually what I was going to say.... I am a semi coder...much more of a visual designer then a coder, so it would be great to get some handholding here... It will also be a cool example on using CMB2. As it would be my first tutorial for me on using CMB2, and my first serious attempt at using CMB2. 
Let it be a good one..:)

Another thing.
I could actually use this example for splitting up longer tutorials I do as well.

**Comment by tnorthcutt** [comment]
> Thoughts ideas? Step by step code samples I can play with?

Unfortunately, we can't support every person's specific or custom implementations for CMB2. Github issues are reserved for confirmed bug reports and occasional feature requests. Please review the [CONTRIBUTING.md](https://github.com/WebDevStudios/CMB2/blob/master/CONTRIBUTING.md) for support suggestions. Please also review the additional resources listed at the bottom of that document, as the solution you're looking for may already be present.
