### ISSUE TITLE
How to use sanitization_cb for validation?

### ISSUE THREAD

**Issue by gnujach** [WebDevStudios/CMB2#604]
Hi, howto i use sanitization_cb parameter, some example, i have a field type text and require strlen validation, i write my function:
```
public function my_custom_sanitization($value) {            
   if (strlen($value) < 10)
           return false;
   else
         return true
}
```

**Comment by tw2113** [comment]
For that, you provide the function name you want to pass the value to, and then in the function declaration, you would sanitize however you see fit and return the result.

Also for future support requests, could you please start a support thread over at https://wordpress.org/support/plugin/cmb2? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
