### ISSUE TITLE
3rd Party Resource — Custom Field Type: Tags

### ISSUE THREAD

**Issue by florianbeck** [WebDevStudios/CMB2#605]
Hi,
i created a custom field type for WordPress-Tags-like input:
https://github.com/florianbeck/cmb2-field-type-tags

This plugin gives you two CMB2 field types:

1. The `tags` field acts like WordPress's default tags list.
2. The `tags_sortable` field acts like WordPress's default tags list as well, but adds sorting.

The Entrys will be saved as single string separated with semicolons.

![Screenshot](https://cloud.githubusercontent.com/assets/15218751/13541696/29825b9e-e25e-11e5-88d3-1f714d943403.jpg)

It would be great, if it will be listed in the 3rd party resources.

Greetings, 
Florian

**Comment by jtsternberg** [comment]
This looks great! So does it save actual tags, or just arbitrary text entries?

**Comment by florianbeck** [comment]
The entrys are saved as one single text string - actually in a textarea - separated with semicolons. If you disable javascript you will see that textarea. Just like the Wordpress Tags metabox does. The rest is just some javascript magic.
