### ISSUE TITLE
Any audio file uploading support exist ? 

### ISSUE THREAD

**Issue by himelkazi** [WebDevStudios/CMB2#607]
What have do if I want to to upload audio file through cmb2 fields ?

**Comment by tnorthcutt** [comment]
@himelkazi have you tried the [file](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#file) field type?

**Comment by tw2113** [comment]
I'm going to have to echo what Travis said. If you're having any other trouble, could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 and we can attempt to tackle the issue(s) there before elevating to GitHub here.
