### ISSUE TITLE
Get custom metadata on frontpage / postspage

### ISSUE THREAD

**Issue by niklasp** [WebDevStudios/CMB2#608]
I cannot get the custom metadata on the front page or posts page. My frontend code is:

```
    $meta = get_post_meta( get_the_ID());
    var_dump($meta);
```
and my backend code:
```

add_action( 'cmb2_admin_init', 'eedee_af_metaboxes' );

function eedee_af_metaboxes() {
    $prefix = '_eedee_';
    $cmb = new_cmb2_box( array(
        'id'            => 'subtitle_metabox',
        'object_types'  => array('post', 'page'), // Post type
        'context'       => 'normal',
        'priority'      => 'high',
        'show_names'    => true, // Show field names on the left
    ) );


    $cmb->add_field( array(
        'name'       => __( 'Subtitle', 'cmb2' ),
        'id'         => $prefix . 'subtitle',
        'type'       => 'text',
    ) );

}
```
In the backend the subtitle is saved on all pages but the posts_meta array only contains the custom data when not on the front page / posts page.

**Comment by tw2113** [comment]
Hey @niklasp 

Could you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue? We use the WordPress.org forums for initial support and try to leave the GitHub issues area for confirmed bugs.

Thanks
