### ISSUE TITLE
How Come theme options doesn't work "out of the box"?

### ISSUE THREAD

**Issue by andrew-ok7** [WebDevStudios/CMB2#609]
Used this in the past and updated cmb2, but when I use the example code the options do not display in dashboard. I understand that it reads "Will not be added automatically, but needs to be called with * the `cmb2_metabox_form` helper function. See wiki for more info."
But why would you not have a working example? Can't wrap my head around the problem and I looked in wiki for solution but to no avail.

**Comment by jtsternberg** [comment]
I have no idea what you are referring to. Please post your code, or a link for context.

**Comment by andrew-ok7** [comment]
adding this to my theme to create option page:
https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/options-and-settings-pages/theme-options-cmb.php
adds a link in the dashboard, but nothing on the page.


`<?php
/**
 * Include and setup custom metaboxes and fields. (make sure you copy this file to outside the CMB2 directory)
 *
 * Be sure to replace all instances of 'yourprefix_' with your project's prefix.
 * http://nacin.com/2010/05/11/in-wordpress-prefix-everything/
 *
 * @category YourThemeOrPlugin
 * @package  Demo_CMB2
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     https://github.com/WebDevStudios/CMB2
 */

/**
 * Get the bootstrap! If using the plugin from wordpress.org, REMOVE THIS!
 */

if ( file_exists( dirname( __FILE__ ) . '/cmb2/init.php' ) ) {
	require_once dirname( __FILE__ ) . '/cmb2/init.php';
} elseif ( file_exists( dirname( __FILE__ ) . '/CMB2/init.php' ) ) {
	require_once dirname( __FILE__ ) . '/CMB2/init.php';
}

add_action( 'cmb2_admin_init', 'ajtok7_register_theme_options_metabox' );
/**
 * Hook in and register a metabox to handle a theme options page
 */
function ajtok7_register_theme_options_metabox() {

	$option_key = 'ajtok7_theme_options';

	/**
	 * Metabox for an options page. Will not be added automatically, but needs to be called with
	 * the `cmb2_metabox_form` helper function. See wiki for more info.
	 */
	$cmb_options = new_cmb2_box( array(
		'id'      => $option_key . 'page',
		'title'   => __( 'Theme Options Metabox', 'cmb2' ),
		'hookup'  => false, // Do not need the normal user/post hookup
		'show_on' => array(
			// These are important, don't remove
			'key'   => 'options-page',
			'value' => array( $option_key )
		),
	) );

	/**
	 * Options fields ids only need
	 * to be unique within this option group.
	 * Prefix is not needed.
	 */
	$cmb_options->add_field( array(
		'name'    => __( 'Site Background Color', 'cmb2' ),
		'desc'    => __( 'field description (optional)', 'cmb2' ),
		'id'      => 'bg_color',
		'type'    => 'colorpicker',
		'default' => '#ffffff',
	) );

}
`

**Comment by andrew-ok7** [comment]
same problem referenced here: 
https://github.com/WebDevStudios/CMB2-Snippet-Library/issues/21
and here:
https://github.com/WebDevStudios/CMB2/issues/484
and here:
https://github.com/WebDevStudios/CMB2-Snippet-Library/issues/29

**Comment by jtsternberg** [comment]
Are you using the latest version (2.2.1) of CMB2 (or the master branch)?

I am using the latest version, pasted the file in my theme exactly as it's posted, and it works exactly as it should.

**Comment by andrew-ok7** [comment]
I am using version 2.2.1

**Comment by jtsternberg** [comment]
Closing this in favor of https://github.com/WebDevStudios/CMB2-Snippet-Library/issues/29.
