### ISSUE TITLE
REST: Research & determine proper schema

### ISSUE THREAD

**Issue by JPry** [WebDevStudios/CMB2#615]
For CMB2 items in REST, we need an appropriate schema.

Pulled from https://github.com/WebDevStudios/CMB2/issues/107#issuecomment-156175070.

**Comment by JPry** [comment]
Here's a site that describes RESTful naming of routes and resources: http://www.restapitutorial.com/lessons/restfulresourcenaming.html.

**Comment by jtsternberg** [comment]
Done, though It could definitely be improved in the future.
