### ISSUE TITLE
REST: Properly use WP_REST_Request methods

### ISSUE THREAD

**Issue by JPry** [WebDevStudios/CMB2#619]
When working in the REST API, it is expected that an instance of `WP_REST_Request` is available (usually as the variable `$request`). Instead of directly accessing `$_GET`, `$_POST`, etc., the `$request` object methods should be used.

*Pulled from https://github.com/WebDevStudios/CMB2/issues/107#issuecomment-156175070*

**Comment by jtsternberg** [comment]
Done.
