### ISSUE TITLE
Including CMB2 in my plugin

### ISSUE THREAD

**Issue by spwebguy** [WebDevStudios/CMB2#624]
Hi there,

I'd like to **include CMB2 in my plugin**. I will add this plugin to the WordPress directory so here is a question for you:

> Should I add the CMB2 files directly to my plugin folder or use something like the _TGM activation class_ to "require" it instead?

I'm asking this because including CMB2 directly will cause my plugin to have **two headers**, which is not going to work when uploading it to the directory. The only way I could do this would be to _remove_ CMB2's header, which is not a good idea in my opinion.

I'd like your opinion on this.

Thank you!

**Comment by jtsternberg** [comment]
Think the best bet for plugins in the repo is to use TGM.

**Comment by jirayu16563** [comment]
I'd prefer to use TGM over bundle CMB into my plugin

**Comment by spwebguy** [comment]
Hi both,

That's what I did. It's cleaner, easier, lighter and the users are getting the CMB2 updates as you release them. My plugins are up to date so there's no risk of compatibility issue or anything.

Thank you! Keep up the great work.
