### ISSUE TITLE
Term metabox priority

### ISSUE THREAD

**Issue by phh** [WebDevStudios/CMB2#626]
Hi there,

It seems like the term metabox priority is pretty high (or late) so the metabox will be output after other plugins that adds their own metaboxes. Is is possible to control when a metabox should be output? Posts metaboxes do have the 'context' where the term metaboxes does not.

**Comment by jtsternberg** [comment]
Set the 'priority' param on the metabox array sent to new_cmb2_box to something lower (maybe 5?)

**Comment by phh** [comment]
Priority works for metaboxes registered on {$taxonomy}_edit_form but older plugins would have used the {$taxonomy}_edit_form_fields hook. I didn't know there was a difference until now but using the _edit_form seems like a way better idea.

Thank you.
