### ISSUE TITLE
Theme Options Page with Submenus

### ISSUE THREAD

**Issue by gorirrajoe** [WebDevStudios/CMB2#627]
Was wondering if there was a clean way to make a theme options page with multiple submenus?

I'm guessing it would be based off of this code: https://github.com/WebDevStudios/CMB2-Snippet-Library/tree/master/options-and-settings-pages

I'm currently trying to hack my way through that code...

**Comment by rianbotha** [comment]
This might be what you're looking for http://arushad.org/how-to-create-a-tabbed-options-page-for-your-wordpress-theme-using-cmb/

**Comment by gorirrajoe** [comment]
not quite. i'm looking for submenus, not tabs.

**Comment by rianbotha** [comment]
The tabs are listed as submenu items in the admin menu too. If that is what you want then removing the tabs and only retaining the menu items should be fairly simple.

**Comment by gorirrajoe** [comment]
i wanted it more like this:

https://cloudup.com/c7ihI7yUO1q

independent pages so i can break menus up into years

**Comment by rianbotha** [comment]
It does that. See screenshot attached.
![menu](https://cloud.githubusercontent.com/assets/11853275/14434022/1192b5b2-0011-11e6-8b35-d17233366eb1.jpg)

It follows the normal Wordpress convention. Flyout menu until you are in the section and then it expands as in example.

The tabbed part is separate and you can eliminate that without losing the menu part.

**Comment by rianbotha** [comment]
You would just need to remove line 101 to prevent the tab links from being created.

**Comment by gorirrajoe** [comment]
oh interesting -- i'll look into this and close after i test!
thanks!!

**Comment by tw2113** [comment]
Any update with this one @gorirrajoe ?

**Comment by gorirrajoe** [comment]
my bad... i'll test this out soon.

**Comment by gorirrajoe** [comment]
boom -- yea that's exactly what i was looking for. thanks!

**Comment by vucumbra** [comment]
how..... get a subbage and subsection??

**Comment by tw2113** [comment]
@vucumbra I'd look over the tutorial provided at https://github.com/CMB2/CMB2/issues/627#issuecomment-208409965

**Comment by jtsternberg** [comment]
#301 is Somewhat related, and this snippet in particular: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/options-pages-with-submenus.php

**Comment by jtsternberg** [comment]
Doing submenu pages with tabbed navigation snippet can be found here: https://github.com/CMB2/CMB2-Snippet-Library/blob/master/options-and-settings-pages/options-pages-with-tabs-and-submenus.php
