### ISSUE TITLE
Select Checkbox should show products

### ISSUE THREAD

**Issue by elbsurfer** [WebDevStudios/CMB2#628]
Hello,
I am looking for a possibility to add a select box as a meta box and the contents of the select box should be the products which I have added to my WooCommerce shop. 

Is there any possibility? I think of something like this:

```
	$cmb->add_field( array(
	    'name'     => 'Product #1',
	    'desc'     => 'The first product to be shown',
	    'id'       =>  'shop_box_one',
	    'post_type' => 'product',
	    'type'     => 'taxonomy_select',
	) );
```

**Comment by elbsurfer** [comment]
Found it:
https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types

Example 3.

**Comment by fakeartist** [comment]
Hi @elbsurfer, I want to do the exact same thing, but the example 3 you mention, seems to be missing from the page. Could you please tell me how you did it? Thanks

**Comment by elbsurfer** [comment]
@fakeartist I checked several projects that I did at that time, but I can not find the project where I used it. Sorry.

**Comment by tw2113** [comment]
Not easily finding an "Example 3" from the wiki page history either, sadly.

**Comment by fakeartist** [comment]
Ok, just found a solution! First, download and install the [select2 plugin](https://github.com/mustardBees/cmb-field-select2). Then, you can use this code:

`$single_post_metaboxes->add_field(array(
        'name' => __('Select products', 'cmb2'),
        'id' => $prefix . 'products',
        'type' => 'pw_multiselect',
        'options' => get_products(array('post_type' => 'product')),
    ));

function get_products($query_args = array()) {
    $defaults = array(
        'posts_per_page' => -1
    );
    $query = new WP_Query(array_replace_recursive($defaults, $query_args));
    return wp_list_pluck($query->get_posts(), 'post_title', 'ID');
}`
