### ISSUE TITLE
Bugs with taxonomies

### ISSUE THREAD

**Issue by EmilEriksen** [WebDevStudios/CMB2#629]
While working with a metabox that would show on both pages, posts and a couple of terms, I discovered a few bugs.

If you set object_types to an array of `array( 'page', 'post', 'term' )` the metabox will not show on the taxonomy pages. "term" has to be the only object type.

If object_types is defined as `'object_type' => 'term'` the metabox will show on the taxonomy page but will not save. It has to be defined as `array( 'term' )`.

For anyone interested, I got around the first issue the following way:

```
global $pagenow;

$object_types = array( 'page', 'post' );

if ( 'term.php' === $pagenow || 'edit-tags.php' === $pagenow ) {
	$object_types = array( 'term' );
}
```

**Comment by jtsternberg** [comment]
Thanks for reporting this issue! It should be fixed in the `trunk` branch, and will be in the next release.
