### ISSUE TITLE
Can't Change Text of Add/Remove Buttons for Repeatable Select List

### ISSUE THREAD

**Issue by brandondove** [WebDevStudios/CMB2#630]
WordPress Version 4.5
CMB2 Version 2.2.1

When registering a select list as a repeatable field, changing the add/remove button text adds the button text as an option to the select list because you have to change the text in the options argument which is where the options for the select list live.

Here's a gist showing the issue: https://gist.github.com/brandondove/5e72f7497bbb01a6c1962c9d3846827e

Here's a screenshot of the result:
<img width="1440" alt="screen shot 2016-04-18 at 5 14 14 pm" src="https://cloud.githubusercontent.com/assets/300348/14624940/b9d8ae34-0593-11e6-9eba-f9b59fa00e9a.png">

**Comment by jtsternberg** [comment]
Yep, that was definitely a bug. The text overrides should not be mashed up w/ the option values, so I've created a `'text'`/`'text_cb'` parameter which is used exclusively for text strings. It will fall back to the options value only for back-compatibility. This will be in the next release, but you can use the `trunk` branch for testing.

**Comment by brandondove** [comment]
:+1: I'll give that a try.

**Comment by tw2113** [comment]
Any success with this one @brandondove so we could confirm it and close the issue?

**Comment by brandondove** [comment]
@tw2113 Just tested this and it looks good.

**Comment by tw2113** [comment]
Cool, thanks for the feedback.
