### ISSUE TITLE
How can I update all rows in a new domain configuration? Been having problems due to cmb2 serialization of objects.

### ISSUE THREAD

**Issue by goncalomarques** [WebDevStudios/CMB2#631]
I need to deploy my website to production. In the stage server, where final content is already in the database, custom metaboxes URL's are serialized and I can't replace the old website domain with the new one with a simple replace due to the serialized string format. 

How can I do this automatically? 

Why did you decide to serialize it storing the string length? Shouldn't this be stored in more accessible and easily editable JSON file? If so, do you want me to make a pull request?

**Comment by carasmo** [comment]
I use:

https://christinacreativedesign.com/fast-and-free-wordpress-database-migration-without-losing-serialized-data/

https://interconnectit.com/products/search-and-replace-for-wordpress-databases/

Very easy. Takes a few min.

**Comment by jtsternberg** [comment]
@goncalomarques I didn't 'decide' to store serialized, that is the default way WordPress meta apis work with non-scalar values. Even if we changed it for CMB2, you would still have migration issues w/ other plugins/meta/widgets/etc. I suggest using @carasmo's solution.
