### ISSUE TITLE
How can replace the text button. Image attached!

### ISSUE THREAD

**Issue by iiandrade** [WebDevStudios/CMB2#632]
There is a possibility to change the button text of file uploads windows? How can I do it?

![file](https://cloud.githubusercontent.com/assets/8454560/14651048/9a0b4c4a-0644-11e6-89dd-2dd115cc54f6.jpg)

I know that giving to applying filters. But there is a simpler way?

It would be great if we could change this type of text too!
Regards to all, here in Brazil.

**Comment by tnorthcutt** [comment]
You would need to use the `cmb2_localized_data` filter to change that text.
