### ISSUE TITLE
Featured image for Custom Post Type taxonomy

### ISSUE THREAD

**Issue by jry8412** [WebDevStudios/CMB2#634]
Wondering if there is any option for me to use the Wordpress original featured image upload to set my taxonomy featured image.

Like what WooCommerce does for their category featured image.
<img width="434" alt="screen shot 2016-04-21 at 2 07 27 pm" src="https://cloud.githubusercontent.com/assets/5256988/14699452/769b1c5e-07ca-11e6-8376-a394b135ba80.png">

https://wordpress.org/plugins/woocommerce/

**Comment by jtsternberg** [comment]
Yes, look at the taxonomy metabox example: https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L525-L565
