### ISSUE TITLE
Resources Section: How to add a new resource?

### ISSUE THREAD

**Issue by willthemoor** [WebDevStudios/CMB2#635]
I've updated @hasinhayder's handy [metabox generator](https://github.com/hasinhayder/cmb2-metabox-generator) with a couple of features others might find useful. I've opened a pull request on the original but haven't heard back in months. Presuming it's actually useful to others, do I open a pull request with an edit to the CMB2 readme to suggest it as a resource? 

Main new features are automatic field-id guessing ("My Field") becomes `'id' => 'my-field'`, the ability to bulk add fields via a text box instead of clicking though the UI (super speedy!) and support for `group` fields (which also work via bulk entry). 

**Bulk entry example**
(`--` denotes the subfield of a group)

```
Area Copy; textarea
Area Logo; file
Projects; group
--Project Title; text
--Project Copy; textarea
``` 

will generate the all of the form rows within the generator that you normally create by hand allowing you to adjust it. Without adjusting anything, 'generate code' will output:

```php
    // Snipped boilerplate for example
    $cmb->add_field( array(
		'name' => __( 'Area Copy', 'cmb2' ),
		'id' => $prefix . 'area_copy',
		'type' => 'textarea',
	) );

	$cmb->add_field( array(
		'name' => __( 'Area Logo', 'cmb2' ),
		'id' => $prefix . 'area_logo',
		'type' => 'file',
	) );

	$projects = $cmb->add_field( array(
		'name' => __( 'Projects', 'cmb2' ),
		'id' => $prefix . 'projects',
		'type' => 'group',
	) );

		$cmb->add_group_field( $projects, array(
			'name' => __( 'Project Title', 'cmb2' ),
			'id' => $prefix . 'project_title',
			'type' => 'text',
		) );

		$cmb->add_group_field( $projects, array(
			'name' => __( 'Project Copy', 'cmb2' ),
			'id' => $prefix . 'project_copy',
			'type' => 'textarea',
		) );
```

Demo:  http://willthemoor.github.io/cmb2-metabox-generator/
More details in the readme:  https://github.com/willthemoor/cmb2-metabox-generator

**Comment by jtsternberg** [comment]
That's pretty sweet. Have you considered/attempted a pull request to the original?
Also, a nice option would be one-click button to create a full example using [example-functions.php](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php).

**Comment by willthemoor** [comment]
Thanks. Think the next thing I'd like to add is some HTML boilerplate output a user can stuff into a WP template in order to get the fields printed to the screen quickly.
