### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by jrfnl** [WebDevStudios/CMB2#636]
Looks like there's something wrong with the Travis setup as for PRs against `trunk`, the `.travis.yml` file from `master` is being used...

See this PR: https://github.com/WebDevStudios/CMB2/pull/582 versus the Travis output: https://travis-ci.org/WebDevStudios/CMB2/builds/124999634

**Comment by tnorthcutt** [comment]
Seems to be resolved – checks are passing on that PR now. @jrfnl if I'm misunderstanding the situation, please re-open 😄 .
