### ISSUE TITLE
Examples of how to use 'row_classes'

### ISSUE THREAD

**Issue by stabilimenta** [WebDevStudios/CMB2#639]
Can you show some examples of how to use 'row_classes' to group some fields into a single row?
Beautiful work on CMB2. I love it.
Thanks!

**Comment by stabilimenta** [comment]
I understand how I could use 'before_row' and 'after_row' to add wrappers and then use a lot of css, but I am hoping there is a better way. I'm trying to get a Dimensions section which will have separate fields for "width", "height" & "depth", all in single row.

**Comment by jtsternberg** [comment]
You'll either need to use a lot of css/wrappers, or create a custom field type akin to the 'address' field type: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types#example-4-multiple-inputs-one-field-lets-create-an-address-field

**Comment by stabilimenta** [comment]
OK. I got it set up using css and a combination of before/after and row_classes. Thanks!
