### ISSUE TITLE
Consider integration tests for your WP REST API endpoints

### ISSUE THREAD

**Issue by danielbachhuber** [WebDevStudios/CMB2#642]
Hi!

On behalf of [Pantheon](https://pantheon.io/), I'm [writing a tutorial](https://paper.dropbox.com/doc/You-absolutely-need-test-coverage-for-your-WP-REST-API-project-MKvKy9DzoTQ2HYhbyWBxM) on why integration tests are critical for your WP REST API endpoints, and how you can go about writing them. 

Given your use of `register_rest_field()`, I think you could benefit from reading and applying the tutorial. And, because the tutorial isn't yet published, I'd very much appreciate any constructive criticism you have, so that we can make the tutorial an evergreen resource for the community.

Thanks in advance for your time. Happy to take any questions, comments, etc. you might have in this Github issue, or on the document itself (you'll need to be signed into Dropbox).

**Comment by eriktelepovsky** [comment]
Great idea. +1

**Comment by jtsternberg** [comment]
Complete, https://github.com/WebDevStudios/CMB2/blob/cmb2-rest-api/tests/test-cmb-rest-controllers.php, https://github.com/WebDevStudios/CMB2/blob/cmb2-rest-api/tests/test-cmb-rest-registered-fields.php, and https://github.com/WebDevStudios/CMB2/blob/cmb2-rest-api/tests/test-cmb-rest.php
