### ISSUE TITLE
object_id returning wrong value for existing user

### ISSUE THREAD

**Issue by Kudratullah** [WebDevStudios/CMB2#643]
in my current project i embed in theme folder. and the issue is: cmb2 metabox form getting wrong object_id for user edit form, so it's can't display the meta values stored in database.
[here is a sample](https://gist.github.com/Kudratullah/75c6aeac28b3c5b03478fbf908a617c4l) of my codes for user metaboxes.
after debugging i found that cmb getting wrong object_id for user edit form, eventually i found that its getting the value of `$GLOBALS['post']->ID`

**Comment by widoz** [comment]
@Kudratullah The gist is a 404.

**Comment by Kudratullah** [comment]
@widoz sorry i updated that. here is new link https://gist.github.com/Kudratullah/75c6aeac28b3c5b03478fbf908a617c4

**Comment by jtsternberg** [comment]
There is no reason that should happen, and it's working as expected for me. I would need to know more. Is this a fresh install? Have you tried deactivating other plugins?

**Comment by Kudratullah** [comment]
thanks for your reply. changing `add_action` priority fixes this for me.
