### ISSUE TITLE
Can't add user metaboxes to an MU site?

### ISSUE THREAD

**Issue by gorirrajoe** [WebDevStudios/CMB2#644]
I'm trying to add metaboxes to the user profile screen, but it doesn't seem to work for MU sites? I don't know why this would be an issue, but when I add the code to a non-MU site, it works perfectly fine.

I even tried it with the [example code from here](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L454-L524)

Anyone else experience this?

**Comment by tw2113** [comment]
Hey @gorirrajoe do you think you could start a thread over at https://wordpress.org/support/plugin/cmb2 for this issue? If you could also provide the code you're using for this, that would help expedite the debugging process. Thanks.
