### ISSUE TITLE
Taxonomy_select in front end ?

### ISSUE THREAD

**Issue by fredericgalline** [WebDevStudios/CMB2#645]
Hi,  (sorry for my english I'm french)

All _**field type**_ work fine for me except "taxonomy" : radio, select ...Etc
If I use the field type "taxonomy_select" in the backend, it's working fine  👍 

> $cmb->add_field( array(
> 		'name'     => __( 'Secteur d\'activité', 'cmb2' ),
> 		//'desc'     => __( 'Quel est le secteur', 'cmb2' ),
> 		'id'       => $prefix . 'enseigne_secteur',
> 		'type'     => 'taxonomy_select',
> 		'taxonomy' => 'secteur', // Taxonomy Slug
> 		'attributes' => array(
> 			'required' => 'required',
> 		)
> 	) );

But if I use the same in front end, it's not saved : 
> $cmb->add_field( array(
> 		'name'     => __( 'Secteur d\'activité', 'cmb2' ),
> 		//'desc'     => __( 'Quel est le secteur', 'cmb2' ),
> 		'id'       => 'enseigne_secteur',
> 		'type'     => 'taxonomy_select',
> 		'taxonomy' => 'secteur', // Taxonomy Slug
> 		'attributes' => array(
> 			'required' => 'required',
> 		)
> 	) );

Perhaps could you help me ?

thx a lot

**Comment by tw2113** [comment]
Hey @fredericgalline do you think you could start a forum thread over at https://wordpress.org/support/plugin/cmb2 for this, and we'll get it looked at there first? Thanks
