### ISSUE TITLE
Using Repeatable Group Field with meta_query?

### ISSUE THREAD

**Issue by contempoinc** [WebDevStudios/CMB2#650]
I'm using a repeatable group of fields for a "multi floor plan" feature in my theme (screenshot http://cl.ly/13231S1I3N2I) and that group includes a Price field now my question is how can I use those fields within a meta_query() the problem comes into play when trying to use _ct_multiplan[0][_ct_plan_price] as the key it doesn't recognize it since its stored within an array (code screenshot http://cl.ly/3C0v243g2o2x), is there a way to convert that to something usable like plan_1_price or plan_2_price which works perfectly within the query by adding multiple price fields via ACF for testing purposes.

**Comment by tw2113** [comment]
Trying to figure out where the lines 110-111 are coming from, and how you're getting that for a meta key. The biggest question would be what does the key look like in the actual meta table for some example values you're trying to fetch prices for. With some more information, we can better answer the question.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
