### ISSUE TITLE
Changes in 4.6 (WP_Term_Query) cause errors

### ISSUE THREAD

**Issue by Ipstenu** [WebDevStudios/CMB2#653]
When using CMB2 everything shows fine on the front end, but when I go to look at my post editor (where I show a custom taxonomy multicheck) I get errors

Warning: Illegal string offset 'taxonomy' in /Users/ipstenu/Documents/Websites/lezwatchtv.dev/wp-includes/taxonomy.php on line 1192

Notice: Array to string conversion in /Users/ipstenu/Documents/Websites/lezwatchtv.dev/wp-includes/taxonomy.php on line 1192

And then ALL the taxonomies show in one big fugly section.

The tax grab is the very basic:

```
	$cmb_showdetails->add_field( array(
	    'name'     => 'Cliché Plotlines',
	    'id'       => $prefix . 'cliches',
		'taxonomy' => 'lez_cliches', //Enter Taxonomy Slug
		'type'     => 'taxonomy_multicheck',
		'select_all_button' => false,
	) );
```

I'm pretty sure this is all related to https://core.trac.wordpress.org/changeset/37572

**Comment by jrfnl** [comment]
I'd wager a guess it has to do with the change in 4.5 mentioned here: https://developer.wordpress.org/reference/functions/get_terms/

While this could of course be solved in CMB2, I believe this should be solved in core as this is a big backwards compatibility break..
It looks like they are trying ro detect legacy arguments and correct them with incorrect results. So my tentative conclusion would be that the change in the arguments for `get_terms()` is not properly accounted for in the WP core.

**Comment by Ipstenu** [comment]
FWIW, nothing is broken in 4.5 which is why I pointed at 4.6 (and in fact, everything was fine in 4.6 until May 26th, which is why that changeset caught my eye).

**Comment by jrfnl** [comment]
And you're right about that - that changeset changes something in how the deprecated argument is being handled, so could well be the culprit.

**Comment by jtsternberg** [comment]
Ugh, [that change](https://developer.wordpress.org/reference/functions/get_terms/) is pretty annoying, as it requires every thing ever that's using `get_terms` to write a compatibility shim for older versions of WP. :(

**Comment by jtsternberg** [comment]
@Ipstenu can you test on trunk?

**Comment by Ipstenu** [comment]
I'm not sure if it's an accident on core's part and needs a poke by people who actually understand what the heck happened (it also broke StudioPress' Genesis theme and I'm sure a hundred little plugins).

WP Core - 4.6-alpha-37590)
CMB2 - Trunk

It works without any errors.

**Comment by jtsternberg** [comment]
👍

**Comment by jtsternberg** [comment]
Thanks for reporting @Ipstenu. For those following this convo, @boonebgorges is on it: https://core.trac.wordpress.org/ticket/35381#comment:22

**Comment by jrfnl** [comment]
Looks like the fix has been committed to core: https://core.trac.wordpress.org/changeset/37599
