### ISSUE TITLE
"file" thumbnail size?

### ISSUE THREAD

**Issue by ruturaaj** [WebDevStudios/CMB2#654]
Hello,

I wish to know if there is any way that will allow me to set the thumbnail size for "file" field. I checked the documentation and didn't find any attribute to set height/width for the thumbnail; or am I missing something?

Thanks!

Ruturaaj.

**Comment by jtsternberg** [comment]
On the front or backend? For the field file preview size, you can use the `preview_size` parameter: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#custom-field-attributes-5
```php
'preview_size' => array( 100, 100 ),
```

**Comment by ruturaaj** [comment]
on both front as well as backend. Thanks so much for your quick reply. I will try it out right now...

**Comment by jtsternberg** [comment]
Well, the wiki also has documentation for how to get it on the front-end: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#css-field-class-28

**Comment by ruturaaj** [comment]
YES! It worked. :+1:  I thought it's only applicable for file_list.

**Comment by noim015** [comment]
Would you please tell me how to add the image size for front end ?
It worked on back end very much well but i can not fix the front end .
Thanks

**Comment by tw2113** [comment]
Should be handled the same way, if I'm not mistaken, which is at the point of setting up the field.

**Comment by noim015** [comment]
I used 'preview_size' => array(100,100), for back end but I want to fix the size of front end side.
But it is not working.
If you know how to fix it then please let me know .
Thank in advance.

**Comment by tw2113** [comment]
What aspect isn't working? The resulting image sizes? Is this a new image size that you just added? Are you using freshly uploaded images or are you trying with images that already existed in your library? It's possible that an image at the intended size doesn't exist yet and thumbnail regeneration may be needed.

Also if you could provide all the code you're using to set things up, we can try things out on our end, as necessary.

**Comment by noim015** [comment]
Thank You for your reply.
I fixed it couple hours ago after all thank you.

**Comment by tw2113** [comment]
Welcome, and glad you got things figured out.

**Comment by pawel-kieryk** [comment]
Hi, I need to require to upload only 100x100 images, but I don't know where I can require image size. Can you help me?

**Comment by tw2113** [comment]
I don't know offhand of any potential way to limit the dimensions of the upload, but if you have a 100x100 image size registered, you can use the attachment ID that gets saved as part of the post meta to make sure to force-display that image size once you hit the frontend with your display code
