### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by marjwyatt** [WebDevStudios/CMB2#659]
I have been using Custom Metaboxes and Fields for WordPress for many years, perhaps since it was launched.  In an effort to continue to use maintained code on new projects, I just reviewed the folder structure for the old versus the new.

My first question is, why did you alter the structure so?

I tried a quick test of the functionality by loading the new code into the mu-plugins area where I have another script that defines custom metaboxes and taxonomies.  This was code that worked perfectly with the old version of the CMB.

My method for testing was to load your newer code into the lib folder of mu-plugins.  I then replicated the script I used to define metaboxes and taxonomies, changing the reference for the init.php to the new folder where CMB2 is.  None of my custom metaboxes were available on posts, pages, or custom post types.

The CMB software used a filter to create the metaboxes.  This is the statement at the end of my custom metabox script:
`add_filter( 'cmb_meta_boxes' , 'vm_metaboxes' ); `

What would be the equivalent filter for CMB2?

I am a WordPress Developer.  If your software cannot be used without adding the plugin from WordPress.org, please let me know that because what I have been using and incorporating into my custom themes has worked very well for me without having to add another plugin to the mix.

**Comment by jtsternberg** [comment]
The answers to most of your questions can be found in either the [project readme](https://github.com/WebDevStudios/CMB2/blob/master/readme.md), the [project wiki](https://github.com/WebDevStudios/CMB2/wiki), or the provided [example-functions.php](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php) file. 

> What would be the equivalent filter for CMB2?

Best bet would be to follow the example in [example-functions.php] and use the box/field registration methods, but `'cmb2_meta_boxes'` [filter exists](https://github.com/WebDevStudios/CMB2/blob/master/bootstrap.php#L35-L43) for back-compatibility purposes. Generally speaking, any `'cmb_*'` filters will now be named `'cmb2_*'`.

> If your software cannot be used without adding the plugin from WordPress.org, please let me know...

I would review the [wiki documentation](https://github.com/WebDevStudios/CMB2/wiki/Basic-Usage).

**Comment by marjwyatt** [comment]
I had reviewed example-functions.php, the project readme an the project wiki, as well as the wiki documentation before posting my inquiry.

Simply put, I won't be installing the plugin from WordPress.org.  

This is the code that works perfectly with the old version, albeit revised to call CMB2 from it's location in the wp-content folder for my starter theme.
http://pastebin.com/advhBvgC

The metaboxes just don't show up with the new code and the whole reason I place this in mu-plugins is to avoid muddying the theme functions.php with code and allow for custom fields and metaboxes to continue to work properly when the theme is switched.

**Comment by marjwyatt** [comment]
Here are screenshots showing custom metaboxes with old code

page metaboxes
http://screencast.com/t/ZKcXcrR1

post metaboxes
http://screencast.com/t/7kOYCUHBPEt

**Comment by jtsternberg** [comment]
1. Lines 163-167 of your snippet should be outside of any hook. `'init'` is too late. 
2. If you don't plan on using the updated box/field registration API (i.e `new_cmb2_box` function to create your metabox object, and then create the fields with `add_field`), then you should not be using the `'cmb2_admin_init'` hook, but the `'cmb2_meta_boxes'` filter instead.
3. `'pages' => array('page'),` should be `'object_types' => array('page'),`

**Comment by marjwyatt** [comment]
Sorry to take so long getting back to you.
Thank you for your response.

The problem I'm having, comparing the old example-functions.php to the one in this version is that your examples-functions.php doesn't make it clear, to me, how combine metaboxes into groups for custom post types or taxonomies.  Is there a reason for this?  What are the benefits to using CMB2?

I don't mean to sound like a whiner but the original code is working with the latest version of WordPress.  I've tried everything you've suggested above and the result is a complete fail.

I'm tired.  It's been a long couple of weeks.  I'll try it again with fresh eyes over the weekend but if you could at least summarize what the benefits you folks had in mind before completely rewriting the plugin, I'd be interested to hear that.

**Comment by jtsternberg** [comment]
Feel free to use the old version if you're happy with it. [Blog post on the change](https://webdevstudios.com/2015/02/02/cmb2-wordpress-plugin/).
