### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by johnsonpaul1014** [WebDevStudios/CMB2#661]
I have been trying to submit a pull request, but it keeps failing the builds.  It doesn't appear that anything I did should have affected the failing tests.  I did fix some code in the tests that was failing due to a timezone problem, but I'm not sure why this wasn't failing before.  I'm probably just misunderstanding something.  Any help would be appreciated.

**Comment by bradp** [comment]
Do tests fail if you run them locally?

**Comment by johnsonpaul1014** [comment]
Thanks for the reply.

I was able to get the default Grunt task to run once I changed the time zone test.  However the Ajax tests failed in the continuous integration build.  I don't think my code should have affected either of these things, so I wanted to make sure I'm not missing something.  The code I wrote only applies to the WYSIWYG editors created for groups.

Paul

**Comment by johnsonpaul1014** [comment]
This was not in issue when I did a pull request against trunk like I was supposed to.
