### ISSUE TITLE
Field type: Taxonomy select

### ISSUE THREAD

**Issue by ingozoell** [WebDevStudios/CMB2#665]
Hi,

I´d like to use the taxonomy select field with a custom post type "expose" with the taxonomy "object".

I can choose the taxonomy in backend, but can't echo the value in my template.

### functions.php
```
...	
$cmb->add_field( array(
		'name' => __( 'Objektart', 'cmb2' ),
		'id' => $prefix . 'expose_objektbeschreibung_objektarten',
		'taxonomy' => 'objektarten',
		'type'     => 'taxonomy_select',
		'row_classes' => 'col-md-3',
	) );
...	
```

### Template
```
<?php
$expose_objektbeschreibung_objektarten = get_post_meta( get_the_ID(), '_cmb_expose_objektbeschreibung_objektarten', true );
echo $expose_objektbeschreibung_objektarten; 
?>
```

Thanks for your help.

**Comment by jtsternberg** [comment]
See response here: https://wordpress.org/support/topic/field-type-taxonomy-select?replies=3#post-8527781
