### ISSUE TITLE
show_on for WDS Page Builder

### ISSUE THREAD

**Issue by ingageco** [WebDevStudios/CMB2#667]
Hey guys - not sure if this exists or not, but didn't see it on either repo. 

Is there a way to link show_on in a CMB2 box to the WDS page builder? As in, if "Hero" page builder section is being included, the cmb2 options for that area then appear on the edit screen. 

Is that currently possible with the two plugins together?

**Comment by tw2113** [comment]
@jazzsequence Pinging you for this one as it's your name on the .org repo for https://wordpress.org/plugins/wds-simple-page-builder/

Any thoughts on @ingageco's thoughts/request?

**Comment by bradp** [comment]
Closing due to no movement here, and is better suited for an issue over on Simple Page Builder. Feel free to re-open if needed.
