### ISSUE TITLE
The Custom Field Attributes 'text' for the file field type does not work

### ISSUE THREAD

**Issue by twoelevenjay** [WebDevStudios/CMB2#670]
As referenced here: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#file

```
$cmb->add_field( array(
    'name'    => 'Test File',
    'desc'    => 'Upload an image or enter an URL.',
    'id'      => 'wiki_test_image',
    'type'    => 'file',
    // Optional:
    'options' => array(
        'url' => false, // Hide the text input for the url
    ),
    'text'    => array(
        'add_upload_file_text' => 'Add File' // Change upload button text. Default: "Add or Upload File"
    ),
) );
```

Does not work. After looking through the code I found that if you move `add_upload_file_text` into the `options` array then it does work. Like this:

```
$cmb->add_field( array(
    'name'    => 'Test File',
    'desc'    => 'Upload an image or enter an URL.',
    'id'      => 'wiki_test_image',
    'type'    => 'file',
    // Optional:
    'options' => array(
        'url' => false, // Hide the text input for the url
        'add_upload_file_text' => 'Add File' // Change upload button text. Default: "Add or Upload File"
    ),
) );
```

Because on line `945` of `/include/CMB2_Types.php` it uses `CMB2_Types::_text()` which uses `CMB2_Fields::get_options()`.

For some reason this fix does not work for `file_list`, although it uses the same function `_text( 'add_upload_file_text', __( 'Add or Upload File', 'cmb2' ) ` to check for the argument.

In addition to this I do not see any code that would suggest `file_list` would obey the other `text` parameters.

I am having trouble deciding what type of pull request to submit.

Should I make the fields work like the docs suggest, or should I make them work like `file` is kind of already working using `options` and then change the docs too?

**Comment by twoelevenjay** [comment]
I found a similar issue with `taxonomy_multicheck` and `no_terms_text`:

```
$cmb->add_field( array(
    'name'      => 'Test Taxonomy Multicheck',
    'desc'      => 'Description Goes Here',
    'id'        => 'wiki_test_taxonomy_multicheck',
    'taxonomy'  => '', //Enter Taxonomy Slug
    'type'      => 'taxonomy_multicheck',
    // Optional :
    'text'      => array(
        'no_terms_text' => 'Sorry, no terms could be found.' // Change default text. Default: "No terms"
    ),
) );
```
Does not work and:

```
$cmb->add_field( array(
    'name'      => 'Test Taxonomy Multicheck',
    'desc'      => 'Description Goes Here',
    'id'        => 'wiki_test_taxonomy_multicheck',
    'taxonomy'  => '', //Enter Taxonomy Slug
    'type'      => 'taxonomy_multicheck',
    // Optional :
    'options'      => array(
        'no_terms_text' => 'Sorry, no terms could be found.' // Change default text. Default: "No terms"
    ),
) );
```
does work.

**Comment by jtsternberg** [comment]
Apologies, I have a bad habit of updating the wiki with the changes that are in trunk (not yet released). I plan on pushing the next release tonight, so the wiki will be correct shortly.

**Comment by twoelevenjay** [comment]
@jtsternberg thanks, no need to apologize :-)

Yeah after finding the `master` method in:
https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#override-text-strings-in-field

I realized that `trunk` and `master` may have a good amount of differences. I have been working on the Admin Extension, and that I test with the CMB2 WP plugin. Will tonights release be pushed to teh wordpress.org repo too?

I read your post about the whole "libraries in the plugin repo", and I am not too thrilled about that either :-( My first and only wordpress.org plugin is built around the CMB2 library being available in the repo!

**Comment by jtsternberg** [comment]
I pushed the release today, and it's also on wordpress.org.

**Comment by twoelevenjay** [comment]
Ok, thank you. I will update CMB2 Admin Extension to work with the new plugin and have some BC.
