### ISSUE TITLE
'column' field parameter not working with grouped fields

### ISSUE THREAD

**Issue by noquierouser** [WebDevStudios/CMB2#671]
I'm testing the new `column` field parameter in a development, and I see that fields inside a group are not showing in post columns.

**Comment by jtsternberg** [comment]
That's correct. If you want group fields to display in the admin column, you'll have to define your own [`'display_cb'](https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#display_cb)`. It would be impossible to normalize the display of a grouped field in a small post column, so you're on your own if you decide that is necessary.
