### ISSUE TITLE
Meta boxes not showed for author role

### ISSUE THREAD

**Issue by sorchiapone** [WebDevStudios/CMB2#681]
Hello,
it looks like that the meta boxes show up only if the user is at least an editor. No show for authors, even if I haven't defined any "show_on" parameter and haven't changed the default capabilities in Wordpress.
It's not a screen settings matter: the boxes are simply not showed.
Please, has anyone experience of this issue?
Many thanks.

**Comment by tw2113** [comment]
hey @sorchiapone could you start a forum thread over at https://wordpress.org/support/plugin/cmb2 for this one? I'm not managing to recreate the issue at all, but would love to try and see if I can with your metabox code instead of whatever I happen to have handy with my testing of things. Thanks
