### ISSUE TITLE
Select field will not save option value if that value contains apostrophe

### ISSUE THREAD

**Issue by brandondove** [WebDevStudios/CMB2#686]
When an option in a select list contains an apostrophe, the selected value is not saved. I have tested this in a standard select list, repeatable select list, and a select list nested in a group field. The outcome is the same across the board. My example below is silly, but when considering a country select list, apostrophes become an issue (i.e. `Cote d&#39;Ivoire`, `Korea, Democratic People's Republic of`).

Example:
```
<?php
require_once( 'lib/cmb2/init.php' );
add_action( 'cmb2_admin_init', 'reps_only_meta_fields' );
function reps_only_meta_fields() {
	$cmb_user = new_cmb2_box( array(
		'id'               => 'user-edit-it',
		'title'            => __( 'Custom Info' ),
		'object_types'     => array( 'user' ),
		'show_names'       => TRUE,
		'new_user_section' => 'none',
	) );

	$cmb_user->add_field( array(
		'name'               => __( 'State' ),
		'id'                 => 'state',
		'type'               => 'select',
		'show_option_none'   => true,
		'options'            => array( 'co\'ol' => 'cool', 'awe&#39;some' => 'awesome' ),
		'desc'               => __( 'Select state of mind.' )
	) );
}
```

**Comment by tw2113** [comment]
Early status update. The metadata is saving fine, the rendering of the field afterwards appears to be the issue. More coming soon.

**Comment by tw2113** [comment]
Value being passed through esc_attr().

@brandondove Biggest thing I can see, using your code above is the following:

```
awe&#39;some   // Your provided test value
awe&#039;some  // Returned value from esc_attr() with 'awe\'some'
```

Once I added the 0 to my metabox declaration values, it saved fine and showed as the selected dropdown item.

While it definitely has not been a frequent issue to come up, Brandon is the first one I can recall doing so, not sure what's the best route to take for this.

Easiest that I can think of and have tested is having the user use esc_attr() on their keys when passing into the options param.

```
'options' => array( esc_attr('co\'ol') => 'cool', esc_attr('awe&#039;some') => 'awesome' )
```

If we want to handle it internally, perhaps check for strpos() and escape before processing in the render methods?

**Comment by jtsternberg** [comment]
If it's a sanitization issue, I'd use the `'sanitization_cb'`, and if it's an escaping issue, the `'escape_cb'`. This seems like enough of an edge case that handling the escaping/sanitization on your side is the right way to go.
