### ISSUE TITLE
Allow to specify repeatable row title

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#688]
Currently we only can specify the title of the repeatable group with `{#}` being replaced. It would be way more user friendly to be able to specify the title based on some field value.

Ie., I have a group with fields `item_id` and `item_title`. I would like to be able to specify that I want the header to be `item_title` - that would make it way easier to navigate thru than current `Item 1`, `Item 2` etc.

**Comment by jtsternberg** [comment]
I suggest you use adapt this snippet for yourself: https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/javascript/dynamically-change-group-field-title-from-subfield.php
