### ISSUE TITLE
File fields suddenly throwing fatal errors.

### ISSUE THREAD

**Issue by capscoll** [WebDevStudios/CMB2#690]
Hi, today I've been trying to implement custom render callbacks for text fields (haven't touched file fields at all) and suddenly all file fields started throwing errors like these:
	
`Fatal error: Call to a member function escaped_value() on boolean in /home/xxxxx/public_html/wp/wp-content/plugins/cmb2/includes/types/CMB2_Type_File.php on line 53`

Also, when I try to save a post type:

`Fatal error: Call to a member function save_field() on boolean in /home/xxxxx/public_html/wp/wp-content/plugins/cmb2/includes/CMB2_Sanitize.php on line 400`

What could be causing these errors? I have reverted my custom render functions and the errors are still there. I have no more ideas and I am really desperate right now because I need this fixed ASAP...

**Comment by tw2113** [comment]
Hi @capscoll, if this is still proving to be an issue for you, can you please start a thread over at https://wordpress.org/support/plugin/cmb2, including all relevant code for the metaboxes you're setting up? It'd be greatly appreciated and we can see if we can work through what's going on.
