### ISSUE TITLE
Can't delete group rows in the middle of the group

### ISSUE THREAD

**Issue by jessicashortt** [WebDevStudios/CMB2#691]
I saw this issue was opened a year or two ago but it's happening again where if you delete a row that isn't the last one and update, it'll keep a ghost row there with nothing in it. You can get around this by moving it to the bottom of the group and then deleting it to update.

**Comment by tw2113** [comment]
Can you start a thread over at https://wordpress.org/support/plugin/cmb2 with the applicable code and we'll see if we can recreate/debug there. If confirmed, we'll return here with relevant information for how to potentially fix.
