### ISSUE TITLE
CMB2 Taxonomy Select not saving in database 

### ISSUE THREAD

**Issue by armstrongtom** [WebDevStudios/CMB2#695]
Hi All,

I am trying to display a list of downloads from a custom post type through a specific category ID within a template on different pages.

So far I have created a custom post type, set the fields title and download file(cmb2 metabox). I have created five categories within my 'forms' custom post type.

For the website admin to display certain downloads on specific pages I have created a 'taxonomy_select' drop down field using CMB2, this worked fine on the initial build but once the user changes the desired category no posts will then show.

In a nutshell, it seems that the selection of a new category does not create a new entry within the post_metadata table and I'm not sure why.

Below is all of the relevant code. Any help is greatly appreciated.

Many thanks!

CMB2 metaboxes.php:

```
$meta_boxes['service_default_custom_fields'] = array(
'id' => 'service_default_custom_fields',
'title' => __( 'Service Custom Fields', 'ct' ),
'object_types' => array( 'page', ), // Post type
'show_on' => array( 'key' => 'page-template', 'value' => 'template-service-default.php' ),
'context' => 'normal',
'priority' => 'high',
'show_names' => true, // Show field names on the left
// 'cmb_styles' => false, // false to disable the CMB stylesheet
// 'closed' => true, // Keep the metabox closed by default
'fields' => array(
array(
'name' => 'Downloads Category',
'desc' => 'Select the downloads category.',
'id' => $prefix . 'download_cat',
'taxonomy' => 'form_category', //Enter Taxonomy Slug
'type' => 'taxonomy_select',
),
),
);

Template file:

<?php

$download_category = get_post_meta(get_the_ID(), '_ct_download_cat', true);

?>

<?php
// the query
$args = array(
'post_type' => 'forms_pt',
'orderby'=>'title',
'order'=>'ASC',
'posts_per_page' => 7,
'tax_query' => array(
array(
'taxonomy' => 'form_category',
'field' => 'id',
'terms' => $download_category,
),
),
);
$the_query = new WP_Query( $args ); ?>

<?php if ( $the_query->have_posts() ) : ?>

<!-- pagination here -->

<!-- the loop -->
<?php while ( $the_query->have_posts() ) : $the_query->the_post();

$file = get_post_meta(get_the_ID(),'form_download', true);

?>

"><?php the_title(); ?>
<?php endwhile; ?>
<!-- end of the loop -->

<!-- pagination here -->

<?php wp_reset_postdata(); ?>

<?php else : ?>
<p><?php _e( 'Sorry, no posts matched your criteria.' ); ?></p>
<?php endif; ?>
```

**Comment by tw2113** [comment]
Closing this since we are working on the same one over on the CMB2 forums.

**Comment by DannyCooper** [comment]
For reference I believe this is the relevant thread: https://wordpress.org/support/topic/cmb2-taxonomy-select-not-saving-in-database-1/

**Comment by jtsternberg** [comment]
The taxonomy fields are not intended to provide an arbitrary list of terms to pick from, but are intended to be a replacement for the default taxonomy metaboxes. I.e. they are meant to set the taxonomy terms on an object. Any other use of these types will be hacky and/or buggy. I suggest looking at building a custom field type for this: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post

**Comment by tw2113** [comment]
For what it's worth Justin, we had that thread covered pretty well last month, and it's not really a new issue being brought up, just a cross reference.
