### ISSUE TITLE
Use of deprecated is_taxonomy()

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/CMB2#699]
includes/CMB2_hookup.php line 332.

Suggestion: Switch to taxonomy_exists()

**Comment by jtsternberg** [comment]
I'm afraid you're reporting too soon. `is_taxonomy` is not in use. You should only open issues for bugs that exist outside of trunk, since trunk is fast-moving.

**Comment by tw2113** [comment]
Derp, it existed in my copy from my testing of #593, which wasn't pulled in exactly as is. My bad. :)
