### ISSUE TITLE
Term meta is saved but it doesn't appear in term edit screen later

### ISSUE THREAD

**Issue by taunoha** [WebDevStudios/CMB2#700]
I've run into a problem where the metadata is stored but It doesn't appear in term edit screen later.

``` php
    $oi_catalog = new_cmb2_box( array(
            'id' => $prefix . 'catalog_metabox',
            'title' => esc_attr__('Catalog settings'),
            'object_types' => array('term'),
            'taxonomies' => array('product_category'),
            'context' => 'normal',
            'priority' => 'high',
            'show_names' => true
        )
    );

    $oi_catalog_group_id = $oi_catalog->add_field( array(
            'id'          => '_cmb_catalog_repeat_group',
            'type'        => 'group',
            'options'     => array(
                'group_title'   => __( 'Banner {#}'),
                'add_button'    => __( 'Add banner'),
                'remove_button' => __( 'Remove banner'),
                'closed'    => false,
                'sortable' => false
            )
        )
    );

    $oi_catalog->add_group_field($oi_catalog_group_id, array(
            'name' => 'URL',
            'id'   => 'url',
            'type' => 'text_url'
        )
    );
```

Am I missing something? I'm running WP 4.5.3, CMB2 2.2.2.1

**Comment by tw2113** [comment]
Hey @taunoha can you start a thread for this over at https://wordpress.org/support/plugin/cmb2 and we'll get you taken care of there. If we find it is indeed a bug in CMB2 itself, we'll move the new details back here.

Thanks.

**Comment by rogercoathup** [comment]
We are seeing the same problem -- group fields don't display in term meta after saving

**Comment by jtsternberg** [comment]
As soon as I can duplicate this issue, it's something I can look into. Right now, it would appear to be an environment specific issue. You may want to try the standard "deactivate all other plugins and switch to default theme" to see if that helps narrow down the issue.

**Comment by rogercoathup** [comment]
@jtsternberg -- if you'd like; to help you duplicate -- I can send you our plugin that creates the meta fields (CMB2 is added via composer)... you can activate and hopefully see the same problem.

**Comment by jtsternberg** [comment]
Related: https://wordpress.org/support/topic/term-meta-is-saved-but-it-doesnt-appear-in-term-edit-screen-later/

@rogercoathup and @taunoha if you use [this PR](https://github.com/WebDevStudios/CMB2/issues/763), does it solve it for you?

**Comment by tw2113** [comment]
@rogercoathup for what it's worth, myself, and I believe Justin, aren't sure that it's anything to do with the CMB2 configuration, but some conflict coming from away from CMB2. 

Alternative possibility, perhaps a different version of CMB2 bundled with a different plugin getting loaded first? or even the theme could be doing something like this.

**Comment by rogercoathup** [comment]
@tw2113 -- I've not had chance to try Justin's PR yet.  I'll try to make time later today.

Please see my edit above though -- I've tried with just our plugin that creates the meta, no other plugins active and the 2016 theme (so just the one instance of CMB2), and the repeatable group still fails in that case on a term page (the repeatable group works fine on a post type page, and other types of meta field work on term page ok).

**Comment by tw2113** [comment]
No rush on the PR testing, we understand people have busy schedules.

Noted on the other part, and sounds very much like the setup I was using for https://wordpress.org/support/topic/term-meta-is-saved-but-it-doesnt-appear-in-term-edit-screen-later/page/2/#post-8444411 and the results I outlined there.

To aid in things, I'd be willing to take a copy of the plugin you're using for this, and try to recreate similar to how I was in that wordpress.org reply. If I don't succeed then, would you be willing to do a step by step for what you're doing? For example "upload and set an image", "fill in a value for 2nd field", "hit save", "Click edit term link". Very nitpicky detailed steps to ensure recreateabilty for every step.

**Comment by rogercoathup** [comment]
Thanks @tw2113 -- is there an email address I can send it to you on?  I don't want to share in public as it has the client name / details in the code

**Comment by tw2113** [comment]
michael @ webdevstudios.com will reach me.

**Comment by rogercoathup** [comment]
@jtsternberg -- yes, [that PR](https://github.com/WebDevStudios/CMB2/issues/763) fixes the problem for me.

**Comment by tw2113** [comment]
@jtsternberg I'm reopening, and from what I'm understanding, the #763 PR is working with no ill effects thus far, from tester feedback.

**Comment by joshuadavidnelson** [comment]
I was having the same issue on a custom taxonomy, the field wouldn't populate (though it appeared to save the data to the database). PR #763 fixed the issue.
