### ISSUE TITLE
Placeholder: Add "remove_default" field parameter docs for taxonomy_* fields

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/CMB2#702]
See: 6ee7222812bef1229a8b2e10d4c0259c0fda615b

**Comment by tw2113** [comment]
On wiki, with note that it's pending being released, as of the time of this comment.

**Comment by jtsternberg** [comment]
Rather than doing that, commit it to the trunk branch of the wiki. I maintain that branch w/ pending changes.

**Comment by tw2113** [comment]
I was not aware that GH wiki had their own git repos. Will revert and re-add in trunk.

**Comment by tw2113** [comment]
giving me authentication errors. May not be able to push to it? I have it locally, regardless, at the moment.

**Comment by tw2113** [comment]
Nevermind, switched to git@github.com:WebDevStudios/CMB2.wiki.git for a remote and it worked.
