### ISSUE TITLE
Is it possible to add a postfix to text fields?

### ISSUE THREAD

**Issue by natashaallsopp** [WebDevStudios/CMB2#704]
I would like to add a postfix of 'minutes' to my cmb2 text field so that the field reads:
![screenshot 2016-08-10 09 56 01](https://cloud.githubusercontent.com/assets/7151191/17547753/b39f38b6-5ee0-11e6-9a04-49bd0431a7fe.png)

Is this currently possible, if so how do I achieve this?

Thank you in advance.

**Comment by vitaly-safonov** [comment]
@natashaallsopp Of course you do this. 
More about this you can see here `https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#inject-static-content-in-a-field`
And if you watch to text_money field you see the parameter
> // 'before_field' => '£', // Replaces default '$'
This parametr you can add to all fields.

**Comment by jtsternberg** [comment]
if you're using the `text_small` field, use the `'desc'` field.

**Comment by natashaallsopp** [comment]
Thank you for your help, that's worked perfectly.
