### ISSUE TITLE
oEmbed not displaying the object when using default value

### ISSUE THREAD

**Issue by devanonyme** [WebDevStudios/CMB2#710]
Hello CMB2 users and dev! new user here.

I am evaluating CMB2 as a form solution to be used outside of the dashboard and support a post / edit worflow.

I have assigned a default value while calling add_group_fieldand then object is not instanciated completely (I dont see the visual, but it's get updated after a cut and paste).

```
    $cmb->add_group_field( $group_field_oembed,  array(
        'name' => 'Lien externe',
        'desc' => 'Enter a youtube, twitter, or instagram URL. Supports services listed at <a href="http://codex.wordpress.org/Embeds">http://codex.wordpress.org/Embeds</a>.',
        'id'   => 'wiki_test_embed',
        'type' => 'oembed',
        'default' => '*** some url from youtube ***'
    ) );
```

As a temporary workaround, I have patched init with something like this:

```
                var oEmbedList = $('.cmb2-oembed');
                oEmbedList.each(function(index) {
                    cmb.doAjax($( this ));
                });
```

And then commented out this code (assume that the object is in focus (true when updating after a url paste, but not in this case), I guess there could be a extra parameter to differentiate the use case.

```
                /*
                    if ( $( '.cmb2-oembed:focus' ).val() !== oembed_url ) {
            return;
        }
                */
```

The visual refresh (cm.maybeOembed in javascript file) seem to be called only on focusout, keyup and paste events.

My first question would surely be : is it a intended behavior?

**Comment by jtsternberg** [comment]
Setting a default value for the oembed field whether it's in a group or not works for me as expected (e.g. it displays the embed when the page loads). It's likely we'll need more information.

**Comment by tw2113** [comment]
Also curious about any changes with this one @devanonyme

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
