### ISSUE TITLE
Docblock in tests\bootstrap.php out of date

### ISSUE THREAD

**Issue by bobbingwide** [WebDevStudios/CMB2#714]
The docblock in `tests\bootstrap.php` appears to have been copied from https://github.com/blobaugh/wordpress-plugin-tests
which uses a method of loading the plugin that's now been deprecated.
```
 * Edit 'active_plugins' setting below to point to your main plugin file.
 *
 * @package wordpress-plugin-tests
 ```

I would argue that both the instruction and package are wrong.

Also that the double slash comments that follow could be improved.
```
// Support for:
// 1. `WP_DEVELOP_DIR` environment variable
// 2. Plugin installed inside of WordPress.org developer checkout
// 3. Tests checked out to /tmp
```
Perhaps it's just a case of updating 1. to reference the environment variables that are tested before you go digging around.

**Comment by jtsternberg** [comment]
Thank you for reporting. Would you care to submit a PR?

**Comment by bobbingwide** [comment]
OK. What's the @package?

**Comment by jtsternberg** [comment]
I use `CMB2` everywhere else: https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Base.php#L6

**Comment by bobbingwide** [comment]
Realised I could have changed a couple of the else if's to elseif while I had the chance.

**Comment by jtsternberg** [comment]
You can always open a new PR, but i've updated that: https://github.com/WebDevStudios/CMB2/commit/d10688076e979f73a2caf6ab0d2268639bc81541
