### ISSUE TITLE
Taxonomy is not being saved correctly in repeatable group

### ISSUE THREAD

**Issue by eriktelepovsky** [WebDevStudios/CMB2#716]
### Expected Behavior:
Each value in repeatable taxonomy group field should save its unique value. 

### Actual Behavior:
Same taxonomy value is saved for every repeatable group field.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  add group
2. add field of the taxonomy_radio type into the group
3. create post with at least 2 items in the repeatable group and set 2 different values of that repeatable field
4. save post
5. check the values

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		'id' => 'food_menu',
		'title' => 'Menu',
		'object_types'  => array( 'restaurant' ),
		'context'       => 'normal',
		'priority'      => 'high',
	) );

	$group = $cmb->add_field( array(
		'id'  => 'food_menu_group',
		'type' => 'group'
	) );

	$cmb->add_group_field( $group, array(
		'id'  => 'food_menu_section',
 		'type' => 'taxonomy_radio',
		'taxonomy' => 'menu_sections'
	) );
}
```

**Comment by tw2113** [comment]
@eriktelepovsky Biggest question I have first is if you're intending these repeated group values to be stored in post meta to be queried for later on, or something else. The reason I ask is because the taxonomy_* functions are meant for assigning terms to the post itself that the metabox is associated with. Essentially an alternative/replacement for the default metaboxes that WordPress Core provides.

If you're looking more for the meta version that you use somehow elsewherre, we recommend the standard select/radio/etc and programmatically providing the terms to display.

However, before I go to far in either direction, I want confirmation from you on your intents here.

**Comment by jtsternberg** [comment]
@tw2113 is right, the taxonomy fields are not intended to provide an arbitrary list of terms to pick from, but are intended to be a replacement for the default taxonomy metaboxes. I.e. they are meant to set the taxonomy terms on an object. Any other use of these types will be hacky and/or buggy. I suggest looking at building a custom field type for this: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#a-dropdown-for-taxonomy-terms-which-does-not-set-the-term-on-the-post

**Comment by eriktelepovsky** [comment]
Hi, thank you for your answers. I understand the post/taxonomy metabox saving functionality. I just thought it is already handled somehow for the repeatable groups as well. I will use the standard select field type with taxonomy options provided in solution posted by @jtsternberg instead. Just one more question, is the `cmb2_get_term_options`function already included in the CMB2 or do I have to insert it into my code?

**Comment by tw2113** [comment]
Looks like you have to define the function yourself, as does the example, and then use it as the value for the `options_cb` so that it'd get the field object passed to it like in the example

**Comment by eriktelepovsky** [comment]
All right. Maybe it would be useful to put it into library, or not?

Btw. in the issue #707 created by you @tw2113 is used a group field of "taxonomy_radio" type without any `options_cb` callback. Does it work for you? Am I missing something?

```
$cmb_demo->add_group_field( $group_field_id, array(
        'name'     => __( 'Test Taxonomy Radio', 'cmb2' ),
        'desc'     => __( 'field description (optional)', 'cmb2' ),
        'id'       => $prefix . 'text_taxonomy_radio',
        'type'     => 'taxonomy_radio',
        'taxonomy' => 'category', // Taxonomy Slug
        'default'  => 'dogs'
        // 'inline'  => true, // Toggles display to inline
    ) );
```

**Comment by tw2113** [comment]
I'd say it's best to link to the tips n tricks function when appropriate and per-user. The reason being is that everyone's needs for the field may be different or they will want to implement it slightly differently than someone else. Providing it in one version in CMB2 would work for some, but others who need a different version are back to implementing their own. It's also a chance to get them reading a bit more about the topic via some level of docs.

I'd need to dig through the code to confirm, but my hunch is no provided options_cb value would just do all the terms in the provided taxonomy.

**Comment by eriktelepovsky** [comment]
Check it out. The field options will be rendered fine, but the values won't be saved correctly for each group as taxonomy is mapped to the post, not to repeatable group.

**Comment by tw2113** [comment]
That's also the purpose of the taxonomy_* field types. It's meant to associate the terms to the post, not be saved as meta to be used elsewhere. The field example that Justin linked to is a regular "select" field type

**Comment by eriktelepovsky** [comment]
Yes I understand, that's the reason why I don't get it why you used it in the repeatable group field in the issue #707

**Comment by tw2113** [comment]
Gotcha, makes sense on that front, and I can provide more info.

The issue I opened there, is a copy/paste from the support forums on wordpress.org, and the issue being outlined is not related to the field type. The original user for that one would need to amend there, long term.

**Comment by tw2113** [comment]
Closing as we've clarified purposes, despite different examples in other filed issues.
