### ISSUE TITLE
Empty repeater is not empty if containing a file field

### ISSUE THREAD

**Issue by phh** [WebDevStudios/CMB2#721]
### Expected Behavior:

The meta value of the repeater group to be empty
### Actual Behavior:

Instead returning one entry in the array with a file_id field containing `0`

```
get_post_meta(...) array(1)
  →array(1)
    'myprefix_file_id' => integer 0
```
### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):
1. Save a post without filling these data in
2. Output the data of the meta - try to compare with version 2.2.1
### CMB2 Field Registration Code:

``` php
add_filter( 'cmb2_meta_boxes', function( $meta_boxes ) {
    return [ 'prefix_my_repeater' => [
        'title'        => __( 'Fact boxes' ),
        'id'           => 'prefix_my_repeater',
        'type'         => 'group',
        'object_types' => 'post',
        'fields'       => [
            [
                'id'          => 'prefix_factbox_group',
                'type'        => 'group',
                'description' => __( 'Add multiple fact boxes to the page' ),
                'options'     => [
                    'group_title'   => __( 'Fact box {#}' ),
                    'add_button'    => __( 'Add another fact box' ),
                    'remove_button' => __( 'Remove fact box' ),
                    'sortable'      => true
                ],
                'fields' => [
                    [
                        'name' => __( 'Title' ),
                        'id'   => 'prefix_title',
                        'type' => 'text'
                    ],
                    [
                        'name' => __( 'Image' ),
                        'id'   => 'prefix_image',
                        'type' => 'file'
                    ],
                    [
                        'name' => __( 'Text' ),
                        'id'   => 'prefix_text',
                        'type' => 'wysiwyg',
                        'options' => [
                            'media_buttons' => false,
                            'teeny'         => true,
                            'textarea_rows' => 6
                        ]
                    ],
                    [
                        'name' => __( 'Link' ),
                        'id'   => 'prefix_link',
                        'type' => 'text_url'
                    ],
                    [
                        'name' => __( 'Link text' ),
                        'id'   => 'prefix_link_text',
                        'type' => 'text'
                    ]
                ]
            ]
        ]
    ] ];

    return $meta_boxes;
} );
```

**Comment by jtsternberg** [comment]
Are you saying this is a regression? (and worked with 2.2.1?)

**Comment by phh** [comment]
Correct. Worked with 2.2.1. Updated to 2.2.2.1 and it "broke". After we updated the client kept getting empty boxes (due for us checking for ! empty meta) and everytime they updated a post the empty boxes appeared on the post.

Tested on 2.2.2 and @dev and the same problem appears. So currently rolled back to 2.2.1.

**Comment by skrichten** [comment]
I'm having the same issue here.  Does anyone have a workaround instead of having to roll back?

**Comment by tw2113** [comment]
No solutions that I'm aware of at the moment.

**Comment by phh** [comment]
I will go through the commits one by one and report on which commit this bug appears. If it's simple enough I will suggest a pull request.

**Comment by tw2113** [comment]
Did you ever make any headway with this one @phh ?

**Comment by phh** [comment]
Not yet :( Will test if the new update solves this problem or not.

**Comment by phh** [comment]
As of 2.2.3.1 the issue is still occurring.

**Comment by phh** [comment]
Found it. Seems like the last time it was working was after https://github.com/WebDevStudios/CMB2/commit/e0c7a19bb8e7fc797d76d15634deb9b68110e720. In https://github.com/WebDevStudios/CMB2/commit/69bf9baf706de87249e27514b54e00e1cb4bcb9b it seems to break but I have no idea why.

**Comment by tw2113** [comment]
A git bisect could provide a definitive answer for what commit caused the breakage.

**Comment by phh** [comment]
Finally! Seems like https://github.com/WebDevStudios/CMB2/commit/dba5776ea47b3bebda36f848e6a470dfe49a46c3 broke it.

**Comment by tw2113** [comment]
Ick, anything revolving around '0' is an instant headache :)

**Comment by phh** [comment]
True. Is there a reason for the file type to always have a value of '0'? How is normal file types saved? I guess these also have this '0' value?

**Comment by tw2113** [comment]
That one I'm going to have to defer to @jtsternberg

**Comment by ReidTC** [comment]
Anything new on this? I am finding that it is still an issue. Making some things look unseemly on a project I'm working on.

**Comment by phh** [comment]
Thanks!
