### ISSUE TITLE
radio_inline doesn't support 'default'

### ISSUE THREAD

**Issue by mathetos** [WebDevStudios/CMB2#723]
### Expected Behavior:
Example field:

```
array(
	'name' => esc_html__( 'Test Mode', 'give' ),
	'desc' => esc_html__( 'Test mode description.', 'give' ),
	'id'   => 'test_mode',
	'type' => 'radio_inline',
	'default' => 'on', // This is the relevant line
	'options' => array(
		'on' => esc_html__( 'On', 'give' ),
		'' => esc_html__( 'Off', 'give' )
	)
),
```

We should be able to set the default radio button just like `select` fields.

### Actual Behavior:
Adding `'default' => 'on',` forces the default to always be checked, even after a new value is saved.

### Other Notes:
* Using CMB version 2.2.2.1.
* Haven't tested trunk (2.2.3 beta) because we wouldn't use it in production.
* Did search through existing open and closed issues and didn't see this reported already.
* I kinda assume this is the case with the Radio Type as well, but didn't test that.

**Comment by mathetos** [comment]
Apologies, I believe the issue is that the `'default'` has to appear AFTER the `'options'` array. 

I updated the radio_inline part of the Wiki to clarify that:
https://github.com/WebDevStudios/CMB2/wiki/Field-Types#radio_inline

**Comment by tw2113** [comment]
Odd that it has to be in a specific order. I'm going to open this back up for further investigation, because the order, unless I'm mistaken somehow, shouldn't matter.

**Comment by tw2113** [comment]
Quick notes:
Setting it to "off" with code above deletes the post meta being set if you save it in on position initially.

**Comment by tw2113** [comment]
@mathetos Not sure I want to consider this a bug, but more just an edge case of sorts. The fact that you didn't provide a value for off makes sense in the observed behavior. For anything but "on" there would be no value to save, and also not something to check against for a default value, outside of ones with values provided.

**Comment by tw2113** [comment]
Going to mark as closed again, due to previous finding, and belief that it's pretty edge case.
