### ISSUE TITLE
Loads tinymce "skin font" many times

### ISSUE THREAD

**Issue by leolondon** [WebDevStudios/CMB2#725]
### Expected Behavior:

On a page with multiple Wysiwygs:
Loads tinymce "skin font" only once

### Actual Behavior:
The tinymce.woff "skin font" is loading once,
then the browser is loading "data:application/font-woff;charset=utf-8;base64,d...."
as many times as there are wysiwyg on the page.

This "font" is loaded from cache,
but if we have a few wysiwyg,
the page load time is affected.

Do we need to reload this font file again and again?

This is happening with CMB2 installed as plugin,
and with default wysiwyg field

I tried to fix this but no luck so far

Thanks for the great plugin guys!

**Comment by tw2113** [comment]
Just off the top of my head, I have to wonder if it's a case of simply calling wp_editor() multiple times. We don't do any sort of special font loading or anything like that for WYSIWYG fields, we simply use wp_editor() and WP core handles the rest.

Would you be willing to share your CMB2 config code so I can try and recreate on my own test site?

**Comment by leolondon** [comment]
Hi tw2113,

I use Wordpress 4.6, and CMB2 2.2.2.1 installed as plugin

Then I have this:
```

add_action( 'cmb2_init', 'cmb2_rdm_metaboxes' );

function cmb2_rdm_metaboxes() {

	$prefix = '_cmb_';

	$cmb = new_cmb2_box( array(
		'id'         => 'homepage_details_metabox',
		'title'      => 'Details:',
		'object_types'      => array( 'page' ), // Post type
		'context'    => 'normal',
		'priority'   => 'high',
		'show_names' => true,
		'show_on'    => array( 'key' => 'id', 'value' => array( 6 ), ),
	) );

	for ($i = 1; $i <= 15; $i++) {

		$cmb->add_field( array(
			'name'     => esc_html__( 'Edito' . $i , 'cmb2' ),
			'desc'     => esc_html__( 'Entrez ici le text pour l\'édito pour la page d\'accueil', 'cmb2' ),
			'id'       => $prefix . 'edito' . $i ,
			'type'     => 'wysiwyg'
		) );

	}
}

```
As shown on the attached jpeg,
the font is loaded again and again,
even if it loads from cache and sayx timing is 0ms,
it actually double the page load time (eg: the gap between 2500ms and 4500ms)

once the page has images and other elements, the whole page loads in 10sec...

![tunymce-font](https://cloud.githubusercontent.com/assets/2861162/18202967/f726d1d0-7113-11e6-93d0-729c460031c2.jpg)

Thanks for your help!
:-)

**Comment by jtsternberg** [comment]
As @tw2113 said, this is definitely an issue with the core `wp_editor()` function, and not something to do with CMB2. Also, based on your screenshot and the time associated w/ each of those calls, I don't think that's the source of the slowness, though there is no doubt in my mind that each `wp_editor` instance will add some loading latency, as there is a LOT going on.

**Comment by leolondon** [comment]
Hi jtsternberg, 

Thanks for your reply,
I understand and agree this is wp_editor issue,

maybe it's not designed to load more than one tinymce per page ?

There should be an option in wp_editor 
to tell (this is not the first wysiwyg, please do not reload everything)
I don't dont know if you guys has any idea on how to achieve this?

Performancewise: Yes this duplicate font thing is definitely causing slowness,
The page is blank,
As soon as I load wysiwigs, it is slow,
and gets back to "fast" once wysiwygs removed

Thanks again for your reply!

**Comment by tw2113** [comment]
Interesting note found in the phpdoc for wp_editor:

```
 * NOTE: Once initialized the TinyMCE editor cannot be safely moved in the DOM. For that reason
 * running wp_editor() inside of a meta box is not a good idea unless only Quicktags is used.
 * On the post edit screen several actions can be used to include additional editors
 * containing TinyMCE: 'edit_page_form', 'edit_form_advanced' and 'dbx_post_sidebar'.
 * See https://core.trac.wordpress.org/ticket/19173 for more information.
```

**Comment by leolondon** [comment]
Interesting! Thanks!
I finally used textarea instead.
:-)
