### ISSUE TITLE
How to check if values are empty with cmb2_override_meta_save filter?

### ISSUE THREAD

**Issue by luxdeluks** [WebDevStudios/CMB2#726]
Have been making a custom relationship system with CMB2 using 

```
add_filter('cmb2_override_meta_value', 'get_custom_data', 10, 4);
add_filter('cmb2_override_meta_save', 'save_custom_data', 10, 2);
```

However I can't get my function to recognize if the field values are empty (aka removing the last item). In my case I was using the "attach post" custom field but I'm guessing this applies more to the filter in general?

Example simple function:
```
function save_custom_data($data, $values)
{
	if (!array_key_exists('value', $values)) {
		$values['value'] = null;
	}
	
	if ($values['field_id'] == 'attached_user_workshop_posts') {
		hub_write_user_data($values);
	}

    return true;
}
```

Whatever I try to do with $values I can't get it to register as empty if the field has no values. Any ideas would be greatly appreciated

**Comment by tw2113** [comment]
perhaps a basic `unset( $values['value'] );` would work. Null, while it doesn't seem like it would be, is considered a value, if I recall right

**Comment by luxdeluks** [comment]
Actually I figured it out. turns out I forgot to also include the remove filter that also calls the function for save:

```
add_filter('cmb2_override_meta_save', 'save_custom_data', 10, 2);
add_filter('cmb2_override_meta_remove', 'save_custom_data', 10, 2);
```

now if we do this 
```
if (!array_key_exists('value', $values)) {
		$values['value'] = null;
	}
```
the value is null :)

**Comment by tw2113** [comment]
Good to hear you got it worked out. :)

**Comment by dskurth** [comment]
THANK YOU!!!!
