### ISSUE TITLE
Undefined Function

### ISSUE THREAD

**Issue by JayWood** [WebDevStudios/CMB2#732]
Says it all, should be `get_the_ID()` notice caps -  https://github.com/WebDevStudios/CMB2/blob/049c48d95411365114379a8fd163341f363c895a/includes/CMB2_Show_Filters.php#L84

Also, doc block needs updated.

**Comment by tw2113** [comment]
From the looks of it, that line has been in there for awhile. I agree we should make sure that we're using the proper capitalization, and also remove that error suppressor.

**Comment by jtsternberg** [comment]
@JayWood you don't want the props on this one?

**Comment by JayWood** [comment]
@jtsternberg haha I found it in passing, probably put in a PR later today, just logged it so I knew it was there.
