### ISSUE TITLE
Change "Add Row" text for repeatable select or checkbox field

### ISSUE THREAD

**Issue by MapSteps** [WebDevStudios/CMB2#733]
Is it possible to change the "Add Row" text for a repeatable select or checkbox field?

```
$cmb->add_field( array(
	'id'      => $prefix . 'platform',
	'type'    => 'select',
	'show_option_none' => true,
	'repeatable' => true,
	'options' => array(
		'value-one' => 'Facebook',
		'value-two' => 'Twitter',
		'value-three' => 'Google+'
	),
) );
```

Adding `'add_row_text' => __('add platform', 'textdomain'),` to the options array adds it to the select dropdown.

**Comment by tw2113** [comment]
Did you try outside of the options array? perhaps on the line above that one?

**Comment by MapSteps** [comment]
Hey @tw2113,

yes, didn't work.

**Comment by tw2113** [comment]
I'll use this as a quick example: https://github.com/WebDevStudios/CMB2/wiki/Field-Types#taxonomy_multicheck

If you pass it in this way, it looks like it works:

```
'text' => array(
	'add_row_text'     => __( 'add platform', 'textdomain' ),
),
```

**Comment by MapSteps** [comment]
oh, thank you @tw2113!

I've missed that. Works! :)
