### ISSUE TITLE
l10n js var should not be printed in browser console

### ISSUE THREAD

**Issue by slaFFik** [WebDevStudios/CMB2#734]
I believe,

```js
cmb.log( 'CMB2 localized data', l10n );
```

should not be printed in browser console on `cmb.init()`.

**Comment by tw2113** [comment]
I think it'd be fine to keep for the unminified version, but it should be removed from the minified copy. It's more a dev notif of sorts, and prod shouldn't be running the unminified

**Comment by jtsternberg** [comment]
it doesn't run unless `SCRIPT_DEBUG` is enabled. That's the purpose of the `cmb.log` method.

**Comment by slaFFik** [comment]
Yes, you are right (I didn't dive that deep until now).
Personally I would gladly remove this log anyway. Anyway it's easily accessible on-demand in console via `window.cmb2_l10` - so why print it separately? When SCREEN_DEBUG is true - that means heavy development, with lots of js involved, so the less distracting things in console - the better.

What do you think?

**Comment by jtsternberg** [comment]
I agree. I'll remove.
