### ISSUE TITLE
Get metaboxes by given post type

### ISSUE THREAD

**Issue by eriktelepovsky** [WebDevStudios/CMB2#737]
Hi, I am trying to get all metaboxes by given post type. Currently I am using this solution:
 
```php
$meta_boxes = CMB2_Boxes::get_all();
$result = array();

if ( ! empty( $meta_boxes ) ) {
    foreach ( $meta_boxes as $meta_box ) {
        if ( in_array( $post_type, $meta_box->meta_box['object_types'] ) ) {
            $result[] = $meta_box;
        }
    }
}
```

It works, but it isn't very nice. Do you think there is a better approach? Thank you.

**Comment by tw2113** [comment]
I'd dare say it could be a lot worse, and if it works, it works. Maybe turn it into a function with a post type parameter

**Comment by eriktelepovsky** [comment]
I just wanted to know if there isn't implemented a helper for this functionality in the CMB2 library already. So I guess it isn't?

**Comment by tw2113** [comment]
Not that I'm aware of. Guess I haven't seen many usecases that need to grab the metaboxes in that way, but I definitely don't have my head in active CMB2 usage frequently.

**Comment by eriktelepovsky** [comment]
Do you think this is more optimal solution?

```php
$result = array_filter( CMB2_Boxes::get_all(), function( $meta_box ) use( $post_type ) {
    return in_array( $post_type, $meta_box->meta_box['object_types'] );
});
```

**Comment by tw2113** [comment]
That was the only other idea I had, thanks to a recent blog post I came across about ditching foreach loops, but at the same time it's a little bit borderline micro-optimization.

**Comment by eriktelepovsky** [comment]
My final solution:

```php
function get_metaboxes_by_post_type( $post_type ) {
    if ( version_compare ( phpversion(), '5.3.0', '>=' ) ) {
        return array_filter( CMB2_Boxes::get_all(), function( $meta_box ) use( $post_type ) {
            return in_array( $post_type, $meta_box->meta_box['object_types'] );
        } );
    } else {
        $result = array();

        foreach ( CMB2_Boxes::get_all() as $meta_box ) {
            if ( in_array( $post_type, $meta_box->meta_box['object_types'] ) ) {
                $result[] = $meta_box;
            }
        }

         return $result;
    }
}
```
