### ISSUE TITLE
WPBakery Visual Composer inside meta boxes

### ISSUE THREAD

**Issue by tripad** [WebDevStudios/CMB2#738]
Is there a way to activate Visual Composer page builder inside a custom meta box ?

**Comment by tw2113** [comment]
Closest way I can think of, while using CMB2, is using the WYSIWYG field type. This is assuming Visual Composer knows how to detect when that's in use away from the main editor, and override it.

**Comment by kampiamodikuesto** [comment]
WYSIWYG field type doesn't recognize visual composer. No switch buttons. is there a way to enable this?
