### ISSUE TITLE
cmb2_admin_init For Custom Post Types

### ISSUE THREAD

**Issue by yehiasalam** [WebDevStudios/CMB2#739]
Hi,

So assuming I have 2 or more custom post types, im loading the action in my bootstrap class like this

```
		$this->loader->add_action( 'cmb2_admin_init', $plugin_push , 'setup_metaboxes_cmb2', 10 , 5 );
		$this->loader->add_action( 'cmb2_admin_init', $plugin_featured_slider , 'setup_metaboxes_cmb2', 10 , 5 );
```

The problem is both setup_metaboxes_cmb2 functions (in two different classes) are executed on every page in the admin part. How can I just hook it to a custom page type, similiar to save_post_custompost native wordpress action is doing.

**Comment by tw2113** [comment]
Perhaps you could do something with https://codex.wordpress.org/Function_Reference/get_current_screen and return early in the methods if not in the intended place for the rest of the method.

I can't think of any hooks for specific screens that would for sure still work.

**Comment by yehiasalam** [comment]
I tried the current_screen hook, but looks like it's executed after cmb2_admin_init since i cant see any metaboxes added now in the admin screen

**Comment by jtsternberg** [comment]
there's not a lot overhead to registering boxes. You should register them, then use the [`show_on_cb`](https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-using-the-show_on_cb-to-limit-the-display-of-a-metabox-unless-metadata-exists) to determine where they should show (get_current_screen should be available in the callback).

**Comment by luxdeluks** [comment]
In case of using additional queries for populating metaboxes it can become a potential bottleneck since it fires on all admin pages.

Any ideas on a solution to bind metabox creation to specific edit screens only?

**Comment by tw2113** [comment]
in your callback hook where you set up your metaboxes, fetch the current screen yourself and return early if it's not where you want.

If you're talking about things like the 'option' param, I believe the case is use `'option_cb' => 'my_function'` instead of `'option' => my_function()` to prevent functions from running on every page.

**Comment by luxdeluks** [comment]
I can't seem to grab the current screen with cmb_admin_init to perform checks.

However using option_cb does seems to work. So thanks for that! Gonna go test the field object it passes to a function to see if it all works.

**Comment by tw2113** [comment]
From the get_current_screen() codex page, this may be the issue:

"The function returns null if called from the admin_init hook. It should be OK to use in a later hook such as current_screen."

**Comment by luxdeluks** [comment]
cb_options worked great and thanks again for that. For those in need:

```
function my_function ( $field ) { 
echo $field->args['name'];
}
```

if we would call this function like so:

'options_cb' => 'my_function ',

we would get the name value of the field. For those interested in other values I suggest simply using print_r($field) inside your function to see all the object values.

**Comment by tw2113** [comment]
XDebug and execution pausing is also an awesome way to inspect what's passed in and the state of the pageload at that point in time.

**Comment by jtsternberg** [comment]
Use the `'show_on_cb'` to conditionally load the meta box execution.

**Comment by jtsternberg** [comment]
Examples: https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-using-the-show_on_cb-to-limit-the-display-of-a-metabox-unless-metadata-exists

**Comment by jtsternberg** [comment]
If you're still having issues with the latest version, please open a new issue.
