### ISSUE TITLE
cmbs2 Type Checkbox double Description Text

### ISSUE THREAD

**Issue by WebDevLan4You** [WebDevStudios/CMB2#746]
### Expected Behavior:

using checkbox field and get one Description
### Actual Behavior:

getting 2 Description if i use it for a custom type like checkbox with input field
### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):
1.  
2.  
### CMB2 Field Registration Code:

``` php
function cmb2_render_checkbox_input_field_callback( $field, $value, $object_id, $object_type, $field_type_object ) {
    $value = wp_parse_args( $value, array(
        'active_on_front' => '',
        'title' => '',
    ) );
    ?>

    <div class="alignleft">
        <?php echo $field_type_object->checkbox( array(
            'name'  => $field_type_object->_name( '[active_on_front]' ),
            'id'    => $field_type_object->_id( '_active_on_front' ),
            'value' => $value['active_on_front'],
            'desc'  => 'ja',
        ) ); ?>

        <?php echo $field_type_object->input( array(
            'name'  => $field_type_object->_name( '[title]' ),
            'id'    => $field_type_object->_id( '_title' ),
            'value' => $value['title'],
            'desc'  => '',
        ) ); ?>
    </div>
        <p class="clear">
     <?php echo $field_type_object->_desc();?>  
    </p>
<?php
}
add_filter( 'cmb2_render_checkbox_input', 'cmb2_render_checkbox_input_field_callback', 10, 5 );
```

possible Solution:
file: https://github.com/WebDevStudios/CMB2/blob/trunk/includes/types/CMB2_Type_Checkbox.php

``` php

public function render(){
...
return $this->rendered(
            sprintf(
                '%s <label for="%s">%s</label>',
                parent::render( $args ),
                $this->_id(),
                $this->_desc()
            )
        );
}
```

with

``` php

public function render(){
...

return $this->rendered(
            sprintf(
                '<label for="%s"><input%s/>%s</label> ',
                $this->_id(),
                        $this->concat_attrs($args, array( 'desc', 'js_dependencies' )),
                                $args['desc']
            )
        );
}
```

**Comment by tw2113** [comment]
Can you provide the other part of the registration that you're using? the part that adds the fields in question. Above looks like just the filter/callback to alter their output, away from the default CMB2 uses.

**Comment by tw2113** [comment]
Any updates on this one @WebDevLan4You ?

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.

**Comment by mbsouth** [comment]
@bradp 
I feel so free and reopen this issue.

When creating **own fields** with checkbox elements, the label attribut **for** gets the value of it´s parent object:

```
<div class="cmb-td">
    <div style="overflow: hidden">    
      <input type="checkbox" class="cmb2-option cmb2-list" name="slider_test[status]" id="slider_test_status" value="on" data-hash="d07846j0pdi0">
     <label for="slider_test"></label>
   </div>
</div>
```

This behavior is also evident in the original CMB2 code snippet here: [https://github.com/CMB2/CMB2-Snippet-Library/blob/master/custom-field-types/textarea-with-checkbox.php](https://github.com/CMB2/CMB2-Snippet-Library/blob/master/custom-field-types/textarea-with-checkbox.php)

The snippet shown above is a copy&paste excerpt from it.
