### ISSUE TITLE
 How do I use "get_option ()" in CMB2?

### ISSUE THREAD

**Issue by jquimera** [WebDevStudios/CMB2#747]
Hi, I met CMB2 these days, I know how to print a custom field. I have over 20 fields and would like to know how to print them more efficiently.

For example:

instead of like this: `<? php echo get_post_meta (get_the_ID (), 'MyField', true); ?>`

I want to use it like this: `<? php echo get_option ('MyField');?>`

it's possible? can anybody help me? this is really very important to me.

I appreciate it.

**Comment by tw2113** [comment]
Easiest way I can think of, as I can't find a ready-made helper function at the moment, would be to use the metabox to save a value, and then check your wp_options table in the database to see what option_name got used for that value. Once you have that, you can utilize get_option() with it.

**Comment by tw2113** [comment]
there's also https://github.com/WebDevStudios/CMB2/blob/trunk/includes/helper-functions.php#L118-L128 now that i remember it, but you'd still need to know the parts for the parameters.

**Comment by jquimera** [comment]
@tw2113 I'm trying to do this using the example of theme CMB2. As we already know, it uses the CMB2 to create a panel of options, and this method I'm wanting to use already exists in this theme. The problem is that I am not able to do the same thing for metaboxes on pages and posts.

**Comment by jquimera** [comment]
@tw2113 From what I could see, the code below is what makes the whole thing work, one must also work with the metaboxes post_type, page / post.

`function cmb2_example_theme_get_option( $key = '' ) {
	global $cmb2_example_theme_options;

	if( function_exists( 'cmb2_get_option' ) ) {
		return cmb2_get_option( $cmb2_example_theme_options->key, $key );
	} else {
		$options = get_option( $cmb2_example_theme_options->key );
		return isset( $options[ $key ] ) ? $options[ $key ] : false;
	}

}`

**Comment by tw2113** [comment]
Well, if it's a theme options page, then it's still going to be saving to the wp_options table. Using the code you outlined above, you'd just need to know the key/id of the field you're trying to fetch.

If you would be willing to provide all your code for this, I can look it over+trial&error and help figure out the parts you need to provide to fetch the right data/content.

**Comment by jquimera** [comment]
@tw2113 I am building my whole project using as example-functions.php base without changing anything vital, I'm just copying the fields and changing ID's.

https://github.com/WebDevStudios/CMB2/blob/trunk/example-functions.php

This file is what I'm using.

**Comment by jtsternberg** [comment]
I don't think @jquimera is asking about options pages, but instead post meta/fields. If you want a simpler function, you can simply make your own helper function:
```php
function yourprefix_get_meta( $key ) {
	return get_post_meta( get_the_ID(), $key, 1 );
}
```

**Comment by jquimera** [comment]
@jtsternberg Yes Yes! this is exactly what I needed. Everything is perfect now. I am very happy. I am grateful to you and @tw2113 for helping me.

**Comment by tw2113** [comment]
Sorry for the misunderstanding on my part.

**Comment by jquimera** [comment]
@tw2113 No, I do apologize. I'm still learning English and still have the google translator ... maybe I have not expressed myself well. I thank you.
