### ISSUE TITLE
CMB2 file_list error on transfer of site from dev to production

### ISSUE THREAD

**Issue by infobuster** [WebDevStudios/CMB2#748]
currently developed a site using the CMB2 plugin and all works well on the development server

Functions File

```
$cmb_demo->add_field( array(
'name' => __('Images', 'cmb2' ),
'desc' => '',
'id'   => $prefix . 'wiki_test_file_list',
'type' => 'file_list',
) );
```

Template File

```
<?php
        //Start Of Thumbnails
        $img_size = 'page-thumb';
        $files = get_post_meta( get_the_ID(), '_yourprefix_'.$proptype.'_twowiki_test_file_list', 1 );
        echo '<ul class="clearing-thumbs small-block-grid-2 " data-clearing>';
        // Loop through them and output an image
        foreach ( (array) $files as $attachment_id => $attachment_url ) {
        echo ' <li>';
        echo wp_get_attachment_image( $attachment_id, "full" );
        echo '</li>';
        }
        echo '</ul>';
        //End Of Thumbnails
        ?>
```

This code works fine and allows the user to upload multiple images in the admin and they show up in the front end all ok

However this is my problem... i've moved the site to a production server and the images failed to show up in the front end or the admin thinking it was possible to do with a different php version i duplicated the same dev server moved the files over and still it did not show the thumb nails i've checked whats going on in the database as the data is serialised but urls are all correct, even if i go in and manually add the new images once transfered they work ok just for some reason they wont show up with a simple copy of files and update the database URLs to a different server

hope someone can help shed some light

**Comment by tw2113** [comment]
Are you updating the character count for the serialized data when you update the domain?

```
s:25:"http://devsite.domain.com";
```

to

```
s:21:"http://www.domain.com";
```

Notice the difference in numbers at the start. It's a count of the string characters in that portion of the serialized data.

**Comment by infobuster** [comment]
Ahh that makes sense thanks for your help
