### ISSUE TITLE
file & file_list is not working

### ISSUE THREAD

**Issue by fazleerabby** [WebDevStudios/CMB2#754]
### Expected Behavior:

It should pop up the default WordPress uploader.
### Actual Behavior:

It does Nothing. I tried everything. I looked at my previous coding and it was alright. But then I understand there is some bug with the new version. I included my old version of CMB2 and it was working fine. So I think you guys will get to that as soon as possible.

Thanks,
SK Fazlee Rabby

**Comment by jtsternberg** [comment]
This sounds like a compatibility problem. The fields work as expected. Are you getting javascript errors in your console?

**Comment by fazleerabby** [comment]
I don't know much about compatibility. But I'm using latest version of WordPress, I'll let you know if there is any JavaScript errors in console. Thanks for the concern.

**Comment by mw247** [comment]
Same proble on WP 4.5.4

**Comment by tw2113** [comment]
If someone could provide their CMB2 configuration code, we can look into it better.

**Comment by mw247** [comment]
Looks like the js wasn't being loaded correctly. The "cmb2_utils()->url was returning a path to my local files...

src='http://localhost:57912C:/Users/Marc/Documents/My%20Web%20Sites/WordPress%20Sandbox/wp-content/themes/foundation/cmb2/js/cmb2.min.js'

I just loaded the script with a direct path for now.

"/wp-content/themes/foundation/cmb2/js/cmb2{$min}.js"

**Comment by mw247** [comment]
Thanks! Will do.

**Comment by mw247** [comment]
Give the URL filter a try with no luck. Still adds a system path to the URL...

http://localhost:57912C:/Users/Marc/Documents/My%20Web%20Sites/WordPress%20Sandbox/...

If it matters, I am not using the plugin version.

**Comment by tw2113** [comment]
Based on what I'm seeing, this should work, perhaps with some needed minor tweaks for the spaces in "My Web Sites" and "WordPress Sandbox". Both varieties shown below.

```
function update_cmb2_meta_box_url( $url ) {
    return str_replace( 'C:/Users/Marc/Documents/My%20Web%20Sites/WordPress%20Sandbox', '', $url );
}
add_filter( 'cmb2_meta_box_url', 'update_cmb2_meta_box_url' );
```

```
function update_cmb2_meta_box_url( $url ) {
    return str_replace( 'C:/Users/Marc/Documents/My Web Sites/WordPress Sandbox', '', $url );
}
add_filter( 'cmb2_meta_box_url', 'update_cmb2_meta_box_url' );
```

**Comment by mw247** [comment]
Awesome, thanks!

w/ spaces worked...

return str_replace( 'C:/Users/Marc/Documents/My Web Sites/WordPress Sandbox', '', $url );

**Comment by tw2113** [comment]
@fazleerabby is your issue similar to the one @mw247 was experiencing, and thus perhaps solved the same way?

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
