### ISSUE TITLE
textarea_code

### ISSUE THREAD

**Issue by needtakehave** [WebDevStudios/CMB2#757]
I just have a question... for the "textarea_code" box, what does it do? Is it for php code or html? And does it convert the html tags in html or does it just like wrap the code like if you have code here and wrap it with a thingy, like this;

`<?php code ?>`

Like that?

**Comment by tw2113** [comment]
Based on https://github.com/WebDevStudios/CMB2/blob/trunk/includes/types/CMB2_Type_Textarea_Code.php, it'd be the latter, and wrap the output in `<pre></pre>` tags.

**Comment by needtakehave** [comment]
Thanks!
