### ISSUE TITLE
Pagination Loop

### ISSUE THREAD

**Issue by needtakehave** [WebDevStudios/CMB2#760]
I was wondering if someone could help me figure out what I am doing wrong. I'm trying to create a pagination loop for custom post types to include post (if possible) along with my custom post types. I've tried it without post, with JUST post, with JUST a custom post type, and still nothing.

```
<?php if (have_posts()) :
	$paged = (get_query_var('paged')) ? get_query_var('paged') : 1; 
	$args=array(
		'post_type' => array( 'post', 'blogtours', 'reviews' ),
		'posts_per_page' => 5,
		'ignore_sticky_posts'=>1,
		'paged'=>$paged 
	);
	$the_query = new WP_Query($args);
	while ($the_query->have_posts()) : $the_query->the_post(); ?>
```

**Comment by tw2113** [comment]
Couple things.

1. This isn't a CMB2 issue by any means, so really not the best place to ask for support with this question.
2. The GitHub issues for CMB2 aren't the preferred location for general support questions like this. For those, please use the forum located at https://wordpress.org/support/plugin/cmb2. You'll still get to see and work with me still. The issues area here is for confirmed bugs and enhancement ideas.

If you could start a thread at that forum, I'll give it a go with answering, despite bullet point 1. Just in case it is a help, I have this that I typed up for our CPTUI users, but it'd apply here. http://docs.pluginize.com/article/81-cleanly-done-pagination-with-custom-wpquery-objects

That said, I am going to close this issue at the moment. Thanks
