### ISSUE TITLE
When adding Select field to custom field type render function, it can't concat options

### ISSUE THREAD

**Issue by Pilskalns** [WebDevStudios/CMB2#761]
### Expected Behavior:

When adding Select field to custom field type render function, it can't `concat_items` options.

I have custom field, which outputs a table. Within each table row, I output set of other fields, like text intput, slider etc. Sounds fancy, but everything worked, until I tried to add Select instead of Input...
### Actual Behavior:

Here's error:

``` php
Fatal error:  Uncaught ErrorException: Array to string conversion in ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php:23
Stack trace:
#0 [internal function]: exceptions_error_handler(8, 'Array to string...', 'C:\\nginx\\html\\s...', 23, Array)
#1 ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php(23): sprintf('\t<option value=...', 0, ' selected='sele...', Array)
#2 ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php(101): CMB2_Type_Multi_Base->select_option(Array, 1)
#3 ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Select.php(23): CMB2_Type_Multi_Base->concat_items()
#4 ...\wp-content\plugins\cmb2\includes\CMB2_Types.php(447): CMB2_Type_Select->render()
#5 ...\wp-content\plugins\rue\includes\cmb2-drag-drop-group-type.php(246): CMB2_Types->select(Array)
#6 ...\wp-includes\plugin.php(524): cmb2_render_bug_select_fi in ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php on line 23
```
### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):
1.  Register custom field. Add options. Everything works. Saving, changing, sanitization. 
2.  Try to swap one of those fields from input to select.
### CMB2 Field Registration Code:

``` php

$cmb = new_cmb2_box( array(
    'id'         => 'display',
    'title'         => 'Display Options',
    'hookup'     => false,
    'cmb_styles' => false,
    'show_on'    => array(
        // These are important, don't remove
        'key'   => 'options-page',
        'value' => array( $this->key, )
    ),
) );

$cmb->add_field( array(
    'name' => __( 'Owned Fields', 'rue' ),
    'desc' => __( 'All fields found in users metadata', 'rue' ),
    'id'   => 'owned_fields',
    'type' => 'bug_select',
    'options_cb' => 'check_min_required_fields',
    'escape_cb' => false,
    // 'sanitization_cb' => false,
) );
```

Here's render of this field. Problem can be found digging `$field_type_object->select( array(...));`

``` php
function cmb2_render_bug_select_field_type( $field, $escaped_value, $object_id, $object_type, $field_type_object ) {

    $drag_table = '<table class="widefat bug_select" name="' . $field->args['_name'] . '[]" id="' . $field->args['_id'] . '"';
    foreach ( $field->args['attributes'] as $attribute => $value ) {
        $drag_table .= " $attribute=\"$value\"";
    }
    $drag_table .= ' data-item-count="'.count($field->options()).'"';
    $drag_table .= ' style="width:auto;"/><thead><tr>
        <th class="column-handle"><span class="dashicons dashicons-sort"></span></th>
        <th class="column-name column-primary">Field Name</th>
        <th class="column-type">Input Type</th>
    </tr></thead><tbody>';

    $fid = 0;
    foreach ( $field->options() as $row ) {

        $drag_table .= '<tr><td class="column-handle drag-handle"><span class=" dashicons dashicons-editor-justify"></span></td>';

        $drag_table .= '<td class="column-name column-primary">' . $field_type_object->input( array(
            'name'  => $field_type_object->_name( "[$fid][name]" ),
            'id'    => $field_type_object->_id( '_'.$fid.'_name' ),
            'value' => $row['name'],
            'repeatable'=> true,
            'desc'  => '',
            'pattern' => '[a-z0-9-_]+',
        ) ) . '</td>';

        // Error comes in next line's "select"
        $drag_table .= '<td class="column-type">' . $field_type_object->select( array(
            'name'    => $field_type_object->_name( "[$fid][type]" ),
            'id'      => $field_type_object->_id( '_'.$fid.'_type' ),
            'desc'    => '',
        ) ) . '</td>';

        $drag_table .= '</tr>';
        $fid++;
    }

    $drag_table .= '</tbody></table>';

    echo $drag_table; // WPCS: XSS ok.
}
add_action( 'cmb2_render_bug_select', 'cmb2_render_bug_select_field_type', 10, 5 );
```

**Comment by tw2113** [comment]
Correct me if I'm wrong here, just trying to make sure I follow correctly. You originally set a field to be a standard text input field, and then you switched it to a select field, and now it's erroring on you? All without changing the saved value to the meta field? If that's the case, do the errors occur with a new post where there's not metadata already saved?

**Comment by Pilskalns** [comment]
@tw2113 No, it's not because of saved data. I tried clearing it in db etc. I said that just to prove, that adding field to field thing was working for me - I have spen't enough hours digging CMB2 source code, I understand why error is, but I can't figure how to fix it proper way.

Error happens because `sprintf` function receives array instead of string. On `CMB2_Type_Multi_Base` class, there's a loop inside `concat_items` function, which sends already array (here should be already string) to `select_option`:

```php
$options = array();
if ( $option_none = $field->args( 'show_option_none' ) ) {
	$options[ '' ] = $option_none;
}
$options = $options + (array) $field->options();

foreach ( $options as $opt_value => $opt_label ) {

// Clone args & modify for just this item
$a = $args;

$a['value'] = $opt_value;
$a['label'] = $opt_label;

// Check if this option is the value of the input
if ( $value == $opt_value ) {
	$a['checked'] = 'checked';
}
$concatenated_items .= $this->$method( $a, $i++ );
}
```

In pasted excerpt, options comes from [THIS](https://github.com/WebDevStudios/CMB2/blob/trunk/includes/types/CMB2_Type_Multi_Base.php#L87) line, I can sanitize it manually, but I can't figure out, how it should work, if it is regular use of Select, not Select inside other field.

**Comment by jtsternberg** [comment]
And you're saying you're having this issue on the trunk branch?

**Comment by Pilskalns** [comment]
@jtsternberg If term `trunk branch` means main / master branch, then yes. I use CMB2 as WP plugin. Checked versions already before and they match with latest release here on GitHub - v2.2.2.1

**Comment by jtsternberg** [comment]
No, I mean the trunk (development) branch here on GitHub. NOT the master branch or the plugin from .org. Please test with trunk. Thank you.

**Comment by Pilskalns** [comment]
@jtsternberg  Ok, now understand meaning.

Yes, here's  the same error (some line numbers are +/- up down as previously I had shifted them when dumping variables for debug):

```php
Fatal error:  Uncaught ErrorException: Array to string conversion in ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php:22
Stack trace:
#0 [internal function]: exceptions_error_handler(8, 'Array to string...', 'C:\\nginx\\html\\s...', 22, Array)
#1 ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php(22): sprintf('\t<option value=...', 0, ' selected='sele...', Array)
#2 ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php(97): CMB2_Type_Multi_Base->select_option(Array, 1)
#3 ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Select.php(21): CMB2_Type_Multi_Base->concat_items()
#4 ...\wp-content\plugins\cmb2\includes\CMB2_Types.php(447): CMB2_Type_Select->render()
#5 ...\wp-content\plugins\rue\includes\cmb2-drag-drop-group-type.php(96): CMB2_Types->select(Array)
#6 ...\wp-includes\plugin.php(524): cmb2_render_rue_drag_drop_f in ...\wp-content\plugins\cmb2\includes\types\CMB2_Type_Multi_Base.php on line 22
```

**Comment by tw2113** [comment]
This part has me curious: \wp-content\plugins\rue\includes\cmb2-drag-drop-group-type.php

Is this being done via a custom plugin, or in conjunction with a 3rd party plugin?

**Comment by Pilskalns** [comment]
@tw2113 yes, I am trying to create my plugin, so functionality becomes theme independent.

That line points to this:
```php
$drag_table .= '<td class="column-type">' . $field_type_object->select( array(
	'name'    => $field_type_object->_name( "[$fid][type]" ),
	'id'      => $field_type_object->_id( '_'.$fid.'_type' ),
	'desc'    => '',
) ) . '</td>';
```
I tried, of course, pass to this function option/s, select_option/s, but unsuccessful.

And here's the array what is passed to [`select_option`](https://github.com/WebDevStudios/CMB2/blob/trunk/includes/types/CMB2_Type_Multi_Base.php#L21)

```php
Array
(
    [value] => 0
    [label] => Array
        (
            [name] => surname
            [nicename] => Hard Surname
            [pattern] => 11
            [type] => 12
            [read] => 5
            [write] => 2
        )

)
```

**Comment by tw2113** [comment]
Would you be willing to zip up the whole plugin for me, I'll see what I can do to try and figure things out, or verify things are amiss on our end? I'm curious if a value is getting passed incorrectly at some point, and having all the relevant code would help me.

**Comment by Pilskalns** [comment]
@tw2113 Even better. Stripped out everything else, isolating only this corner case.
There will be _Rich User Editor_ page under _Users_

[select-bug.zip](https://github.com/WebDevStudios/CMB2/files/512432/select-bug.zip)

**Comment by tw2113** [comment]
I've kicked this around and traced my way through with XDebug and all that fancy stuff, and in the end it feels like too much is being passed into the 'options_cb' field.

As per https://github.com/WebDevStudios/CMB2/wiki/Field-Types#select, the field is passed a basic array of key/value pairing, all of which are strings. What is occurring at the moment is that the values for this are ending up being arrays.

To add to that, my experience with check_min_bug_fields() is showing `$field->value` as being false on line 225 of select-bug.php. Both parts of the if statement in that area are also set to likely return nested arrays instead of the key/value string pairs highlighted above in the example link.

At least from what I can determine, it's less a bug in CMB2, and more issue in the implementation of the options callback.

Leaving the issue open a bit longer for further help debugging/discussion, but that's what I've found thus far.

**Comment by Pilskalns** [comment]
Function `check_min_bug_fields()` is showing `$field->value` because at that state DB is empty/ wiped. It just adds minimal required fields to be shown there.

The `check_min_bug_fields()` is called for whole `select_bug` field, which is called with `$cmb->add_field( array(...));` on `select-bug.php:153`

How to add such callback to individual field `$field_type_object->select( array(...) );` on `cmb2-drag-drop-group-type.php:31`?

**Comment by tw2113** [comment]
@jtsternberg you have any thoughts for this one? I've never done much for extending CMB2 in this way.

**Comment by Pilskalns** [comment]
Hi, just letting know, that I made workaround that still works still as CMB2 html field & returns legit value on save.

----------
Thanks for great tool. With this I create small community site where I belong to, and hiring external coders are not efficient or too pricey for quality I wan't. This saves a lot of effort and lets focus on things I wan't create to, not rather how to do basic security or even reinvent. It feels also really efficient piece of code as I filled DB with full-scale test data (~800 users with bunch of meta)  which results in dynamically generated (available to user) fields and it doesn't add any noticeable drag. Thanks again!

**Comment by eriktelepovsky** [comment]
Hi @Pilskalns, can you share your workaround please? I have same issue here.

**Comment by Pilskalns** [comment]
@eriktelepovsky sorry for delay. Didn't notice this notification in email.

In ideal case, process would return just string with HTML. As I look code what wrote back then, main idea is to create [select html element](http://www.w3schools.com/tags/tag_select.asp) manually. First, a bit of concept, what's happening.

Here's loop that processes multi dimension array row by row, but structure is predictable and known:
```php
$fid = 0;
foreach ( $field->options() as $row ) { // This is data we want to display as table
	$row['fid'] = $fid++; // Adding whch row it is
	$drag_table .= self::render_row($row, $field_type_object);
	$fid++; // Field ID (actually ROW ID) is just growing number so HTML table when submitted as form fields, would be possible to parse into rows.
}
```

So as I know how table should be formed in HTML and normally it is put together bit by bit from $field_type_object, but in this case it doesn't work that way, so I wrap it manually:
```php
public static function render_row($row, $field_type_object){
/* ... Other fields (columns) in regular way ... */
	$return .= '<td class="column-type"><select '.
		'name="'. $field_type_object->_name( "[$fid][type]") . '" '.
		'id="'	. $field_type_object->_id( '_'.$fid.'_type' ). '">';
		foreach($field_types as $key => $value){ // $field_types possible entries defined elsewhere.
			$return .= "<option value='$key' ".($row['type']==$key?"selected":"").">$value</option>";
		};
	$return .= '</select></td>';
/* ... Other fields (columns) ... */
}
```

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
