### ISSUE TITLE
Drop down list with all Revolution Slider

### ISSUE THREAD

**Issue by br0k3n** [WebDevStudios/CMB2#771]
Hi guys, is there a way to get a drop down list of all revolution sliders created to use as option?

Thanks in advance :)

**Comment by tw2113** [comment]
I'm sure there must be a way somehow, but that's more of a question for Revolution Slider support, more than our support. Not sure if they populate their own dropdown menus at all, or if they just have each be a post type, for example, but those would be good places to start.

**Comment by tw2113** [comment]
Closing as not a bug/enhancement idea.

**Comment by themevan** [comment]
Try the following codes

if ( class_exists( 'RevSlider' ) ) {
    $rev_slider = new RevSlider();
    $sliders = $rev_slider->getAllSliderAliases();
} else {
    $sliders = array();
}
