### ISSUE TITLE
CSS for repeatable group - remove icon

### ISSUE THREAD

**Issue by slaFFik** [WebDevStudios/CMB2#773]
### Expected Behavior:
When hovering on a disabled icon of a close action for a repeatable group user would possible like not to see an actionable mouse pointer (like this icon is clickable, when it's not).
That is good for UX and might save from a useless click.
Also might be a good idea to add **accessibility** text and a **title** to it.

### Actual Behavior:
When hovering on a disabled icon it still shows that it is clickable.
![image](https://cloud.githubusercontent.com/assets/282234/19457037/29a5ad8e-94cd-11e6-971c-130cdb6f7bbd.png)

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

Create a repeatable group of fields using wiki example.

**Comment by tw2113** [comment]
Related: #749

**Comment by slaFFik** [comment]
Might be fixed in #780
