### ISSUE TITLE
Pass a closure to show_on_cb param

### ISSUE THREAD

**Issue by anhskohbo** [WebDevStudios/CMB2#775]
An **Exception: Serialization of 'Closure' is not allowed** will be throw when I pass a closure to any `_cb` params:

The problem in the `CMB2_hookup::once()` method when CMB2 try  get unique key by function args.

```
$key = md5( serialize( func_get_args() ) );
```

An alternative solution is to use `jeremeamia/super_closure` but because CMB2 not use Composer, so integration it will not be positive.

Or we must find other ways :(

### Example

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		'show_on_cb' => function() {},
 		'classes_cb' => function() {}
	) );
}
```

PS: Sorry for my bad English :(

**Comment by tw2113** [comment]
For the time being, probably best to not use anonymous functions here, instead defining the function elsewhere.

**Comment by jtsternberg** [comment]
This has been a problem (and annoyed me) for a while. Thanks for reporting, and we should be good to go here now.

**Comment by anhskohbo** [comment]
Great, I can't wait for next version of CMB2 release.

**Comment by tw2113** [comment]
I say be bold and daring, try out trunk right now ;)
