### ISSUE TITLE
Not saved when data volume is high

### ISSUE THREAD

**Issue by laos94** [WebDevStudios/CMB2#778]
If the data volume is large,  data not saved,
If you delete something,when data is saved

**Is there a limit for metaboxes ?**

**Comment by tw2113** [comment]
I'm sure there'd be a limit eventually, due to things like memory and input vars for PHP, but the question is when is that.

How many metaboxes are you trying to save at one time?

**Comment by ingageco** [comment]
I'd also like to bring up this issue. I have a large amount of boxes (6-7) with varying types and amounts of fields within each. i'm currently experiencing an issue where the LAST box - whichever one you drag down to the bottom - will not display the data. If you do a before on it, the data is right in the database - but the field will not display the data. If I delete one of our metaboxes - any one - the data saves & displays fine. 

I think it has to do with the large amount of data being displayed / updated. Any ideas @jtsternberg ?

**Comment by jtsternberg** [comment]
It's entirely possible your data is exceeding your php.ini's `post_max_size`. You might try increasing that to see if it solves it.

**Comment by ingageco** [comment]
Thanks for the reply - but like I said, it's saving to the database fine. The CMB field / group just doesn't have the values set it looks like. I tried setting it manually but it still wouldn't show.

**Comment by jtsternberg** [comment]
then I'm not sure. Feel free to post your boxes/fields so we can review.

**Comment by ingageco** [comment]
@jtsternberg I'm going to open up a new issue since it persisted with some of the fields removed.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
