### ISSUE TITLE
Is any way to divide 2 columns or float left layout in options page?

### ISSUE THREAD

**Issue by websumon** [WebDevStudios/CMB2#787]
![firefox_screenshot_2016-10-31t03-31-35 039z](https://cloud.githubusercontent.com/assets/8939556/19843662/eaef5176-9f4e-11e6-94a1-0b815da8f713.png)

It's my plugin options page. i have create it by using cmb2. every field type is under down. but i want to divide it 2 columns or float left layout. is there any way  to do it in options page??

**Comment by tw2113** [comment]
I have to believe there would be, but it would take setting up custom overrides for settings rendering. As is, we stick with what WordPress core does for its markup for settings/options pages. That way the pages look as native to WordPress core as can be.

**Comment by slaFFik** [comment]
There is https://github.com/origgami/CMB2-grid, which give ability to do something similar.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
