### ISSUE TITLE
Manually added post/field meta isn't grabbed from the databse

### ISSUE THREAD

**Issue by wiejakp** [WebDevStudios/CMB2#788]
I'm adding some meta value by using add_post_meta with data I've generated, but after saving, it is not visible from admin GUI.

How to refresh cmb2 so it would grab new entries?

Thanks,

```
function cmb2_file_values($override_value, $value, $object_id, $field_args) {
    if (!empty($value)) {
        $csv_id = fjarrett_get_attachment_id_by_url($value);

        if (!empty($csv_id)) {
            $id = $field_args['id'];
            $id_array = explode('_', $id);
            $meta_group = '';

            for ($i = 0; $i < 8; $i++) {
                $meta_group .= $id_array[$i] . '_';
            }

            $meta_video = $meta_group . 'video';
            $meta_post = get_post_meta($object_id);
            $post_video_array = array();

            foreach ($meta_post as $key => $data) {
                if (strpos($key, $meta_group) !== false) {
                    $post_video_array[] = $data;
                }
            }

            $post_video_count = count($post_video_array) / 2;
            $csv_path = get_attached_file($csv_id);
            $csv_file = fopen($csv_path, 'r');
            $csv_data = array();

            while (($result = fgetcsv($csv_file)) !== false) {
                if (array(null) !== $result) {
                    if (!filter_var($result[1], FILTER_VALIDATE_URL) === false) {
                        $csv_data[] = $result;
                    }
                }
            }

            fclose($csv_file);

            $video_array = array();

            foreach ($csv_data as $temp_video) {
                $video_array[] = array(
                    'title' => $temp_video[0],
                    'url' => $temp_video[1],
                );
            }

            for ($i = 0; $i < $post_video_count; $i++) {
                array_unshift($video_array, array(
                    'title' => '',
                    'url' => '',
                ));
            }

            foreach ($video_array as $key => $data) {
                if (!empty($data['title'] && !empty($data['url']))) {
                    $title_meta = $meta_group . 'video_' . $key . '_title';
                    $url_meta = $meta_group . 'video_' . $key . '_url';

                    add_post_meta($object_id, $title_meta, $data['title']);
                    add_post_meta($object_id, $url_meta, $data['url']);
                }
            }
        }
    }

    return '';
}
```

**Comment by tw2113** [comment]
The only reason why it wouldn't match up properly, that I'm aware of, is if the meta keys aren't matching. With CMB2, that's often provided by the `id` field in a meta field configuration. If you're setting a `$prefix` of '_cmb2_' for example in the metabox configuration, you'd need to make sure that's being appended in the code above, specifically these two lines:

```
$title_meta = $meta_group . 'video_' . $key . '_title';
$url_meta = $meta_group . 'video_' . $key . '_url';
```

**Comment by wiejakp** [comment]
They are matching, I'm off with the Video Index, but I don't think that's the issue.

I'm pretty sure I need to modify the cpts_section_group_id meta as well. Is there something in CMB2 that would do that for me?

This is how I insert data by GUI:
```
cpts_section_group_id_0_cpts_section_group_video_1_title
cpts_section_group_id_0_cpts_section_group_video_1_url
```

And this is through add_post_meta:
```
cpts_section_group_id_1_cpts_section_group_video_5_title
cpts_section_group_id_1_cpts_section_group_video_5_url
```

**Comment by jtsternberg** [comment]
CMB2 groups are stored as one big array in one meta row. You need to build the whole group array and then use `update_post_meta`, not `add_post_meta`.

**Comment by wiejakp** [comment]
Where is it stored? Which entries do I have to modify?

I assume I have to change $_POST table? And then change the individual post meta?

**Comment by tw2113** [comment]
The meta key to use would be whatever `id` value you pass for the file field in question. The `$object_id` value would be the numeral ID to use for the meta. In this case, post ID.

**Comment by tw2113** [comment]
@wiejakp were your issues solved with my last replies for this issue and #786 ?

**Comment by wiejakp** [comment]
No, I'm going different route from here. I'm regenerating the object array and field data manually, but I've noticed that after the validation my group meta is being over written, field  cpts_section_group_id_0_cpts_section_group_video_1_title meta is in database correctly, but the cpts_section_group_id field is reset. 

Any thoughts on this?

**Comment by tw2113** [comment]
no immediate thoughts.
