### ISSUE TITLE
ReferenceError: tinyMCE is not defined

### ISSUE THREAD

**Issue by spwebguy** [WebDevStudios/CMB2#790]
Hi team!

First of all, this tool is **wonderful**, I've been using it for more than a year and it's the best thing I found for creating metaboxes in my WordPress plugins.

I'm having an issue since the last update of the CMB2 plugin (2.2.3). I use it for repeating groups of fields. In short, my metaboxes look like this:

- Repeatable group
    - Text field
    - Textarea

It's very simple. You just have a repeatable group with two fields in it. 

***Whenever I try to remove an item from the group (using either the red cross on the top-left corner or the "Remove" button) I get this message: ReferenceError: tinyMCE is not defined.***

Here's a screenshot of the console:
![Error screenshot](https://i.imgsafe.org/0de53dbd37.png)

 Thank you very much in advance, I appreciate all the work you do!

Gia —

**Comment by tw2113** [comment]
Curious if #730 is related to your case. Perhaps pull a copy of Trunk and re-try with that?

**Comment by jtsternberg** [comment]
Yep, as @tw2113 mentioned, this is likely resolved in trunk. Please test and let us know. Thank you.

**Comment by spwebguy** [comment]
Hi both,

Thank you for the quick response, it's very much appreciated. I will test it with the version in trunk but I'm using your CMB2 WordPress plugin as a dependency for my own plugin, and the last version is throwing this error. 

What I mean is even if trunk works, my users will always have the latest version you've uploaded on *WordPress.org*. And I don't really want to *integrated/embed* (sorry for the shitty English...) your entire code here in my plugin.

I hope this makes sense, let me know if I'm missing something... and thank you for reacting that fast.

Gia —

**Comment by hexagongirl** [comment]
Just to confirm I also had the same issue (in a front end form) as above/[#730](https://github.com/WebDevStudios/CMB2/issues/730).

Using trunk fixed it - thanks! Will use this rather than plugin for now...

**Comment by spwebguy** [comment]
Hi all,

If I was creating a plugin now I would definitely use trunk but I have thousands of active users that were prompted to install CMB2 as a dependency, if I use the trunk code in my plugin now, the CMB2 WordPress plugin will take over and throw this error (because they already have it installed).

The solution I have now is to add the trunk's code in my plugin and ask my users to delete the CMB2 WordPress plugin, but I'd rather keep it as dependency.

Hope it's clear :) Keep me posted!

GIa —

**Comment by jtsternberg** [comment]
I'm going to release a quick bug-fix update today.

**Comment by jtsternberg** [comment]
Closing, as this has been fixed, and a [release](https://github.com/WebDevStudios/CMB2/releases/tag/v2.2.3.1) [pushed out](https://wordpress.org/plugins/cmb2/changelog/).

**Comment by spwebguy** [comment]
Wow! I don't know what to say I wasn't expecting this.

Thank you very much, you're the best.

Gia —
