### ISSUE TITLE
Documentation - Link "Limit to specific page template" to "Adding Your Own show_on filter"....

### ISSUE THREAD

**Issue by rhyswynne** [WebDevStudios/CMB2#791]
Apologies if this is the wrong place to cover it, but in the documentation, should "Example: Page Template show_on Filter" on the Adding your own show_on filter page (https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters#example-page-template-show_on-filter) reference "Limit to specific page templates" on the Display Options page (https://github.com/WebDevStudios/CMB2/wiki/Display-Options#limit-to-specific-page-templates).

The reason I ask is the "Adding your own show_on filter page" shows up first on Google Search in the UK for "Show CMB2 Box on Page Template", whereas I feel we could direct people to the better solution, on the "Display Options" page.

Happy to change the documentation if need be. Thanks!

**Comment by jtsternberg** [comment]
Yah, the example on "Adding your own" should really be removed and a link to the "Display Options" be placed there instead. Good catch and good call. Would love it if you'd be willing to update. Thanks.

**Comment by rhyswynne** [comment]
Hi Justin,

Thanks for it. I've made the change. Happy to hear any other recommendations.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
