### ISSUE TITLE
Update readme: Compatible up to

### ISSUE THREAD

**Issue by slaFFik** [WebDevStudios/CMB2#793]
Update this value in `readme.txt`

```
Compatible up to: 4.4.5
```
It works with up to WP 4.7 currently.

Otherwise it shows this warning:

![image](https://cloud.githubusercontent.com/assets/282234/20309515/e3895ffe-ab50-11e6-87d2-78c241dc685a.png)

**Comment by jtsternberg** [comment]
Fixed in https://github.com/WebDevStudios/CMB2/commit/f8e7291fd99dd010c90003a13398957b088db5b0. Thank you for reporting!
