### ISSUE TITLE
Can't Add Attributes to WYSIWYG Field

### ISSUE THREAD

**Issue by pea** [WebDevStudios/CMB2#795]
The [attribute](https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#attributes) option doesn't seem to be working for WYSIWYG-type fields when they are added to a group.

To reproduce:

```php
$cmb = new_cmb2_box(
    [
        'id' => 'posts_metabox',
        'title' => 'Metabox',
        'object_types' => ['post'],
        'context' => 'normal',
        'priority' => 'high',
        'show_names' => true
    ]
);
$id = $cmb->add_field([
    'id' => 'posts_group',
    'type' => 'group',
    'description' => '',
    'options' => [
        'sortable' => true
    ]
]);
$cmb->add_group_field($id, [
    'name' => 'Text',
    'id'   => 'posts_text',
    'type' => 'text',
    'attributes' => ['data-my-attribute' => 'text']
]);
$cmb->add_group_field($id, [
    'name' => 'WYSIWYG',
    'id'   => 'posts_wysiwyg',
    'type' => 'wysiwyg',
    'attributes' => ['data-my-attribute' => 'wysiwyg']
]);
```

Executing `document.querySelector('[data-my-attribute]')` in the console returns only the text field.

**Comment by pea** [comment]
I think this was fixed in 2.2.3.1

**Comment by jtsternberg** [comment]
Yes, this is because the wysiwyg output is handled by the native WordPress `wp_editor` function, and we are not building the element as we are the others. If you're looking to modify the field output, you can use the native WP filter, `'the_editor'`.

**Comment by pea** [comment]
Got it. I ended up just wrapping the input with 'before' and 'after':

```php
$cmb->add_group_field($maincontentId, [
    'name' => 'Text',
    'id'   => $this->prefix . 'text_text',
    'type' => 'wysiwyg',
    'before' => '<div data-content-type="text">',
    'after' => '</div>'
]);
```
