### ISSUE TITLE
Hide title HTML if nothing entered

### ISSUE THREAD

**Issue by daveredfern** [WebDevStudios/CMB2#799]
Hi,

I sometimes use the title field type to display a description rather than a description and title. It would be great if the HTML wasn't printed out for a title if one is not available. I am using the following code:

```php
$homepage_boxes_meta_box->add_field( array(
    'desc' => 'This lives above the surgery search. A maximum of three is recommended.',
    'type' => 'title',
	'id' => $prefix . '_desc',
) );
```

![image](https://cloud.githubusercontent.com/assets/183473/20528144/f38d0e6a-b0c2-11e6-9836-294612fc2e25.png)

Many thanks,

Dave.

**Comment by jtsternberg** [comment]
Thanks for reporting. I've actually changed it to span if there is no `'name'` field param. It's still needed as the title field is intended to provide an anchorable section of the metabox (so, needs an ID).

**Comment by daveredfern** [comment]
@jtsternberg great, thanks for the fast turn around and keep up the good work!
