### ISSUE TITLE
text_number field

### ISSUE THREAD

**Issue by stabilimenta** [WebDevStudios/CMB2#800]
### Expected Behavior:
should allow a decimal number

### Actual Behavior:
strips out decimals, so 100.00 turns into 10000 when saved.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  
2.  

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		'id'         => 'repm_meta_container',
		'title'      => 'Rental Property Data',
		'object_types' => array('re_property_manager'), // post type 
		'context'    => 'normal',
		'priority'   => 'high',
		'show_names' => true, // Show field names on the left

	) );

	$cmb->add_field( array(
		'name' => 'Rent',
		'id'   => $repm_prefix . 'rent',
		'type' => 'text_number'

	) );

	// Additional fields...
}
```

**Comment by tw2113** [comment]
@stabilimenta is this a custom field type you've created? We don't have a text_number field type as far as I'm aware https://github.com/WebDevStudios/CMB2/wiki/Field-Types#types

I managed to get "1000,9444.00" to save, as is, with a standard text field.

**Comment by stabilimenta** [comment]
Yes, a text_field is what I reverted to. It used to be that text_number was a custom field. However, it seems to be rolled into the core now. See this: https://github.com/WebDevStudios/CMB2/pull/214

I used to have a custom function, but when I updated CMB2 it started appearing twice on my WP admin pages, so I removed my function, and then it appeared once, so it seems to be part of the core. However, there isn't any documentation of it, and it seems very buggy. (No decimals). 

BTW, I also tried using the text_money field, but found I couldn't get it to sort by that in my WP_Query, as it adds non-numeric things to the string.

The regular text field works, as long as the end user doesn't put in stupid stuff like $. Hopeing for the best. Thanks!

**Comment by tw2113** [comment]
Looks like that PR was never actually merged in, and I can't find any text_number field types in either master or trunk.

You could add your own sanitization callback to strip out things like dollar sign if you need to.

**Comment by ehrig** [comment]
You can use the text field type and manually set type to number using the attributes property. See this Gist: https://gist.github.com/jtsternberg/c09f5deb7d818d0d170b

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
