### ISSUE TITLE
Required field's label asterisk

### ISSUE THREAD

**Issue by fakeartist** [WebDevStudios/CMB2#802]
I think it would be great if an asterisk was added next to the field's label, if the field has the "required" attribute. So that the user, know from start which fields are mandatory. Any way to achieve this?

**Comment by jtsternberg** [comment]
You could do something like this: 

```php
add_action( 'admin_footer', function() {
	?>
	<script type="text/javascript">
		jQuery( '#YOUR_METABOX_ID input:required' ).each( function() {
			jQuery( this ).after( '<span style="color:red;padding-left:5px">*</span>' );
		} );
	</script>
	<?php
} );
```

**Comment by tw2113** [comment]
You could also likely make use of https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#before-after-before_row-after_row-before_field-after_field if you don't want to rely on javascript.

**Comment by fakeartist** [comment]
Excellent answers! Thank you! Would be perfect, if this feature could be added in the core.
