### ISSUE TITLE
jQuery datepicker moves september to bottom and replaces with "undefined"

### ISSUE THREAD

**Issue by ajuliano** [WebDevStudios/CMB2#803]
### Expected Behavior:
The jQuery datepicker should show all months in the dropdown.

### Actual Behavior:
Atm it moves september to bottom. Clicking "Dec" returns month 11.

<img width="295" alt="undefined" src="https://cloud.githubusercontent.com/assets/323637/20719281/b14d21f4-b65b-11e6-9b62-7bc483fdd4f2.png">

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  
2.  

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

$prefix = '_int_';

	$cmb_exhibition = new_cmb2_box( array(
		'id'           => $prefix . 'exhibition_metabox',
		'title'        => 'Utställning',
		'object_types' => array( 'kulturen_exhibition' ), // post type
		//'show_on'      => array( 'key' => 'exclude_id', 'value' => 25 ),
		'context'      => 'normal', //  'normal', 'advanced', or 'side'
		'priority'     => 'high',  //  'high', 'core', 'default' or 'low'
		'show_names'   => true, // Show field names on the left
	) );

	$cmb_exhibition->add_field( array(
			'name' => 'Startdatum',
			//'desc' => 'Välj typ',
			'id'   => $prefix . 'date_start',
			'type'    => 'text_date_timestamp',
			'date_format' => 'Y-m-d'
		) );

}
```

**Comment by bradp** [comment]
I can't seem to re-produce this locally, going to close this. Feel free to re-open if needed.
