### ISSUE TITLE
Initializing dynamic fields, is there a way?

### ISSUE THREAD

**Issue by wiejakp** [WebDevStudios/CMB2#805]
Now I understand that when I need to initialize the CMB2 box I need to use add_action outside of my function. 

Is there a way to initialize dynamic boxes other way?

This is what I go, of course it doesn't work, as add_action will not render within a function (for some reason).

```
function section_fields($prefix, $id)
{
    $meta = get_post_meta($id);
    $locations = unserialize($meta['sections_location'][0]);
    $sections = unserialize($meta['sections_category'][0]);

    foreach ($locations as $location) {
        add_action('cmb2_admin_init', function () use (&$location) {
            echo 'aaa';
            die();

            $location_name = $location['sections_location_name'];
            $location_abbr = $location['sections_location_abbr'];
            $location_prefix = 'location_' . strtolower($location_abbr) . '_';

            ${'location_' . strtolower($location_abbr)} = new_cmb2_box(array(
                'id' => $location_prefix . 'locations',
                'title' => esc_html__($location_name, 'cmb2'),
                'object_types' => array('group'),
                'options' => array(
                    'closed' => true,
                ),
            ));

            ${'location_' . strtolower($location_abbr)}->add_field(array(
                'name' => 'aaa',
                'type' => 'title',
                'id' => $location_prefix . 'title',
            ));
        });
    }
}
```

**Comment by tw2113** [comment]
Hi @wiejakp.

As far as I know, it's fine to use add_action() inside function calls, the question turns to how early are those add_action calls being called. With your example above, the function would need to be run before the code has passed the `cmb2_admin_init` hook or else it won't know it needs to invoke your callbacks there.

**Comment by wiejakp** [comment]
Ah, ok. I was running my function within `cmb2_admin_init`. I'm experimenting as so, because I though my fields are not initialized because on save there is no post meta for generated fields. Not sure why this is happening. My static fields (group name) does get saved, sop let's step back and focus on this, because this is ultimate prioblem that I am having.

I have a custom type with title and select box. Select box references another content type which stores 'locations' and 'sections' (both in this content type) and on select change, I want to generate different quantity/content of fields. I get to generate those fields, but when I get to 'save post' or 'update post' there are no meta referencing to my fields.

```
function groups_metabox_setup()
{
    $post_id = filter_input(INPUT_GET, 'post', FILTER_SANITIZE_ENCODED);
    $post_meta = get_post_meta($post_id);

    $default_name = '';
    $default_selected = '';
    $group_name = filter_input(INPUT_POST, 'group_name', FILTER_SANITIZE_ENCODED);
    $section_id = filter_input(INPUT_POST, 'section_id', FILTER_SANITIZE_ENCODED);
    $section_name = filter_input(INPUT_POST, 'section_name', FILTER_SANITIZE_ENCODED);

    // assuring we are changing the Section Year on redirect
    if (isset($section_id) && !empty($section_id)) {
        $default_selected = $section_id;
        $default_name = $group_name;
    }

    $prefix = 'groups_';

    $info = new_cmb2_box(array(
        'id' => $prefix . 'info',
        'title' => esc_html__('Group Information', 'cmb2'),
        'object_types' => array('group'),
    ));

    $info->add_field(array(
        'name' => esc_html__('Group Name', 'cmb2'),
        'id' => $prefix . 'title',
        'type' => 'text',
        'default' => $default_name,
        'attributes' => array(
            'required' => 'required',
            'type' => 'text',
        ),
    ));

    $info->add_field(array(
        'name' => 'Section Year',
        'id' => $prefix . 'year',
        'type' => 'select',
        'default' => $default_selected,
        'options' => section_years(),
        'attributes' => array(
            'required' => 'required',
        ),
    ));

    $year_id = $post_meta['groups_year'][0];

    if (isset($year_id) && !empty($year_id)) {
        $locations = get_section_meta($year_id, 'sections_location');
        $sections = get_section_meta($year_id, 'sections_location');

        foreach ($locations as $location) {
            $location_name = $location['sections_location_name'];
            $location_abbr = $location['sections_location_abbr'];
            $location_prefix = $prefix . strtolower($location_abbr) . '_';

            $field = new_cmb2_box(array(
                'id' => $location_prefix . 'locations',
                'title' => esc_html__($location_name, 'cmb2'),
                'object_types' => array('group'),
            ));

            $field->add_field(array(
                'name' => 'test',
                'type' => 'text',
                'id' => $location_prefix . 'text',
            ));
        }
    }
}
```

**Comment by jtsternberg** [comment]
That's because during `save_post` there is no `$_GET['post']`. You need to check for the post ID in `$_POST`, and it's a different key.. If I recall, it might be `$_POST['ID']`.. So you'll need to check for both.

**Comment by wiejakp** [comment]
Sorry, I meant save post/update post i meant when I click the button after creating or editing new post type. I do not modify my save_post or update_post wordpress methods.

So the problem is that when I save, the static fields are saved but dynamic ones aren't.

**Comment by jtsternberg** [comment]
Right, again, that's because when it goes through the save/update routine, your `$post_id` is empty, and so is your `$post_meta`, so your dynamic fields are not registered at the time of saving.

**Comment by wiejakp** [comment]
I owe you a couple of beers now. It worked, thanks!

**Comment by tw2113** [comment]
So everything's good here now? :dancing_men:

**Comment by wiejakp** [comment]
Correct. Thank you guys.

**Comment by tw2113** [comment]
Excellent.
