### ISSUE TITLE
Missing tags on WP SVN

### ISSUE THREAD

**Issue by khromov** [WebDevStudios/CMB2#806]
CMB2 isn't properly tagged on the WordPress.org SVN which means it doesn't work properly with WPackagist (WPackagist can't detect the correct version so it always serves up trunk, which means you will get a random version, whichever was in trunk at the time of `composer install` )

https://plugins.svn.wordpress.org/cmb2/tags/

The URL above should contain a tag folder for each release.

**Comment by jtsternberg** [comment]
This is a true statement. The SVN repo is somewhat neglected in its structure. To be honest, I'm not sure I'll ever get around to fixing the tags. I would instead recommend you use the official composer package, https://packagist.org/packages/webdevstudios/cmb2.
