### ISSUE TITLE
Remove or not show any button on group elements

### ISSUE THREAD

**Issue by wiejakp** [WebDevStudios/CMB2#807]
I'm generating groups dynamically and I don't want default 'Add Group' button on the bottom of each group.

How to remove them from the CMB2 point of view?

```
                $section_group = ${$location_prefix}->add_field(array(
                    'id' => $section_prefix . $section_abbr,
                    'type' => 'group',
                    'options' => array(
                        'group_title' => __($section_name, 'cmb2'), // since version 1.1.4, {#} gets replaced by row number
                        'closed' => true,
                        'add_button'    => '', // don't need at all!
                        'remove_button' => '', // don't need at all!
                    ),
                ));
```

![untitled](https://cloud.githubusercontent.com/assets/22645549/20804209/a1fad75c-b7b7-11e6-9a57-66201e888955.png)

**Comment by wiejakp** [comment]
left out ` 'repeatable' => false`, didn't know it's default behavior. Closing.

**Comment by tw2113** [comment]
Thanks for keeping this updated with your findings @wiejakp :)
