### ISSUE TITLE
Store and retrive field attributes

### ISSUE THREAD

**Issue by wiejakp** [WebDevStudios/CMB2#808]
We can create a field with attributes on the admin side, is there a way to save the attribute and it's value into meta, so we can use it from post type template?

**Comment by tw2113** [comment]
Well, the biggest question is where are those field attributes being saved/stored in the database? Once you know that, you'll know the best way to start using the WP functions/API to fetch wherever you need the data.

**Comment by wiejakp** [comment]
This is my question. I don't see that the attributes are stored in post meta data at all. As we initialize fields and set it's preferences we are creating only temporary attributes like default values or default selections etc. My question is, besides the setting attributes sitting in 'cmb2_admin_init' callback function, does the CMB2 store extra attribute option information elsewhere by default?

**Comment by tw2113** [comment]
What's your cmb2 config for this?

**Comment by wiejakp** [comment]
This for example. 'data-title' and 'data-unique'. Do those values get stored in database?

Not in meta:

`a:1:{i:0;a:1:{s:34:"groups_cah_section_adm_group_video";a:1:{i:0;s:13:"http://dfgdfg";}}}`

Example field setup:

```
                ${$location_prefix}->add_group_field($section_group, array(
                    'name' => esc_html__('Video', 'cmb2'),
                    'id' => $section_prefix . '_group_video',
                    'type' => 'text_url',
                    'repeatable' => true,
                    'attributes' => array(
                        'data-title' => $section_name,
                        'data-unique' => $token,
                    ),
```

**Comment by jtsternberg** [comment]
No, the only thing stored in the database is the field value.

**Comment by tw2113** [comment]
Ah, I see what you mean now. Those parts are more for the field output used to render the metabox, not something that's actually saved. Your bit above would provide something like `<input type="url" data-title="something" data-unique="token value" />` in the admin.

**Comment by wiejakp** [comment]
Well, this would be a fantastic addition! For now, I think i got my answer and I'm going to close this.

Thank you guys for being patient with me! :)
