### ISSUE TITLE
Checkbox not saved as false when set to true in default.

### ISSUE THREAD

**Issue by iiandrade** [WebDevStudios/CMB2#809]
### Expected Behavior:
When we set the **true** _(default => true)_ pattern to checkbox, it is expected that when it is unzipped it will remain unchecked when the "post" is saved.

### Actual Behavior:
When we are editing the post and the code is **"default => true"** for checkbox, and we uncheck the checkbox in the post panel it does not get unchecked when we save and refresh the page.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  Create a field of type checkbox with CMB2
2.  Set it to have the default "true"
3. Try to save the post with the checkbox unchecked.

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	$cmb = new_cmb2_box( array(
		// The metabox config
	) );

	$cmb->add_field( array(
		'name'   => __( 'Checkbox name', 'text-domain' ),
	        'desc'    => __( 'Checkbox desc', 'text-domain' ),
	        'id'         => 'checkbox-id',
		'type'     => 'checkbox',
                'default' => true
	) );

	// Additional fields...
}
```

**Comment by tw2113** [comment]
Very likely a case of boolean false evaluating to empty, prompting CMB2 to simply delete the meta key, thus falling back to the default, which is boolean true.

Better to stick with string values, like "on" and "off" or whatever your preference is to differentiate, but still provide a value for both. I believe Justin does that a lot with the examples he provides.

**Comment by jtsternberg** [comment]
This is documented in the wiki: https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#setting-a-default-value-for-a-checkbox

**Comment by iiandrade** [comment]
Maybe it's cool to deploy to the CMB2 core, so it might be a bit less complicated.

Thanks for the answers...

**Comment by anhskohbo** [comment]
An another solution for this: https://github.com/WebDevStudios/CMB2/issues/564#issuecomment-261328088

**Comment by bradp** [comment]
Looks like this is solved, closing.
