### ISSUE TITLE
Embed CMB2 fields on Content Type sub-pages.

### ISSUE THREAD

**Issue by wiejakp** [WebDevStudios/CMB2#810]
Is it possible to embed custom fields into sub-page of custom content type?

I need it just to show file upload input but not need to save it or be bound to any post ID.

Url would be something like this: `http://domain.com/wp-admin/edit.php?post_type=video&page=admin-import.php`

**Comment by tw2113** [comment]
Not quite sure i'm following the intended end result here. You want to have file field, that I assume would be used to upload something...but not save the value in any way? More context would be helpful here.

**Comment by wiejakp** [comment]
I would like to generate esthetic upload file button with ability to choose already existing uploaded file.

So I don't have to create and style my file upload functionality from scratch.

Not sure if CMB2 can do it or not.

**Comment by tw2113** [comment]
Guess I'm still not seeing the bigger picture here, as I have to believe the default media manager would cover everything needed. Even the lack of attachment to a post. Just don't trigger the media model from within the post editor, and add new items directly from that part of the admin.

Creating the field in the post editor, would attach it, I believe, and would also save as post meta. However, you don't need either of those. So you're just trying to get an image uploaded so you could paste the url into the primary post content editor?

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
