### ISSUE TITLE
"cmb2_save_field",how to use?

### ISSUE THREAD

**Issue by a7517** [WebDevStudios/CMB2#811]
I want to modify the replacement data.

**Comment by tw2113** [comment]
I'm a little confused. Are you trying to intercept and modify the data before it gets saved? or intercept and override the returned value?

For intercepting and overriding the to-be saved value, I'd recommend checking out these filters: https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Field.php#L292-L326

For intercepting and overriding the returned value, I'd recommend checking out these filters: https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Field.php#L226-L262

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
