### ISSUE TITLE
[Contribution] : field type post search ajax

### ISSUE THREAD

**Issue by alexis-magina** [WebDevStudios/CMB2#812]
Hello,

I made this new custom field type [cmb2-field-post-search-ajax](https://github.com/alexis-magina/cmb2-field-post-search-ajax).

The approach is the same than CMB2 Attached Posts Field but with Ajax request, multiple/single option, and different UI.

Feel free to test it and reference it on 3rd party resources if you like it :-)

**Comment by proweb** [comment]
wow. thanks man, that UI what I was looking

**Comment by jtsternberg** [comment]
Looks awesome, nice work!

**Comment by alexis-magina** [comment]
I'm glad you like it.
If someone is interested, I just forked a plugin from [harryfinn](https://github.com/harryfinn/yoast-cmb2-field-analysis) which allow fields to be analysed by YoastSEO WP Plugin. 
You can find it here [yoast-cmb2-field-analysis](https://github.com/alexis-magina/yoast-cmb2-field-analysis)
It is basic for now and surely requests enhancements, but it works for text inputs and textareas. 
Feel free to contribute :-)

**Comment by jtsternberg** [comment]
Sure, thanks for the resource.
