### ISSUE TITLE
CSS: height/paddings for text_datetime_timestamp_timezone field

### ISSUE THREAD

**Issue by slaFFik** [WebDevStudios/CMB2#815]
Currently CSS for `text_datetime_timestamp_timezone` field with everything default is a bit broken. Take a look at the screenshot:

![image](https://cloud.githubusercontent.com/assets/282234/21064990/c0653fb0-be66-11e6-9084-18e0bb261851.png)

Using example field registration from wiki.
Chrome 54.0.2840.99 m (64-bit) on Windows 10.

**Comment by tw2113** [comment]
i'd say inconsistent more than broken, but semantics :D

**Comment by slaFFik** [comment]
Hm, well, you are technically right. But I will not edit the description to preserve the conversation to be still valid :)

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
