### ISSUE TITLE
Radio button + text input

### ISSUE THREAD

**Issue by fakeartist** [WebDevStudios/CMB2#817]
Hi! Does anyone know any way to achieve this field? Basically, what I need is in one of the radio buttons to give the ability to the user to insert a text input.

![screenshot_2](https://cloud.githubusercontent.com/assets/2536468/21072539/0bb289e2-becf-11e6-9148-85451dec27b6.jpg)

Thanks a lot for any ideas!

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.
