### ISSUE TITLE
Repeatable field group with a single title field

### ISSUE THREAD

**Issue by Julianoe** [WebDevStudios/CMB2#822]
I can't find how i can to this with CMB2, every tweaks i tried don't seem to work. I concluded 

What i'm trying to do : a repeatable group of text field + text area field ... but with a single textarea attached to this group.

Did someone created something similar already with CMB2 ?

(i did not know where to ask other than here :/ )

**Comment by tw2113** [comment]
May be best to leave the single title field as a separate meta key/value instead of trying to lump it in with the repeatable field groups. Hopefully I'm understanding what you're aiming for here.

**Comment by Julianoe** [comment]
Hi ! Thanks for the answer.
I understand what you mean but what i want to achieve is multiple "sections" built like this : 

*My single Section Title*
**Label field : content field**
**Label field : content field (repeatable)**
**Label field : content field**

*My single Section Title 2*
**Label field : content field**
**Label field : content field (repeatable)**
**Label field : content field**

The number of repeatable groups (and fields inside those groups) could vary... I'm not sure i'm clear ^^
Do you think there is a way to do this ?

**Comment by Julianoe** [comment]
Hello @tw2113 : i've tried the following ; 
```php
add_action( 'cmb2_admin_init', 'repeatable_group_field_metabox' );
function repeatable_group_field_metabox() {
	$prefix = 'myprefix_';
	/**
	 * Repeatable Field Groups
	 */
	$cmb_presentation_fields = new_cmb2_box( array(
		'id'           => $prefix . 'metabox',
		'title'        => __( 'Custom Contents', 'cmb2' ),
		'object_types' => array( 'myposttype' ),
	) );

	$my_repeatable_group = $cmb_presentation_fields->add_field( array(
		'id'          => $prefix . 'custom_entries',
		'type'        => 'group',
		'description' => __( 'Generates reusable form entries', 'cmb2' ),
		'options'     => array(
			'group_title'   => __( 'Bloc {#}', 'cmb2' ),
			'add_button'    => __( 'Add Another Entry', 'cmb2' ),
			'remove_button' => __( 'Remove Entry', 'cmb2' ),
			'sortable'      => true,
			'closed'     => true
		),
	) );

	$cmb_presentation_fields->add_group_field( $my_repeatable_group, array(
		'name'       => __( 'Title', 'cmb2' ),
		'id'         => 'title',
		'type'       => 'text',
	) );

  $cmb_presentation_fields->add_group_field( $my_repeatable_group, array(
		'name'       => __( 'Text Entry', 'cmb2' ),
		'id'         => 'text_content',
		'type'       => 'textarea_small',
    'repeatable' => true // i've made this one repeatable
	) );
}
```

It's a repeatable group of two fields (title and content). Title with allow to enter the "My single Section Title" from above and all the content goes in the text_content field.

Now i did try to display this content but i'm obviously missing something ...
```php
$entries_group_field = get_post_meta( $theID, 'wine_group_repeatable_custom_entries', true );

						foreach ( (array) $entries_group_field as $key => $entry ){
							$title = $content = '';

							if( isset( $entry['title'] ) ) {
								$title = '<h2>'.esc_html( $entry['title'] ).'</h2>';
							}

							if( isset( $entry['text_content'] ) ) {
								$content = wpautop( $entry['text_content'] );
							}

							echo $title;
							echo $content;
							echo 'hello';

						}
```

**Comment by tw2113** [comment]
Did you figure it out? Since you closed the issue yourself?

**Comment by Julianoe** [comment]
I edited the previous message ;)

**Comment by tw2113** [comment]
Word, thanks Julien
