### ISSUE TITLE
file_list link to existing folder inside wp-content/uploads/my-custom ??

### ISSUE THREAD

**Issue by medlemark** [WebDevStudios/CMB2#825]
uploaded 10k images to my custom uploads folder wp-content/uploads/my-custom
and using while loop i have generated attachment for all my images that are inside my-custom folder using 
$attach_id = wp_insert_attachment(  );
how can i link to CMB2 file_list i tried to build it manual like this but did not work 
a:1:{45:"mylink"}
how can i insert file_list using custom code ??

**Comment by tw2113** [comment]
Hey @medlemark if you could, please open a support thread at https://wordpress.org/support/plugin/cmb2 for this question.

We try to keep GitHub issues for possible/confirmed bugs, or enhancement ideas. This here is more along the lines of helping use it and customization of your website.

Thanks.
