### ISSUE TITLE
Value of "disabled" text field get resetted

### ISSUE THREAD

**Issue by psaikali** [WebDevStudios/CMB2#829]
Hi !

### Expected Behavior:
I have a couple of simple text fields in a metabox, with the 'disabled' attribute enabled so the field is not editable. It's here only to see a value. 
The post meta is dynamically added/updated via my code, not manually added.
![capture 2017-01-08 a 14 21 22](https://cloud.githubusercontent.com/assets/1606655/21750201/1c698b50-d5ae-11e6-8dde-40f23c4306cf.png)

### Actual Behavior:
When I dynamically create a (pending) post with wp_insert_post() and add a value for theses 2 fields with update_post_meta(), both fields initially display the value in a disabled field.
![capture 2017-01-08 a 14 28 32](https://cloud.githubusercontent.com/assets/1606655/21750227/c491add0-d5ae-11e6-92e3-288674bc5e9b.png)

So far so good.
I soon as I publish my post manually via the WP back-office, the field value disappear and my disabled inputs are empty.
![capture 2017-01-08 a 14 29 08](https://cloud.githubusercontent.com/assets/1606655/21750229/da465702-d5ae-11e6-8c53-648acce5e4e6.png)

Post meta in database also disappear.
If I remove the "disabled" attribute on these fields, everything works as expected.

### CMB2 Field Registration Code:

```php
	$message_annonce_fields->add_field(
		array(
			'name'       => __('Annonce', 'mestravaux'),
			'id'         => 'annonce_id',
			'type'       => 'text_small',
			'attributes' => array(
				//'disabled' => 'disabled'
			),
			'column'     => array('position' => 3),
			'display_cb' => 'mt_message_annonce_id_display',
		)
	);

	$message_annonce_fields->add_field(
		array(
			'name'       => __('Artisan', 'mestravaux'),
			'id'         => 'artisan_id',
			'type'       => 'text_small',
			'attributes' => array(
				//'disabled' => 'disabled'
			)
		)
	);
}
```

Any idea why ?
Seems like CMB2 doesn't care if my disabled field has a value.

Thanks for your help.

**Comment by jtsternberg** [comment]
You'll probably need `readonly` instead of `disabled`.

**Comment by psaikali** [comment]
Awesome, it's working.
Thanks a lot !!
