### ISSUE TITLE
Cleaning the group

### ISSUE THREAD

**Issue by m-pokrovskii** [WebDevStudios/CMB2#833]
Hi. I have created a new field type and added an image inside( or any not an input related html tags). In the new group item the image is still apear. I know that group fields are cleaned by the JS. But how i can remove the image?

**Comment by tw2113** [comment]
Hey @m-pokrovskii can you please start a support thread over at https://wordpress.org/support/plugin/cmb2 for this issue? Also, when you do, could you provide the CMB2 configuration and any other related PHP code you're using, so I can potentially set things up on my localhost for testing purposes?

We try to keep the GitHub issues for confirmed bugs or enhancements. If we confirm it is indeed a bug, we will return things here with the new findings.

Thanks.
