### ISSUE TITLE
WP_Query in options callback causes data not to show (affects next save)

### ISSUE THREAD

**Issue by ingageco** [WebDevStudios/CMB2#835]
### Expected Behavior:

Metabox with group (repeatable, sortable) that contains selects. Each select's options are populated by a options_cb that has a WP_Query. Query just grabs post ID and title from another post type and outputs a compatible array, with the key being the ID and the value being the title.

### Actual Behavior:

Fields save in the database, but the metabox doesn't reflect that it saved. Looks as if it's newly created. Not only does it affect this field, but it affects the display of every CMB2 meta box below it. The boxes below show the same way, but boxes above the problem field are unaffected.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  Setup a new field as I detailed above using the code below (or similar)

### CMB2 Field Registration Code:

```php
add_action( 'cmb2_admin_init', 'yourprefix_register_demo_metabox' );
function yourprefix_register_demo_metabox() {

	    $event_speakers = new_cmb2_box( array(
        'id'            => 'iphc_event_speakers',
        'title'         => __( 'Event Speakers', 'cmb2' ),
        'object_types'  => array( 'events' ), //Post type
        'context'       => 'normal',
        'priority'      => 'high',
        'show_names'    => true, // Show field names on the left
    ) );

	$speakerGroup = $event_speakers->add_field( array(
	    'id'          => 'iphc_event_speakers_list_group',
	    'type'        => 'group',
	    'repeatable'  => true, 
	    'options'     => array(
	        'group_title'   => __( 'Speaker {#}', 'cmb2' ),  
	        'add_button'    => __( 'Add Another Speaker', 'cmb2' ),
	        'remove_button' => __( 'Remove Speaker', 'cmb2' ),
	         'sortable'      => true, 
	        'closed'     => false, // true to have the groups closed by default
	    ),

	));

	$event_speakers->add_group_field( $speakerGroup, array(
	    'name' => 'Speaker',
	    'id'   => 'speaker_id',
	    'type' => 'select',
	   'options_cb' => 'get_speaker_list_options',
	) );
}


function get_speaker_list_options($field){
	    
 
	$args = array(
		'post_type' => 'speakers',
		'posts_per_page' => '-1',
		'orderby' => 'title',
		'order' => 'ASC'
	);
 
 	$speakOps = array();

 
	$speaks = new WP_Query($args);


	if($speaks->have_posts()) : 
		while($speaks->have_posts()): $speaks->the_post();

			$id = get_the_ID();
			$title = get_the_title($id);

			$speakOps[$id] = $title;

		endwhile;
	endif;

	wp_reset_postdata();
 
	return $speakOps;

}

```

**Comment by ingageco** [comment]
I've confirmed this in a fresh install. I replaced the WP_Query with get_results($sql) and it works as expected.

**Comment by tw2113** [comment]
I wonder if this is related at all, which coincidentally came up in internal chat this morning: https://core.trac.wordpress.org/ticket/18408

**Comment by ingageco** [comment]
Great find @tw2113 ! Certainly could be it.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if needed.

**Comment by davidlonguk** [comment]
Also getting this issue
