### ISSUE TITLE
Repeatable group doesn't fill the default value

### ISSUE THREAD

**Issue by Areha11Fz** [WebDevStudios/CMB2#845]
### Expected Behavior:
repeatable group auto fill the new group added.

### Actual Behavior:
Repeatable group doesn't fill the default value.

### CMB2 Field Registration Code:
	$link_download = $cmb->add_field( array(
			'name' => __( 'Link Download', 'dln' ),
			'id' => $prefix . 'link_download',
			'type' => 'group',
			'options' => array(
				'group_title' => 'episode {#}',
				'add_button' => 'tambah episode',
				'remove_button' => 'hapus episode',
				'sortable' => true,
			),
	) );

		$cmb->add_group_field( $link_download, array(
			'name' => __( 'Episode', 'dln' ),
			'id' => $prefix . 'episode',
			'type' => 'text_small',

		) );

		$cmb->add_group_field( $link_download, array(
			'name' => __( 'Kualitas 1', 'dln' ),
			'id' => $prefix . 'kualitas',
			'type' => 'text_small',
			'default' => '480p',

		) );
```

**Comment by tw2113** [comment]
@Areha11Fz did you figure out a solution to this? or realized you set something up wrong and it was working like it should?

**Comment by Areha11Fz** [comment]
yes, i find the solution about this.
why the added row doesn't fill automatically by the default value instead the empty value?

**Comment by tw2113** [comment]
Will tinker a bit later and see if I can come up with anything

**Comment by tw2113** [comment]
@jtsternberg I think this one is boiling down to the js/clone functionality.

**Comment by jtsternberg** [comment]
This is likely similar to #768. Please review that issue.

**Comment by bradp** [comment]
Closing due to no movement here. Feel free to re-open if applicable.
