### ISSUE TITLE
are callbacks only functions in the global namespace?

### ISSUE THREAD

**Issue by AlchemyUnited** [WebDevStudios/CMB2#849]
I think I asked that the right way? :)

Maybe I'm misreading, or can't find an example, but it looks like the _cb's are all called directly and not via an action hook.  Is there no way to encapsulate the _cbs as methods within a class? 

Perhaps there's a work around? Or something?

tia

**Comment by tw2113** [comment]
Just as an offshoot chance, perhaps pass in an array with the class and then method, similar to how you apply them to hooks. Worth a shot in my mind. Also, hello quick reply ;)

**Comment by jtsternberg** [comment]
@tw2113 is right, something like:
`'escape_cb' => array( $this, 'my_escape_callback_method )`

**Comment by AlchemyUnited** [comment]
@tw2113 + @jtsternberg 

Ok. Thank you.
