### ISSUE TITLE
JS error for plugin using CMB2 (with repeatable TinyMCE)

### ISSUE THREAD

**Issue by spwebguy** [WebDevStudios/CMB2#850]
Hi all,

I'm getting a "generic" JS error in the console when clicking the Add Media button of a CMB2 repeatable TinyMCE field in my plugin.

Everything else works fine. The Add Media button works fine for the Post/Page custom types, it's a clean WordPress install with the default theme and no other conflicting plugin. Would you have any clue where this might come from?

Thank you very much for the framework, keep up the great work. 

![js-error](https://cloud.githubusercontent.com/assets/8936613/22397814/0bca7998-e572-11e6-8105-9e27fe39d171.png)

**Comment by tw2113** [comment]
Can you set SCRIPT_DEBUG to true in your wp-config.php file so that the WP admin will use the unminified/unconcatenated versions of js files? It'll help better track down the source of the issue. May or may not be directly related to CMB2, but we'll need to check.

Thanks.

**Comment by spwebguy** [comment]
Thank you for the quick answer, very much appreciated.

Here's the new log:
![log-js](https://cloud.githubusercontent.com/assets/8936613/22399422/2d67a8b0-e594-11e6-8ea3-2116c486e86e.png)

**Comment by tw2113** [comment]
Hmm, nothing obvious sticking out to me, but I don't have the backbone chops to really know for sure. @jtsternberg Do you have any idea on this one?

**Comment by bradp** [comment]
I'm not seeing CMB2-specific issues here, going to close. 
Please re-open if this is CMB2-specific.
