### ISSUE TITLE
Remove error silencing

### ISSUE THREAD

**Issue by ernilambar** [WebDevStudios/CMB2#851]
I downloaded CMB2 plugin (version 2.2.3.1) from directory and embeded in the theme. 

When theme is checked with new sniffs, following error appears.
`FILE: simple-life/cmb2/includes/CMB2_Utils.php`
`Line: 404 ERROR Silencing errors is forbidden`

Code is `$parsed = @parse_url( $file, PHP_URL_PATH );`

This is sniffer repo for Theme Check plugin. https://github.com/WPTRT/WordPress-Coding-Standards

We may want to fix that because new Theme Check plugin will not allow theme embedded with CMB2 due to this error.

**Comment by jtsternberg** [comment]
Fixed with https://github.com/WebDevStudios/CMB2/commit/5870a5acab64166b1f4ca848bc42c59ed5a96ed1
