### ISSUE TITLE
How to give credits?

### ISSUE THREAD

**Issue by ShariqKhan2012** [WebDevStudios/CMB2#854]
This is not an issue, but a question. I created it as an issue because I could not find any other way to leave a comment or ask a question. 
So here it goes.

I have used CMB2 to create a plugin. Many of the features of that plugin would not have possible (without writing a whole lot of custom code) if it were not for CMB2. 
So many thanks to the WebDevStudios team for this plugin.

Now my question is where do I put credits for CMB2 in my plugin? Should I do it in a readme file, or within the code or an accomponying credits.txt file? Or perhaps some other better place?

Thanks.

**Comment by jtsternberg** [comment]
Glad you've found it helpful. No credit is required but if you feel inclined, any of the ways you mentioned sound reasonable.

**Comment by ShariqKhan2012** [comment]
Many thanks. Yes, I appreciate the hard work that you guys and many contributors have put in this tool and and giving credits is the least I can do as a token of my appreciation.
I will add the credits in one of the ways when I release it.
Right now doing some testing :)

**Comment by ShariqKhan2012** [comment]
Quick question: I read in one of the comments that CMB2 loads only one instance. So if there are multiple plugins (say P1, P2 and P3) that use CMB2, then only one  instance will be loaded for all of them.

Does this also mean that if one of the plugins (P1) is not using the latest version of CMB2, then it could cause problem for other plugins (P2 and P3) too if the instance of CMB2 is loaded from the not-up-to-date library coming from P1?

**Comment by jtsternberg** [comment]
Only the most recent version that exists in the system will be loaded. For more info, I've abstracted the loader into it's own library, and the readme should explain it well (but let me know if not!): http://jtsternberg.github.io/wp-lib-loader/

**Comment by ShariqKhan2012** [comment]
That looks super helpful!. However, I have some lingering doubts.
Let's say while working with CMB2, I've encountered some issues with repeatable-groups that have not been fixed in the trunk. However, I have managed to patch those issues with some custom code. BUT it is just that- a patch. It fixes the issues bugging my project, but do not do anything for the other known issues. More so, it may even break other functions for some other projects using CMB2.
But since it works well for my project, I decide to anyway go ahead with it and knowlingly assign a higher version to the library, so that my CMB2 library project is being used.

Now there can be 2 things:

1. My version of CMB2 contains fixed just relevant for my project, and so it may break some other plugin
2. Somebody else thinks the same way and has already assigned his version of CMB2 a version number higher than mine. So it would be his version of CMB2 that would be used, thus making my plugin error prone.

Could this happen?

As a side note, there are many issues with repeatable groups that have been in opened state for quite a long time. Most of these are related to incorrect assigning of index to group/row elements after some elements have been added/removed.
I totally understand that it is quite difficult for you to invest time in a project that demands much in terms of coding and testing efforts. And on top of which the project is open-source and is not a source of revenue for you. And that is exactly why I so much appreciate your efforts and contribution towards making this plugin accessible to all. 
The thing is that those issues need to be fixed to make this already awesome library even more awesome. So, understanding that you might be busy in some other projects or that this be not on the radar right now, I would like to try to fix some of those issues. 
But if you could please let me know whether there's already some work-in-progress for fixing those issues, that would be great. because my JavaScript skills are not that great and I would have to spend sometime updating my skills and understanding the code.
So if there's already some work going on, I dont see the point of me doing that because there are already brighter minds working on it.
But f no work is on for it , then I would be more than happy to contribute by trying to fix it and/or testing.

Your thoughts?

**Comment by jtsternberg** [comment]
For your first question, just like with WordPress core, or any other plugin you download/use, you should never edit the core files of CMB2 (unless you're in a development version working a patch). As you outlined, it is not a reliable practice, and you risk breaking CMB2 for other things depending on it, or having your patch be ignored when a new version of CMB2 is released.

As for the second, we take Pull Requests all the time, and would be happy to look at one that addresses any of these issues. If you want to see if anyone has begun work on them, feel free to look through the pending pull requests.
