### ISSUE TITLE
Modify CMB2 Templates

### ISSUE THREAD

**Issue by kingstakh** [WebDevStudios/CMB2#855]
Hi! Thank you for great work!
Have question about fields template modification. I use CMB2 with front end submission and my WP Theme based on Bootstrap framework. How modify CMB2 radio_inline template to Bootstrap like this https://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

**Comment by jtsternberg** [comment]
To do that, you'll likely need to create your own custom field type, https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-field-types

**Comment by bradp** [comment]
Looks to be resolved here, going to close. Feel free to re-open if needed.
