### ISSUE TITLE
Taxonomy select field type, broken during sanitization

### ISSUE THREAD

**Issue by JayWood** [WebDevStudios/CMB2#857]
### Expected Behavior:

To run `wp_set_object_terms()` when using `taxonomy_select` field type on a non-options page.

### Actual Behavior:

When using `taxonomy_select` for the field type, the condition seems incorrect during data sanitization.

See - https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Sanitize.php#L124

It seems the conditional here is just backwards.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

```
$this->metabox->add_field( array(
            'name'              => __( 'Location', 'textdomain' ),
            'id'                => $prefix . 'location',
            'taxonomy'          => 'category',
            'type'              => 'taxonomy_select',
            'remove_default'    => 'true',
        ) );
```

**Comment by JayWood** [comment]
@jtsternberg Yo, was going to fix this today, but I'm unsure of the relationship between trunk here, and the .ORG trunk - mind getting me up to speed, is there one person who handles that, etc...

You also have me on the NC slack if PM's are required, just hit me up.

**Comment by tw2113** [comment]
@JayWood trunk on GH is the development version. master GH = .org trunk, which is the stable release.

**Comment by JayWood** [comment]
Thanks @tw2113

**Comment by jtsternberg** [comment]
Hey @JayWood, i'll probably need more info about the context you are using this. The taxonomy fields all depend on the default WordPress hooks to store the terms (`wp_set_object_terms()`). This is accomplished by using the same field names as the default WP term fields. Any context outside of the post new/edit screens, they will likely fail to be associated.

The conditional you pointed to is simply whether the sanitized values are returned, a do not reflect anything being saved.

I could see the need to update the taxonomy fields to be able to set the object terms when the default saving mechanisms are not possible, but will need to introduce some hairy logic to determine if/when it's needed.

**Comment by JayWood** [comment]
@jtsternberg The only context I have at this point is that the `taxonomy_select` field is now ( with the latest updates on trunk ) are not saving now.

It seems at this point that I need to look deeper into the taxonomy_select as a whole I guess.

Looking at the docblock for the 2.2.4 tag it states:
> Sets the object terms to the object (if not options-page) and optionally returns the sanitized term values.

But the related conditional is contrary to that ( line 124 ):
```
			if ( 'options-page' !== $this->field->object_type ) {
				$return_values = true;
			} else {
				wp_set_object_terms( $this->field->object_id, $this->value, $this->field->args( 'taxonomy' ) );
				$return_values = false;
			}
```

`wp_set_object_terms()` is ran in the else, which means if it IS an options page. Where else in CMB _( I can look obviously )_ are we running this? Again, maybe I need to look deeper into the `taxonomy_select` field type?

**Comment by jtsternberg** [comment]
To be clear, CMB uses the `tax_input` `$_POST` namespace so that WP will takeover in `edit_post()https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/post.php#L328-L372

**Comment by jtsternberg** [comment]
huh, I think I need to re-review how this works, and test trunk. You bring up some good points, and i'm trying to remember how it all works.

**Comment by JayWood** [comment]
I'll do some digging on our side as well - will update this accordingly.

**Comment by jtsternberg** [comment]
> It seems the conditional here is just backwards.

That was it. I'm a dummy. Thank you for reporting and being so thorough!

**Comment by JayWood** [comment]
@jtsternberg good to know you're still human ❤️

**Comment by jtsternberg** [comment]
Ha, sometimes a little too much!

**Comment by JayWood** [comment]
I shall go ahead and get this fixed then :D thanks for clarifying!

**Comment by JayWood** [comment]
LOL nvm, speed demon! Thanks again @jtsternberg

**Comment by banago** [comment]
`taxonomy_select` still not saving for me. Did you manage to tackle this back then @jtsternberg?

**Comment by tw2113** [comment]
@banago Just to be certain, because it's a detail that trips people up still. Are you checking the associated terms for the object being saved? or are you checking the post meta? You'd want the former with associated terms being set/updated with the field.
