### ISSUE TITLE
Featured image instead of "file upload"?

### ISSUE THREAD

**Issue by moreplavec** [WebDevStudios/CMB2#858]
### Expected Behavior:
I'm trying to create custom post with CMB2. All works fine, but is there an option to create featured image just like in reagular post to be able set it's size while used in template? Now, with posts i use this in my functions.php, but missing this in CMB2:

```php
add_theme_support ( 'post-thumbnails' );
add_image_size ( 'large-thumb', 1060, 600, true );
```
Thanks for your time, CMB2 is awesome!

**Comment by Cai333** [comment]
The file field stores the attachment ID (in the form of `$id . '_id'`) so you can use that to get any size you need (the image is still uploaded with your custom sizes as any image is). You can do something like the [example in the wiki](https://github.com/WebDevStudios/CMB2/wiki/Field-Types#file):

    $image = wp_get_attachment_image( get_post_meta( get_the_ID(), 'wiki_test_image_id', 1 ), 'your-custom-size' );

Does that not give you what you need? Alternatively, can't you just use the built-in WP featured image on your custom post type as you do with posts?

**Comment by jtsternberg** [comment]
The featured image is simply a post meta field which stores an attachment ID. If you simply want to replace the default featured image field with a CMB2 field, but continue using the frontend thumbnail functions (`has_post_thumbnail()`, `get_post_thumbnail_id()`, `the_post_thumbnail()`, etc), you can do so by using `_thumbnail` as your field id, and the `_thumbnail_id` key (the featured image meta key) will automatically be populated with the attachment ID.

**Comment by bradp** [comment]
Looks to be resolved here, going to close. Feel free to re-open if needed.
