### ISSUE TITLE
date picker not display on firefox

### ISSUE THREAD

**Issue by chomomahesh** [WebDevStudios/CMB2#859]
hello, im using kupon wordpress theme, cmd inside on theme, when i open form on firefox browser its not display date-picker. i asked from theme owner about this issue but they mentioned remove the "Type="date"", but it wasn't work can i know how to fix this issue.

**Comment by tw2113** [comment]
Can you provide some screenshots of what it's looking like when you try to use the date picker? Also if you're familiar with your browser developer tools, any errors appearing in he javascript console would be awesome if you could provide those as well.

**Comment by chomomahesh** [comment]
![dateissue](https://cloud.githubusercontent.com/assets/25505315/23002526/3ec3fa24-f411-11e6-8e68-3e9b5f762732.jpg)

![console](https://cloud.githubusercontent.com/assets/25505315/23002552/67b7426a-f411-11e6-865a-33faf53defc2.jpg)

![inspect](https://cloud.githubusercontent.com/assets/25505315/23002576/90b9778c-f411-11e6-86c6-2d1f8bd3d1da.jpg)

i think issue is firefox not support html 5, is there way to change cmb2

**Comment by jtsternberg** [comment]
The input you are showing is not a CMB2 input, and CMB2 does not use `type="date"`. Looks like you'll need to take your support request to the developer of your theme.

**Comment by chomomahesh** [comment]
Thank you jtsternberg.
