### ISSUE TITLE
textarea_code strips back slashes

### ISSUE THREAD

**Issue by Timofey81** [WebDevStudios/CMB2#862]
There is no way to maintain back slashes in source code. This is happening because of stripslashes_deep CMB2_Sanitize constructor

**Comment by tw2113** [comment]
Just for my understanding, are you using this for storing code that is intended to be executed? or just for display? I have a feeling this field type is meant more for display only.

**Comment by bradp** [comment]
No response here, going to close. Feel free to re-open if needed.
