### ISSUE TITLE
fields order

### ISSUE THREAD

**Issue by riccardoracci** [WebDevStudios/CMB2#864]
is there a way to specify the fields' order ?

**Comment by tw2113** [comment]
The order you declare/add them is the order they're rendered, generally. Field types with "sortable" make it so that the user can arrange them at the time of populating, but that is going to be different than a text field being provided first, followed by a radio button, in regards to UI rendering.

**Comment by bradp** [comment]
Looks to be fixed, going to close. Feel free to re-open if needed.
