### ISSUE TITLE
How to intercept save_post

### ISSUE THREAD

**Issue by guile-d** [WebDevStudios/CMB2#870]
Hello,
I'm new with CMB2 and i have a problem to intercept a hook before save. Sorry for my bad English.

I have a field "city" in my custom post type (directory)
```
$cmb = new_cmb2_box( array(
			'id'            => 'adress_meta_box',
			'title'         => 'Adress',
			'object_types'  => array( 'directory'), // post type
			'context'       => 'normal', 
			'priority'      => 'high', 
			'show_names'    => true,
			'cmb_styles'    => true, 
			'closed'        => false, 
		) );
		$cmb->add_field( array(
			'name' => 'City',
			'id'   => 'city',
			'type' => 'text_medium',
		) );

```
I would like before save call my function "geolocalize ($city)" and return lat -lng into 2 meta_key.
these meta_key are not visible fields.

When i'm not use CMB2, i use a hook save_post like this, and it works!!

	public function save_custom_content_type($post_id)
	{
		//check for nonce
		if(!isset($_POST[$this->content_type_name . '_nonce_field'])){
			return $post_id;
		}
		//verify nonce
		if(!wp_verify_nonce($_POST[$this->content_type_name . '_nonce_field'] , $this->content_type_name . '_nonce')){
			return $post_id;
		}
		//check for autosaves
		if(defined('DOING_AUTOSAVE') && DOING_AUTOSAVE){
			return $post_id;
		}
		//check if the user can edit
		if(!current_user_can('edit_posts')){
			return $post_id;
		}
		//collect sanitized information
		
		$city= sanitize_text_field($_POST['city']);
		
		 $encode = $this->geolocalize( $city );
                  .....
                 ....... // some code

		update_post_meta($post_id,'lat',$encode);

               update_post_meta($post_id,'test_meta', 'blablabla'); // work
               
               update_post_meta($post_id,'city', 'blablabla'); // not save value in city field
               
		
	
	}

But with CMB2, it doesn't work or i don't understant how to make this.

All fields created by CMB2 are not active in my save_custom_content_type function
ex: update_post_meta($post_id,'test_meta', 'blablabla'); => work, because field are not created by CMB2 but update_post_meta($post_id,'city', 'blablabla'); => not work, in my DB, it's always the older value

Actually, my question is "how to intercept data after push on wordpress update button, make operations and inject result in a CMB2 meta_key"
Could you help me?

Guillaume

**Comment by guile-d** [comment]
i ve tested with

```
add_action( 'save_post', array($this, 'geo_wal'), 10, 2 );
 
	function geo_wal ( $post_id, $post ) {

		update_post_meta( $post_id, 'city', 'mycity' );  //not work, no change in DB
		 update_post_meta( $post_id, 'meta_test', 'value meta'); // work Change ok in DB
	}
```

**Comment by tw2113** [comment]
If I'm understanding correctly, you want to basically intercept the saved City value, and use that to save geolocation coordinates for it, off to the side in their own meta field, perhaps some not exposed to the UI.

I'm thinking this filter would be a good start https://github.com/WebDevStudios/CMB2/blob/trunk/includes/CMB2_Field.php#L334-L343

The actual filter name you attach things to would be `cmb2_override_city_meta_save`.

With this, you'd be passed the value being saved to the City value, and you could pass that through your 
`geolocalize()` method, and do what you need with that part. I would then return null from the callback, so that CMB2 will continue to save the city value like expected. That way the user doesn't need to re-save each time the page loads.

**Comment by jtsternberg** [comment]
That's actually exactly what the [`sanitization_cb`](https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#sanitization_cb) and [`escape_cb`](https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#escape_cb) field parameters are for. To handle sanitizing your field, and saving/splitting off other values, etc. Keep in mind, if you use these, CMB2 won't handle the sanitization/escaping at all, so you will need to do that.

**Comment by guile-d** [comment]
Thanks for your answer michael & justin.

Yes, I would like when I press update,
1) retrieve the field 'city'
2) pass the value to my geolocation function
3) Retrieve this value and store it in a meta_key "coordinated"

like this

```
$city= sanitize_text_field($_POST['city']);
$encode = $this->geolocalize( $city );
update_post_meta($post_id,'coordonate',$encode);
```
i will try to test cmb2_override_city_meta_save, sanitization_cb and escape_cb

**Comment by guile-d** [comment]
I did not succeed using your functions but with save_post it works, just change the priority.
It did not work because the value was overwritten by the "save_post" of CMB2 I suppose
Thanks for your help

**Comment by tw2113** [comment]
Whatever works for you, in the end. :)
