### ISSUE TITLE
"Insert Media" modal does not show dropdown-filter

### ISSUE THREAD

**Issue by arkonisus** [WebDevStudios/CMB2#873]
The media-modal which opens with the CMB-fields "file" or "file_list" does not show the attachment filter dropdown. If there is a big amount of files the search-filter-box on the right is not the best solution. 
![media](https://cloud.githubusercontent.com/assets/7242966/23619142/fdbffe8e-0292-11e7-871e-9bdd1308a87c.gif)

As a workaround you can use the Plugin https://de.wordpress.org/plugins/default-media-uploader-view/ which lets you preselect "Uploaded to this post". But then - because of the missing dropdown - you are not able to return to show all files ... ;)

**Comment by jtsternberg** [comment]
Thanks for the report. Will be in the next version. Feel free to test the `trunk` branch.

**Comment by arkonisus** [comment]
+1 Thank you very much, i will take look!
