### ISSUE TITLE
How to show Conditional Statement In CMB2 for input text?

### ISSUE THREAD

**Issue by nriddhi** [WebDevStudios/CMB2#875]
I want to show text or file with if else statement. If text is input in box it will show the input text otherwise it will show input your text from admin panel. the code may be like this,

 ```
  <?php if(!empty('projects')) { ?>

           <?php echo get_post_meta(get_the_ID(), 'projects', true);   ?>
            
             <?php }

  else  echo __("<h2> input your text from admin panel </h2>", "casanova")  ?>
```
though this is not working, but how can i do that? thanks for help.

**Comment by tw2113** [comment]
Is this for when creating/setting up the fields for the post editor screen? or for something when displaying the saved metabox fields on the frontend?

Curious how much https://github.com/jcchavezs/cmb2-conditionals would help here as well.

**Comment by nriddhi** [comment]
when displaying the saved metabox fields on the frontend, >> when i will input anything it will show there in front otherwise will show else condition text

**Comment by tw2113** [comment]
```
 <?php if ( ! empty( 'projects' ) ) {
    echo get_post_meta(get_the_ID(), 'projects', true);
} else {
    echo __( "<h2>input your text from admin panel</h2>", "casanova" );
}
?>
```
Based on the code above, which is what you have, outside of some touchups around spacing and opening/closing php tags, the code would never reach the else portion. This part: `( ! empty( 'projects' ) ) ` is always going to return true, because you're passing in a set string each time. It feels like you want to be checking a variable that may or may not have a value set yet.

Perhaps something like the following:
```
 <?php
$projects = get_post_meta(get_the_ID(), 'projects', true);
if ( ! empty( $projects ) ) { // May have a value to echo, may just be an empty string that would trigger the else.
    echo $projects;
} else {
    echo __( "<h2>input your text from admin panel</h2>", "casanova" );
}
?>
```

**Comment by nriddhi** [comment]
ow, thank you very much
