### ISSUE TITLE
How to change date format?

### ISSUE THREAD

**Issue by alzearafat** [WebDevStudios/CMB2#883]
Hi there,

Great plugin!, but the default date format of `text_date` not so great for me. How I can change the format to become something like `7 January 2017` ?

I cannot find it in docs...

Any help would be greatly appreciated :)

Thanks!

**Comment by tw2113** [comment]
Should be able to pass a custom date format via the `date_format` parameter seen at https://github.com/WebDevStudios/CMB2/wiki/Field-Types#text_date. It'll use the format characters seen at https://secure.php.net/manual/en/function.date.php if I'm not mistaken.

For example, you will want either `j F Y` if you want no leading zeros on the days, like "7" or `d F Y` if you want "07"

**Comment by alzearafat** [comment]
@tw2113 wow, thanks my friend! :+1:
