### ISSUE TITLE
require_once not using absolute path - results in possible conflict

### ISSUE THREAD

**Issue by fliespl** [WebDevStudios/CMB2#886]
### Expected Behavior:
require_once should use absolute path.

### Actual Behavior:
require_once uses relative path.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1.  `require_once 'bootstrap.php';` in code.

When using relative path it's possible that another library / plugin will "steal" your inclusion.

In my case it was civicrm plugin which adds it's path by set_include_path and one them consisted bootstrap.php hence cmb2_bootstrap function was never loaded. CiviCRM took precedence.

Should probably be replaced in this case with: `require_once dirname(__FILE__).'/bootstrap.php';`

**Comment by jtsternberg** [comment]
Thank you for the detailed description of the issue. Should be good in trunk.

**Comment by fliespl** [comment]
That works. Thank you for prompt reponse :)
