### ISSUE TITLE
How to get all metaboxes from a cmb2 form?

### ISSUE THREAD

**Issue by fakeartist** [WebDevStudios/CMB2#887]
Hi! Is there any way I can retireve anywhere on my site, all metaboxes keys from a specific cmb2 form through php?

**Comment by tw2113** [comment]
Are you wanting the whole objects? or just specific items from the metabox? I'm curious if the code examples at https://github.com/WebDevStudios/CMB2/wiki/Bringing-Metaboxes-to-the-Front-end would help. If anything, it'd return items that you could possibly poke through to get what you need.

**Comment by fakeartist** [comment]
Hi! I found #737 and it works. Thanks for the feedback!

**Comment by tw2113** [comment]
Sounds good.
