### ISSUE TITLE
HTML5 input types: range, number

### ISSUE THREAD

**Issue by allysonsouza** [WebDevStudios/CMB2#891]
At the moment there's no default support for HTML inputs like **range** and **number**?

**Comment by allysonsouza** [comment]
Ok, I've found how to set a text field to be a number only input, but for range this don't work.
https://github.com/WebDevStudios/CMB2/wiki/Tips-&-Tricks#limit-text-field-to-numbers-only

**Comment by jtsternberg** [comment]
The field's `'attributes'` property will be transferred as input attributes, so there's no reason you couldn't create a range field.

```php
$cmb_demo->add_field( array(
    'name' => __( 'My Range Field', 'theme-domain' ),
    'id'   => $prefix . 'range',
    'type' => 'text',
    'attributes' => array(
        'type' => 'range',
        'min' => '0',
        'max' => '100',
    ),
) );
```

**Comment by allysonsouza** [comment]
You are right, sorry for the inconvenient issue, it was an error in my code.

**Comment by K15Lmk98** [comment]
Hi,

This is an automatic translation

How is the value displayed while dragging the slider - 'type' => 'range' -?

Thanks, Claudio_

**Comment by tw2113** [comment]
Not quite following what you're asking @K15Lmk98

**Comment by tw2113** [comment]
All I was seeking was more explanation for what you're looking for, so I can help better. :)

**Comment by K15Lmk98** [comment]
I understood your intentions. Thanks :)

Unfortunately I do not speak English.
 I'm trying to explain.

In Html5, the slider input type works to render the slider, but not to show dragging values.

Therefore, when you move the cursor, you do not know what the value is.

See here:
https://stackoverflow.com/questions/10004723/html5-input-type-range-show-range-value

or

https://stackoverflow.com/questions/10004723/html5-input-type-range-show-range-value

Thanks, Claudio

**Comment by tw2113** [comment]
I don't believe CMB2 has much support for the `<output>` tag, but all the rest of those solutions look like they're standard javascript based, and wouldn't necessarily rely on anything from CMB2 itself.

**Comment by K15Lmk98** [comment]
Yes you are right.
We hope CMB2 will support the type slider natively.

Good night :) Thanks again.
Claudio_

**Comment by jtsternberg** [comment]
Possibly consider this custom field type: https://github.com/mattkrupnik/cmb2-field-slider

**Comment by K15Lmk98** [comment]
Thanks jtsternberg, I did not know him.

**Comment by jtsternberg** [comment]
Also, something like this works:

```php
$cmb_demo->add_field( array(
	'name' => __( 'range_type', 'cmb2' ),
	'id'   => 'range_type',
	'type' => 'text',
	'attributes' => array(
		'type' => 'range',
		'min' => '0',
		'max' => '100',
		'onchange' => 'document.getElementById( \'range_type_value\' ).value = this.value;',
	),
	'after' => function( $args, $field ) {
		$value = $field->value ? absint( $field->value ) : 50;
		echo ' <input type="text" disabled readonly style="background: #fff; color: #32373c; width: 3em;" id="range_type_value" value="' . $value . '" />';
	},
) );
```

**Comment by K15Lmk98** [comment]
Fantastic jtsternberg.
Thank you :)
