### ISSUE TITLE
Escaping values in textarea on settings page

### ISSUE THREAD

**Issue by vasikgreif** [WebDevStudios/CMB2#892]
I have a settings page, that I created by adjusting the example Settings page class. 

One of the settings is textarea_code, where I need to store HTML template of an email (including the html and head tags). When I hit save, the `"` are escaped with `\` and displayed in the textarea as

```
<meta name=\"viewport\" content=\"width=device-width\" />
```

The problem is, when I hit resave, it escapes again and becomes:

```
<meta name=\\\"viewport\\\" content=\\\"width=device-width\\\" />
```

How can I prevent the infinite re-escaping?

Thanks

**Comment by jtsternberg** [comment]
hmm, maybe try setting the `'escape_cb'` to `false`? https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#escape_cb

**Comment by vasikgreif** [comment]
That doesn't help, still the same problem.

**Comment by jtsternberg** [comment]
I just added a `textarea_code` to my test site w/ the site options, and it works perfectly (saved it many times). Maybe there's something else going on on your end.

![textarea_code](http://b.ustin.co/8lv+)

**Comment by vasikgreif** [comment]
Sorry, it works, my fault. Thanks!
