### ISSUE TITLE
String "Next" causes false notice

### ISSUE THREAD

**Issue by rubengc** [WebDevStudios/CMB2#894]
Setting `"next"` or `"Next"` as `default` causes next notice: 
```
Notice: CMB2_Field::__construct() was called with a parameter that is deprecated since version 2.2.3! Using the "default" field parameter as a callback has been deprecated in favor of the "default_cb" parameter.
```

**Comment by tw2113** [comment]
if you're explicitly passing in a value that you're typing in as "default", change it to be "default_cb"

Basic example code:

Use
```
new CMB2_field( array( 'default_cb' => 'next' ) );
```
instead of 
```
new CMB2_field( array( 'default' => 'next' ) );
```

**Comment by rubengc** [comment]
Well, I fixed it using `"Next:"` for `default` parameter value

Anyway I followed docs recommendations on use `default` for values and `default_cb` for callbacks, so I does not expect that `default` will trigger any notice/error (error comes from next() call)

I hope `default` could be turned into a not function caller in the future to avoid this

Thanks for your help and if you are want then close it
