### ISSUE TITLE
Metabox does not appear in WP edit file even though I have others who work fine.

### ISSUE THREAD

**Issue by udezekene** [WebDevStudios/CMB2#897]
### Expected Behavior:
I have 5 different metaboxes that have been defined to show on specific custom pages. They all work well. However, when I created the 6th one, it doesn't show up on the create/edit page. I even defined it globally (ie. without `object_types`); and it still doesn't show up.

Any ideas why this can be happening? @jtsternberg, @tw2113 

Here's a link to the gist: https://gist.github.com/udezekene/8540b449c73000dde48d76e2f35352fe

**Comment by tw2113** [comment]
Which one, specifically isn't showing up, to help us narrow down possible contributing factors.

**Comment by tw2113** [comment]
nevermind, figured which one out. Once I renamed it away from "test_metabox" it suddenly showed up. Looks like you have two trying to use that ID. The test one that you were just working with, and the metabox for "Incubation & Pre-Incubation" Once you get those no longer matching, you should be golden.

**Comment by udezekene** [comment]
Oh wow! Thanks @tw2113. I've been pulling my hair on this
