### ISSUE TITLE
Shortcode support for text field

### ISSUE THREAD

**Issue by ingozoell** [WebDevStudios/CMB2#898]
Hi,

is it possible to add shortcode support for text files / textarea?

```
$cmb->add_field( array(
	'name' => __( 'Headline', 'irras_cmb' ),
	'id' => $prefix . 'start_video_title',
	'type' => 'text',
));
```

`add_filter( 'start_video_title', 'do_shortcode');`
Doesn't work for me

**Comment by tw2113** [comment]
There's no "start_video_title" which is why that attempt isn't working.

I'm thinking something like this should work fine:

It will provide a dummy `$prefix` since you don't provide yours.

```
$title = get_post_meta( get_the_ID(), '_my_prefix_start_video_title', true );
echo do_shortcode( $title );
```
Instead of trying to use the do_shortcode filter, we'll just pass the entire fetched content through the do_shortcode function.

**Comment by ingozoell** [comment]
Sorry, I prefixed it.

What I'd like is:
To output the shortcode hear:

![bildschirmfoto 2017-03-25 um 19 35 50](https://cloud.githubusercontent.com/assets/2229940/24325077/4b50c742-1192-11e7-9f33-f5e77b25cec2.png)

**Comment by tw2113** [comment]
So you want to have the shortcode parsed and the result output into the text/textarea?

If you're just wanting to store the shortcode, unparsed, until ready to use on the frontend of the site, then go with my last comment. If my question at the top of this reply is accurate, then I'm not quite sure how to go about that. Never tried to output shortcode results into html attributes.

**Comment by ingozoell** [comment]
> So you want to have the shortcode parsed and the result output into the text/textarea?

Yes. Never done?

**Comment by ingozoell** [comment]
The WP Title `the_title();` supports shortcodes. Is just a input field.

**Comment by ingozoell** [comment]
I found This: [https://wordpress.stackexchange.com/questions/195707/shortcode-not-working-inside-html-input](url)

But works not for me

**Comment by ingozoell** [comment]
I found a solution without the need of shortcodes: [https://stackoverflow.com/questions/772510/wordpress-filter-to-modify-final-html-output](url)
