### ISSUE TITLE
Select dropdown not keeping selected value after updating page

### ISSUE THREAD

**Issue by emwebber** [WebDevStudios/CMB2#899]
### Expected Behavior:
The selected 'category' chosen from the select field drop-down will keep the chosen option after updating the page.

### Actual Behavior:
The selected value reverts back to the first item in the select field drop-down list

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):
1.  ?
2.  ?

### CMB2 Field Registration Code:
```
<?php
add_filter( 'cmb_meta_boxes', 'cmb_sample_metaboxes' );

function cmb_sample_metaboxes( array $meta_boxes ) {
	$prefix = '_cmb_';

	// Products
	$meta_boxes['products_metabox'] = array(
		'id'         => 'products_metabox',
		'title'      => __( 'Products', 'cmb' ),
		'pages'      => array( 'products', ), // Post type
		//'show_on' => array( 'key' => 'id', 'value' => array( 10 ) ),
		'context'    => 'normal',
		'priority'   => 'high',
		'show_names' => true, // Show field names on the left
		// 'cmb_styles' => true, // Enqueue the CMB stylesheet on the frontend
		'fields'     => array(

array(
	'name'             => 'Category',
	'desc'             => 'Select a category for this product',
	'id'               => $prefix . 'category_select',
	'type'             => 'select',
	'show_option_none' => true,
	'default'          => 'custom',
	'options'          => array(
			'Caps' 								=> __( 'Caps', 'cmb' ),
			'Centennial' 							=> __( 'Centennial', 'cmb' ),
			'Corner Tub' 							=> __( 'Corner Tub', 'cmb' ),
			'Drop In Tub'							=> __( 'Drop In Tub', 'cmb' ),
			'Handicapped Unit' 					=> __( 'Handicap Unit', 'cmb' ),
			'Neo Angle Shower' 					=> __( 'Neo Angle Shower', 'cmb' ),
			'1 Piece Remodeler Shower Shallow Depth'	=> __( 'One Piece Remodeler Shower Shallow Depth', 'cmb' ),
			'1 Piece Remodeler Tub & Shower Shallow Depth'	=> __( 'One Piece Remodeler Tub and Shower Shallow Depth', 'cmb' ),
			'Sectional Piece Remodeler Shower'		=> __( 'Sectional Remodeler Shower', 'cmb' ),
			'Sectional Remodeler Tub & Shower' 		=> __( 'Sectional Remodeler Tub and Shower', 'cmb' ),
			'Shower Base' 							=> __( 'Shower Base', 'cmb' ),
			'Shower Only 1 Piece' 					=> __( 'Shower Only One Piece', 'cmb' ),
			'Tub & Shower 1 Piece' 					=> __( 'Tub Shower One Piece', 'cmb' ),
			'Tub Only with Apron' 					=> __( 'Tub Only Apron', 'cmb' )
	),
),
	// Add other metaboxes as needed
	return $meta_boxes;
}

add_action( 'init', 'cmb_initialize_cmb_meta_boxes', 9999 );
/**
 * Initialize the metabox class.
 */
function cmb_initialize_cmb_meta_boxes() {
	if ( ! class_exists( 'cmb_Meta_Box' ) )
		require_once 'init.php';
}
```

**Comment by tw2113** [comment]
Looks like the configuration methods from https://github.com/WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress/ to be honest. Possible you're still using that plugin specifically as well.

Since that's no longer updated or supported, and if you're for sure using CMB2 specifically, I recommend looking over https://github.com/WebDevStudios/CMB2/blob/trunk/example-functions.php and recreating your parts above using the examples from there. Possible that the issue you're facing fixes itself with this change, but if not, we can proceed to troubleshoot from there with the new code.

**Comment by emwebber** [comment]
Thanks for the quick reply! Is there a CMB to CMB2 migration section somewhere that I'm just not seeing or is there no documentation for such a move?

**Comment by tw2113** [comment]
I'd look over https://github.com/WebDevStudios/CMB2/wiki in general, but https://github.com/WebDevStudios/CMB2/wiki/Notable-Changes-in-CMB2 would be a good one specifically.

**Comment by emwebber** [comment]
I've switched out CMB with CMB2 and things initially seem to be working fine. Thanks for the help!

**Comment by tw2113** [comment]
Welcome. For any other issues that arise, feel free to start a thread over at https://wordpress.org/support/plugin/cmb2 where we try to do all our end user/initial support. I keep my eye on that area as well, so you'll still get me responding :)
