### ISSUE TITLE
Mailto spam protection

### ISSUE THREAD

**Issue by ingozoell** [WebDevStudios/CMB2#900]
Hi,

is it possible to protect my mailto links in my cmb fields on frontend  as well in `the_content();`?

E. g. with the [Email Address Encoder Plugin](https://wordpress.org/plugins/email-address-encoder/) or PHP/Javascript

**Comment by tw2113** [comment]
Looking at that plugin, and the FAQ tab, you could pass your content through their functions before echo'ing.

Otherwise, CMB2 doesn't do anything for this topic out of box and automatically.

Closing as it's not an issue on the code itself, but we can still discuss if necessary afterwards.
