### ISSUE TITLE
Is there any field type for Google Map?

### ISSUE THREAD

**Issue by nriddhi** [WebDevStudios/CMB2#902]
I want to show google map with CMB2 custom field. Is there any way to show Google Map with CMB2 field type ?

**Comment by dowen121** [comment]
https://github.com/mustardBees/cmb_field_map

**Comment by nriddhi** [comment]
how should i adjust cmb_field_map with CMB2

**Comment by dowen121** [comment]
So you can use get_post_meta() to return the data entered into the CMS. This will return lat/long coordinates which you can then pass into javascript and use like so;

`
(function($) {

    var latitude = $('#map-lat').val();
    var longtitude = $('#map-long').val();

    // When the window has finished loading create our google map below
    google.maps.event.addDomListener(window, 'load', init);

    function init() {
        // Basic options for a simple Google Map
        // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
        var mapOptions = {
            // How zoomed in you want the map to start at (always required)
            zoom: 15,

            // The latitude and longitude to center the map (always required)
            center: new google.maps.LatLng(latitude, longtitude),

    		disableDefaultUI: true,
    		scrollwheel: false,

        };

        // Get the HTML DOM element that will contain your map 
        // We are using a div with id="map" seen below in the <body>
        var mapElement = document.getElementById('map');

        // Create the Google Map using our element and options defined above
        var map = new google.maps.Map(mapElement, mapOptions);

        // Let's also add a marker while we're at it
        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(latitude, longtitude),
            map: map,
            title: 'Map'
        });
    }

})(jQuery);`

You will need a "Google Maps JavaScript API" key from the google developer console.

A simple guide on setting up a google map via the API can be found on snazzy maps and then following their example -> link to download https://snazzymaps.com/download-example/1

**Comment by tw2113** [comment]
From the looks of it, the cmb_field_map addon linked to earlier is a fancy latitude/longitude storage field. As dowen121 pointed out, at that point you'd need to fetch the values and plot them on an instantiated map, which CMB2 isn't going to have much helpers for.

Closing as not an issue with CMB2 itself. Feel free to continue discussion as necessary though.

**Comment by Rezaul1300** [comment]
kindly see this link please: - 1.  http://prntscr.com/iwelp5      2.  http://prntscr.com/iwem5z      3.   http://prntscr.com/iwemub﻿ 

In my first post are showing the map. but the next post not showing the map. please help me

**Comment by dowen121** [comment]
A quick glance suggests like the <div id="map"></div> element should have
unique ID foreach of the the items.

e.g.

<div id="map1"></div>
<div id="map2"></div>
<div id="map3"></div>

and then the JS code updated to reflect this;


    var mapElement = document.getElementById('map');

**Comment by rohitwebguru** [comment]
Hello All, 

I am trying to add google map field with cmb2, But it is not getting appeared at all. AM i making any mistake there? 

![image](https://user-images.githubusercontent.com/10211589/44896713-cb824c80-ad16-11e8-9d22-af27ae208eda.png)
