### ISSUE TITLE
Video Post oembed is not working in wordpress 4.7.3

### ISSUE THREAD

**Issue by nriddhi** [WebDevStudios/CMB2#903]
I have attached CMB2 field type oembed in post type. But when i input video url. This is showing 

> No oEmbed Results Found for https://www.youtube.com/watch?v=sd0grLQ4voU View more info at codex.wordpress.org/Embeds.

How can i solve this?

N.B: I am using latest version of worpress

**Comment by tw2113** [comment]
What's the CMB2 configuration code you're using, as well as any code used to try and display the saved content?

**Comment by nriddhi** [comment]
Like This
```
function clava_metabox_post() {

    $cmb = new_cmb2_box( array(
        'id'            =>  'metabox1',
        'title'         => __( 'Post Metabox', 'cmb2' ),
        'object_types'  => array( 'post')
    ) );

    $cmb ->add_field( array(
        'name'       => __( 'Enter Your Video URL here', 'cmb2' ),
        'desc'       => __( 'Your Video URL here', 'cmb2' ),
        'id'         => 'clava_post_video',
        'type'       => 'oembed',
    ) );   
}
add_action( 'cmb2_admin_init', 'clava_metabox_post' );
```
i have tried with default value of CMB2 , but it don't working in wordpress latest version

**Comment by tw2113** [comment]
Not managing to have any issues.

Frontend: https://cloudup.com/czs3oqjTAlk

Backend: https://cloudup.com/ch9TkwrHgDf

I am on 4.7.3 as well. Curious if it's a momentary issue only.

**Comment by bradp** [comment]
Seems to be resolved here, going to close this. 

If this comes up again as a bug, feel free to re-open.

**Comment by nriddhi** [comment]
I am using localhost server

**Comment by tw2113** [comment]
I was too when I posted my last reply.

**Comment by nriddhi** [comment]
but what can be the problem, now i am using wordpress older version

**Comment by tw2113** [comment]
I'm curious about any possible console errors that were occurring at the time, and if it was just a temporary issue or if it was consistent. I think the functionality as a whole is just fine at this point, so that sort of leaves it isolated at the environment it was struggling in, and what external factors may be playing a part.

**Comment by nriddhi** [comment]
it was consistent error, now i am using wordpress older version 4.6

**Comment by rendy44** [comment]
It still occurs on 5 and up.

**Comment by tw2113** [comment]
@rendy44 what is your CMB2 config and some sample URLs you're using? Beyond that, any other questions I've posted above would apply to your situation as well. We haven't seen a constant/consistent issue so we have to take things as a per-use-case situation.
