### ISSUE TITLE
Non-Repeatable Groups?

### ISSUE THREAD

**Issue by GregLancaster71** [WebDevStudios/CMB2#93]
Is there anyway to add a group of fields that cannot be repeated?  Or, maybe some way to create a custom field that has multiple inputs?

**Comment by jtsternberg** [comment]
Closed by https://github.com/WebDevStudios/CMB2/commit/c8b904de3a84a7323bfecdc188f5234da51f74ed

Will be in the next release.

**Comment by jaxgeller** [comment]
Sorry to reopen, but @jtsternberg when is the next release due/ how can i use this feature right now? Clone master or another branch?  All i can seem to find is this https://github.com/WebDevStudios/CMB2/tree/c8b904de3a84a7323bfecdc188f5234da51f74ed, but no branch info. Thanks!

**Comment by jtsternberg** [comment]
Hey @jaxgeller, I [just released 2.0.7](https://github.com/WebDevStudios/CMB2/releases/tag/v2.0.7), but for future reference, you can find/download the trunk branch here: https://github.com/WebDevStudios/CMB2/tree/trunk
