### ISSUE TITLE
Using 'show_on' parameter with child themes not working as expected

### ISSUE THREAD

**Issue by iantbarker** [WebDevStudios/CMB2#942]
### Expected Behavior:

I have a large WP setup where a main theme contains CMB to use on main theme and child themes. I want to add CMBs as needed that are needed on child themes for different page templates. So CMBs are extended from main theme to child theme and then all those are included to extend to a particular page template.

### Actual Behavior:

It works to extend from main theme to a child theme (keeps main theme CMBs but adds news ones), but when I try to use the 'show_on' property to add individual CMBs to certain page templates or page ids, it adds those CMBs to every page on the child theme.

### Steps to reproduce (I have confirmed I can reproduce this issue on the trunk branch):

1. Add CMBs to main theme functions.php
2. Add additional CMBs to child theme functions.php
3. Specify which fields should be displayed when it is using a particular page template or page id.

### CMB2 Field Registration Code:

This is what is in main theme functions file (truncated cause about 10 fields, which aren't all that exciting):

```php
add_action( 'cmb2_init', 'ihopkc_theme_metaboxes' );
function ihopkc_theme_metaboxes() {

	$prefix = 'ihopkc_theme_page_';

	$cmb = new_cmb2_box( array(
		'id'           => $prefix . 'ihopkc_theme_page',
		'title'        => __( 'IHOPKC Universal Theme Page Options', 'cmb2' ),
		'object_types' => array( 'page', 'post' ),
		'context'      => 'normal',
		'priority'     => 'high',
	) );

	$cmb->add_field( array(
		'name' => __( 'Page Header Image URL', 'cmb2' ),
		'id' => $prefix . 'template_header_image',
		'type' => 'text',
		'desc' => __( 'URL of the custom header image (type "false" to force default background image)', 'cmb2' ),
	) );

	$cmb->add_field( array(
		'name' => __( 'Below content full-width', 'cmb2' ),
		'id' => $prefix . 'below_content_full',
		'type' => 'textarea_code',
	) );
}
```

And here is code in child theme functions.php file:

```php

add_action( 'cmb2_init', 'cmb2_add_metabox_onething2017' );
function cmb2_add_metabox_onething2017() {

	$prefix = 'ihopkc_theme_page_';

	$cmb = new_cmb2_box( array(
		'id'			=> $prefix . 'ihopkc_theme_page',
		'title'			=> __( 'Onething 2017 Page Options', 'cmb2' ),
		'object_types'	=> array( 'page' ),
		'context'		=> 'normal',
	) );

	$cmb->add_field( array(
		'name' 			=> __( 'Speakers', 'cmb2' ),
		'id' 			=> $prefix . 'onething2017_speakers',
		//'show_on'		=> array( 'key' => 'page-template', 'value' => 'onething-home.php' ),
		'show_on'      => array( 'key' => 'id', 'value' => array( 2 ) ),

		'type' 			=> 'textarea_small'
	) );

	$cmb->add_field( array(
		'name' 			=> __( 'Registration', 'cmb2' ),
		'id' 			=> $prefix . 'onething2017_registration',
		'type' 			=> 'wysiwyg',
	) );
}

```

**Comment by iantbarker** [comment]
I just realized that 'show_on' is for boxes, not fields. Is that correct?

So I guess my question would be, how do I create 2 boxes on a page or post?

**Comment by tw2113** [comment]
Correct, show_on is for the metabox, not so much individual fields.

Overall, I'd look https://github.com/WebDevStudios/CMB2/wiki/Adding-your-own-show_on-filters over as it could lead you to some ideas on how to approach some things.

Regarding 2 boxes, you can invoke new_cmb2_box(...) multiple times, even from inside the same callback. say `$cmb1 = new_cmb2_box(...);` and `$cmb2 = new_cmb2_box(...)` and add different fields to each, both with their own unique `show_on` conditions.

**Comment by jtsternberg** [comment]
use `'show_on_cb'`: https://github.com/WebDevStudios/CMB2/wiki/Field-Parameters#show_on_cb

**Comment by iantbarker** [comment]
@tw2113 Ahhhh... I figured out how to invoke a new box. I had tried that but didn't change a prefix. This is super helpful. Thanks so much!

**Comment by jtsternberg** [comment]
👍
